### ISSUE TITLE
homebridge plugin doesn't see any devices, devices section says no devices

### ISSUE THREAD

**Issue by fhivet** [OpenWonderLabs/homebridge-switchbot#1005]
### Describe Your Problem

Installed plugin on latest Homebridge on docker, everything up to date, entering my token and secret, restart the plugin and whole homebridge, but no devices is detected. Cloud is activated on all the devices. Using a smartbot mini hub.

### Relevant log output

```shell
something weird, logs are empty, completely empty
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "token",
        "secret": "secret",
        "notice": "Keep your Token & Secret a secret!"
    },
    "platform": "SwitchBot"
}
```

### Device & Model

switchbot hub mini

### Node.js Version

v18.18.2 

### NPM Version

can't find info

### Homebridge Version

1.8.3

### Homebridge SwitchBot Plugin Version

3.6.0

### Homebridge Config UI X Plugin Version

latest

### Operating System

docker

**Comment by donavanbecker** [comment]
turn debug logs on and provide or I can't be much help

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.6.1-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by fhivet** [comment]
Installing latest beta solved the problem. Also i tried to return to stable version just after that and devices are still there. Really weird...

And logs are back, previously logs were totally empty
