### ISSUE TITLE
Feature Request: Water Sensor Dry State

### ISSUE THREAD

**Issue by bassetwilson** [OpenWonderLabs/homebridge-switchbot#1025]
### Problem

The water leak sensors have a native dry state but HomeKit does not. Even if the water sensor is set to dry state in the Switchbot app HomeKit will report the matter as a leak.  Though you can remove most of the alarms and notices it will still present a warning in the HomeKit app.  

### Solution

A device function in the configuration that allows the system to report the opposite of the state in the API to HomeKit.  For example, "Mark here if device is reporting dry state." Then instead of reporting the device state as "1" it reports it as "0."  The person then just needs to know that the HomeKit leak warning is of a dry state for those devices.  

### Alternatives

Not sure given we just need to report the opposite of the "1" or "0."

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.7.1-beta.23/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

I have added a config that allows Dry Alert to be enabled which sets the state opposite to what it comes in as on the api.

**Comment by donavanbecker** [comment]
Released 3.8.0 which supports this. If you are having issues with this enhancement, please open new issue.
