### ISSUE TITLE
Feature Request: Curtain 3 mode switch

### ISSUE THREAD

**Issue by alanstrok** [OpenWonderLabs/homebridge-switchbot#1037]
### Solution

Hi,
Would it be possible to add a dummy switch to select the opening/closing mode of curtain 3. 
This is for automation and to have on demand silent mode. 
For example automation to open curtains in the morning in quiet mode and after that can be opened in performance mode if wanted without having to modify the homebridge config.
Thanks

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.7.1-beta.20/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

I have added a config to both Curtain and Blind Tilt that if enabled will display two switches. 1 that is for close and one that is for open. If the switch is turned on then silent mode is enabled.

**Comment by n0de0ne** [comment]
I tried the beta, it only exposes one switch which seems to be for closing and it works. I tried opening with that one switch on but it opens at normal speed

**Comment by donavanbecker** [comment]
> I tried the beta, it only exposes one switch which seems to be for closing and it works. I tried opening with that one switch on but it opens at normal speed

Good to hear. I will look into that.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.7.1-beta.27/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
released 3.8.0 which supports this. If you are having issues with this enhancement, please open new issue.

**Comment by n0de0ne** [comment]
It seems to be working now. Only thing I would suggest is naming which one is for opening and which one is for closing. Aside from that it's good

**Comment by donavanbecker** [comment]
I even set the name, but the home app doesn't accept it. I can try adding a Characteristic that may display a warning the firs time you install this beta, and then won't display after that.

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.8.1-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by n0de0ne** [comment]
All good now thank you very much !

**Comment by donavanbecker** [comment]
> All good now thank you very much !

Did you get a warning?

**Comment by n0de0ne** [comment]
> > All good now thank you very much !
> 
> Did you get a warning?

No, not in the logs or anywhere else
