### ISSUE TITLE
Bug: Contact Sensor, Motion Sensor and Meter does not update state

### ISSUE THREAD

**Issue by smartmatic** [OpenWonderLabs/homebridge-switchbot#104]
### Describe The Bug

Thanks a lot for integrated BLE only function! It works so far with the Bot. In terms of Contact Sensor, Motion Sensor and Meter  i am able to add them to Homebridge but the state of the device does not change. For instance if a open the contact sensor the open state is not submitted to homebridge. Same for Motion sensor and Meter.

### To Reproduce

Add contact sensor per BLE to Homebridge and open the sensor

### Expected behavior

State should change once the sensor changes his values like open for contact sensor or motion for the motion sensor

### Relevant log output

[SwitchBot_Log.txt](https://github.com/OpenWonderLabs/homebridge-switchbot/files/7576547/SwitchBot_Log.txt)

### Config for homebridge-switchbot

```shell
"options": {
                "devices": [
                    {
                        "deviceId": "D273C8Axxxx",
                        "configDeviceName": "Bot Test",
                        "configDeviceType": "Bot",
                        "ble": true,
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "F5F453Exxxx",
                        "configDeviceName": "Contact Sensor",
                        "configDeviceType": "Contact Sensor",
                        "ble": true
                    },
                    {
                        "deviceId": "84F70353xxxx",
                        "configDeviceName": "Color Bulb Test",
                        "configDeviceType": "Color Bulb",
                        "ble": true
                    },
                    {
                        "deviceId": "E1D35C4Dxxxx",
                        "configDeviceName": "Meter Test",
                        "configDeviceType": "Meter",
                        "ble": true
                    },
                    {
                        "deviceId": "F97B404Fxxxx",
                        "configDeviceName": "Motion Test",
                        "configDeviceType": "Motion Sensor",
                        "ble": true
                    }
                ],
                "refreshRate": 30,
                "debug": "device"
            },
            "platform": "SwitchBot"
```

### Screenshots

![SwitchBot BLE Homebridge](https://user-images.githubusercontent.com/74932663/142768018-1c0f13ce-4c6c-4851-9edf-b7101a35a189.png)

I observed some smaller form issues. I guess the hide option related to the contact sensor has the wrong naming?

![Contact Sensor Hide Option](https://user-images.githubusercontent.com/74932663/142768259-b45d8cc9-57ed-4326-8c90-49f856d91ac1.png)

In the device section the Type of the device is not recognized although the device is configured as BLE device in config.json

![Contact_Sensor_Undefined](https://user-images.githubusercontent.com/74932663/142768286-e698e6b9-bcd9-4030-8d5b-a51f389dbc6a.png)

### Device & Model

Switchbot Contact & Motion Sensor, Meter, Bulb

### Node.js Version

v14.18.1

### NPM Version

v6.14.15

### Homebridge Version

v1.3.6

### Homebridge Switchbot Plugin Version

v1.2.0

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
I have fixed the issue with the connectionType with the latest beta. I will have to look into the states not updating for BLE though

**Comment by SeanHama** [comment]
HI, I'm getting this error

[25/11/2021, 12:00:47] [SwitchBot] [DEVICE] Device: Meter 59 Neither OpenAPI and BLE Enabled
[25/11/2021, 12:00:47] [SwitchBot] [DEVICE] Unable to Register new device: Meter 59 Meter - F2D210301B59

Have you got a fix by anychance

**Comment by donavanbecker** [comment]
> HI, I'm getting this error
> 
> 
> 
> [25/11/2021, 12:00:47] [SwitchBot] [DEVICE] Device: Meter 59 Neither OpenAPI and BLE Enabled
> 
> [25/11/2021, 12:00:47] [SwitchBot] [DEVICE] Unable to Register new device: Meter 59 Meter - F2D210301B59
> 
> 
> 
> Have you got a fix by anychance
> 
> 

@SeanHama Please open separate issue, as your issue is different then this issue.

**Comment by donavanbecker** [comment]
@smartmatic This is an issue with node-SwitchBot, that will have to be fixed first before resolving it for this plugin.

**Comment by smartmatic** [comment]
> @smartmatic This is an issue with node-SwitchBot, that will have to be fixed first before resolving it for this plugin.

@donavanbecker What does that mean for my environment? Should i update to Node 16.x ?

**Comment by donavanbecker** [comment]
@smartmatic That means [node-switchbot](https://github.com/OpenWonderLabs/node-switchbot) need to be updated for this to work.

**Comment by smartmatic** [comment]
> @smartmatic That means [node-switchbot](https://github.com/OpenWonderLabs/node-switchbot) need to be updated for this to work.

@donavanbecker Thank you, done.

I've done some new test after installation of node-switchbot. Here are my quick results:

Bot:

I can control the Bot. If i click the button the arm moves but the state remains On like shown in the below screenshot. Do i click the Button again the arm moves again and Homebridge shows the state as off.

Meter:
Meter shows now values for temperature and humidity. The humidity value is the same as shown in switchbot app but the temperature is wrong.

Contact & Motion Sensor:
Both devices does not react and i putted them close the PI in order to avoid any connection issues.

![IMG_8051](https://user-images.githubusercontent.com/74932663/143401161-b410e6fb-0893-4c39-919c-5da050cbe0c8.jpg)

![Bildschirmfoto 2021-11-25 um 08 46 47](https://user-images.githubusercontent.com/74932663/143400627-01967cc4-5611-4264-a70c-4f4d1eb7a9e6.png)

[switchbot.txt](https://github.com/OpenWonderLabs/homebridge-switchbot/files/7601154/switchbot.txt)

**Comment by donavanbecker** [comment]
@smartmatic node-switchbot is what this plugin uses to connect to BLE Seitchbot devices. You don’t have to install it yourselves. But a fix in that library is needed to fix this plugin.

**Comment by donavanbecker** [comment]
@smartmatic can you test the latest beta and let me know if it is working for you on BLE? With Motion and contact sensors.

**Comment by mrbungle64** [comment]
@donavanbecker 

For me it works with homebridge-switchbot v1.12.6-beta.0 👍🏻 

But it takes quite a long time until the values are updated and I think the light sensor values are not correct.


![homebridge-switchbot 2022-02-22 14 03 45](https://user-images.githubusercontent.com/37313763/155138560-bc62e6bf-c4e3-45a0-ab8b-e52754b7b7e8.png)

**Comment by donavanbecker** [comment]
@mrbungle64 Thanks, I will look over this BLE code since I haven't touched it in a while since node-switchbot wasn't working.

**Comment by donavanbecker** [comment]
v1.12.7 should resolve this.
