### ISSUE TITLE
Bug: latest update with error

### ISSUE THREAD

**Issue by mtressl** [OpenWonderLabs/homebridge-switchbot#1048]
### Describe the Bug

the latest update brings a new error message, and it's not clear why.

with debug log ON I see the following:
`[9/14/2024, 10:51:18 AM] [homebridge-switchbot] [DEBUG] Discovered Hub Mini: E94F9E55B6AA, **is currently not supported**, device: {"deviceId":"E94F9E55B6AA","deviceName":"Büro Hub Mini","deviceType":"Hub Mini","enableCloudService":true,"hubDeviceId":"000000000000"}`

resulting in the error:
`Error: from server 192.168.1.xxx:46559 Error: connect ECONNREFUSED 192.168.1.xxx:46559
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.xxx',
  port: 46559
}`

this did not happen in prior versions.

both log entries are also not colored as error but are regular white font.

### To Reproduce

latest version of pluging.
turn on debug log --> see Discovered Hub Mini: E94F9E55B6AA, **is currently not supported**
(even without debug log, the error appears in the log.

### Expected Behavior

no error, or at least make clear why?

### Relevant Log Output

```shell
with debug log ON I see the following:
`[9/14/2024, 10:51:18 AM] [homebridge-switchbot] [DEBUG] Discovered Hub Mini: E94F9E55B6AA, **is currently not supported**, device: {"deviceId":"E94F9E55B6AA","deviceName":"Büro Hub Mini","deviceType":"Hub Mini","enableCloudService":true,"hubDeviceId":"000000000000"}`

resulting in the error:
`Error: from server 192.168.1.xxx:46559 Error: connect ECONNREFUSED 192.168.1.xxx:46559
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.xxx',
  port: 46559
}`
```

### Config for homebridge-switchbot

```shell
{
            "name": "homebridge-switchbot",
            "credentials": {
                "token": "lalalala",
                "secret": "sasasasa",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "CF9118456559",
                        "configDeviceName": "Büro Synology",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "C985E24B3C39",
                        "configDeviceName": "Büro Vorhang",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "curtain": {
                            "setOpenMode": "1",
                            "setCloseMode": "1"
                        },
                        "history": true,
                        "logging": "standard"
                    },
                    {
                        "deviceId": "CAD916E5BC05",
                        "configDeviceName": "Schlafzimmer Vorhang",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "curtain": {
                            "setOpenMode": "1",
                            "setCloseMode": "1"
                        },
                        "history": true,
                        "logging": "standard"
                    }
                ],
                "refreshRate": 360,
                "pushRate": 1,
                "logging": "debug",
                "allowInvalidCharacters": false
            },
            "_bridge": {
                "username": "0E:8E:8E:A1:54:EE"
            },
            "platform": "SwitchBot"
        },
```

### Device and Model

Hub mini?

### Node.js Version

latest

### NPM Version

latest

### Homebridge Version

latest

### Homebridge Switchbot Plugin Version

latest

### Homebridge Config UI X Plugin Version

latest

### Operating System

Raspian

**Comment by donavanbecker** [comment]
do you have a ipaddress bind in Homebridge settings?

<img width="1411" alt="Screenshot 2024-09-14 at 4 36 10 AM" src="https://github.com/user-attachments/assets/c8a7e85e-0881-4dcd-9edb-38680d0208ba">

might need to bind your network interface
```json
"_bridge": {
                "username": "0E:8E:8E:A1:54:EE",
                "bind": [
                    "en0"
                ]
            }
```

**Comment by mtressl** [comment]
I actually do have an ipaddress bind, so I added in the SwitchBot config:
`            "_bridge": {
                "username": "0E:8E:8E:A1:54:EE",
                "bind": [
                    "eth0"
                ]
            }`

But this did not help, error still appears.

**Comment by donavanbecker** [comment]
One thing to point out hub mini isn't supported to be displayed as anything with the plugin. However would also no error because of that.

If you go to old versions then the error doesn't appear?

**Comment by mtressl** [comment]
I did remove all optional values from my config now, and it seems the above mentioned error disappeared.
It also solved the two warnings I had reported before in #995 / #1000.
Seems like some legacy values were causing those hick-ups.
