### ISSUE TITLE
Feature Request: To be able to exclude devices from configuration

### ISSUE THREAD

**Issue by Jacquesherivault** [OpenWonderLabs/homebridge-switchbot#1059]
### Problem

I use the plugin to expose IR devices to Homekit. I have a hub 2.0 and my switchbot curtains are Matter compatible and don't need to be imported to Homekit through the Homebridge.

### Solution

An option in the plugin configuration to be able to exclude devices would be nice.

**Comment by donavanbecker** [comment]
This is already possible. Grab the deviceId from the config, put it in the SwitchBot device settings and set hide device to true.

**Comment by donavanbecker** [comment]
v4.0.0 will also support setting config by deviceType.
