### ISSUE TITLE
Feature Request: Option to set config for entire device class

### ISSUE THREAD

**Issue by ErikMeinders** [OpenWonderLabs/homebridge-switchbot#1064]
### Problem

I have many curtains, and none of them open to 0% or close to 100% exactly. That means, in every curtain config I have to add a statement to consider 20% 'open enough' and 80% 'close enough'. Every time I add a curtain (group) I have to manually edit the config file.

### Solution

It would be great if there could be a config setting for an entire class, like the default for that class, that could still be overruled by an individual instance of that class - like today. But that would define a more relevant default value than 0 and 100 in case of the curtain. I'm sure this applies to other classes, but I happen to have only curtains in SwitchBot.
```
class_defaults: {
  "curtain" : {
     "set_min" : 20,
     "set_max" : 80
  },
  "some_other_class" : {
      "..." : "..."
  }
}
```

### Alternatives

Alternatively a 'bulk' editor might be a solution, select all curtains and change a setting of all selected curtains at once. But the current device editor doesn't allow for multiple selects.

### Additional context

With 16+ sets of curtains (and counting) changing the JSON file after every (batch of) addition(s) is no fun!

**Comment by donavanbecker** [comment]
I can look into this. It would be a big change.

**Comment by donavanbecker** [comment]
I have added this functionality in the latest beta, if you are willing to try it. Keep in mind this whole beta is a major change to the config so if you already have settings set for your devices, some will need to be re set up.

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=4.0.0-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
Will be supported in v4.0.0
