### ISSUE TITLE
Bug: Not loading after update to 4.0

### ISSUE THREAD

**Issue by jscherry** [OpenWonderLabs/homebridge-switchbot#1075]
### Describe the Bug

After updating to version 4.0 the child bridge got stuck in a reboot loop. After dongrading to version 3.8 everything started working again?

### To Reproduce

upgrade from 3.8 to 4.0

### Expected Behavior

Expected the bridge to load

### Relevant Log Output

```shell
Sorry didn't download logs before reverting back to 3.8
```

### Config for homebridge-switchbot

```shell
Sorry didn't download logs before reverting back to 3.8
```

### Device and Model

Hub 2 and universal remote

### Node.js Version

v20.17.0

### NPM Version

not sure

### Homebridge Version

v1.8.4

### Homebridge Switchbot Plugin Version

v4.0

### Operating System

Debian GNU/Linux Bookworm (12)

**Comment by donavanbecker** [comment]
Not much I can do for you if I don't get logs. Closing until provided.
