### ISSUE TITLE
Bug: "Devices" Don't clear after fresh install

### ISSUE THREAD

**Issue by ukiews** [OpenWonderLabs/homebridge-switchbot#1076]
### Describe the Bug

The Devices section shows a repeated list of old devices. Even after deleting the config settings when uninstalling, the list is still there after a new install, without any initial setup/config.

### To Reproduce

This has been there for a while.

### Expected Behavior

Expected a clear list

### Relevant Log Output

```shell
na
```

### Config for homebridge-switchbot

```shell
This is before any config.
```

### Screenshots

![Screenshot 2024-10-14 at 13 38 55](https://github.com/user-attachments/assets/0cad7157-2c99-4d57-8dbf-df65b5172113)

### Device and Model

Raspberry Pi 4

### Node.js Version

20.17.0

### NPM Version

10.2.4

### Homebridge Version

1.8.4

### Homebridge Switchbot Plugin Version

4

### Homebridge Config UI X Plugin Version

4.61.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
add the deviceId and click hide device

you could also use the new deviceType config and delete all devices of that deviceType by checking the hide device checkbox.

**Comment by ukiews** [comment]
They are all "undefined."
I used to use a hub, but don't any longer.

**Comment by donavanbecker** [comment]
can you clear them using Homebridge Settings to clear accessories?
