### ISSUE TITLE
Failed pushChanges with OpenAPI Connection

### ISSUE THREAD

**Issue by jacobio** [OpenWonderLabs/homebridge-switchbot#108]
### Describe Your Problem

API error occurs when Bot switch is turned on or off in the Home app

After configuring my SwitchBot hum in homebrige, I can't seem to use my one Bot accessory. While the accessory shows on the Home app, anytime I try to turn it on or off, I get the following error message in the log:

### Relevant log output

```shell
[SwitchBot] Bot: Coffee Maker failed pushChanges with OpenAPI Connection
[SwitchBot] Initializing SwitchBot platform...
[SwitchBot] Using Default Refresh Rate (2 minutes).
[SwitchBot] Using Default Push Rate.
[SwitchBot] Total SwitchBot Devices Found: 2
[SwitchBot] Restoring existing accessory from cache: Coffee Maker DeviceID: DE39D92A5A62
[SwitchBot] Total IR Devices Found: 0
[SwitchBot] Bot: Coffee Maker Displaying as Outlet
```

### Config for homebridge-switchbot

```shell
{
  "platform": "SwitchBot",
  "name": "SwitchBot",
  "credentials": {
    "openToken": "<elided>",
    "notice": "Keep your token a secret!"
  },
  "refreshRate": 30,
  "pushRate": 2,
  "debug": "device"
}
```

### Device & Model

N/A

### Node.js Version

v14.17.5

### NPM Version

v6.14.14

### Homebridge Version

v1.3.8

### Homebridge SwitchBot Plugin Version

v1.2.1-beta.4

### Homebridge Config UI X Plugin Version

N/A

### Operating System

CentOS

**Comment by tomasfreres** [comment]
I have the same problem :)

**Comment by tomasfreres** [comment]
I solved it. You need to add the switch bot manually to the config json

In my case, it looks like this:

`{
    "name": "SwitchBot",
    "credentials": {
        "openToken": "xxxxxxxxxxxxxxxxxx",
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "xxxxxxxxxxxxxxx",
                "configDeviceName": "Bot",
                "hide_device": false,
                "configDeviceType": "Bot",
                "ble": false,
                "bot": {
                    "mode": "switch",
                    "deviceType": "bulb"
                }
            }
        ]
    },
    "platform": "SwitchBot"`

The device ID of the swich is its BLE MAC address

**Comment by robberburn** [comment]
Same here, no push changes with openapi. Devices (Motion and Cantact) all present in Homebridge. Automations not possible.
All devices working with Alexa in routines.

**Comment by jacobio** [comment]
@tomasfreres, yeah, I tried that, too, but it is still throwing the same error.

**Comment by donavanbecker** [comment]
@jacobio please update to v1.2.4 and then provide me with more logs please.

**Comment by jacobio** [comment]
After upgrading to the latest beta, it appears I'm still getting the same error. Here's what's being reporting in my log:

```
Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[SwitchBot] Initializing SwitchBot platform...
[SwitchBot] Using Default Refresh Rate (2 minutes).
[SwitchBot] Using Default Push Rate.
[SwitchBot] Loading accessory from cache: Coffee Maker
[SwitchBot] Total SwitchBot Devices Found: 2
[SwitchBot] Restoring existing accessory from cache: Coffee Maker DeviceID: <elided>
[SwitchBot] Total IR Devices Found: 0
[SwitchBot] Bot: Coffee Maker Displaying as Outlet
[SwitchBot] Bot: Coffee Maker failed pushChanges with OpenAPI Connection
```

**Comment by Maddin1684** [comment]
Same issue. 
yesterday everything works fine with v1.3.0

Today with 1.3.0 „failed to discover devices“

with latest beta:
`[SwitchBot] Light: RGB failed pushChanges with OpenAPI Connection `

**Comment by komihb** [comment]
Same here. at 1.3.0

**Comment by Maddin1684** [comment]
There are server-problems!
 That seems to be the reason why any things don´t work...

`@SwitchBot
·
4 Std.
Connection to the AWS server is back online. However, there are still some delays on the server, or people may be expecting connection issues due to heavy traffic.`

**Comment by donavanbecker** [comment]
I need more logs the logs I am receiving will not help with looking into this. enable device logging from the config.

**Comment by jacobio** [comment]
I've tried changing the `debug` config option to either `device` or `debug` and it doesn't appear that it has any material effect on what's logged. Here's what the relevant portion of my `config.json` looks like:

```json
{
  "platform": "SwitchBot",
  "name": "SwitchBot",
  "credentials": {
    "openToken": "xxx",
    "notice": "Keep your token a secret!"
  },
  "refreshRate": 30,
  "pushRate": 2,
  "debug": "debug"
}
```

**Comment by donavanbecker** [comment]
@jacobio Are you using Homebridge UI?

**Comment by donavanbecker** [comment]
For Bots you need to set the device config settings. I would recommend using Homebridge UI so that it is easier to setup.

**Comment by jacobio** [comment]
Unfortunately, my system isn't configured to use the UI, and I would prefer to keep it that way. I'll play around with enabling debugging for the device. Thanks!

**Comment by jacobio** [comment]
I rebuilt my config and now my bots are working. I must have had a syntax error in the SwitchBot config portion.

**Comment by donavanbecker** [comment]
Awesome!
