### ISSUE TITLE
Support Request: Where is DEVICEID??

### ISSUE THREAD

**Issue by sptv1** [OpenWonderLabs/homebridge-switchbot#1081]
### Describe Your Problem

I cannot find Device ID for a TV that is linked to my mini hub. It works fine controlling it from the app, but can't get the TV into Homebridge.

### Relevant log output

```shell
[SwitchBot] Device: undefined with Device Type: undefined, is currently not supported. Submit Feature Requests Here: https://tinyurl.com/SwitchBotFeatureRequest, device: {"configDeviceName":"TV","deviceId":"0e:74:96:8c:88:72","configRemoteType":"DIY TV","connectionType":"OpenAPI"}
```

### Screenshots

It says Switchbot is running on Homebridge, and I've set up a child bridge and it shows up in HomeKit as a hub. I just can't get my IR TV to show up. It did before, but now with the latest 4.0.0 it disappeared.

### Device & Model

Hub Mini

### Node.js Version

20.18.0

### NPM Version

??

### Homebridge Version

1.8.4

### Homebridge SwitchBot Plugin Version

4.0.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Where did you get your deviceId because that is clearly not an IR deviceId. Can you post all your debug logs?

**Comment by sptv1** [comment]
I don’t have a DeviceID. That’s my problem. I don’t know where to get it.


Steve Pearlman
***@***.***

**Comment by donavanbecker** [comment]
If you don't have a deviceId why would you put in what you put in, in your config? Please remove all your config except your token and secret and turn debug logs on. Your deviceId is in the logs

**Comment by sptv1** [comment]
OK I've done that now. I'm an idiot. I had this working before, so I know this is possible, but for some reason it's not working now since I upgraded to 4.0.0. Here are my logs. I see the TV in Homebridge but it won't show up in HomeKit. I can't add it manually as it doesn't appear in my app.

```
, 09:23:00] [SwitchBot] Restarting child bridge...
[19/10/2024, 09:23:00] Got SIGTERM, shutting down child bridge process...
[19/10/2024, 09:23:05] [SwitchBot] Child bridge process ended
[19/10/2024, 09:23:05] [SwitchBot] Process Ended. Code: 143, Signal: null
[19/10/2024, 09:23:12] [SwitchBot] Restarting Process...
[19/10/2024, 09:23:16] [SwitchBot] Launched child bridge with PID 23363
[19/10/2024, 09:23:29] [SwitchBot] Loaded @switchbot/homebridge-switchbot v4.0.0 child bridge successfully
[19/10/2024, 09:23:31] [SwitchBot] Loading external accessory: Bedroom TV deviceId: 02-202406301011-21797185
```

**Comment by donavanbecker** [comment]
TVs will always be external. So when you go to the Home App, you click add accessories, you don't see the TV? if that is the case you might need to clear the cache of this device in homebridge settings.
