### ISSUE TITLE
Speaker volume up/down in remote app issue

### ISSUE THREAD

**Issue by deflao** [OpenWonderLabs/homebridge-switchbot#11]
**Describe The Bug:**

So I was using the IR remote function to adjust volume up/down for my soundbar. so every time i open remote on my iPhone to adjust the volume, it adjusts but then turn off the soundbar right after. i went to the logs to check, and turn out that everytime you open the remote on iphone and adjust the volume for the 1st time, it will automatically send a 'turn on' request also causing the 'already on soundbar' to turn off

**To Reproduce:**

Press on the volume buttons after open the remote on iphone 
 
**Expected behavior:**

Only to turn the volume up/down without effecting the soundbar current power state

**Logs:**
```
[04/09/2021, 01:38:04] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: volumeAdd parameter: default commandType: command
[04/09/2021, 01:38:04] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: turnOn parameter: default commandType: command
[04/09/2021, 01:38:05] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: volumeAdd parameter: default commandType: command
[04/09/2021, 01:38:06] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: volumeAdd parameter: default commandType: command
[04/09/2021, 01:38:06] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: volumeAdd parameter: default commandType: command
[04/09/2021, 01:38:07] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: volumeAdd parameter: default commandType: command
[04/09/2021, 01:38:07] [SwitchBot] Sending request for Sound Bar DIY Speaker to SwitchBot API. command: volumeAdd parameter: default commandType: command
```
**Homebridge Config:**
```
{
	"name": "SwitchBot",
	"credentials": {
		"openToken": "***",
		"notice": "Keep your token a secret!"
	},
	"devicediscovery": true,
	"platform": "SwitchBot"
}
```
**Screenshots:**

N/A

 **Environment:**

- **Node.js Version**: 14.17.6
- **NPM Version**: 7.22.0
- **Homebridge Version**: 1.3.4
- **Homebridge SwitchBot Plugin Version**: 3.5.0
- **Homebridge Config UI X Plugin Version**: 4.41.2
- **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by donavanbecker** [comment]
@deflao, this is actually not a bug. It looks at the default value, which is off and then when it sends the volume control it also sends the on control so that the speaker turns on.

I could potentially add an option in the config that would ignore on an off if you think that would help?

**Comment by donavanbecker** [comment]
@deflao I have added this into the latest beta if you could give it a test. This beta has major changes in it to the config. 

there is now a device config setting that you must set specific configs for each device.

**Comment by deflao** [comment]
So I tried to remove the current version, clean cached accessories and Unpair Bridges / Cameras / TVs / External Accessories in homebridge setting in order to clean install the beta version you suggested. For some reason, the soundbar and the fan (infrared controlled devices) weren’t showing up in HomeKit or even homebridge accessories.

**Comment by donavanbecker** [comment]
@deflao, I have pushed this into v1.0.0. You can disable power in the config.

**Comment by deflao** [comment]
It works, but it also creates another problem. So I’m able to control the volume up/down in the remote app without the power command. But it also disable the ability to turn on and off the speaker in the Home app.

**Comment by donavanbecker** [comment]
@deflao, this is nothing that I can control, with it being IR, I never get info back from the devices. If you have another idea of how to implement this, let me know.

**Comment by deflao** [comment]
So what I don’t understand is in the Switchbot app, when I control volume up/down it doesn’t produce on/off IR signal, just volume up/down IR signal is produced.
So why is it different when implemented into HomeKit? I would think that in the Home app, it would just simply be an on/off button. Then in the remote app, when adjusting volume up/down it would just simply be volume up/down.
I understand that you said the default value is off and when the volume is adjusted then it will also sending on control but can we remove/ignore the state which it check for default value and going straight to just volume up/down?

**Comment by donavanbecker** [comment]
When you use the Control Center Remote, there isn't an on and off button, so how would you turn your soundbar on if you are are using the Control Center Remote?

This is where the HomeKi Implementation comes into play. It sends a power on every time because it is making sure that the device is on when it is sending the command, then it sends the command (in this case) volume up/down.

**Comment by deflao** [comment]
In that scenario, it would make sense. But let’s say, you have an automation where when you turn on your tv, the speaker turn on. Now the speaker is already on, you use control center remote in order to adjust the volume. Having it sending another power on/off signal will now turn off the speaker, and that’s inconvenient and doesn’t make sense in this scenario.
I think it would make sense to make it works like the Switchbot app where doesn’t matter what state your speaker is, volume up/down will just be volume up/down, no power on/off

**Comment by AtTimesChris** [comment]
Apologies for necro but have been having this issue and came across this, been using my tv and found turning the volume up turned off the tv, able to get this to work as intended by enabling the disable sending on command option but now this has ruined my automations, is there an option to disabled the turn on command on the first input I've missed from this thanks

**Comment by Twox0** [comment]
Hello, I've seen that this problem dates from a long time ago but I have exactly the same, I tried to disable the off and on commands but it still does not work, is there a solution so that the ON command does not send when controlling the volume via the CC Remote? Because I deactivated the ON command but it still sends...
