### ISSUE TITLE
Bug: meter BLE not reading temp

### ISSUE THREAD

**Issue by SeanHama** [OpenWonderLabs/homebridge-switchbot#112]
### Describe The Bug

Bug: meter BLE not reading temp

### To Reproduce

set it up

### Expected behavior

should be reading correct temp

### Relevant log output

```shell
[25/11/2021, 14:43:48] [SwitchBot] [DEVICE] Meter: Meter 59 serviceData: {"model":"T","modelName":"WoSensorTH","temperature":{"c":30.2,"f":86.4},"fahrenheit":false,"humidity":79,"battery":100}
[25/11/2021, 14:43:48] [SwitchBot] [DEVICE] Meter: Meter 59 model: T, modelName: WoSensorTH, temperature: {"c":30.2,"f":86.4}, fahrenheit: false, humidity: 79, battery: 100
[25/11/2021, 14:43:49] [SwitchBot] [DEVICE] Meter: Meter 59 serviceData: {"model":"T","modelName":"WoSensorTH","temperature":{"c":30.2,"f":86.4},"fahrenheit":false,"humidity":79,"battery":100}
[25/11/2021, 14:43:49] [SwitchBot] [DEVICE] Meter: Meter 59 model: T, modelName: WoSensorTH, temperature: {"c":30.2,"f":86.4}, fahrenheit: false, humidity: 79, battery: 100
[25/11/2021, 14:43:49] [SwitchBot] [DEVICE] Meter: Meter 59 serviceData: {"model":"T","modelName":"WoSensorTH","temperature":{"c":30.2,"f":86.4},"fahrenheit":false,"humidity":79,"battery":100}
[25/11/2021, 14:43:49] [SwitchBot] [DEVICE] Meter: Meter 59 model: T, modelName: WoSensorTH, temperature: {"c":30.2,"f":86.4}, fahrenheit: false, humidity: 79, battery: 100
[25/11/2021, 14:43:50] [SwitchBot] [DEVICE] Meter: Meter 59 updateCharacteristic StatusLowBattery: 0
[25/11/2021, 14:43:50] [SwitchBot] [DEVICE] Meter: Meter 59 updateCharacteristic BatteryLevel: 100
[25/11/2021, 14:43:50] [SwitchBot] [DEVICE] Meter: Meter 59 updateCharacteristic CurrentRelativeHumidity: 79
[25/11/2021, 14:43:50] [SwitchBot] [DEVICE] Meter: Meter 59 updateCharacteristic CurrentTemperature: 0

__________________


CURRENTTEMP = 0
Currently it should be 23.8 celcius
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "openToken": "",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xx",
                        "configDeviceName": "Meter 59",
                        "configDeviceType": "Meter",
                        "ble": true
                    }
                ],
                "debug": "device"
            },
            "_bridge": {
                "username": "0E:CD:CA:9D:A4:F4",
                "port": 35673
            },
            "platform": "SwitchBot"
```

### Device & Model

Meter

### Node.js Version

v14.18.1

### NPM Version

v6.14.15

### Homebridge Version

latest

### Homebridge Switchbot Plugin Version

1.2.1

### Operating System

Raspbian

**Comment by SeanHama** [comment]
BTW - re this line in debug - [25/11/2021, 14:43:48] [SwitchBot] [DEVICE] Meter: Meter 59 serviceData: {"model":"T","modelName":"WoSensorTH","temperature":{"c":30.2,"f":86.4},"fahrenheit":false,"humidity":79,"battery":100}

"c":30.2

FYI - my meter is actually 23.9 right now, so that line is not correct

**Comment by donavanbecker** [comment]
@SeanHama that is what I am pulling from the device using node-switchbot

**Comment by SeanHama** [comment]
Something isnt right, see image of my meter right now, a few mins after the ticket raised.
![IMG_8467](https://user-images.githubusercontent.com/57736130/143376833-dcf668f0-2c80-4d7f-ba31-c2c7f7571d4b.jpg)
t
There is a bug somewhere in getting the right temp, and the second one, no temp is showing in HB or HK.

**Comment by donavanbecker** [comment]
try v1.2.2

**Comment by SeanHama** [comment]
Let me try now

**Comment by SeanHama** [comment]
Now the temp is coming thru, but the temp & humidity showing in HB is a completely different to the Temp showing on switchbot device (switchbot device is showing the correct temp)

**Comment by SeanHama** [comment]
Hey, any updates. At the moment this plugin and Switchbot for Homekit is un-useable. Should I be going back to the old plugin?

**Comment by donavanbecker** [comment]
This is definitely a node-SwitchBot issue, which plugin were you using?

**Comment by SeanHama** [comment]
The SwitchBot-ble plugin

>

**Comment by SeanHama** [comment]
Any suggestions on how to fix this "This is definitely a node-SwitchBot issue, which plugin were you using?"

**Comment by donavanbecker** [comment]
@SeanHama, I will have to look at the old plugin, because I am pulling what the API is sending me and pushing to HomeKit.

**Comment by SeanHama** [comment]
Ok please fix, its making all my Temp sensors and home automation dead. Its a real show stopper.

**Comment by donavanbecker** [comment]
@SeanHama please install the latest beta and let me know if it is fixed now?

**Comment by SeanHama** [comment]
![Screen Shot 2021-12-13 at 3 49 54 pm](https://user-images.githubusercontent.com/57736130/145754244-51081bca-0f44-414c-8bb8-b44f682c2618.png)
hmmm, no its still "Not working" - the temp showing on the physical meter switch bot is 23.1 degrees celesius, this plugin is showing over 30degrees (which is incorrect)

**Comment by donavanbecker** [comment]
I am seeing that exact results as I am with the SwitchBot app, so not experiencing the same thing.

@, can you try the newest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.3.1-beta.12/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by SeanHama** [comment]
No 1.3.1.-beta.12 still not working - Ive restart that plugin also after upgrading.

Does my switchbot meter firmware need upgrading (I'm on v2.6)?

This is my HB config.
```
"name": "SwitchBot",
            "credentials": {
                "openToken": "8da9xxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "F2D210301Bxx",
                        "configDeviceName": "Meter 59",
                        "configDeviceType": "Meter",
                        "ble": true
                    }
                ]
            },
            "_bridge": {
                "username": "0E:CD:CA:9D:A4:xx",
                "port": 35673
            },
            "platform": "SwitchBot"
        },
```

**Comment by SeanHama** [comment]
Could there be a caching issue with this plugin and HB?

**Comment by SeanHama** [comment]
![Screen Shot 2021-12-13 at 4 05 43 pm](https://user-images.githubusercontent.com/57736130/145755548-5e35f9c9-7f0c-42ae-8e34-7e0abb345981.png)
 I installed beta13 and this is appearing.

Here is the log
![Screen Shot 2021-12-13 at 4 08 23 pm](https://user-images.githubusercontent.com/57736130/145755696-73a9815b-74b8-48ca-bfca-fc36098cb24d.png)

**Comment by donavanbecker** [comment]
> No 1.3.1.-beta.12 still not working - Ive restart that plugin also after upgrading.
> 
> 
> 
> Does my switchbot meter firmware need upgrading (I'm on v2.6)?
> 
> 
> 
> This is my HB config.
> 
> ```
> "name": "SwitchBot",
> 
>             "credentials": {
> 
>                 "openToken": "8da9xxx",
> 
>                 "notice": "Keep your token a secret!"
> 
>             },
> 
>             "options": {
> 
>                 "devices": [
> 
>                     {
> 
>                         "deviceId": "F2D210301Bxx",
> 
>                         "configDeviceName": "Meter 59",
> 
>                         "configDeviceType": "Meter",
> 
>                         "ble": true
> 
>                     }
> 
>                 ]
> 
>             },
> 
>             "_bridge": {
> 
>                 "username": "0E:CD:CA:9D:A4:xx",
> 
>                 "port": 35673
> 
>             },
> 
>             "platform": "SwitchBot"
> 
>         },
> ```

Firmware is the newest, I wonder if you need to calibrate your meter. Because I am not experiencing this. I will try to emulate this by doing BLE only mode.

**Comment by donavanbecker** [comment]
> ![Screen Shot 2021-12-13 at 4 05 43 pm](https://user-images.githubusercontent.com/57736130/145755548-5e35f9c9-7f0c-42ae-8e34-7e0abb345981.png)
> 
>  I installed beta13 and this is appearing.
> 
> 
> 
> Here is the log
> 
> ![Screen Shot 2021-12-13 at 4 08 23 pm](https://user-images.githubusercontent.com/57736130/145755696-73a9815b-74b8-48ca-bfca-fc36098cb24d.png)
> 
> 
> 
> 

This happens when you don't receive a connection.

**Comment by SeanHama** [comment]
Just incase - this is what is showing in Homekit for the switchbot meter.
Not responding.

**Comment by SeanHama** [comment]
How did you go testing the BLE version?

**Comment by SeanHama** [comment]
I found a workaround for this (I think initial bug still needs fixing). I held onto the reset button on the meter on the back and repair it after restarting the plugin and it works.

**Comment by donavanbecker** [comment]
@SeanHama Awesome. If someone reports again, I will look further
