### ISSUE TITLE
Feature Request: Support for Hub Mini 5E with Device Type: Hub Mini2

### ISSUE THREAD

**Issue by Davide750** [OpenWonderLabs/homebridge-switchbot#1144]
### Problem

When starting the latest release of HomeBridge the Logs report that SwitchBot Hub Mini is not supported and a Feature Request should be raised.

### Solution

Support for SwitchBot Hub Mini

**Comment by donavanbecker** [comment]
Do you have the logs? Also what are you expecting the Hub mini to do?

**Comment by Davide750** [comment]
The Mini Hub hosts a Meter Pro, an Outdoor Meter and seven indoor Thermometer/Hygrometers all of which I hope to display on Apple HomeKit.

HomeBridge is running on an iMac with Sequoia 15.1.1

The initial comment in the Log is:

[12/19/2024, 5:37:32 PM] [SwitchBot] Device: Meter Pro B6 with Device Type: MeterPro, is currently not supported. Submit Feature Requests Here: https://tinyurl.com/SwitchBotFeatureRequest, device: {"deviceId":"B0E9FE5340B6","deviceName":"Meter Pro B6","deviceType":"MeterPro","hubDeviceId":"000000000000”}

This prompted the Feature Request.

The full Log is attached.

Regards,
David

￼

**Comment by donavanbecker** [comment]
This is saying deviceType if meterPro not a hub?

**Comment by Davide750** [comment]
MeterPro is not a hub.On 19 Dec 2024, at 21:31, Donavan Becker ***@***.***> wrote:﻿
This is saying deviceType if meterPro not a hub?

**Comment by Davide750** [comment]
Please close this request. I have replaced the Mini Hub

**Comment by donavanbecker** [comment]
I want to add support? So can you get me logs? Can you try beta for Meter Pro?
