### ISSUE TITLE
Feature Request: Add Support for Switchbot Camera

### ISSUE THREAD

**Issue by smartmatic** [OpenWonderLabs/homebridge-switchbot#12]
**Describe the solution you'd like**

Hello,

i have a the new released SwitchBot camera at home and it would be really nice if the camera can be added in order to work with the plugin. The device discovery text is added in the related section.

Is that possible?

**Additional context**

[23/08/2021, 12:13:47] [SwitchBot] {"deviceId":"xxxxxxx","deviceName":"GarageCam","enableCloudService":true,"hubDeviceId":"xxxxxx"}
[23/08/2021, 12:13:47] [SwitchBot] Device: GarageCam with Device Type: undefined, is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[23/08/2021, 12:13:47] [SwitchBot] deviceStatus - Hub Mini 3C {"statusCode":100,"body":{},"message":"success"}
[23/08/2021, 12:13:47] [SwitchBot] deviceStatus - GarageCam {"statusCode":100,"body":{},"message":"success"}

**Comment by donavanbecker** [comment]
@smartmatic I have created the [homebridge-tuya-camera](https://github.com/donavanbecker/homebridge-tuya-camera) which will give you the `hls` or `rtsp` url, this could potentially be used in the [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg) plugin.

**Comment by smartmatic** [comment]
@donavanbecker Really great news and big thank for this development! I will try to start testing the plugin soon. But one question. You mention in the release notes that RTSP is currently not working. 
Can you estimate when it will be ready?

**Comment by donavanbecker** [comment]
@smartmatic Both really aren't working, because the link will timeout and then you need a new link.

**Comment by djjlipod** [comment]
Is there a update on this, would love to get more cameras for homekit :) thanks for the great plugin so far

**Comment by donavanbecker** [comment]
> Is there a update on this, would love to get more cameras for homekit :) thanks for the great plugin so far

The API doesn't support cameras yet so not possible.

**Comment by EddieDaYankee** [comment]
Trying to expose SwitchBot Indoor Camera to HomeKit via HomeBridge. Any progress on incorporating this into the SwotchBot API or SwitchBot HomeBridge plugin? If not, can someone step me through adding the camera via the Smart Life app and Tuya?

**Comment by donavanbecker** [comment]
nope because SwitchBot hasn't added it to the API.

**Comment by EddieDaYankee** [comment]
I was just looking at your homebridge Tuya camera plugin. I’m not sure I understand your instructions for configuration. It says to fill in the following Tuya, test, test in your Tuya Camera username, password, and host name in the plug-in setting UI. Where exactly does this information go? I have a Tuya IOT platform account where I have other devices linked. I added my SwitchBot indoor cam which I can now see under the Tuya IOT platform. I’m not sure what to do now to try to get my SwitchBot indoor camera exposed in Homekit. any help is appreciated. Thank you.

**Comment by donavanbecker** [comment]
@EddieDaYankee that is a work in progress and we need to wait till camera-ffmpeg can support it.

**Comment by EddieDaYankee** [comment]
Thank you for your reply. I’ll reach out to some of my contacts at SwitchBot and see if I can help nudge them. Thank you for all the work you’ve done helping the GitHub/HomeBridge community.

**Comment by donavanbecker** [comment]
@EddieDaYankee, @smartmatic, & @djjlipod, can you try: [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform)?

Until SwitchBot adds the camera to the API, you will have to remove your camera from the switchbot app, down the tuya app and add your camera. Then follow the instructions from this plugin to get your tuya account hooked up to this plugin.

**Comment by EddieDaYankee** [comment]
I thought you responded to this a while ago? Did something change? Do you need me to test something for the future development of the plugin? I’m happy to help. -EddieOn

**Comment by donavanbecker** [comment]
Use but my plugin did do streaming, this one does.

> [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform)?

**Comment by smartmatic** [comment]
> @EddieDaYankee, @smartmatic, & @djjlipod, can you try: [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform)?
> 
> Until SwitchBot adds the camera to the API, you will have to remove your camera from the switchbot app, down the tuya app and add your camera. Then follow the instructions from this plugin to get your tuya account hooked up to this plugin.

Means its now possible to add either Switchbot Indoor camera or the new Outdoor Spotlight camera by adding tuya account to the Switchbot Plugin?

**Comment by donavanbecker** [comment]
@smartmatic no you will have to remove the SwitchBot cameras from the SwitchBot app and add them into the Tuya app, until SwitchBot opens the API for us.

**Comment by smartmatic** [comment]
Ah ok but that’s nothing new. This is the way i am using the camera in Third Party Software since i have raised this request. But in this case it brings no benefit only you can connect tuya IoT to other plattforms. I ve tried this but the stream quality in this scenario was very bad.

**Comment by donavanbecker** [comment]
@smartmatic, there was no third party that I am aware of that brought the video feed to HomeKit. This plugin I am mentioning does.

I am using it myself, and it is good quality

**Comment by smartmatic** [comment]
Not to Homekit but i am using in the meantime mainly Home Assistant. Then i‘ve added the camera to tuya and added the tuya Integration to Home Assistant and got the stream. Therefore i said Third Party Software instead of Homekit.

**Comment by EddieDaYankee** [comment]
Hi Donavan,Utilizing ***@***.***/homebridge-tuya-platform HomeBridge plug-in you suggested, I was able to add my SwitchBot Camera to Tuya (via http://iot.tuya.com/) and have been able to successfully add it to HomeKit. I get updated screenshots, but I am not getting live streams. When I try, I get the following:[1/28/2023, 12:44:34 PM] ***@***.***×5e/homebridge-tuya-platform] [SwitchBot Indoor Camera] FFmpeg exited with code:1 and signal: null (Error) SwitchBot Indoor Camera
[1/28/2023, 12:44:34 PM ***@***.***×5e/homebridge-tuya-platform][SwitchBot Indoor Camera] Stopped video stream. SwitchBot Indoor CameraAny ideas? I’m using an Apple Mac Pro (from mid-2010) running macOS High Sierra version 10.13.6 with a 3.3GHz 6-Core Intel Xeon processor.Thanks,EddieOn Dec 14, 2022, at 8:00 AM, Donavan Becker ***@***.***> wrote:﻿
@smartmatic, there was no third party that I am aware of that brought the video feed to HomeKit. This plugin I am mentioning does.
I am using it myself, and it is good quality

**Comment by suhajda3** [comment]
Just a quick update that [homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) does support cameras. You just need to remove your SwitchBot Indoor Cam from the SwitchBot app and add it to the Tuya app. You can then connect it to the Tuya IoT Platform and display the stream in HomeKit with homebridge-tuya-platform.

**Comment by donavanbecker** [comment]
@suhajda3 Thanks for reiterating this. Yea this plugin works really good!

**Comment by EddieDaYankee** [comment]
Thank you so much for the update. I just moved and will be re-setting up my smart home soon. I can’t wait to add my cameras.

**Comment by donavanbecker** [comment]
Closing as [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) supports this with Tuya which is what SwitchBot Cameras are.
