### ISSUE TITLE
Support Request: do you need the SwitchBot hub with this plugin?

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#126]
### Describe Your Problem

SwitchBot Hub necessarily requested?

### Relevant log output

```shell
Hello, I’m about to install two Switchbot curtains and I’d like to know if the Switchbot hub is necessarily requested to make this plugin work and see the device in the Home app. Thank you for you support.
```

### Device & Model

N/A

### Node.js Version

14.16.0

### NPM Version

7.6.3

### Homebridge Version

4.41.3

### Homebridge SwitchBot Plugin Version

The latest

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@FranciRoosters You can use it without a hub, you just don't provide the OpenToken

**Comment by FranciRoosters** [comment]
> 

Thank you. I appreciate your answer. I’ve read other users saying that the plugin is somewhat unreliable over BLE. Would using the OpenAPI method make it more reliable? Thank you.

**Comment by donavanbecker** [comment]
You could use both methods if you have a hub, it will try BLE first and if it fails then it will fallback on OpenAPI. 

When using OpenAPI, a hub is required for some devices.

**Comment by FranciRoosters** [comment]
Thanks for getting back to me. I’ll start the configuration of everything tomorrow when I’ll be able to install the SwitchBot curtains on my current rods. I’ve already installed the plugin, but upon installing it I’ve got this. Not really sure what it means as I can still interact with the plugin config page. Will it not work though? Thank you.

**Comment by FranciRoosters** [comment]
Guess it didn’t paste the screenshot, did it? Here you go:

USER: pi
DIR: /usr/local
CMD: sudo
-E
-n pm install
-g @switchb
ot/homebridge-switchbot@latest
pm WARN EBADENGINE Unsupported engine
{
pm WARN EBADENGINE
package:
"@switchbot/homebridge-switchbot@1.3.0
pm WARN EBADENGINE
required:
{ homebridge: ^1.3.8', node: '^14.18.1^16. 13.0}
pm WARN EBADENGINE
current: { node: 'V14.16.0 npm: nom WARN EBADENGINE '7.6.3'}

**Comment by donavanbecker** [comment]
@FranciRoosters You just need to update your node version.

**Comment by FranciRoosters** [comment]
What’s the right sudo command to run in the HB Terminal? Is it safe to execute? I’d rather not mess my setup up. Thank you.

**Comment by bwp91** [comment]
> What’s the right sudo command to run in the HB Terminal? Is it safe to execute? I’d rather not mess my setup up. Thank you.
> […](#)

Follow these steps here!

https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607

**Comment by donavanbecker** [comment]
Thanks @bwp91

**Comment by FranciRoosters** [comment]
Thank you!
