### ISSUE TITLE
Feature Request: Hide Humidity Sensor from Humidifier

### ISSUE THREAD

**Issue by jw172** [OpenWonderLabs/homebridge-switchbot#129]
### Problem

I would like to hide the humidity sensor from my humidifier as I have a more accuarate sensor I'd like to use instead

### Solution

Like the ability to hide the temperature sensor, I'd like to be able to add an entry to the homebridge config hide_humidity=true

**Comment by donavanbecker** [comment]
@jw172, the humidity sensor is a required characteristic needed for HomeKit humidifier accessories. It wouldn’t be possible to hide it.
