### ISSUE TITLE
SwitchBots being triggered multiple times when using Home automation

### ISSUE THREAD

**Issue by jimmyfisher** [OpenWonderLabs/homebridge-switchbot#13]
**Describe The Bug:**

Started noticing that the SwitchBots were running multiple times when triggered by a Home automation. 

I have my house set up with an AppleTV as the main hub. Each evening, I have an automation where the SwitchBots turn on the outdoor lights and then in the morning, they turn them off.

This has been working totally normally until a few days ago (we did have a power outage, so not sure if that triggered something). Seems like each day, it's adding another instance to the trigger. Yesterday was 5x on, this morning 6x off.

**To Reproduce:**

I just let the automation run. If I manually turn on/off the accessory in the Home app, it only runs once. Seems to just be for automation.

**Expected behavior:**

I expect the SwitchBots to perform the same way as when I manually toggle them on/off.

**Logs:**

This is from both last night and this morning. I had upgraded HOOBS to the latest version, hence the initializing log lines:
```
8/13/2021, 4:45:19 PMSwitchBot BridgeBridge is running on port 53826.
8/13/2021, 4:45:19 PMSwitchBot BridgeSwitchBotTotal Devices Found: 3
8/13/2021, 4:45:19 PMSwitchBot BridgeSwitchBotDiscovered Deck Lights Bot
8/13/2021, 4:45:19 PMSwitchBot BridgeSwitchBotRestoring existing accessory from cache: Deck Lights Bot DeviceID: xxxxxxxxxxxxx
8/13/2021, 4:45:19 PMSwitchBot BridgeSwitchBotDiscovered Garage Door Bot
8/13/2021, 4:45:19 PMSwitchBot BridgeSwitchBotRestoring existing accessory from cache: Garage Door Bot DeviceID: xxxxxxxxxxxxx
8/13/2021, 4:45:19 PMSwitchBot BridgeSwitchBotDiscovered a Hub Mini
8/13/2021, 4:58:11 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 4:58:11 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 4:58:50 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/13/2021, 4:58:50 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:40 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:41 PMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOn parameter: default commandType: command
8/13/2021, 7:23:41 PMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOn parameter: default commandType: command


8/14/2021, 6:12:43 AMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:43 AMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Garage Door Bot to SwitchBot API. command: turnOff parameter: default commandType: command
8/14/2021, 6:12:44 AMSwitchBot BridgeSwitchBotSending request for Deck Lights Bot to SwitchBot API. command: turnOff parameter: default commandType: command
```

**Homebridge Config:**

```json
{
    "accessories": [],
    "platforms": [
        {
            "platform": "SwitchBot",
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "openToken": "hidden for security"
            },
            "options": {
                "bot": {
                    "device_switch": [
                        "xxxxxxxxxxxxxx (hidden)",
                        "xxxxxxxxxxxxxx (hidden)",
                    ]
                }
            }
        }
    ]
}
```

**Screenshots:**

These are from the SwitchBot app. This is where I first found the issue. 2 stills per device of the 'Log' section. The one with the red error 'Unknown error (190)' is the same both days.

![IMG_6850](https://user-images.githubusercontent.com/35467099/129452350-da348ee5-61e3-4d3a-bb86-7546f20cbf29.PNG)
![IMG_6851](https://user-images.githubusercontent.com/35467099/129452353-17af6c1f-3454-4c9e-a4a6-05464bcc442a.PNG)
![IMG_6854](https://user-images.githubusercontent.com/35467099/129452354-f9fa9b04-3914-4cff-924c-f15e593c0190.PNG)
![IMG_6855](https://user-images.githubusercontent.com/35467099/129452356-dc500b00-93d1-489e-9353-f471e4fbc458.PNG)

**Device Model:**

Raspberry Pi 4 4GB Model B with 1.5GHz 64-bit quad-core CPU

# **Environment:**

- **Node.js Version**: 14.17.5
- **NPM Version**: 6.14.14
- **Homebridge Version**: 1.3.4
- **Homebridge SwitchBot Plugin Version**:  2.0.5
- **Homebridge Config UI X Plugin Version**: Latest (I believe 4.41.2 but not sure how to check on HOOBS)  
- **Operating System**: Raspbian Buster

**Comment by jimmyfisher** [comment]
Was trying to look through the source code but can't see where any notice from Home would be interpreted (I'm nowhere near as well-versed as you in the code landscape, but figured I'd see if I could be creative)

It does seem odd that the automation is doing this. Prior to setting up this plugin, I was using SwitchBot's built-in Siri shortcuts. Those were also set up as an automation, albeit in the Shortcuts app and running off my iPhone.

When I tap the light button in Home (manually turning on/off), it only sends once. The automation is one that is set up by time of day, based on sunrise/sunset to trigger. All I've done in the Home app is tell it to either turn on or off each of the two SwitchBots in addition to a MagicHome lightbulb that I have (also using a plugin to communicate)

Very odd thing I just tested - when I hit 'Test This Automation' and look at the logs simultaneously, it only sends one request for each, so I think you're correct that there's something weird w the automation when it's running.

But I'm not sure how to troubleshoot. Any ideas?

Thanks again!

**Comment by jimmyfisher** [comment]
Quick update because GitHub marked as closed. 

Sept 23 was the last day that this issue showed in my logs. Starting the 24th, it seemingly went away. Not sure if a SwitchBot app update or my tvOS getting updated to iOS 15.

**Comment by donavanbecker** [comment]
@jimmyfisher Has closed yet, but was marked as stale.

Glad it is working now. I will close now since it is working. Comment if you start seeing issues again.
