### ISSUE TITLE
Feature Request: Auto-Off “Press” SwitchBot

### ISSUE THREAD

**Issue by yungsters** [OpenWonderLabs/homebridge-switchbot#132]
### Problem

I want to automate a “Press” SwitchBot by turning the projected Light Switch to “On”. However, the automation only works once because after the SwitchBot is turned “On”, it stays “On” until turned off.

### Solution

When a SwitchBot is configured to be in “Press” mode, automatically turn the projected Light Switch back to “Off” immediately. This would enable automations that trigger the “Press” to be used repeatedly.

### Additional context

I am using SwitchBot with BLE, without the Hub.

**Comment by donavanbecker** [comment]
@yungsters, this must be a BLE issue, because this is how it is handled in OpenAPI. I will look into this.

**Comment by yungsters** [comment]
Ah, I see.

Good to know… it sounds like I should get the hub and switch to OpenAPI, haha.

My guess is that OpenAPI automatically signals to turn off the switch, and that this needs to be manually emulated for the BLE integration.

**Comment by donavanbecker** [comment]
No I should be able to emulate what I do for the OpenAPI with the BLE connection. Just have to look at what I have set wrong in the code.

**Comment by donavanbecker** [comment]
@yungsters, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.5.1-beta.5/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by yungsters** [comment]
Awesome! I am traveling and not able to test this out until next Wednesday, but I will definitely try the beta out as soon as I can.

**Comment by yungsters** [comment]
@donavanbecker — I've confirmed that using both v1.6.4-beta.5 and v1.7.0, this bug has been fixed. When I use SwitchBot over BLE in "Press" mode, the HomeKit switch automatically turns off now. Thanks!

**Comment by donavanbecker** [comment]
@yungsters, that is good news!
