### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by att11** [OpenWonderLabs/homebridge-switchbot#138]
### Describe Your Problem

Curtains are not visible among homebridge accessories

### Relevant log output

```shell
Have been using the plugin for a while for Curtains, now they disappeared. Within the plugin the curtains show up, outside of it, however, they are not visible, hence cannot see in homekit either.

One error visible in the logs:

[2021. 12. 07. 22:30:04] [SwitchBot] Failed to Discover Devices. "Request failed with status code 504"

Reinstalled the plugin and did the integration again, did not help. Changed the token, paired again, result is the same.
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "openToken": "openToken",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

<img width="781" alt="Képernyőfotó 2021-12-07 - 22 37 25" src="https://user-images.githubusercontent.com/75098355/145110128-050e3f03-504a-463b-b61e-95d942af89fe.png">

### Device & Model

SwitchBot Curtain & Hub Mini

### Node.js Version

 v17.2.0

### NPM Version

 1

### Homebridge Version

1.3.8

### Homebridge SwitchBot Plugin Version

1.3.0

### Homebridge Config UI X Plugin Version

4.41.3

### Operating System

Raspbian

**Comment by att11** [comment]
... and to give it a try, removed the plugin, removed hub mini and reconnected everything again... did not help.

**Comment by anatwo2019** [comment]
@att11 Please remove your openToken from GitHub as it is confidential

**Comment by anatwo2019** [comment]
I have the same issue. The Switchbot integration just stopped working. The error message is the same.

**Comment by att11** [comment]
thanks @anatwo2019, token is changed already. any idea where the problem might be? I even tried to use another plugin, did not help

**Comment by anatwo2019** [comment]
> thanks @anatwo2019, token is changed already. any idea where the problem might be? I even tried to use another plugin, did not help

I have the same issue and no solution. I‘ve already updated everything on my system and reinstalled the plugin. Nothing helped.

**Comment by donavanbecker** [comment]
This is an issue with AWS. AWS was having issues yesterday.
