### ISSUE TITLE
Curtains do not open or close, but its state is reported correctly

### ISSUE THREAD

**Issue by saphierr** [OpenWonderLabs/homebridge-switchbot#14]
**Describe The Bug:**
Curtains no longer respond to open/close commands from homebridge UI or home app on iOS. Closing from the SwitchBot app works fine, and the status change is accurately reflected (i.e. homebridge will successfully receive the status as "Closed" after the curtains have closed using the app) 

Tried reinstalling the plugin/purging cache, and regenerating API key but doesn't seem to fix it.

**To Reproduce:**
Tap the open/close button for the curtains, no response. 

**Expected behavior:**
The curtains would open or close. 

**Logs:**
[6/5/2021, 10:12:32 AM] [SwitchBot] Sending request for Shade Curtain Curtain to SwitchBot API. command: setPosition parameter: 0,ff,0 commandType: command
[6/5/2021, 10:12:33 AM] [SwitchBot] Checking Shade Curtain Curtain Status ...
[6/5/2021, 10:12:38 AM] [SwitchBot] Checking Shade Curtain Curtain Status ...

**Homebridge Config:**

   {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "[redacted]",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }

**Environment:**

* **Node.js Version**: v14.17.0
* **NPM Version**: v6.14.13
* **Homebridge Version**: v1.3.4
* **Homebridge SwitchBot Plugin Version**:  homebridge-switchbot-openapi v3.4.2
* **Homebridge Config UI X Version**: homebridge-config-ui-x v4.41.1
* **Operating System**: Raspbian / Docker
* **Process Supervisor**: Docker

**Comment by saphierr** [comment]
Issue resolved itself :) No configuration changes.

**Comment by smartmatic** [comment]
Facing the same issue but can't find a solution. Please tell your solution, Probably a simple thing i guess...

**Comment by donavanbecker** [comment]
@saphierr I would need more logging so if you can get me logs in debug mode or screenshots from the SwitchBot app showing it erroring out.

**Comment by donavanbecker** [comment]
Just released 1.1.0 which fixes issues with curtains.
