### ISSUE TITLE
Feature Request: ability to select device icon within HomeKit if using OpenAPI connection

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#140]
### Problem

At present, this is only possible through BLE. With OpenAPI, curtains show as blinds, and not actual curtains. 

### Solution

It would be nice to select a different device icon for Curtains if the connection was set up using OpenAPI.

**Comment by donavanbecker** [comment]
@FranciRoosters you can change the icons in HomeKit, if you have light sensors enabled you will have to click on the device icon then click on the Accessories and then click on the curtain icon again and you can change them to one of the following.
![PNG image](https://user-images.githubusercontent.com/9875439/145263232-23a49b87-1613-4cc8-81ef-2a7b32fa8f49.png)

**Comment by FranciRoosters** [comment]
Hi, thank you for replying. I appreciate it. 

Mmm… I’m afraid I didn’t explain myself well. I meant, how do you change the icon of your curtain device on the Home app once you’ve already added it through OpenAPI? I cannot edit my curtain devices in Homebridge since they’re not listed under Optional SwitchBot Device Settings. I’m afraid of touching them since it took me a while to get everything to work the way I wanted.

Thank you for your support,
Francesco

**Comment by FranciRoosters** [comment]
I just realized that somehow the light sensor is enabled because I see the lux sensor in the Home app. Yet, I cannot change the icon.

**Comment by donavanbecker** [comment]
I guess I am not sure what you mean then by changing icon. You can change settings on devices, by going to the devices tab and finding the curtain from the drop down, then copy deviceID and Add it to the Optional SwitchBot Device settings.

**Comment by zeroecho** [comment]
> @FranciRoosters you can change the icons in HomeKit, if you have light sensors enabled you will have to click on the device icon then click on the Accessories and then click on the curtain icon again and you can change them to one of the following.
> ![PNG image](https://user-images.githubusercontent.com/9875439/145263232-23a49b87-1613-4cc8-81ef-2a7b32fa8f49.png)

I didn't know you could change this, this is awesome! Working great for me and I'm using OpenAPI and have the lux sensor enabled still
