### ISSUE TITLE
Add Water Level to Humidifier

### ISSUE THREAD

**Issue by chrisschlitt** [OpenWonderLabs/homebridge-switchbot#15]
**Is your feature request related to a problem? Please describe.**

I want to be able to trigger Siri Shortcuts based on the water level

**Describe the solution you'd like**

Expose the water level as a sensor, so that a change to a certain percentage (or empty) can be used as a trigger in Siri Shortcuts. This way I can add a reminder notification for when the tank is low

**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment]
@chrisschlitt this has been added to the @switchbot/homebridge-switchbot plugin. You will need to move over to the new plugin to gain this feature.
