### ISSUE TITLE
Bug: npm ERR! code 1

### ISSUE THREAD

**Issue by DerTiger1** [OpenWonderLabs/homebridge-switchbot#151]
### Describe The Bug

Update or new installtion not possible see messages

### To Reproduce

update on RasbPi fails, same issue on new installation on synolog NAS

### Expected behavior

succesfull update

### Relevant log output

```shell
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | arm
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python3"
npm ERR! gyp ERR! find Python - version is "3.5.3"
npm ERR! gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python"
npm ERR! gyp ERR! find Python - version is "2.7.13"
npm ERR! gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:297:7)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:388:7)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:450:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
npm ERR! gyp ERR! System Linux 4.19.66-v7+
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-12-19T11_20_56_009Z-debug.log
```

### Config for homebridge-switchbot

```shell
{
            "platform": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "openToken": "xxx"
            },
            "name": "SwitchBot"
        },
```

### Device & Model

RasbPi 3 / Synology DS220+

### Node.js Version

v16.13.1

### NPM Version

v8.1.2

### Homebridge Version

v4.41.5 

### Homebridge Switchbot Plugin Version

v1.3.0

### Homebridge Config UI X Plugin Version

v4.41.5 

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
any update @DerTiger1?

**Comment by DerTiger1** [comment]
[2021-12-29T11_13_14_274Z-debug.log](https://github.com/OpenWonderLabs/homebridge-switchbot/files/7788562/2021-12-29T11_13_14_274Z-debug.log)
@donavanbecker, tested with 1.5 - still the same issue.
Edit 211229: It worked with an earlier npm version: npm 7.24.2
see: [https://forum.smartapfel.de/forum/thread/9091-npm-err-gyp-err-find-python-is-not-set-from-command-line-or-npm-configuration/](url)

**Comment by lotfielhafi** [comment]
I have the exact same issue with a fresh install on my Synology NAS DS716+II (Intel Celeron) on DSM 7.0.1-42218 with the Synology Homebridge package (https://github.com/oznu/homebridge-syno-spk#how-to-install) and Node.js v16.13.1 / Npm v6.14.11.


```USER: homebridge
DIR: /volume1/@appdata/homebridge
CMD: npm install -g @switchbot/homebridge-switchbot@latest

npm ERR! code 1
npm ERR! path /volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.8 found at "/usr/bin/python3.8"
npm ERR! gyp info spawn /usr/bin/python3.8
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/packages/homebridge/home/.cache/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/var/packages/homebridge/home/.cache/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/var/packages/homebridge/home/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 3.10.108
npm ERR! gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /volume1/@appdata/homebridge/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2022-01-02T00_25_03_436Z-debug.log

Command failed. Please review log for details.```

**Comment by donavanbecker** [comment]
This is a noble issue, you must install perquisites first

**Comment by lotfielhafi** [comment]
@donavanbecker thank you for your response.

I thought that `noble` was not required if I only wanted to use the OpenAPI.
Since I prefer to avoid installing `noble` directly on my NAS, I will test on a separate Raspberry Pi.

**Comment by donavanbecker** [comment]
@lotfielhafi I have it as a required dependency, right now.

**Comment by lotfielhafi** [comment]
I confirm that the installation works on a Raspberry Pi 3 B 4GB using the latest Homebride image (https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started).

**Comment by donavanbecker** [comment]
okay I am making `node-switchbot` an optionalDependencies which is why `@abandonware/noble` is trying to install, but then BLE will not work if you can't get node-switchbot installed.

**Comment by donavanbecker** [comment]
v1.6.1 has been released which will fix this, but will not allow BLE connection, since node-switchbot will not install.

**Comment by frimar75** [comment]
Now the update worked, but after restart : 

====================
[2.1.2022, 23:07:12] ERROR LOADING PLUGIN @switchbot/homebridge-switchbot:
[2.1.2022, 23:07:12] Error: Cannot find module 'node-switchbot'
Require stack:
- /usr/lib/node_modules/@switchbot/homebridge-switchbot/dist/devices/bots.js
- /usr/lib/node_modules/@switchbot/homebridge-switchbot/dist/platform.js
- /usr/lib/node_modules/@switchbot/homebridge-switchbot/dist/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[2.1.2022, 23:07:12] ====================

As a result, the plugin isn´t loaded at all ...

**Comment by donavanbecker** [comment]
@frimar75, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.6.2-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by frimar75** [comment]
Tried it, updated and homebridge restarted without any issues, so it seems to work. Thumbs up, thank you.

**Comment by DerTiger1** [comment]
I can confirm it - it's working here too with 1.6.2 . Many thanks !!!

**Comment by donavanbecker** [comment]
@frimar75 and @DerTiger1, can you test the latest beta? I have made another change and want to make sure this is still working? 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.6.2-beta.1/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

**Comment by frimar75** [comment]
Just installed it and as far as it belongs to installation and Homebridge restart, everything looks good, no issues, so far. In HomeKit it also seems to be working...

**Comment by donavanbecker** [comment]
Thanks, when I get time I will push out an update.

**Comment by donavanbecker** [comment]
@frimar75 Can you try one more thing for me? Set up a device in the SwitchBot config and select the BLE as if you were going to enable BLE for that specific device and see if you get any issues, besides a log that says not able to connect with BLE.

Like any homebridge restarts?

**Comment by frimar75** [comment]
![image](https://user-images.githubusercontent.com/66782016/147957245-b5bd95fc-1a22-429f-8eda-ec51f646e397.jpeg)


The only thing that pops up, after the restart, is a short note about a missing "config section"...

**Comment by frimar75** [comment]
But besides that, the plug-in starts normal...

**Comment by donavanbecker** [comment]
> ![image](https://user-images.githubusercontent.com/66782016/147957245-b5bd95fc-1a22-429f-8eda-ec51f646e397.jpeg)
> 
> 
> The only thing that pops up, after the restart, is a short note about a missing "config section"...

You will have to set the device type to Bot then that should got away. Then report back again, please.

**Comment by frimar75** [comment]
When removing BLE again the message doesn't show up on restart...

**Comment by frimar75** [comment]
Yes I can confirm that, after setting Type to bot the message doesn't show up again...

**Comment by frimar75** [comment]
But...

![image](https://user-images.githubusercontent.com/66782016/147958236-48d46c2c-87c1-4f40-8eef-8b7aa60841c3.jpeg)

**Comment by frimar75** [comment]
The bridge restarts over and over again...

**Comment by donavanbecker** [comment]
> But...
> 
> <a><img src="https://user-images.githubusercontent.com/66782016/147958236-48d46c2c-87c1-4f40-8eef-8b7aa60841c3.jpeg" width="350px"></a>
> 
> 

This is what I needed!! Thanks. I will fix this. Then can you test again?

**Comment by frimar75** [comment]
Of course 👍

I'm glad, being able to help you.

**Comment by donavanbecker** [comment]
> Of course 👍
> 
> I'm glad, being able to help you.

okay last test. I just pushed a new beta:

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.6.2-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

**Comment by frimar75** [comment]
> > Of course 👍
> 
> > 
> 
> > I'm glad, being able to help you.
> 
> 
> 
> okay last test. I just pushed a new beta:
> 
> 
> 
> [![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.6.2-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)
> 
> 

Okay, just this short message ...
![image](https://user-images.githubusercontent.com/66782016/147968988-d2616c89-01fb-44f0-842f-e2bd8aeac03e.jpeg)

Bridge works👍

**Comment by donavanbecker** [comment]
> > > Of course 👍
> > 
> > 
> > > 
> > 
> > 
> > > I'm glad, being able to help you.
> > 
> > 
> > okay last test. I just pushed a new beta:
> > [![npm version](https://camo.githubusercontent.com/014abf54d4c1ffa4b8e12eeaa83043748957c80d78e4c50d2e2c5b4f2ee84756/68747470733a2f2f62616467656e2e6e65742f62616467652f686f6d656272696467652d737769746368626f7440626574612f2533453d312e362e322d626574612e322f6f72616e6765)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)
> 
> Okay, just this short message ... ![image](https://user-images.githubusercontent.com/66782016/147968988-d2616c89-01fb-44f0-842f-e2bd8aeac03e.jpeg)
> 
> Bridge works👍

This is exactly what I needed to finish this up! Thanks @frimar75!

**Comment by donavanbecker** [comment]
v1.6.2 has been released.
