### ISSUE TITLE
Add Battery Status

### ISSUE THREAD

**Issue by stich86** [OpenWonderLabs/homebridge-switchbot#16]
**Is your feature request related to a problem? Please describe.**

Add the battery status to check it from HK

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment]
@stich86 this is added in the latest beta when BLE is enabled.

**Comment by donavanbecker** [comment]
This is in v1.0.0, when connected through BLE
