### ISSUE TITLE
Bug: HOOBS: Warning plugin site unavailable and the plugin installation fails

### ISSUE THREAD

**Issue by PBXLthrMan** [OpenWonderLabs/homebridge-switchbot#162]
### Describe The Bug

I'm trying to install the certified HOOBS Plugin SwitchBot and I keep getting Warning plugin site unavailable and the plugin installation fails.

### To Reproduce

Launch HOOBS. Go into Plugins. Search for SwitchBot. Click SwitchBot (Certified). Click install

### Expected behavior

A successful installation 

### Relevant log output

```shell
12/26/2021, 11:23:13 PMSwitchbot Bridge starting
12/26/2021, 11:23:36 PMWARNINGplugin site unavailable
12/26/2021, 11:23:39 PMSwitchbot BridgeWARNINGNo plugins installed.
12/26/2021, 11:23:40 PMSwitchbot BridgeBridge is running on port 51866.
12/26/2021, 11:24:46 PMAlexa BridgeAlexaERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.
12/26/2021, 11:27:54 PMWARNINGplugin site unavailable
12/26/2021, 11:27:54 PMWARNINGplugin site unavailable
12/26/2021, 11:27:54 PMWARNINGplugin site unavailable
12/26/2021, 11:31:50 PMWARNINGplugin site unavailable
12/26/2021, 11:31:50 PMWARNINGplugin site unavailable
12/26/2021, 11:31:50 PMWARNINGplugin site unavailable
12/26/2021, 11:31:51 PMAlexa BridgeAlexaERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

Then goes to: "Unable to install plugin. Please try again."
```

### Config for homebridge-switchbot

```shell
Unable to install.
```

### Device & Model

HOOBS 4.x

### Node.js Version

v14.17.6 (unsure)

### NPM Version

v4.0.0

### Homebridge Version

v1.3.4

### Homebridge Switchbot Plugin Version

v2.0.5

### Homebridge Config UI X Plugin Version

HOOBS- v4.0.109

### Operating System

MacOS

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
