### ISSUE TITLE
Feature Request: Show ON/OFF status of controlled device by "press" mode Switchbot

### ISSUE THREAD

**Issue by 618116** [OpenWonderLabs/homebridge-switchbot#165]
### Problem

Currently ON/OFF status of Switchbot in Home app represents status of Switchbot itself. Therefore when I turn on Switchbot which is "press" mode, it goes to OFF status by itself. However controlled device remains turned On, because it is only pressed once.

### Solution

I hope there is an option to change On/Off status by one turning on/off cycle of Switchbot itself. It will represent actual devices status and not Switchbot itself.

**Comment by donavanbecker** [comment]
@618116, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.5.1-beta.5/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by 618116** [comment]
Tried Beta, but it seems doesn't work. Am I missing an option?

**Comment by donavanbecker** [comment]
Can you post your config?

Also take a look at the [Configuration](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Configuration) wiki page.

**Comment by 618116** [comment]
I'm not sure it is expected behavior, when I set to "Switch mode" in the HomeBridge plugin, It works as I want: doing a On/Off cycle by one touch in Home app, and Home app status changes only once by one touch.
By the way, in SwitchBot app the Bot is still set as "Press mode".

**Comment by donavanbecker** [comment]
> I'm not sure it is expected behavior, when I set to "Switch mode" in the HomeBridge plugin, It works as I want: doing a On/Off cycle by one touch in Home app, and Home app status changes only once by one touch.
> 
> By the way, in SwitchBot app the Bot is still set as "Press mode". 

Yes, because you need to set it to match the SwitchBot App. So I would set it to Press mode in the plugin settings.

**Comment by 618116** [comment]
Press mode still doesn't work as expected. The Home app status still shows status of SwitchBot; when I touch SwitchBot in the Home app, it turns on and off by itself. What I want to suggest is switch mode like on/off status when in the press mode.

Log from HomeBridge plugin and current setting are below.
> [1/2/2022, 11:44:29 AM] [SwitchBot] Bot: ボット Sending request to SwitchBot API. command: press, parameter: default, commandType: command
<img width="690" alt="スクリーンショット 2022-01-02 11 45 00" src="https://user-images.githubusercontent.com/5267536/147864677-53e78375-c276-41d2-bb9d-f12ab494d925.png">

**Comment by donavanbecker** [comment]
Press will always go on and then off.

**Comment by 618116** [comment]
I know it is current behavior. I just suggest there is an option.

**Comment by donavanbecker** [comment]
That is what Switch mode is for.

**Comment by 618116** [comment]
As I understand, Switch mode doesn't have on/off cycle of SwitchBot bot device, does it?
My controlled device have simple power button, so I want to use my Bot as press mode; And check controlled device's on/off status in Home app, not status of Bot itself.

**Comment by 618116** [comment]
So it seems it is an opposite situation of #132.

**Comment by donavanbecker** [comment]
@618116 Can you just set it as mode switch in homebridge. And it will work as you are wanting?

I guess I could change the mode from `switch` and `press` to stateless or not? Or just define that press is stateless.

**Comment by 618116** [comment]
Switch mode in HomeBridgh plugin + Press mode in SwitchBot app doing what I want, so I'll close the issue.

**Comment by sam-cheuk** [comment]
Is that the "Switch mode in HomeBridge plugin + Press mode in SwitchBot app" no longer works in recent versions? I found the bot state in Home app always reverted to OFF after upgraded.

**Comment by darkaeden** [comment]
> Is that the "Switch mode in HomeBridge plugin + Press mode in SwitchBot app" no longer works in recent versions? I found the bot state in Home app always reverted to OFF after upgraded.

confirm, same here.
