### ISSUE TITLE
Feature Request: Add support for Bot password

### ISSUE THREAD

**Issue by GcoGr** [OpenWonderLabs/homebridge-switchbot#166]
### Problem

My Switchbot bots don't move. I guess it's because I've set a password for each bot

### Solution

In the plugin configuration you should be able to set up the password for each bot

### Alternatives

Maybe the plugin could manage just one bot, then I would install multiple instances of the plugin, one for each bot?

### Additional context

If you don't set a password for the bots, it's easy to activate them just downloading the Switchbot App

**Comment by donavanbecker** [comment]
Would have to wait for OpenAPI or BLEAPI (node-switchbot) to support this.

**Comment by GcoGr** [comment]
After updating today to plugin 1.6.3, the 2 bots are responding. One of them still has a password, and I had removed the password from the second one, but none of them worked with the previous version of the plugin I had. Thank you for the fix.
They show up in Homekit as electric outlets, I wonder if they could show up as something like a "button" to press. I guess this is not the right place, so I will look for this information in the discussions tab. Thanks again.

**Comment by donavanbecker** [comment]
@GcoGr I didn't chandeliers anything so must be something on the SwitchBot side.

As for displaying it different, HomeKit has stateless buttons that are only really for automations, so would be practical in this situation.

I can potentially do other device types that HomeKit allows though. Like recently I added garage door and door as options in the latest beta.

**Comment by donavanbecker** [comment]
in v1.7.0, I added multiple different Device Types. If there is something else that you would like me to add let me know by opening another feature request.
