### ISSUE TITLE
Support Request: IR Fan

### ISSUE THREAD

**Issue by deanpribetic** [OpenWonderLabs/homebridge-switchbot#17]
### Describe Your Problem

Accessing Dyson Fan via Homebridge

### Relevant log output

```shell
I have an older Dyson fan that I have set up via "Others" with the Switchbot Mini to turn ON and OFF. This works fine through the SwitchBot app, and also if I export to Siri shortcuts. However, I cannot get the device to work at all through Homebridge. 

I have set the device up via `IR Device Settings > Others Settings > Fan` with On and Off as the commands. Now if I try via the Home app it sends the On command but the fan won't come on. Any thoughts?
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "openToken": HIDDEN,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "other": {
                    "deviceType": "Fan"
                }
            },
            "platform": "SwitchBot"
```

### Device & Model

SwitchBot Hub Mini v1.7-1.9

### Node.js Version

v14.17.5

### NPM Version

v6.14.14

### Homebridge Version

v1.3.4

### Homebridge SwitchBot Plugin Version

v0.1.1

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

macOS

**Comment by donavanbecker** [comment]
@deanpribetic Do you have screens of logs or errors from the SwitchBot app

**Comment by deanpribetic** [comment]
> @deanpribetic Do you have screens of logs or errors from the SwitchBot app

Hey Donavan - it appears the On Command is not set?

**Comment by donavanbecker** [comment]
> > @deanpribetic Do you have screens of logs or errors from the SwitchBot app
> 
> 
> 
> Hey Donavan - it appears the On Command is not set?

I need logs and screenshots.

**Comment by deanpribetic** [comment]
Fair enough. I think I've worked it out. Re-programmed the Switchbot with a DIY Fan and it seems to be working now. Sorry for wasting your time!
