### ISSUE TITLE
Bug: Reboot causes No Device Type Set Error

### ISSUE THREAD

**Issue by wilLTes21** [OpenWonderLabs/homebridge-switchbot#172]
### Describe The Bug

When rebooting the Homebridge UI on a RPI4, the 1st reboot appears to have an issue where the Device Type set is not seen by the plugin, once going into the Apple Home app, then coming back and doing a 2nd reboot, it corrects itself.

### To Reproduce

Reboot the RPI

### Expected behavior

Reboot does not cause error

### Relevant log output

```shell
[Swithbot] Other: Fire place No Device Type Set, deviceType: Fan
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "removed",
                "notice": "Keep your token a secret!"
            },
```

### Screenshots

![Log](https://user-images.githubusercontent.com/96880231/147767615-17d140d3-0f7d-4d55-b68a-6037729cc15e.jpeg)

### Device & Model

Raspberry Pi 4

### Node.js Version

v16.13.1

### NPM Version

v8.1.2

### Homebridge Version

v1.3.9

### Homebridge Switchbot Plugin Version

v1.5.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Should be fixed in latest beta

**Comment by wilLTes21** [comment]
This is working properly now with latest beta. Thank you.
