### ISSUE TITLE
Bug: TV function - ON/OFF, but no Volumes control

### ISSUE THREAD

**Issue by avinin1** [OpenWonderLabs/homebridge-switchbot#178]
### Describe The Bug

After adding the TV function, there is only option to turn on/off, with no options to increase or decrease the volume

### To Reproduce

Just add the TV IR controller into the plugin config and look for the Volume buttons

### Expected behavior

'Supported Devices' page says: "TV Allows for On/Off and Volume Controls"

### Relevant log output

```shell
the volume buttons just missing.
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "******",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "****",
                        "configDeviceType": "Bot",
                        "ble": false,
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "****",
                        "configRemoteType": "DIY TV",
                        "logging": "standard"
                    }
                ],
                "logging": "standard"
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

![3bf7fb8d-1182-48e9-bda7-2dfb54e18daa](https://user-images.githubusercontent.com/87506988/147842415-54c4eba1-e9b2-4cef-9e2b-d741dfccede8.jpg)
![399478a1-77db-40c0-8df7-78b491a156b1](https://user-images.githubusercontent.com/87506988/147842417-c11e6bcd-f361-43dd-9555-992ebe9a71d2.jpg)

### Device & Model

Raspbian 4

### Node.js Version

16.13.0

### NPM Version

v8.1.0

### Homebridge Version

v1.3.9

### Homebridge Switchbot Plugin Version

1.6.0

### Homebridge Config UI X Plugin Version

v4.41.5

### Operating System

Raspbian GNU/Linux Buster (10)

**Comment by donavanbecker** [comment]
@avinin1 volume control is only available in the Control Center Remote, using your iOS devices volume button when control the TV from the CC Remote.
