### ISSUE TITLE
Bot showing as door opener?

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#179]
### Describe Your Problem

Planning to buy a SwitchBot bot to automate my building’s main door. Can I set the bot to show as a door so Siri understands me when I say “unlock main door”? Thank you!

### Device & Model

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Homebridge Version

N/A

### Homebridge SwitchBot Plugin Version

Latest

### Operating System

N/A

**Comment by donavanbecker** [comment]
I could try, but there are some characteristics that are required that make this hard.

**Comment by FranciRoosters** [comment]
It would be a nice feature for those who rent and have intercoms. I’ll set up a Siri shortcut in the meantime.

**Comment by donavanbecker** [comment]
@FranciRoosters, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.6.4-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

I have added the option of deviceType garage door

**Comment by FranciRoosters** [comment]
Thank you. I appreciate your work. Could you also add the simple door icon? That’s what I’d really need as I don’t own a garage.

**Comment by donavanbecker** [comment]
@FranciRoosters, ok let's try the next beta:

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.6.4-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

**Comment by FranciRoosters** [comment]
Sweet. That was fast, thank you. Will report back in a couple of days. 🙂

**Comment by FranciRoosters** [comment]
So, after a bit of testing with both door types (Garage Door and Door), the bot responds fine to the Garage Door icon but is unresponsive to the Door icon. I wonder if that’s something that is natively supported by HomeKit since all I’ve ever seen spinning (Opening…) while unlocking are either Garage Doors indeed or actual Locks. Maybe, if it’s not too much of a hassle, you could try fixing things while keeping the Door icon and if that doesn’t work, try implementing the Lock icon. Let me know what you think and thank you so much again for you support and hard work.

**Comment by donavanbecker** [comment]
I am also having issues with the door after testing. 

Let's do both, when I get time I will try to fix the door and add the lock.

**Comment by FranciRoosters** [comment]
Brilliant! Thank you.

**Comment by donavanbecker** [comment]
Just added Lock, I haven't been able to improve door yet.

**Comment by FranciRoosters** [comment]
Lock works like a charm, thank you so much! It even makes more sense to show as a Lock given my circumstances. This will make a lot of sense for those who, like me, will want to use a SwitchBot to unlock a building’s front door using their apartment’s intercom. Again, thanks a lot for your contribution!

**Comment by donavanbecker** [comment]
@FranciRoosters would you retest Door again? I pushed a fix.

**Comment by FranciRoosters** [comment]
Will do and report back.

**Comment by FranciRoosters** [comment]
Works great. Awesome job! Thank you again!

**Comment by donavanbecker** [comment]
> Works great. Awesome job! Thank you again!

Perfect! I will post a new release soon.

**Comment by donavanbecker** [comment]
Might add other device types while I'm at it as well. Ha

**Comment by donavanbecker** [comment]
v1.7.0 has been released.

**Comment by adamrzanek** [comment]
OMG thanks for this! Now i will buy one more bot for intercom door opener! :D
