### ISSUE TITLE
Bug: Curtain doesn’t response with Bluetooth.

### ISSUE THREAD

**Issue by WaldperlachFabi** [OpenWonderLabs/homebridge-switchbot#189]
### Describe The Bug

If i try to open/close the curtain with BLE in HomeKit, nothing happens and i gat a error in the console.

### To Reproduce

Open/close curtain in HomeKit

### Expected behavior

The curtain should open/close

### Relevant log output

```shell
[1/6/2022
2:33:47 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic "Current Position characteristic valueexpected valid finite number and received
"NaN" (number). See https:/git.io/JtMGR for more info.
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "SECRET TOKEN:-)",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "F9:F0:92:DF:35:36",
                        "configDeviceName": "Contact Sensor",
                        "configDeviceType": "Contact Sensor",
                        "ble": true
                    },
                    {
                        "deviceId": "D4:93:0C:61:65:24",
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "ble": true,
                        "curtain": {
                            "set_minStep": 20
                        }
                    },
                    {
                        "deviceId": "E2:80:1D:9D:64:5F",
                        "configDeviceType": "Motion Sensor",
                        "ble": true
                    },
                    {
                        "deviceId": "CF:F4:66:59:1F:20",
                        "configDeviceType": "Meter",
                        "ble": true
                    }
                ]
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

![BBB7A297-49F2-45E9-9353-C618E05EF834](https://user-images.githubusercontent.com/80318133/148391416-730975b5-db63-4e4a-a7bb-c16055ff0227.jpeg)

### Device & Model

SwitchBot Curtain

### Node.js Version

V14.17.3

### NPM Version

V6.14.13

### Homebridge Version

V1.3.9

### Homebridge Switchbot Plugin Version

V1.7.0

### Homebridge Config UI X Plugin Version

V4.41.5

### Operating System

Docker

**Comment by WaldperlachFabi** [comment]
![5E56C987-D594-49B0-B7C0-648274D49724](https://user-images.githubusercontent.com/80318133/148392447-6b814db5-8fb2-42fd-ab9a-0b2da85f23df.jpeg)

**Comment by donavanbecker** [comment]
@WaldperlachFabi Node-SwitchBot didn't get installed.

**Comment by WaldperlachFabi** [comment]
> 

How can I install it?

**Comment by donavanbecker** [comment]
node-switchbot can fail to install because the dependency: `@abandonware/noble` has prerequisites

You will need to follow the prerequisites for [docker](https://github.com/abandonware/noble#docker)

Once done then reinstall plugin.
