### ISSUE TITLE
Support Request: How to change bot device type from electric outlet to press button

### ISSUE THREAD

**Issue by GcoGr** [OpenWonderLabs/homebridge-switchbot#190]
### Describe Your Problem

My bots display as electric outlets instead of press buttons. I'd like them to display as press buttons

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "openToken": "xxx",
        "notice": "Keep your token a secret!"
    },
    "platform": "SwitchBot"
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/96777527/148525759-81ed6c4a-fe4d-4315-b95a-19b0d3e6e85d.png)

### Device & Model

switchbot bot

### Node.js Version

v16.13.1

### NPM Version

v8.3.0

### Homebridge Version

v1.3.9

### Homebridge SwitchBot Plugin Version

v1.7.0

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by donavanbecker** [comment]
There is a [StatefulProgrammableSwitch](https://developers.homebridge.io/#/service/StatefulProgrammableSwitch) that might work. But I have recently added other device types to the device config that you can look at. What are you using the Bot for?

**Comment by GcoGr** [comment]
I am using the bot to press a button in the RFID remote of a garage door. The command should always be PRESS. When the door is open, it closes. When it is closed, it opens with the same press. The second bot does the same thing in another door. I want to control them via a Homepod mini by a single command like PRESS DOOR ONE. Currently, I must previously know the status of the “electric outlet” to say TURN ON DOOR ONE or TURN OFF DOOR ONE even if the actual status of the door is the opposite. Thank  you for your response.

**Comment by donavanbecker** [comment]
> I am using the bot to press a button in the RFID remote of a garage door. The command should always be PRESS. When the door is open, it closes. When it is closed, it opens with the same press. The second bot does the same thing in another door. I want to control them via a Homepod mini by a single command like PRESS DOOR ONE. Currently, I must previously know the status of the “electric outlet” to say TURN ON DOOR ONE or TURN OFF DOOR ONE even if the actual status of the door is the opposite. Thank  you for your response. 

My recommendation would be to use `Device Type` = `Door` and `Garage Door` that I have for options for boys. And use `switch` mode.

All of this is already built into the plugin settings. You just need to set it.

**Comment by GcoGr** [comment]
The problem is that the device 'remembers' the status. Right now the garage door is closed but the device status is displayed in Home app as 'open'. So, when I say "Hey Siri, open door" it does nothing because it thinks it is already open. Updating this status to match the real world wouldn't work, because often we open/close the door manually using a different RFID remote. It is the same problem for "electric outlet", "door" and "garage door".
There is another problem I don't know how to fix. When I say "Hey Siri, open door" to the Homepod mini, she says "You must go on in your personal device" and then I must confirm the operation in the iPhone. I understand this problem is not related to your plugin, you're doing a great work.

**Comment by jdefelice** [comment]
I have a similar use case.

I’m using the SwitchBot to turn on my heating. The button turns the heating on for 1 hour and shuts off. When the heating is off the state gets out of sync.

I would like to be able to just say press the button.

**Comment by donavanbecker** [comment]
@jdefelice Set mode on not to press in the device settings.

**Comment by GcoGr** [comment]
Done! Both switchbots work as expected now! Thank you!
Next step for me will be to get working IR control for TV On/Off and TV Speaker On/Off.
Thanks again!
I will post here my configuration, as it might be useful for other readers:

{
    "name": "SwitchBot",
    "credentials": {
        "openToken": "(my token)",
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "(Mac Address for Switchbot 1)",
                "configDeviceName": "Cancela",
                "configDeviceType": "Bot",
                "bot": {
                    "mode": "press",
                    "deviceType": "garagedoor"
                }
            },
            {
                "deviceId": "(Mac Address for Switchbot 2)",
                "configDeviceName": "Porton",
                "configDeviceType": "Bot",
                "bot": {
                    "mode": "press",
                    "deviceType": "garagedoor"
                }
            }
        ]
    },
    "platform": "SwitchBot"
}
