### ISSUE TITLE
Bug: TV controls for IR hub mini don't show up in iPhone Home App. Also, Speaker ON/OFF button does not work

### ISSUE THREAD

**Issue by GcoGr** [OpenWonderLabs/homebridge-switchbot#191]
### Describe The Bug

The "Accessories" tab of the Homebridge portal shows a square for TV ON/OFF that works OK, and a second button for TV Speaker ON/Silence that does not work. None of them are shown in the iPhone Home App.

### To Reproduce

Don't know.

### Expected behavior

I would expect the TV control buttons to appear in the Homekit App in the iPhone. Also, I would expect the Speaker button to work.

### Relevant log output

```shell
[07/01/2022, 11:01:14] [SwitchBot] DIY TV: LG 49UB850V Sending request to SwitchBot API. command: turnOn, parameter: default, commandType: command
[07/01/2022, 11:08:45] [Homebridge UI] [admin] Accessory layout changes saved.
[07/01/2022, 11:09:27] [SwitchBot] DIY TV: LG 49UB850V Sending request to SwitchBot API. command: turnOff, parameter: default, commandType: command
[07/01/2022, 11:11:22] [Homebridge UI] [admin] Accessory layout changes saved.
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "openToken": "xxx",
        "notice": "Keep your token a secret!"
    },
    "platform": "SwitchBot"
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/96777527/148550337-a67bfcaa-bc3d-46ac-826e-f8ce082be6ca.png)

### Device & Model

Switchbot hub mini

### Node.js Version

v16.13.1

### NPM Version

v8.3.0

### Homebridge Version

v1.3.9

### Homebridge Switchbot Plugin Version

v1.7.0

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by donavanbecker** [comment]
@GcoGr It is an external device, you must add the device to the home app like you did with homebridge

The logs should say this.

**Comment by GcoGr** [comment]
I’m sorry, I don’t know how to add it. I added Homebridge to the Home app via QR code in the Homebridge home page and the two bots appeared in the iPhone app, but not the TV controls. Where is the QR for them? Thanks

**Comment by donavanbecker** [comment]
> I’m sorry, I don’t know how to add it. I added Homebridge to the Home app via QR code in the Homebridge home page and the two bots appeared in the iPhone app, but not the TV controls. Where is the QR for them? Thanks

Have you looked at your logs? It gives you a code to type in. It's the same code as homebridge also.

**Comment by GcoGr** [comment]
Hi,
I've been able to add TV to the IR configuration:
        "irdevices": [
            {
                "deviceId": "(Mac address taken from the gear symbol in the TV button of the 'Accessories' tab in Homebridge)",
                "configRemoteType": "TV"
            }
        ]
Then I addedd it to the iPhone Home App using the homebridge code shown in the "Logs" window of the main Homebridge page.

Now I can turn TV On and Off using the Home App and also using Siri in the Homepod! Great!

However, the TV Speaker On/Off button in the 'Accessories' Homebridge tab is not working. When I clic it, it changes status from On to Silence and vice versa, but the Switchbot hub does not seem to do anything (its LED does not blink).

Thanks!
