### ISSUE TITLE
Bug: Automation triggered by bot showing as door doesn’t work

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#192]
### Describe The Bug

A bot showing as door doesn’t trigger an automation whereby the stairwell lights of my building (controlled by a second bot) should turn on. I think if the bot shows as anything but a switch, the automation fails to happen. Can this be fixed?

### To Reproduce

N/A

### Expected behavior

When the bot (showing as door) that opens the building’s front door turns on, the bot that turns on stairwell lights should turn them on.

### Relevant log output

```shell
N/A
```

### Config for homebridge-switchbot

```shell
N/A
```

### Device & Model

N/A

### Node.js Version

16.13.1

### NPM Version

8.1.2

### Homebridge Version

1.3.9

### Homebridge Switchbot Plugin Version

1.7.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@FranciRoosters I believe this an iOS issue. Can you try iOS 15.2.1 or 15.3 beta 2?

**Comment by FranciRoosters** [comment]
iOS 15.2.1 didn’t fix it. Like I said, automations triggered by bots showing as switches work fine, but when they show as anything else, they automations fail. Having said this, I’m not sure it’s an iOS bug. 🤷‍♂️

**Comment by donavanbecker** [comment]
iOS 15.3 was released today. Please check to see if this is fixed for you now.

**Comment by FranciRoosters** [comment]
Seems to be working now. Will test more tomorrow and report back. Thanks!

**Comment by donavanbecker** [comment]
Please close once you you have verified.

**Comment by FranciRoosters** [comment]
I’ve verified it and it doesn’t work. Before I tested it with the wrong automation. If my automation says “when the front door opens, turn on the stairwell lights”, the bot commanding the stairwell lights doesn’t activate. Again, could it be because one bot is set as “door”?

**Comment by donavanbecker** [comment]
I would recommend install [HomeLog](https://apps.apple.com/us/app/homelog-for-homekit/id1584408332) and watching the the logs in HomeLogs while activating the Automation and see if it is triggering. I have no control over an automation. There is no characteristic on a door service that would cause an automation to work.

**Comment by FranciRoosters** [comment]
HomeLogs doesn’t see the automation working.

**Comment by donavanbecker** [comment]
Then I would report this to Apple. Like I said, I have no control over automation.
