### ISSUE TITLE
Feature Request: Want an old "bug" back as a feature

### ISSUE THREAD

**Issue by RobSjaras** [OpenWonderLabs/homebridge-switchbot#193]
Hi,

I really appreciate the work you're doing for this plugin and would love it if this could be a possibility for the future, I've had a look in the code myself and from what I can see the functionality (mentioned in addiotional context) broke when caching was introduced I think.

### Problem

I've been using your version 1.3.0 for a very long time, recently updated beyond that version and now the SwitchBot Bot doesn't behave as expected

### Solution

Make it possible to get old functionality back as an option

### Alternatives

For me: I keep version 1.3.0, just not ideal

### Additional context

The old functionality is that the on/off events would **always** get sent. Since Siri will resent an event, e.g. Switch is on, you tell siri to turn it on _again_, Siri sends on event to SwitchBot

P.S. I tried to be short and concise, do tell me if I need to provide more information on this "functionality"

**Comment by donavanbecker** [comment]
@RobSjaras What config do you have setup? I don't think it's the caching, but could be wrong.

**Comment by RobSjaras** [comment]
```
        {
            "name": "SwitchBot",
            "credentials": {
                "Token": "secret",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "FC0EECCFBB7E",
                        "hide_device": false,
                        "offline": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch",
                            "doublePress": 1
                        },
                        "logging": "debug"
                    },
                    {
                        "deviceId": "F8A4F6930FFB",
                        "offline": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch",
                            "doublePress": 1
                        },
                        "logging": "debug"
                    }
                ],
                "refreshRate": 120
            },
            "platform": "SwitchBot"
        }
    ],
```


So above config works with version 1.3.0.

To go into more specifics of my use case with the bot, then it's for a normal light switch, which gets used physically and through smart systems, so always out of sync in other words


And thank you for the fast response!

**Comment by Gus-smarthome** [comment]
I’m having the same issue! 
E.g. 

1. Start -> light status in Homekit = on / real-life = on
2. I manually turn it off -> light status in Homekit = on / real-life = off
3. I ask Siri via Homekit to turn it on, Siri says: "Lights are on" and don’t send the command to the bot -> light status in Homekit = on / real-life = off

**Comment by donavanbecker** [comment]
Can you check to verify this is working for you now? I have add a new config `allowPush` that must be set.

**Comment by RobSjaras** [comment]
Thanks so much @donavanbecker 

I've just tested it with the two SwitchBots I have and if the push changes would work for both states, on and off, and they did!

No issues, delays or anything like that, so it behaves exactly like it should

**Comment by donavanbecker** [comment]
@RobSjaras Can this issue be closed then?
