### ISSUE TITLE
Support Request: Hide Light Sensor Capability from Switchbot Curtain

### ISSUE THREAD

**Issue by mayhew132** [OpenWonderLabs/homebridge-switchbot#194]
### Describe Your Problem

I am looking for documentation on the feature that was added into version 1.1.0 which allows hiding of the light sensor from HomeKit on a Switchbot Curtain as I can't see how to configure it in Homebridge

### Device & Model

Switchbot Curtain

### Node.js Version

v14.17.6

### NPM Version

v6.14.15

### Homebridge Version

v1.3.9

### Homebridge SwitchBot Plugin Version

v1.7.0

### Homebridge Config UI X Plugin Version

v4.41.5

### Operating System

Docker

**Comment by donavanbecker** [comment]
Check out the [Configuration](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Configuration#breakdown-of-each-device-config-option) wiki. If you still need help, reach out on discord.

**Comment by mayhew132** [comment]
Thanks! Just realised I needed to add the curtain device in 'Settings' which then gives all the config parameters, doh! 👍 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/25966969/149015982-a3ca46d6-0863-433e-8a1f-b3c8d91f4000.png">
