### ISSUE TITLE
Support Request: A few questions during the excellent experience

### ISSUE THREAD

**Issue by hlc1209** [OpenWonderLabs/homebridge-switchbot#195]
### Describe Your Problem

First of all, I would like to thank you for developing such a wonderful extension and maintaining it constantly. In my use of this extension, I have several questions.

General:

1. I am currently using the API and hub to get the status of all my accessories and have homebridge running on a synology NAS (docker). If I want to use BLE instead of API, does that mean I need to buy an bluetooth adapter for the NAS? 

2. Is it possible in the future to get the status of all accessories via hub, like what is done in the switchbot app? Considering the configuration complexity of BLE and the limitation of API update interval. 

About Contact Sensor 

3. on the switchbot app I can get an EXIT status and configure the scenes accordingly, which is very useful and is an important node for me to configure my smart home. But now I want to use homebridge to do this, but I can't find a similar status. What I can think of is to add a home occupied status to the contact sensor.

About Motion Sensor

4. I have the motion sensor linked to a bot. I'm currently setting up scenes in the switchbot app to do this, and the execution delay is around 2 seconds. But now I want to do the same thing via homebridge. But I find that updating the status of the motion sensor via the API usually takes half a minute to a minute, which is too long. Is there a way to get the status of the motion sensor in about a second and reflect it on homebridge?

About Bot

5. If I let some bots execute commands at the same time, it tends to take a long time. This is certainly not a problem with your extension, I get the same result with Alexa.  I'm just curious if this can be improved in the future.

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge",
        "username": "****",
        "port": 53725,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "****",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "****",
                        "hide_device": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "****",
                        "hide_device": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "****",
                        "hide_device": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "****",
                        "hide_device": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "****",
                        "hide_device": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "****",
                        "configDeviceType": "Contact Sensor"
                    },
                    {
                        "deviceId": "****",
                        "configDeviceType": "Contact Sensor"
                    },
                    {
                        "deviceId": "****",
                        "configDeviceType": "Motion Sensor"
                    }
                ],
                "refreshRate": 35,
                "pushRate": 1
            },
            "platform": "SwitchBot"
        },
        {
            "name": "Nest",
            "refreshToken": "*****",
            "fanDurationMinutes": 30,
            "options": [
                "Thermostat.SeparateBuiltInHumiditySensor.Enable",
                "HomeAway.AsOccupancySensorAndSwitch"
            ],
            "platform": "Nest"
        }
    ]
}
```

### Device & Model

Synology DS920+

### Node.js Version

v16.13.1

### NPM Version

v8.1.2

### Homebridge Version

v1.3.9

### Homebridge SwitchBot Plugin Version

v1.7.0

### Homebridge Config UI X Plugin Version

v4.41.5

### Operating System

Docker

**Comment by donavanbecker** [comment]
Sorry for the late response.

> 1. I am currently using the API and hub to get the status of all my accessories and have homebridge running on a synology NAS (docker). If I want to use BLE instead of API, does that mean I need to buy an bluetooth adapter for the NAS?

Yes, but the OpenAPI (Cloud), is more reliable.

> 2. Is it possible in the future to get the status of all accessories via hub, like what is done in the switchbot app? Considering the configuration complexity of BLE and the limitation of API update interval.

That will depend on if the devices are added to the package `node-switchbot`. Once devices are added there, then I can add it to this plugin. I don't have much experience with BLE, so we have to rely on the SwitchBot Employees themselves. (I maintain this plugin for them.)

> About Contact Sensor
> 
> 3. on the switchbot app I can get an EXIT status and configure the scenes accordingly, which is very useful and is an important node for me to configure my smart home. But now I want to use homebridge to do this, but I can't find a similar status. What I can think of is to add a home occupied status to the contact sensor.

This isn't in the OpenAPI, so I have no way of pulling this.

> About Motion Sensor
> 
> 4. I have the motion sensor linked to a bot. I'm currently setting up scenes in the switchbot app to do this, and the execution delay is around 2 seconds. But now I want to do the same thing via homebridge. But I find that updating the status of the motion sensor via the API usually takes half a minute to a minute, which is too long. Is there a way to get the status of the motion sensor in about a second and reflect it on homebridge?

you definitely could set your refreshrate specificly for that devices by setting it only for that device in the SwitchBot Device Settings for that specific DeviceID, but that will be pulling from the OpenAPI every second then and you could use up your 10,000 pulls to the OpenAPI.

> About Bot
> 
> 5. If I let some bots execute commands at the same time, it tends to take a long time. This is certainly not a problem with your extension, I get the same result with Alexa.  I'm just curious if this can be improved in the future.

This is all relying on the speed of the API. @SwitchBot-Wonderlabs if you have any input?

**Comment by zeroecho** [comment]
@SwitchBot-Wonderlabs - we really need this 10,000 limit lifting for contact sensors. I have 8 contact sensors and using IFTTT I can get them just about responsive enough to use with my Hue lights, but given every other device I own works with Homekit, the lack of OpenAPI integration is making me debate returning them as I can't do complex scripting with Shortcuts. We need ENTER and EXIT toggles and <5second refresh times for these kinds of sensors. I'd happily cancel my IFTTT subscription and give you guys a few extra $ to beef your API up to handle the increase in concurrent connections...am sure I'm not alone!

**Comment by hlc1209** [comment]
Thank you for your detailed reply.

I recently ran into a problem. 
My bot is set to switch mode. 
In the past (I remember it was ver. 1.7.0), if I changed the status of the bot via the app or alexa, homebridge could see that the status of the bot has been changed. But recently, when I change the status of the bot using the app or alexa, the status of the bot in homebridge is not synchronized.

I would like to know if this is normal? I didn't change anything to the config

**Comment by donavanbecker** [comment]
I did introduce a cache like thing around then I believe. You may wanna try enabling `allowPush` config and see if that helps

**Comment by hlc1209** [comment]
> I did introduce a cache like thing around then I believe. You may wanna try enabling `allowPush` config and see if that helps

Thank you for your reply.

I set the allowPush to True, but the status changes I made in app or on alexa still cannot synchronize to homebridge

**Comment by donavanbecker** [comment]
@hlc1209 I don't get info back from the bot that tells me what state it is. And I implemented cache which keeps a record even on restarts of where the bot was at, which might be causing this, but until the API reports back the state there is not much I can do.
