### ISSUE TITLE
Feature Request: disable adding device type to device name

### ISSUE THREAD

**Issue by yjeanrenaud** [OpenWonderLabs/homebridge-switchbot#20]
### Problem

when you install the plugin, all devices get their device descriptor added to their name, e.g. Bedroom Curtain Curtain or Contact Sensor Contact Sensor. This is especially annoying if you are lazy enough to keep the default names

### Solution

a checkbox to toggle in the advanced options of the plugin

### Alternatives

you can rename all the devices manually on the accessories tab of homebridge UI, but you eventually get the names still broadcasted, e.g. to Google Home or other apps.

**Comment by donavanbecker** [comment]
@yjeanrenaud No plans on changing this.

**Comment by donavanbecker** [comment]
@yjeanrenaud  this should be fixed with Beta: 

[![npm version](https://badgen.net/npm/v/@switchbot/homebridge-switchbot/beta)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

can one of you test it out?
