### ISSUE TITLE
Bug: TV randomly turns on and the state doesn’t update in the Home app

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#200]
### Describe The Bug

TV turns on at random and the state doesn’t get updated in the Home app

### To Reproduce

N/A

### Expected behavior

The TV should stay off when off unless turned on.

### Relevant log output

```shell
N/A
```

### Config for homebridge-switchbot

```shell
irdevices": [
                    {
                        "deviceId": "a848faebcced",
                        "configRemoteType": "TV",
                        "irtv": {
                            "disable_power": true
                        }
```

### Device & Model

SwitchBit Hub Mini (IR Blaster), plugin version 1.8.1

### Node.js Version

16.13.2

### NPM Version

8.1.2

### Homebridge Version

1.3.9

### Homebridge Switchbot Plugin Version

1.8.1

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@FranciRoosters If you have disable power set to true, then the plugin wouldn't send a power command. So unless you have some logs then it has to be something else, Sorry.

**Comment by FranciRoosters** [comment]
It is set to true. Apart from the fact that I don’t understand what disable power set to true actually does, there are still two main bugs I’m encountering: 1) I think when the TV should be or turn off in automations, it actually tries the opposite of the state it was in. It’s almost as if the blaster cannot determine when the TV is off or on. Furthermore, the TV doesn’t turn off in the Home app when I turn it off using the remote.

**Comment by donavanbecker** [comment]
@FranciRoosters IR devices will never report the status back.

**Comment by FranciRoosters** [comment]
The issue persists, even with “disable power” set to true. I have a gaming Shortcut by which if the living room TV turns on, the bedroom TV turns off. Just a few minutes ago, I activated the shortcut, but the bedroom TV turned on instead of staying off. So, what gives?

Here’s what the logs say: TV: TV Sending request to SwitchBot API. command: turnoff, parameter: default, commandtype: Command. 

Here’s the configuration:     "irdevices": [
                    {
                        "deviceId": "a848faebcced",
                        "configRemoteType": "TV",
                        "irtv": {
                            "disable_power": true

I don’t know what’s going on. Could switching the device ID to BLE instead of Wi-Fi work? Thank you. 

EDIT: changing the device ID to BLE didn’t make a difference.

**Comment by donavanbecker** [comment]
If you have disable_power set to true then no commands for that TV will get sent. Also BLE is only available for SwitchBot devices,

**Comment by FranciRoosters** [comment]
I see, but although it is set to true, the TV still turns on when it should stay off. So, I don’t think the issue is on my end.

**Comment by donavanbecker** [comment]
```
    if (!this.device.irtv?.disable_power) {
      if (value === this.platform.Characteristic.Active.INACTIVE) {
        this.pushTvOffChanges();
      } else {
        this.pushTvOnChanges();
      }
      this.Active = value;
      this.ActiveCached = this.Active;
      this.accessory.context.Active = this.ActiveCached;
    }
```

this is the code snippet for that config. Unless disable_power is false will it send and `off` or `on` change.

**Comment by FranciRoosters** [comment]
This is my current config and the problem persists. I have no clue what to do now.

"irdevices": [
                    {
                        "deviceId": "a848faebcced",
                        "configRemoteType": "TV",
                        "irtv": {
                            "disable_power": false
                        }

**Comment by donavanbecker** [comment]
@FranciRoosters, `disable_power` set `true` will not send power commands. `disable_power` set `false` will send power commands. IR Devices will never be in sync with the device because IR doesn't communicate that way.

**Comment by FranciRoosters** [comment]
Hmmm… I’m not sure I’m making myself understood. Regardless of whether “Disable Power Command” is ticked or not, the TV still turns on when it should stay off.

**Comment by FranciRoosters** [comment]
I used the Broadlink before and had zero issues with it. I switched to Switchbot to streamline hubs and to have a much more user-friendly interface for the configuration.

**Comment by donavanbecker** [comment]
@FranciRoosters Can you enable debug logging and send me the logs? With disable_power set to true?

**Comment by FranciRoosters** [comment]
That’s alright. I fixed it by reinstalling the BroadLink.
