### ISSUE TITLE
Bug: Siri doesn’t send turn off/on commands if the status of the bot switch is the same as the turn on/off command

### ISSUE THREAD

**Issue by Gus-smarthome** [OpenWonderLabs/homebridge-switchbot#207]
### Describe The Bug

If the light status is off, you manually turn it on and you ask siri to turn it off via homekit, she check the status (in this case off) and don’t send the request to turn the lights off

### To Reproduce

Lights state = off, manually turn lights on, ask siri to turn it off (trough homekit NOT shortcuts)

### Expected behavior

Homekit request to turn it off (as it happens in shortcurts)

### Relevant log output

```shell
Siri checks the status and says "the lights are off" but, don’t  send the command to turn it off
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxxxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xxxxxxxx",
                        "configDeviceName": "Entrance hall lights",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
```

### Device & Model

.

### Node.js Version

v16.13.1

### NPM Version

v8.3.0

### Homebridge Version

v1.3.9

### Homebridge Switchbot Plugin Version

v1.8.2

### Operating System

Raspberry

**Comment by donavanbecker** [comment]
should be fixed in with v1.10.0
