### ISSUE TITLE
Feature Request: add support for motion detection of the contact sensor

### ISSUE THREAD

**Issue by yjeanrenaud** [OpenWonderLabs/homebridge-switchbot#22]
### Problem

even though considered to be beta, it would be cool to use the motion detection feature of the contact sensor in homebdrige. The API already exposes it

### Solution

add support for the motion detector as an additional accessory in homebdrige, maybe optional via advances settings

**Comment by donavanbecker** [comment]
@yjeanrenaud This has been implemented into the latest beta.
