### ISSUE TITLE
Bug: No BLE connection possible to Switchbot-Bot on OSX

### ISSUE THREAD

**Issue by lkshrk** [OpenWonderLabs/homebridge-switchbot#225]
### Describe The Bug

BLE connection not possible on OSX. Permissions for bluetooth are set in the macOS preferences for both, terminal and current node version.

### To Reproduce

Try to connect Switchbot-Bot via BLE on latest OSX

### Expected behavior

Bot should connect via BLE

### Relevant log output

```shell
[1/28/2022, 10:29:11 AM] [SwitchBot] [DEBUG] Executed didFinishLaunching callback
[1/28/2022, 10:29:11 AM] [SwitchBot] [DEBUG] SwitchBot Device Manual Config Set: [{"deviceId":"KKAB12CC45BB","configDeviceType":"Bot","ble":true,"scanDuration":10,"bot":{"mode":"press","deviceType":"switch"}}]
[1/28/2022, 10:29:11 AM] [SwitchBot] [DEBUG] Discovered Bot: KKAB12CC45BB
[1/28/2022, 10:29:11 AM] [SwitchBot] [DEBUG] Device: undefined Neither OpenAPI and BLE Enabled
[1/28/2022, 10:29:11 AM] [SwitchBot] [DEBUG] Unable to Register new device: undefined Bot - KKAB12CC45BB
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "KKAB12CC45BB",
                        "configDeviceType": "Bot",
                        "ble": true,
                        "scanDuration": 10,
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    }
                ],
                "logging": "debug"
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

Switchbot Bot

### Node.js Version

v16.13.12

### NPM Version

v8.1.2

### Homebridge Version

v1.4.0

### Homebridge Switchbot Plugin Version

v1.10.1

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

macOS Monterey 12.2

**Comment by lkshrk** [comment]
Doing further investigation, I suppose it's caused by https://github.com/abandonware/noble/issues/225

**Comment by donavanbecker** [comment]
@lkshrk It is hit or miss. I have a M1 Mac mini and I am able to use BLE connection.

Do you have Xcode Installed? I would recommend also trying to add terminal, npm, and node into security for Bluetooth.

Location for npm and node can by found by doing `which npm` and `which node` in terminal
