### ISSUE TITLE
Feature Request: Adding Support for SwitchBot Remote

### ISSUE THREAD

**Issue by WaldperlachFabi** [OpenWonderLabs/homebridge-switchbot#236]
### Solution

It would be really great if the plug-in would support the Remote!

**Comment by donavanbecker** [comment]
@WaldperlachFabi I agree, would have to come from the OpenAPI or BLE, which I don't think would ever happen since it would be a command that would be pushing info and we are pulling info from those APIs.

**Comment by TristanBrotherton** [comment]
I would love this too!

**Comment by isaaclockett72** [comment]
This would be a game changer... would we be able to use a Switchbot remote to control another device across the Homebridge?
