### ISSUE TITLE
Support Request:  Since 1.12.X, updating plugin return error.

### ISSUE THREAD

**Issue by Aekung** [OpenWonderLabs/homebridge-switchbot#244]
### Describe Your Problem

Since 1.12.X, updating plugin will always return error as the log output below. The only way that I could update the plugin would be to uninstall with rm -rf command for the whole homebridge-switchbot folder and reinstall the plugin again. Uninstall the plugin with Homebridge UI or normal command is not possible as well. Sometimes, it also crashes my homebridge down if the update is unable to finish for whatever reason. I'm using Switchbot Plugin as a child bridge in my set up.

### Relevant log output

```shell
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@switchbot/homebridge-switchbot
npm ERR! dest /usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot' -> '/usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-02-04T07_11_10_700Z-debug-0.log

Command failed. Please review log for details.
```

### Device & Model

Raspberry Pi 3B+

### Node.js Version

v16.13.2

### NPM Version

v8.4.0

### Homebridge Version

v1.4.0

### Homebridge SwitchBot Plugin Version

v1.12.1

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Go into terminal and paste this command:

```
sudo rm -R /usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE
```

**Comment by Aekung** [comment]
Did what you suggested and I could update the plugin but the update process goes on for over 10 minutes now stopping at

`reify:rxjs: timing reifyNode:node_modules/@switchbot/homebridge`

This happens every time I tried to update the plugin since 1.12.X and it will end up crashing my Homebridge. Just like now, my Homebridge is unresponsive since the updating process is not done.

I can't access both SSH and Homebridge UI X and it will be like this for hours or it won't come back at all. If I'm lucky and my Homebridge is accessible hours later, I won't be able to update the plugin again if I don't delete the folder that ends with alphabets just like 'UUyzm0HE'

I'm not sure what's the cause of the problem but I have to re-flashing my Raspberry Pi few times already because of this problem.

Do you have any suggestion on this?

**Comment by donavanbecker** [comment]
sounds like a npm issue.
