### ISSUE TITLE
Feature Request: Adding Support for Meter in the Eve App

### ISSUE THREAD

**Issue by WaldperlachFabi** [OpenWonderLabs/homebridge-switchbot#247]
### Solution

It is possible to get Stats of the Temperature and the Humidy in the Eve App. It would be cool if this could be added.

**Comment by WaldperlachFabi** [comment]
![7E6B148E-151F-4584-B922-6630F0F8F875](https://user-images.githubusercontent.com/80318133/152641647-7c919116-e142-475a-a531-22af773cd552.jpeg)

**Comment by donavanbecker** [comment]
I will look into it.
