### ISSUE TITLE
Bug: Strip Light Adaptive lighting doesn’t work

### ISSUE THREAD

**Issue by WaldperlachFabi** [OpenWonderLabs/homebridge-switchbot#250]
### Describe The Bug

If i use the Adaptive Lighting button in HomeKit nothing wont happen

### To Reproduce

Tap on the adaptive lighting button in HomeKit

### Expected behavior

Make Adaptive lighting 

### Relevant log output

```shell
Strip Light Command is not supported
```

### Config for homebridge-switchbot

```shell
Same as the last issu.
```

### Device & Model

Strip Light

### Node.js Version

//

### NPM Version

//

### Homebridge Version

//

### Homebridge Switchbot Plugin Version

//

### Homebridge Config UI X Plugin Version

//

### Operating System

Docker

**Comment by donavanbecker** [comment]
@WaldperlachFabi Since the light strip doesn't have color temperature this may be something that will not be enabled for Light Strips. I will look to see if I can get it to work without it

**Comment by donavanbecker** [comment]
In v1.12.7, I have removed Adaptive Lighting support from Strip Lights because strip Lights don't have color temperature and that is required for strip lights.
