### ISSUE TITLE
Feature Request: Adding Support for MeterPlus

### ISSUE THREAD

**Issue by henry2423** [OpenWonderLabs/homebridge-switchbot#259]
### Problem

HomeBridge shows the MeterPlus is not supported

### Solution

Add support for MeterPlus(US) in homebridge

### Additional context

Logs: [2/11/2022, 12:45:41 PM] [SwitchBot] Device: Meter with Device Type: MeterPlus, is currently not supported. [2/11/2022, 12:45:41 PM] [SwitchBot] Submit Feature Requests Here: https://git.io/JL14Z

**Comment by donavanbecker** [comment]
@henry2423 If I push a beta quick, can you test?

**Comment by henry2423** [comment]
I can test it later today.

**Comment by donavanbecker** [comment]
Thanks, try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.12.4-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

Once you confirm it works, then I push out a new release.

**Comment by henry2423** [comment]
@donavanbecker It works perfectly. Thanks!
![IMG_5748](https://user-images.githubusercontent.com/20208606/153731307-2da4528f-89b2-4601-b417-28688d278d59.PNG)
![IMG_5747](https://user-images.githubusercontent.com/20208606/153731311-0800b275-f302-4f40-8065-f75272a98ff2.PNG)

**Comment by donavanbecker** [comment]
@henry2423 awesome! Latest version has it in it.
