### ISSUE TITLE
Bug: Can not install/config the plugin 

### ISSUE THREAD

**Issue by HolgerAusB** [OpenWonderLabs/homebridge-switchbot#283]
### Describe The Bug

New install of plugin v1.12.5 and no config available

### To Reproduce

Install Switchbot-plugin the first time from Homebridge UI

### Expected behavior

click on configuration should show dialogs

### Relevant log output

```shell
A click on Plugin>Settimgs raises an error: Failed to load plugins config schema

Trying to Disable plugin (for testing) raises:
Failed to disable plugin: Http failure response for https://brdg.mydomain.de/api/config-editor/plugin/%40switchbot%2Fhomebridge-switchbot/disable: 404 Not found

I think the 404 is because of the %2F in plugin name, trying in the browser:
.../api/config-editor/plugin/%40switchbot%2Fhomebridge-switchbot  >> html Error: 404 Not Found
.../api/config-editor/plugin/%40any_letters  >> json status: 401 Unauthorized (which is ok for the test)
```

### Config for homebridge-switchbot

```shell
There is no code in config.json that contains 'switchbot'
```

### Device & Model

none, but Hub mini, Bot and Thermometer Plus should arrive today

### Node.js Version

v14.19.0

### NPM Version

v6.14.16

### Homebridge Version

v1.4.0

### Homebridge Switchbot Plugin Version

v1.12.5

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Raspian Bullseye

**Comment by donavanbecker** [comment]
Have you tried reinstalling?

**Comment by HolgerAusB** [comment]
of course. I tried to reinstall the switchbot-plugin at least three times, with restarts of HB after each install and uninstall. Maybe you can tell me a command line for the console to install an older version first?

**Comment by donavanbecker** [comment]
You can install older versions from homebridge UI, but I don't know if that will help you

**Comment by HolgerAusB** [comment]
No, I can't install older versions from the UI, it raises the same 404 error, no matter if I try to downgrade from an installed version or as as new install. My idea was, that this bug is maybe new and only happend when installing it the first time with curent version(s). And hopefully an upgrade from an older version will do better.

**Comment by HolgerAusB** [comment]
just tried again and did screenshots while installing. There is an ERR for
https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/...arm.tar.gz

![switchbot_build_err](https://user-images.githubusercontent.com/3876469/156775669-0ad11203-37e5-4a25-ae4b-456f9a91540b.jpg)

**Comment by donavanbecker** [comment]
Looks like a network issue.

**Comment by HolgerAusB** [comment]
Tried to download with firefox https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth-hci-socket-0.5.3-8-node-v83-linux-arm.tar.gz is not found on github.

abandonware/node-bluetooth-hci-socket/ seem not to have any releases. But I am new to Github, don't know if I am right. So its on there side, or? New version?

**Comment by HolgerAusB** [comment]
or maybe moved from `/releases/...` to `/archive/refs/tags/v0.5.3-8.tar.gz` ?

**Comment by donavanbecker** [comment]
please install node-switchbot [prerequisites](https://github.com/homebridge/noble#prerequisites).

**Comment by HolgerAusB** [comment]
They where allready installed and the newest versions. Only the symlink cant be set because the name allready extist:
```
user@server:~ $ sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
libudev-dev ist schon die neueste Version (247.3-6+rpi1).
bluetooth ist schon die neueste Version (5.55-3.1+rpt1).
bluez ist schon die neueste Version (5.55-3.1+rpt1).
libbluetooth-dev ist schon die neueste Version (5.55-3.1+rpt1).

user@server:~ $ ls -l /usr/bin/node*
-rwxr-xr-x 1 root root 69049448  1. Feb 08:57 /usr/bin/node
lrwxrwxrwx 1 root root       24 22. Feb 2021  /usr/bin/nodejs -> /etc/alternatives/nodejs
```
while /etc/alternatives/nodejs redirects to /usr/bin/node which would be the same.

**Comment by HolgerAusB** [comment]
tried some older versions down to 1.9.0 no changes.

**Comment by donavanbecker** [comment]
something with your raspbian then.

**Comment by HolgerAusB** [comment]
mhh, might be, but not shure. Just updated npm and nodejs, no differences.
After installing the plugin in HB, I moved the folder
`/usr/lib/node_modules/@wsitchbot/homebridge-switchbot` to `/usr/lib/node_modules/homebridge-switchbot` and replaced the Plugin-name/id in some files from `@wsitchbot/homebridge-switchbot` to `homebridge-switchbot`. **And this works!!!** Of course I will get problems every time I need to update the plugin, but that shows, that there is a problem with the dash `/` in the plugin-name. If that is only on my side, does anyone have an idea?

As I wrote earlier, Homebridge UI did not find the settings (original install) under https://example.tld/api/config-editor/plugin/%40switchbot%2Fhomebridge-switchbot because of the %2F which is the url-encoded dash.

**Comment by HolgerAusB** [comment]
I am getting closer. It was the reverse proxy in Apache2 which causes the problem with the %2F in the URL. I will need some rewrite-rules, I think.

Now I tried it by accessing HB with the normal http://<ip>:<port> to install the plugin. But now the settings button does not do anything at first, no error and no settings. Installed some older version and then the latest, now it works, finally.

Thank you for your help

**Comment by donavanbecker** [comment]
Good to hear
