### ISSUE TITLE
Bug: Light Sensor LUX 6001

### ISSUE THREAD

**Issue by olikdesign** [OpenWonderLabs/homebridge-switchbot#301]
### Describe The Bug

In Apple Home LUX is always 6001. In my config .json file i can add manually the curtain but nothing happens. The data is automatically in Apple Home from SwitchBot.

### To Reproduce

Everytime

### Expected behavior

Show current lux

### Relevant log output

```shell
Not Relevant for the Light Sensor
Curtain: Vorhang scanDuration is less then updateRate, overriding scanDuration with updateRate
```

### Config for homebridge-switchbot

```shell
{
    "platform": "SwitchBot",
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!",
        "openToken": "XXX"
    }
}
```

### Device & Model

Raspberry PI

### Node.js Version

16.14.2

### NPM Version

??

### Homebridge Version

1.4.0

### Homebridge Switchbot Plugin Version

v1.12.8

### Homebridge Config UI X Plugin Version

HOOBS 4.2.1

### Operating System

Raspberry Pi 4B

**Comment by donavanbecker** [comment]
First of all, this plugin is designed for homebridge not HOOBs.

Secondly there is a device config setting that you can change these for lux max and min.

**Comment by olikdesign** [comment]
If i install the plugin it automatically adds all Accessoires from SwitchBot Hub. I cant even configurate these.

**Comment by olikdesign** [comment]
Got it working.

**Comment by donavanbecker** [comment]
> If i install the plugin it automatically adds all Accessoires from SwitchBot Hub. I cant even configurate these.

Yes it will always add all accessories and you must configure the ones that you don't want to display.

**Comment by olikdesign** [comment]
> > If i install the plugin it automatically adds all Accessoires from SwitchBot Hub. I cant even configurate these.
> 
> Yes it will always add all accessories and you must configure the ones that you don't want to display.

Ok. In Accessoires it shows my curtain and my DIY IR Speaker. How i can show the speaker in Apple Home? In the SwitchBot App there is no DeviceID shown.

**Comment by olikdesign** [comment]
Found the DeviceId in Log Terminal but cant add it to Apple Home. Maybe i miss anything.

**Comment by olikdesign** [comment]
I found out that if i use ble: true the Lux will be correct. If is false it stays 6001.

is this normal?

**Comment by donavanbecker** [comment]
Yes because BLE sees different values for Lux levels then OpenAPI. once again. you are using HOOBs which is different then homebridge, I can really only help with homebridge.

**Comment by olikdesign** [comment]
All plugins i use are working like homebridge itself. But i can use the ble function.

**Comment by donavanbecker** [comment]
> All plugins i use are working like homebridge itself. But i can use the ble function.

The Config UI for homebridge is different then HOOBs which makes it harder to configure the plugin.
