### ISSUE TITLE
Feature Request: Open Silent Close Performance Mode

### ISSUE THREAD

**Issue by olikdesign** [OpenWonderLabs/homebridge-switchbot#302]
### Problem

I dont know if it is possible to get a option for closing curtain in performance mode and open in silent mode.

### Solution

Option in Config/json eg „open_mode“: silent, „close_mode“: performance

**Comment by donavanbecker** [comment]
@olikdesign, if I did implement this, how would you like me to handle this? just a config in homebridge?

**Comment by olikdesign** [comment]
> @olikdesign, if I did implement this, how would you like me to handle this? just a config in homebridge?

i think just a checkbox in config and json text for advanced settings will be great.

**Comment by donavanbecker** [comment]
Instead of a checkbox, I will probably do two drop downs, one for close and one for open. Asking if you quiet or performance for each.

I will see if I can implement this.

**Comment by olikdesign** [comment]
@donavanbecker 
This sounds great. Because for heavy curtains the silent mode cant move it open but for closing it works. Thats why i think it will be cool to have this feature.

**Comment by donavanbecker** [comment]
@olikdesign, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.12.9-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

you should see the settings in the config.

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by olikdesign** [comment]
@donavanbecker installed the beta but there is no option or dropdown under configuration. Is there any config.json code to test it?

**Comment by donavanbecker** [comment]
<a><img src="https://user-images.githubusercontent.com/9875439/161251174-28dbe2b0-eb38-4eb0-a63d-578d72dfeb82.jpeg" width="250px"></a>

**Comment by olikdesign** [comment]
Yeah this dropdowns are missing for me. I will reinstall the whole Plugin and test it again.

**Comment by donavanbecker** [comment]
> Yeah this dropdowns are missing for me. I will reinstall the whole Plugin and test it again.

Homebridge UI is designed to only show it for curtain devices.

**Comment by olikdesign** [comment]
Ok, so i got it working but there are some issues:

When just clicking **closing** it works in silent mode. **(But left curtain stays at 90% closed.)**
When just clicking **opening** left curtain moves in performance mode **but right side in silent**.

When moving the slider for example to 44% opening it also moves in **silent mode** for open and close.


Also when closing the curtain in Home App it shows **40% open.**

**Comment by donavanbecker** [comment]
Still having issues?
