### ISSUE TITLE
Feature Request: Publish value of Temperature from Switchbot Meter to mqtt server.

### ISSUE THREAD

**Issue by Aekung** [OpenWonderLabs/homebridge-switchbot#303]
### Problem

Switchbot Meter can now only be used to display the current temperature of each room, which should be suffice for what it is designed for. However, if we could publish this value to mqtt server, we would be able to use it to control the air conditioner device based on the room temperature.

### Solution

Not really sure if it's possible to publish the temperature value to mqtt broker like Homebridge-mi-hygrothermograph plugin.

**Comment by donavanbecker** [comment]
If someone would like to make a Pull Request, I would consider merging. I believe there is a mqtt repo out there.

**Comment by Aekung** [comment]
> If someone would like to make a Pull Request, I would consider merging. I believe there is a mqtt repo out there.

Thanks for the reply. However, as I'm not a coder, I don't really think I can contribute anything in this project. Though I have found a link to something that might work in combination with this plugin

https://github.com/ronschaeffer/sbm2mqtt

Do you think it would work by following the installation step on Raspberry Pi and then use an IR Blaster Plugin that supports mqtt for air conditioner (like broadlink plugin) to grab the published topic and value from this switchbot meter?

**Comment by donavanbecker** [comment]
Search "SwitchBot MQTT", there are a lot that have this support already, like I said.

https://github.com/godely/sbmeter_to_mqtt
