### ISSUE TITLE
Switchbot - Bot : Press-mode sets Switch to On

### ISSUE THREAD

**Issue by sy5t3ch** [OpenWonderLabs/homebridge-switchbot#306]
### Problem

When you set a bot to "Press-mode" and press it, it goes briefly "On" - when it presses the button, and then goes back to "Off" when it is done pressing the button. However for press-buttons that switch a device on, this then doesn't represent the state of that device.

### Solution

Add an option which enables Press-Mode to set the state of the device. If pressed once, it is set to On - again then Off. This means the device state needs to be remembered instead of the state of the Bot.

**Comment by bradenpecora** [comment]
@donavanbecker Any update on this? This would be a useful feature.

**Comment by donavanbecker** [comment]
unless you are using BLE, the API doesn't contain the state of the device.

**Comment by bradenpecora** [comment]
A good alternative solution is to create a "dummy" bulb using [HTTP Webhooks](https://github.com/benzman81/homebridge-http-webhooks). Then, set up automations that turn the SwitchBot Bot on when the light is turned on or off.

A few drawbacks are:
- Dummy light and bot must be manually synced and could get out of sync
- Potential issues when turning the light on and of rapidly.
