### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by WHITBREADNETWORK** [OpenWonderLabs/homebridge-switchbot#307]
### Describe Your Problem

Motion sensor slow to pick up. I have the poll set the fastest on 30 seconds however when the motion sensor picks up motion it can take around 20 seconds to show motion in home or the HomeBridge ui which is a problem because I want some stair lights to activate as soon as motion seen. 

### Device & Model

Motion sensor

### Node.js Version

16.14.2

### NPM Version

8.5.0

### Homebridge Version

1.4.0

### Homebridge SwitchBot Plugin Version

1.12.9.beta 9

### Homebridge Config UI X Plugin Version

4.42.0

### Operating System

Ubuntu

**Comment by donavanbecker** [comment]
#514
