### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by suketarobei** [OpenWonderLabs/homebridge-switchbot#317]
### Solution

If possible, be able to choose a "Night light" for the light,

**Comment by donavanbecker** [comment]
@suketarobei Do you have an example? Not sure what you mean by night light?

**Comment by suketarobei** [comment]
@donavanbecker 
Paste the Switchbot app and a reference image.  Can you understand this?![image](https://user-images.githubusercontent.com/103834957/163705216-906e08cc-1f04-41c2-9764-c652eca3e213.jpeg)![image](https://user-images.githubusercontent.com/103834957/163705225-53f0f781-13dd-4850-8d7b-2733d69e8f19.jpeg)

**Comment by suketarobei** [comment]
This is an IR light controller. If you don't understand, please let me know.  I'll do my best.
