### ISSUE TITLE
Motion Sensor: Does Not Perform as Expected

### ISSUE THREAD

**Issue by EricSabe** [OpenWonderLabs/homebridge-switchbot#318]
### Describe The Bug

Several Motion Sensors deployed alongside SimpliSafe motion sensors, tied together in nodered with TP-Link Kasa switches to enable room occupancy monitoring.  Motion should reset the occupancy timer.  SimpliSafe sensors work as expected.  SwitchBot sensors do not keep the timer running.

### To Reproduce

Turn on light.  Move around.  Find yourself in unexpected darkness after the timer runs down.

### Expected behavior

Turn on light.  Move around.  SimpliSafe sensors consistently report motion events through HomeBridge to nodered, resetting the timer until the person leaves the area.  

### Relevant log output

```shell
Generating Debug Logs
```

### Config for homebridge-switchbot

```shell
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "encrypted",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "logging": "standard"
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

See Below

### Device & Model

Motion Sensor

### Node.js Version

v16.14.0

### NPM Version

v8.3.1

### Homebridge Version

v1.4.0

### Homebridge Switchbot Plugin Version

v1.12.8

### Homebridge Config UI X Plugin Version

v4.43.0

### Operating System

Homebridge Docker/Alpine Linux (3.12.9)

**Comment by EricSabe** [comment]
Adding screenshot of a SwitchBot Motion Sensor Log:

![image](https://user-images.githubusercontent.com/91292218/163910068-202b2ff6-a133-4c9f-99ef-91ab5f95f602.jpeg)

**Comment by EricSabe** [comment]
To compare with these events I pipe to Syslog:

![image](https://user-images.githubusercontent.com/91292218/163910447-96fd5e7d-50a5-43a7-8c0c-bf7aebfcff79.png)

![image](https://user-images.githubusercontent.com/91292218/163910472-7d301e75-9d5e-4ec8-8678-5375f34ce207.png)

**Comment by donavanbecker** [comment]
not sure what you want me to do here? doesn't seem to be a plugin issue, more of an API? or what?
