### ISSUE TITLE
Bug: Projector and TV IR Remotes not added

### ISSUE THREAD

**Issue by BarnesGH** [OpenWonderLabs/homebridge-switchbot#324]
### Describe The Bug

Projector and Fan IR Remote not added

### To Reproduce

Install plugin with one bot and either a fan or projector remote setup on the hub mini. When adding the bridge to Homekit they do not show up. I added my projector as if it were a fan and it showed up

### Expected behavior

Projector and Fan are not added as accessories in Homekit. The are added to Hoobs but not Homekit. What am I doing wrong? I added my projector as if it were a fan and it showed up in the Home app

### Relevant log output

```shell
No log, the Projector and/or TV accessories are not showing up as an option to add them to the Home app after adding the bridge. I see them in the Hoobs dashboard, but not in the Home app for some reason.
```

### Config for homebridge-switchbot

```shell
I use Hoobs
```

### Device & Model

None needed

### Node.js Version

Hoobs 4.0.71

### NPM Version

Hoobs 4.0.71

### Homebridge Version

Hoobs 4.0.71

### Homebridge Switchbot Plugin Version

1.12.8

### Homebridge Config UI X Plugin Version

Hoobs 4.0.71

### Operating System

Hoobs on Ras Pi

**Comment by donavanbecker** [comment]
first of all, this plugin is developed for homebridge, so use HOOBs at your own risk.

TV and projectors are added as external accessories

**Comment by BarnesGH** [comment]
Understood, but when I set the ir remote for the projector as a fan, rather than a TV or Projector, it gets pulled in with the bots. When I set the projector as a projector it never asks me to add it to the home app when I’m adding the bridge. Perhaps it’s because I’m using Hoobs rather than HomeBridge though.

**Comment by BarnesGH** [comment]
Nevermind. I just tried to add an accessory by saying I don’t have a code and I see them both. 
thanks man!

**Comment by donavanbecker** [comment]
No problem
