### ISSUE TITLE
Bug: Removed Bot Still Showing In HomeKit

### ISSUE THREAD

**Issue by PBXLthrMan** [OpenWonderLabs/homebridge-switchbot#364]
### Describe The Bug

Removed Bot Is Still Showing In HomeKit

### To Reproduce

Remove the Bot from SwitchBot app, remove the bot from the Homebridge config, reboot SwitchBot Hub, reboot Homebridge

### Expected behavior

Bot should be removed from HomeKit

### Relevant log output

```shell
[27/05/2022, 21:09:08] [SwitchBot] Total SwitchBot Devices Found: 3
[27/05/2022, 21:09:08] [SwitchBot] Restoring existing accessory from cache: Exhaust Fan DeviceID: D84B5A4DA639
[27/05/2022, 21:09:08] [SwitchBot] Restoring existing accessory from cache: Bathroom Nightlight DeviceID: ED0BA396296A
[27/05/2022, 21:09:08] [SwitchBot] Bot: Exhaust Fan Config: {"mode":"press","deviceType":"switch"}
[27/05/2022, 21:09:08] [SwitchBot] Bot: Exhaust Fan Displaying as Switch
[27/05/2022, 21:09:08] [SwitchBot] Bot: Bathroom Nightlight Config: {"mode":"press","deviceType":"switch"}
[27/05/2022, 21:09:08] [SwitchBot] Bot: Bathroom Nightlight Displaying as Switch
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": “XXXX”,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "D8XXXXX",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "EDXXXXX",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    }
                ]
           },
            "platform": "SwitchBot"
        },
```

### Screenshots

![IMG_5071](https://user-images.githubusercontent.com/90646855/170804306-65d2fec9-9388-4d3b-a592-bc7d15c74886.PNG)
![IMG_5074](https://user-images.githubusercontent.com/90646855/170804309-69da26c8-c116-4f87-9cdb-6fc18055c07e.PNG)

### Device & Model

SwitchBot

### Node.js Version

v16.13.1

### NPM Version

v8.3.0

### Homebridge Version

v1.4.1

### Homebridge Switchbot Plugin Version

v1.13.0

### Homebridge Config UI X Plugin Version

v4.46.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
You will have to clear with Homebridge Settings by clearing accessory cache on that accessory.

**Comment by PBXLthrMan** [comment]
> You will have to clear with Homebridge Settings by clearing accessory cache on that accessory.

I’m sorry I’ve never had to do that before. How does one accomplish that?

**Comment by PBXLthrMan** [comment]
> You will have to clear with Homebridge Settings by clearing accessory cache on that accessory.

Figured it out. Worked. Thanks.
