### ISSUE TITLE
Bug: Power State Being Resent for On/Off Control

### ISSUE THREAD

**Issue by simplytoast1** [OpenWonderLabs/homebridge-switchbot#378]
### Describe The Bug

Despite HomeKit reporting a device is on when I have an automation that calls for a device to be on a duplicative command is sent actually turning the device off

### To Reproduce

Create an automation that calls for a light to be on.  Despite the light being on it sends an IR command turning it off.

### Expected behavior

If a device is in a state that a command calls for should not be resent (ie: Turn the light on, if the HK state is on no IR command should be sent)

### Relevant log output

```shell
[6/9/2022, 9:00:44 AM] [SwitchBot] Light: LG TV Sending request to SwitchBot API. command: turnOff, parameter: default, commandType: command
```

### Config for homebridge-switchbot

```shell
N/A
```

### Device & Model

Hub Mini

### Node.js Version

v16.15.1

### NPM Version

v8.11.0

### Homebridge Version

v1.4.1

### Homebridge Switchbot Plugin Version

v1.13.0

### Homebridge Config UI X Plugin Version

v4.46.0

### Operating System

macOS

**Comment by donavanbecker** [comment]
what kind of device? Is it an IR device?
