### ISSUE TITLE
Support Request: IR Device Status is Off

### ISSUE THREAD

**Issue by rayyang8228** [OpenWonderLabs/homebridge-switchbot#380]
### Describe Your Problem

IR Devices Status is Incorrect

### Screenshots

Both "Speaker" and "TV" (IR Devices) are shown as Off in the Home App and HomeBridge when the devices are on. Is there a way to change this?

![Screenshot 2022-06-11 at 12 57 53 AM](https://user-images.githubusercontent.com/107270159/173115294-74869696-30ca-4bdc-88f9-a85c10900e98.png)

![IMG_4684](https://user-images.githubusercontent.com/107270159/173115188-11484edf-59b3-4059-b92c-beb83a04585d.PNG)
01b04888d1.png)

### Device & Model

N/A

### Node.js Version

v16.15.1

### NPM Version

v8.11.0

### Homebridge Version

v1.4.1

### Homebridge SwitchBot Plugin Version

v1.13.0

### Homebridge Config UI X Plugin Version

v4.46.0

### Operating System

macOS

**Comment by donavanbecker** [comment]
It isn't incorrect, it gets out of sync since you IR doesn't stay in sync.
