### ISSUE TITLE
Feature Request: Battery % from Curtains to be shown in Homebridge/HomeKit

### ISSUE THREAD

**Issue by siobhanellis** [OpenWonderLabs/homebridge-switchbot#399]
### Problem

Currently, to see how much battery is left I have to go into the SwitchBot app, and go through multiple screens.

### Solution

Pass the Battery % through to homebridge/HomeKit

**Comment by AKWillows** [comment]
I would love to have this feature too :-)

**Comment by donavanbecker** [comment]
Are you using BLE or OpenAPI? Because BLE has this. OpenAPI doesn't supply this info.

**Comment by siobhanellis** [comment]
Using OpenAPI as going via hub

**Comment by donavanbecker** [comment]
Not possible with OpenAPI right now

**Comment by siobhanellis** [comment]
OK. Doesn’t change the feature request though :-D

**Comment by donavanbecker** [comment]
I would like it too, but until SwitchBot adds support, you won't see it.

**Comment by siobhanellis** [comment]
Isn’t this plugin supported by SwitchBot?

**Comment by donavanbecker** [comment]
I mean technically yes.

I created this plugin independently from SwitchBot, They reach out to me and asked me if I would like to merge it with their organization on Github and I said yes. So now I still maintain the plugin, but they are the ones that would have to add support like this to the API, before I can add it to the plugin.

**Comment by siobhanellis** [comment]
Ah. Thanks.

Guess you have a feature request then :-)

**Comment by donavanbecker** [comment]
v2.8.0 is released
