### ISSUE TITLE
Feature Request: ability to use custom IR command for light off

### ISSUE THREAD

**Issue by vladkorotnev** [OpenWonderLabs/homebridge-switchbot#400]
### Problem

Some lights use separate buttons for Power On/Brightness Toggle and Power Off on the remote control. So turning off the light via Homebridge instead just switches the brightness to low.

### Solution

Allow using a custom command for power off and on separately.

**Comment by donavanbecker** [comment]
I will take Pull Requests, but since I don't use the IR function can't really add this support.

**Comment by donavanbecker** [comment]
available in v2.1.0
