### ISSUE TITLE
Bug: No Device Type Set

### ISSUE THREAD

**Issue by Ab4321** [OpenWonderLabs/homebridge-switchbot#408]
### Describe The Bug

SwtichBot Hub Mini. I have a fireplace connected via IR, works fine in the SwitchBot app. In HomeBrdige, I have the device ID as Master Fireplace, Remote Type as Others IR (I've tried AC too, same error).

### To Reproduce

Anytime I reboot HomeBridge

### Expected behavior

IR power switch to show up in HomeKit

### Relevant log output

```shell
[6/25/2022, 5:16:34 PM] [SwitchBot] Total SwitchBot Devices Found: 1
[6/25/2022, 5:16:34 PM] [SwitchBot] Total IR Devices Found: 1
[6/25/2022, 5:16:34 PM] [SwitchBot] Restoring existing accessory from cache: Master Fireplace DeviceID: 02-202206181700-83212306
[6/25/2022, 5:16:34 PM] [SwitchBot] Other: Master Fireplace No Device Type Set, deviceType: undefined
[6/25/2022, 5:16:34 PM] [SwitchBot] Other: Master Fireplace No Device Type Set, deviceType: undefined
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "BLANKED OUT TO KEEP SECRET",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "Master Fireplace",
                        "configDeviceName": "SwitchBot",
                        "configRemoteType": "Others",
                        "other": {
                            "deviceType": "Fan"
                        },
                        "logging": "standard"
                    }
                ]
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

Hub Mini

### Node.js Version

v16.15.1

### NPM Version

not sure what this is?

### Homebridge Version

v1.4.1

### Homebridge Switchbot Plugin Version

@switchbot/homebridge-switchbot v1.13.0

### Operating System

macOS

**Comment by Ab4321** [comment]
Just updated to HomeBridge 1.5.0 and plugin version 1.14.0, same error. Also tried setting it as Remote Type Fan IR, same error.

**Comment by donavanbecker** [comment]
Why is your deviceId = Master Fireplace?

Should be = 02-202206181700-83212306

**Comment by Ab4321** [comment]
Thanks, that solved the issue so not it shows up in HomeKit. Here is my JSON now. Below that is the new error I'm getting when clicking on it in HomeKit...

        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": [DELETED TO KEEP SECRET],
                "notice": "Keep your token a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "02-202206181700-83212306",
                        "configDeviceName": "SwitchBot",
                        "configRemoteType": "Others",
                        "other": {
                            "deviceType": "Fan"
                        },
                        "logging": "standard"
                    }
                ]
            },
            "platform": "SwitchBot"
        }



[6/25/2022, 9:05:22 PM] [SwitchBot] Other: Master Fireplace On Command not set, commandOn: undefined
[6/25/2022, 9:05:27 PM] [SwitchBot] Other: Master Fireplace Off Command not set, commandOff: undefined

**Comment by Ab4321** [comment]
Never mind, figured out how to map the power button to on/off. Is it possible to map other IR buttons to commands too?

**Comment by donavanbecker** [comment]
Not currently
