### ISSUE TITLE
Support Request: Custom IR blast not working on Homekit (DIY AC Remote)

### ISSUE THREAD

**Issue by sekkamoyou** [OpenWonderLabs/homebridge-switchbot#409]
### Describe Your Problem

Custom IR blast not working on Homekit (DIY AC Remote)

### Relevant log output

```shell
[26/06/2022, 05:55:25] [SwitchBot] Air Conditioner: WS AC Sending request to SwitchBot API. command: setAll, parameter: [22,2,1,on], commandType: command
[26/06/2022, 05:55:26] [SwitchBot] Air Conditioner: WS AC Command is not supported.
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "openToken": "",
        "notice": "Keep your token a secret!"
    },
    "platform": "SwitchBot"
}
```

### Screenshots

I'm not native English speaker so sorry for my poor English :(

Just setting up Homebridge and connect with my Switchbots, but one of my AC IR Remote setting not working properly
none of options of switchbot's model options working so I custom up AC On and Off on Switchbot app.
Off is working on Homekit, but On is not, Is there any solutions about it? Thank you.

### Device & Model

Switchbot Hub mini (JP)

### Node.js Version

v16.15.1

### NPM Version

v7.22.0

### Homebridge Version

v1.5.0

### Homebridge SwitchBot Plugin Version

v1.14.0

### Homebridge Config UI X Plugin Version

v4.48.1

### Operating System

Raspbian GNU/Linux Bullseye (Homebridge Image)

**Comment by donavanbecker** [comment]
I would need more details on what would need to happen here. I don't use IR devices.

**Comment by sekkamoyou** [comment]
For example? What kind of details do you need?

**Comment by donavanbecker** [comment]
I guess I don't use Ir devices, so are you wanting an option that you could set a custom On or custom Off Command?

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.1.0-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

I have added a config option into the IR Device settings section.

**Comment by sekkamoyou** [comment]
Ok, I installed 2.1.0 release and check some new options for IR devices but still can't turn on my AC.
Is there something manual about IR devices' commands? If so, I want to read it.

**Comment by donavanbecker** [comment]
@designsforall  what is your config?

**Comment by sekkamoyou** [comment]
```
{
  "deviceId": "deviceId",
  "configDeviceName": "WS AC",
  "configRemoteType": "DIY Air Conditioner",
  "connectionType": "OpenAPI",
  "customize": true,
  "customOn": "On",
  "customOff": "Off",
  "irair": {
    "pushOn": false
  }
}
```

as for now, just type in On and Off for custom commands

```
[14/10/2022, 09:17:55] [SwitchBot] DIY Air Conditioner: WS AC Sending request to SwitchBot API. body: {"command":"setAll","parameter":"25,1,1,on","commandType":"command"},
[14/10/2022, 09:18:01] [SwitchBot] DIY Air Conditioner: WS AC Sending request to SwitchBot API. body: {"command":"SetAll","parameter":"default","commandType":"customize"},
```

and log from Homebridge, First one (as ON ir blast) is not working, but second one (as OFF) is working.

**Comment by donavanbecker** [comment]
Thanks first command shouldn’t have sent it that way with customize on. Let me look at the code. Thanks for the logs

**Comment by donavanbecker** [comment]
@designsforall

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.1.1-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by sekkamoyou** [comment]
Ummm, nope. Now I cant turn off with Homebridge 😂

**Comment by donavanbecker** [comment]
@designsforall let me add some logging and then see if I can reproduce.

**Comment by donavanbecker** [comment]
@designsforall

I think you need to set the Push On Changes Config.

<img width="241" alt="Screenshot 2022-10-14 at 8 07 02 AM" src="https://user-images.githubusercontent.com/9875439/195854455-98d1f5d3-7d0c-4a4b-867c-dafea9ebe41c.png">
