### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Guserhkt** [OpenWonderLabs/homebridge-switchbot#410]
### Describe Your Problem

[SwitchBot] Was 'node-switchbot' found: false

### Relevant log output

```shell
[SwitchBot] Was 'node-switchbot' found: false
[SwitchBot] Curtain: Bedroom wasn't able to establish BLE Connection, node-switchbot: false
```

### Screenshots

Can't seem to get my bluetooth working, it was a fresh install

### Device & Model

Raspberry Pi Zero W

### Node.js Version

v16.15.1

### NPM Version

v5.51

### Homebridge Version

v1.5.0

### Homebridge SwitchBot Plugin Version

v1.14.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Did you follow the prerequisites? On node-SwitchBot that this plugin directs too?

**Comment by apascual** [comment]
Hi @donavanbecker, I followed the instructions, including the noble prerequisites but also got the same issue.

```
[SwitchBot] [DEBUG] Meter uuid: F6BF2C272FDE-Meter, (95af9565-4d00-417c-855e-a6fb3cd2f90a)
[SwitchBot] [DEBUG] Meter: DE BLE Address: f6:bf:2c:27:2f:de`
[SwitchBot] Meter: DE wasn't able to establish BLE Connection, node-switchbot: false
```

**Comment by donavanbecker** [comment]
it is your operating system for some reason it is not able to connect with BLE, sorry not much I can do. If you can figure it out and can add something to like a helpful hints I can create a wiki for it.
