### ISSUE TITLE
Support Request: Unresponsive curtains

### ISSUE THREAD

**Issue by danberger** [OpenWonderLabs/homebridge-switchbot#416]
### Describe Your Problem

Plugin finds my curtains but they're unresponsive

### Relevant log output

```shell
6/29/2022, 10:18:41 PMSwitchbot Bridge starting
6/29/2022, 10:18:54 PMSwitchbot BridgeERROR[31mThe plugin "homebridge-switchbot" requires a Homebridge version of ^1.5.0 which does not satisfy the current Homebridge version of 1.4.1. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
6/29/2022, 10:19:06 PMSwitchbot BridgeLoaded plugin '@switchbot/homebridge-switchbot'
6/29/2022, 10:19:06 PMSwitchbot BridgeLoading 1 platforms...
6/29/2022, 10:19:06 PMSwitchbot BridgeSwitchBotAdding new accessory: Parlor Curtains Curtain DeviceID: CA:CA:3E:96:AB:64
6/29/2022, 10:19:06 PMSwitchbot BridgeSwitchBotWARNINGCurtain: Parlor Curtains scanDuration is less then updateRate, overriding scanDuration with updateRate
6/29/2022, 10:19:07 PMSwitchbot BridgeBridge is running on port 51906.
```

### Config for homebridge-switchbot

```shell
{
    "platform": "SwitchBot",
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "CA:CA:3E:96:AB:64",
                "configDeviceName": "Parlor Curtains",
                "bot": {
                    "mode": "press",
                    "deviceType": "switch"
                },
                "configDeviceType": "Curtain",
                "ble": false
            }
        ]
    }
}
```

### Screenshots

![IMG_0F3527F63F74-1](https://user-images.githubusercontent.com/613302/176592738-67750c52-7723-437b-8693-ce4f053f5a0b.jpeg)

### Device & Model

HOOBS v4.2.5

### Node.js Version

v16.15.1

### NPM Version

unsure

### Homebridge Version

v1.4.1

### Homebridge SwitchBot Plugin Version

v1.14.0

### Operating System

macOS

**Comment by donavanbecker** [comment]
This plugin is desire for homebridge not HOOBs, I would recommend switching

**Comment by danberger** [comment]
HOOBs is Homebridge in a box though... it's running homebridge and uses the same plugin library

**Comment by donavanbecker** [comment]
It is not the same. And since I don't have HOOBs and didn't design the plugin for HOOBs, I won't be able to help you with issues on HOOBs.

**Comment by danberger** [comment]
Understood. Thank you for replying and writing this plugin! <3

**Comment by danberger** [comment]
Wondering if you’d be willing to work with me on this this issue so that you’re plugin is compatible with HOOBS too?

**Comment by donavanbecker** [comment]
@danberger, I have no plan on troubleshooting on HOOBs. I would recommend switching to homebridge.
