### ISSUE TITLE
Bug: IR Air Conditioner has different/missing modes between the iOS app and what gets exposed to HomeKit

### ISSUE THREAD

**Issue by nekonora** [OpenWonderLabs/homebridge-switchbot#423]
### Describe The Bug

IR remote Air Conditioner device added to homebridge is missing modes that are otherwise present in the controls of the iOS App. Specifically `dry` and `fan_only`. Can set only `cool`, `heat` and `auto`.

### To Reproduce

Add and configure a Switchbot account with an Air conditioner remote IR device. Look inside Home.app on iOS or macOS.

### Expected behavior

Air Conditioner device in Home app to have settable `dry` and `fan_only` modes.

### Relevant log output

```shell
No relevant logs, devices are recognised, just modes missing.
```

### Config for homebridge-switchbot

```shell
"platforms": [
        {
            "platform": "SwitchBot",
            "plugin_map": {
                "plugin_name": "homebridge-switchbot"
            },
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "openToken": "///"
            }
        }
    ]
```

### Screenshots

iOS app, can handle all modes (even non needed ones, but it's fine):
![IMG_B944549C54B9-1](https://user-images.githubusercontent.com/7069092/179237908-fb500692-5495-41b2-919d-f43c609d4a37.jpeg)

What gets exposed to HomeKit. Missing `dry` and `fan_only` in this case:
![IMG_B196C32D44B4-1](https://user-images.githubusercontent.com/7069092/179238050-2f3eb50e-932b-47c6-9e56-e65168817c92.jpeg)

### Device & Model

Air Conditioner IR Remote

### Node.js Version

/

### NPM Version

/

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

1.14.1

### Operating System

Docker

**Comment by donavanbecker** [comment]
Not possible to add those other modes.
