### ISSUE TITLE
Feature Request: Support for Pan-Tilt Camera

### ISSUE THREAD

**Issue by andr3a88** [OpenWonderLabs/homebridge-switchbot#429]
### Solution

HomeKit support for Pan/Tilt Camera

**Comment by donavanbecker** [comment]
OpenAPI would have to support first.

**Comment by EcomInsight** [comment]
Any info on this @SwitchBot

**Comment by JanneDeVos** [comment]
Any info on this? @SwitchBot-Wonderlabs

**Comment by donavanbecker** [comment]
@EcomInsight Since SwitchBot cameras are Tuya cameras, There has been some progress with getting this implemented with Tuya. There is a plugin that currently has this working on a branch. I can post more once a release is out.

**Comment by JanneDeVos** [comment]
@donavanbecker thank you, can't wait!

**Comment by donavanbecker** [comment]
@andr3a88 & @EcomInsight, can you try: [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform)?

Until SwitchBot adds the camera to the API, you will have to remove your camera from the switchbot app, down the tuya app and add your camera. Then follow the instructions from this plugin to get your tuya account hooked up to this plugin.

**Comment by donavanbecker** [comment]
Closing as [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) supports this with Tuya which is what SwitchBot Cameras are.
