### ISSUE TITLE
Feature Request: Support for Ceiling light.

### ISSUE THREAD

**Issue by jey3dayo** [OpenWonderLabs/homebridge-switchbot#431]
### Problem

Ceiling light not recognized.

### Solution

Please support Ceiling light of switchbot. https://www.switchbot.jp/products/switchbot-ceiling-light

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.0.0-beta.36/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
Added in v2.0.0

**Comment by jey3dayo** [comment]
@donavanbecker 
Thank you for support!
I tried v2.0.0, but it is not working.

```
[10/13/2022, 2:30:32 PM] [SwitchBot] Total SwitchBot Devices Found: 5
[10/13/2022, 2:30:32 PM] [SwitchBot] Device: My Ceiling Light with Device Type: Ceiling Light Pro, is currently not supported.
[10/13/2022, 2:30:32 PM] [SwitchBot] Submit Feature Requests Here: https://git.io/JL14Z
```

**Comment by donavanbecker** [comment]
@jey3dayo sorry about that. 

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.1.0-beta.7/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by jey3dayo** [comment]
@donavanbecker 
It worked perfectly with 2.1.0-beta.6.
Thank for fixing it!:smile:
