### ISSUE TITLE
Support Request: No IR Devices After Homebridge Uppdate

### ISSUE THREAD

**Issue by TheToLoveRuDarkness** [OpenWonderLabs/homebridge-switchbot#438]
### Describe Your Problem

After the Update to the newest Homebridge UI the IR Device stop working

### Relevant log output

```shell
Yesterday I updated to the latest Homebridge UI and then got the error message in the log that my configuration file for the Switchbot plugin was faulty and I should check it or reinstall the plugin.

Said done I reinstalled the Switchbot plugin. All of the bots I have set up work perfectly and can be added to Apple Home via Homebridge.
Only the IR device (beamer) is no longer possible to be found in the Apple Home app (available in Homebridge devices)

What am I doing wrong?
```

### Config for homebridge-switchbot

```shell
"options": {
                "devices": [
                    {
                        "deviceId": "00000",
                        "configDeviceName": "macMini",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "00000",
                        "configDeviceName": "Leinwand",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "00000",
                        "configDeviceName": "Beamer",
                        "configRemoteType": "TV"
                    }
                ]
            },
            "platform": "SwitchBot"
```

### Screenshots

![5D400BF5-15DE-4FEC-A207-C9BADBA57190](https://user-images.githubusercontent.com/94400178/183827879-2d196bee-cb68-47a1-b780-b525e5ccea61.jpeg)

### Device & Model

Raspberry Pi 3 Model B

### Node.js Version

v16.15.1

### NPM Version

?

### Homebridge Version

v1.5.0

### Homebridge SwitchBot Plugin Version

v1.14.1

### Homebridge Config UI X Plugin Version

v4.50.1

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by donavanbecker** [comment]
Have you tried reinstalling plugin?

**Comment by TheToLoveRuDarkness** [comment]
Yes I have

**Comment by donavanbecker** [comment]
This is something to do with the mqtt client. Which I did not implement.

**Comment by TheToLoveRuDarkness** [comment]
And how can I fix it?

**Comment by donavanbecker** [comment]
Only suggestion I can suggest would be to completely uninstall and remove plugin and then reinstall then reset it up

**Comment by TheToLoveRuDarkness** [comment]
The Error is in the Switchbot Plugin. I tried several installations an 2 complete refreshed Homebridges but im always get this in the Switchbot Plugin Installation.

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v93-linux-arm.tar.gz

**Comment by TheToLoveRuDarkness** [comment]
I now get it somehow fixed but ask me not how.
