### ISSUE TITLE
Feature Request：Switchbot Lock

### ISSUE THREAD

**Issue by kyow41ca** [OpenWonderLabs/homebridge-switchbot#441]
### Solution

I want you to support Switchbot Lock. There is also an API. Thank you.

**Comment by kyow41ca** [comment]
It's already supported. I'm sorry for the lack of confirmation.

**Comment by kyow41ca** [comment]
It's already supported. I'm sorry for the lack of confirmation.

**Comment by jamesalmeida** [comment]
It gives me an error `not support device type` when I try to use the lock: 

<img width="1263" alt="Screen Shot 2022-09-03 at 8 54 04 PM" src="https://user-images.githubusercontent.com/703253/188296942-af6632c6-73ae-4e1b-9eb7-d30c38a9ae84.png">
