### ISSUE TITLE
Support Request: Switchbot lightstrip latency

### ISSUE THREAD

**Issue by LittleJ** [OpenWonderLabs/homebridge-switchbot#442]
### Describe Your Problem

Turning on the light strip is fast. But when I want to change brightness or turn it off it takes up to 15 seconds. The issue happens when I use the Home app on iOS and when I use the switch directly in Homebridge too.

### Relevant log output

```shell
[8/18/2022, 11:57:50 PM] [SwitchBot] [DEBUG] Strip Light: Ruban On: false
[8/18/2022, 11:57:50 PM] [SwitchBot] [DEBUG] Strip Light: Ruban Brightness: 0
[8/18/2022, 11:57:50 PM] [SwitchBot] Strip Light: Ruban Sending request to SwitchBot API. command: turnOff, parameter: default, commandType: command
[8/18/2022, 11:57:51 PM] [SwitchBot] [DEBUG] Strip Light: Ruban pushChanges: {"statusCode":100,"body":{},"message":"success"}
```

### Device & Model

Strip Light (v1.2.8)

### Node.js Version

V16.16.0

### NPM Version

?

### Homebridge Version

V1.5.0

### Homebridge SwitchBot Plugin Version

V1.14.1

### Homebridge Config UI X Plugin Version

V4.50.1

### Operating System

Ubuntu Focal Fossa (20.04.4 LTS) using Docker on Windows Hyper-V

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.0.0-beta.35/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by jimmyfisher** [comment]
Was just poking around trying to see if anyone else had a similar issue - is this possibly the same 15 second delay I just wrote about in #509? Or this could just be some other issue.

**Comment by donavanbecker** [comment]
@jimmyfisher, potentially but not much I can do. if someone else can improve I will take a pull request. Sorry.

**Comment by donavanbecker** [comment]
believe this should have improved in v2.1.0
