### ISSUE TITLE
Feature Request: Use IR Sensor For Input

### ISSUE THREAD

**Issue by bradenpecora** [OpenWonderLabs/homebridge-switchbot#447]
### Problem

It would be nice to be able to use the IR sensor on the hub for input to control my home. I don't know if IR input data goes through the SwitchBot API though...

### Solution

Using a button on a physical remote makes changes in the home

### Additional context

I'd like to be able to control my sound system with just one physical remote. A potential way I could see this being done is:

**Comment by donavanbecker** [comment]
API doesn't have this.
