### ISSUE TITLE
Feature Request: Add Pin Support

### ISSUE THREAD

**Issue by guiltyvictim** [OpenWonderLabs/homebridge-switchbot#45]
**Is your feature request related to a problem? Please describe.**

This plugin does not work if there's a pin set against the bot. I'd like to keep a pin on my bot since I live in an apartment block and I'd like to keep my switch secured

**Describe the solution you'd like**

Config to add pin to access bot

**Describe alternatives you've considered**

Turning off pin, which may compromise my security

**Additional context**

**Comment by donavanbecker** [comment]
@guiltyvictim Pull requests are welcome
