### ISSUE TITLE
Bug: Unable To Update Plugin To Latest Release v1.15.0

### ISSUE THREAD

**Issue by iSteve-O** [OpenWonderLabs/homebridge-switchbot#450]
### Describe The Bug

I am getting an error about a directory not being empty. Never had this issue before & bot is working fine.

### To Reproduce

Try to update from 1.14.2 to 1.15

### Expected behavior

Update success

### Relevant log output

```shell
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@switchbot/homebridge-switchbot
npm ERR! dest /usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot' -> '/usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-28T03_08_56_228Z-debug-0.log (I cannot access this log)
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "openToken": "Xmy_tokenX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "Xmy_deviceX",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    }
                ]
            },
            "platform": "SwitchBot",
            "_bridge": {
                "username": "0E:B1:4E:29:AD:AA",
                "port": 38561
            }
```

### Device & Model

Raspberry Pi 4 model B

### Node.js Version

v16.17.0

### NPM Version

v8.18.0

### Homebridge Version

v1.5.0

### Homebridge Switchbot Plugin Version

v1.14.2

### Homebridge Config UI X Plugin Version

v4.50.1

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
You will have to do sudo rm -R and then the folders in the log, reinstall plugin, finally restart homebridge.

**Comment by iSteve-O** [comment]
> You will have to do sudo rm -R and then the folders in the log, reinstall plugin, finally restart homebridge.

Thank you I will do this. Before I do, will it delete my bot or anything? It would suck to have to redo my automations and all, but I will if I have to. 

Thanks!

EDIT: Thanks that worked. I need to stop being such a ***** LOL
