### ISSUE TITLE
Feature Request: SwitchBot Lock integration

### ISSUE THREAD

**Issue by martindinicolino** [OpenWonderLabs/homebridge-switchbot#454]
### Problem

I can't currently integrate the SwitchBot Lock into HomeKit via Homebridge

### Solution

Please add support for the SwitchBot Lock

### Additional context

Homebridge running on M1 Mac mini with Xcode installed, currently no SwitchBot Hub in this household

**Comment by jamesalmeida** [comment]
Yeah support for the Switchbot Lock would be awesome. My Switchbot Lock is showing up in the Home app but gets an error when I try to lock/unlock it. 

<img width="1263" alt="Screen Shot 2022-09-03 at 8 54 04 PM" src="https://user-images.githubusercontent.com/703253/188296577-c514e025-9577-4504-afeb-65ad2b9c97d8.png">

**Comment by martindinicolino** [comment]
@jamesalmeida are you using a switchbot hub?

i found more information in regards to this issue here https://github.com/OpenWonderLabs/SwitchBotAPI/issues/121
it seems like the Switchbot developers are indeed working on a much needed solution, but some have found a temporary fix by exposing the lock to the smartthings app via the official switchbot integration and then installing the smartthings plugin in homebridge

**Comment by donavanbecker** [comment]
if anyone can help with #474

**Comment by donavanbecker** [comment]
Will be resolved with See https://github.com/OpenWonderLabs/homebridge-switchbot/issues/476

**Comment by martindinicolino** [comment]
Thank you for implementing this!

I noticed that other locks in HomeKit give you the possibility to change the notification preferences (for example only receiving notifications when nobody is at home) - would it be possible to add that functionality to this lock through this plugin?

Please let me know if you would like me to close this issue and start a new one.
Again, your work is much appreciated.

**Comment by donavanbecker** [comment]
> Thank you for implementing this!
> 
> 
> 
> I noticed that other locks in HomeKit give you the possibility to change the notification preferences (for example only receiving notifications when nobody is at home) - would it be possible to add that functionality to this lock through this plugin?
> 
> 
> 
> Please let me know if you would like me to close this issue and start a new one.
> 
> Again, your work is much appreciated.

That is a feature of the home app. You should be able to do that with this lock also.

**Comment by martindinicolino** [comment]
> 

Thank you, I checked again, and for some reason the only way of getting this option to show for this particular lock is under Home settings > Locks > NameOfThisLock; my bad for not checking this particular method
(when exposing this lock to HomeKit via the Smarthings integration, or with other HomeKit locks as far as I can tell, it also appears when opening this locks settings from the favourites tab or room tab - which caused my confusion)

thank you again for your amazing work 👍

**Comment by donavanbecker** [comment]
> > 
> 
> 
> 
> Thank you, I checked again, and for some reason the only way of getting this option to show for this particular lock is under Home settings > Locks > NameOfThisLock; my bad for not checking this particular method
> 
> (when exposing this lock to HomeKit via the Smarthings integration, or with other HomeKit locks as far as I can tell, it also appears when opening this locks settings from the favourites tab or room tab - which caused my confusion)
> 
> 
> 
> thank you again for your amazing work 👍

Could be because this lock is in bridge mode. I am going to add an option to enable it as an external device, but then you will have to re-pair.

Till then I am going to leave this open as a reminder.

**Comment by donavanbecker** [comment]
@martindinicolino, I have added an option to allow for making devices, external accessories. Please test this out. 

You will see this option under device settings. 
You will need to get the device id and set external accessory parameter to true.

This should then show you the setting you are expecting.

**Comment by martindinicolino** [comment]
I‘ll try it out and report back in case i run into any issues, thank you for implementing this

like a different [commenter](https://github.com/OpenWonderLabs/homebridge-switchbot/issues/476#issuecomment-1264673878), i wonder what the difference is (other than adding this ability of course), i‘ll follow the discussion over there

**Comment by martindinicolino** [comment]
i turned this setting on and paired the lock again, but the setting never showed up;
honestly, I am happy with changing this under home settings
thank you for your help

**Comment by donavanbecker** [comment]
> i turned this setting on and paired the lock again, but the setting never showed up;
> 
> honestly, I am happy with changing this under home settings
> 
> thank you for your help

If you click into the subtypes of the device which would show the lock and contact sensor then click into the lock it will. Or you turn the contact sensor off, then it would.
