### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ivanx00** [OpenWonderLabs/homebridge-switchbot#457]
### Describe The Bug

Meter didn't appear in Home app

### To Reproduce

Added in Homebridge, buy can't sei in Home app (or Eve app)

### Expected behavior

To see the meter in the app

### Relevant log output

```shell
nothing
```

### Config for homebridge-switchbot

```shell
all is correct an can see the meter in homebridge
```

### Screenshots

<img width="1097" alt="Schermata 2022-09-02 alle 19 50 08" src="https://user-images.githubusercontent.com/88212307/188209927-8d50a4ec-a2ac-4a98-a65f-06d965791d68.png">

### Device & Model

Meter

### Node.js Version

16.17.0

### NPM Version

8.18.0

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

1.14.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Please fill out details correctly

**Comment by ivanx00** [comment]
done

**Comment by donavanbecker** [comment]
I will close. When if you can open a new issue with config, etc. I can review.
