### ISSUE TITLE
v2.0.0 - Beta Testers Needed

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/homebridge-switchbot#476]
With the move from v1.0 to v1.1 SwitchBot API, there will be a lot of changes.

Please install the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.0.0-beta.37/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

Report Beta Issues here. *I may request you to open separate issues if it is not related to something changed in the beta.*

## API Changes
- [x] Authentication with v1.1 of API
- [x] Device Refresh Status
- [x] Device Push Changes
- [x] Device IR Push Changes

## Note
- A new `secret` key config is required to be set.
- `openToken` config has been changed to `token` a process is in place to move your `openToken` config to the new `token` config but requires you to restart homebridge/child bridge or you can just paste the your `token` into the new `token` config and an additional restart will not be required.
- Added `connectionType` config, this replaces the `BLE` config.
  - You can now select Both Connections, Only OpenAPI, Only BLE, or Disable.
    - `Both` will use BLE as the default connection and will use OpenAPI as a backup connection.
    - `OpenAPI` will only allow connections through the OpenAPI.
    - `BLE` will only allow connections through Bluetooth (BLE), .
    - `Disable` will disable all connections. This will also allow you to disable commands and refreshes for a specific device but leave it in HomeKit.

## Pull Request For Changes
#474

**Comment by donavanbecker** [comment]
Made progress on push changes. Should be able to get a good working beta out soon.

**Comment by chinedu40** [comment]
I'm having a problem with the switchbot lock. Error message below:

[9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen Set LockTargetState: 0
[9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen Sending request to SwitchBot API. command: unlock, parameter: default, commandType: command
[9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen sign: 0N95IZItNe5guBuxnVcAG/SqBMZn4rplPBix/3oPheI=
[9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen failed pushChanges
[9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen failed pushChanges, Error Message: "The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object"

In fact this happens with every accessory that i use with switchbot.

**Comment by martindinicolino** [comment]
> I'm having a problem with the switchbot lock. Error message below:
> 
> [9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen Set LockTargetState: 0 [9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen Sending request to SwitchBot API. command: unlock, parameter: default, commandType: command [9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen sign: 0N95IZItNe5guBuxnVcAG/SqBMZn4rplPBix/3oPheI= [9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen failed pushChanges [9/20/2022, 11:16:32 AM] [SwitchBot] Lock: Kitchen failed pushChanges, Error Message: "The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object"
> 
> In fact this happens with every accessory that i use with switchbot.

I'm seeing the same error messages

additionally the lock's contact sensor always shows as being open (although the lock registers the change and shows its blue/green light every time the door is opened/closed)

**Comment by guptaramm** [comment]
Same here 
using beta I am getting this error "Lock: Door lock failed pushChanges"

Lock: Door lock failed pushChanges, Error Message: "The first argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object"

**Comment by donavanbecker** [comment]
I am going to lock this issue till I get push changes completed. If you read ⬆️ above, that is still an issue I am working on.

**Comment by donavanbecker** [comment]
Push Change support implemented for SwitchBot Devices, May still have issues with IR Devices. Please let me know.

@guptaramm @martindinicolino @chinedu40

**Comment by chinedu40** [comment]
Locking and unlock work well! -  FYI There is a slight delay in updating the status of the lock in the home app when either action is completed, whereas the switchbot app picks it up much faster. 

My curtains and lightstrip also work now. 

Unfortunately i do not have an IR devices to test

**Comment by donavanbecker** [comment]
@chinedu40, the SwitchBot app is using BLE, where as this plugin is sending a command to the API (Cloud) to make the change.

I will add BLE support to the plugin, once node-switchbot supports it.

**Comment by oliveralonzo** [comment]
Thanks for all your work on this @donavanbecker! The beta is working for the most part for me, including the lock, which was really exciting after waiting since support for the lock was removed. I say for the most part because I got this error a few times "Lock: Front Door failed pushChanges," but it worked in between and after.

And just a piece of feedback, consider making those error messages a bit more descriptive if you'd like users to understand what they mean! I may have misinterpreted this, but I took the question of "did you even read the message?" to be a bit passive agressive in the API issue/thread, when I was just trying to help. But it was hard to conclude that pushing changes wasn't supported if the message simply said it failed (I remember it saying something about the OpenAPI, but that didn't suggest it wasn't implemented either). I'm happy to continue supporting the projects with my feedback, so I thought this would be helpful, too!

**Comment by donavanbecker** [comment]
@oliveralonzo, you may feel that way, but it was an actual question because clearly it states that push changes were support resolved at the time. Either way, it is done now. Thanks for testing.

FYI: I don't work for SwitchBot, I manage this plugin for them on my own free time.

**Comment by grunkyb** [comment]
API 1.1 works for me: humidifier (WiFi), bot (BLE), curtains x 2 (BLE).

**Comment by martindinicolino** [comment]
Hi @donavanbecker, thank you very much for your efforts, this is great progress, the lock is working perfectly when connected via the bridge now.
The lock does not work over BLE, although I am unsure whether that is due to the plugin or rather the SwitchBot BLE API.

I just added an IR device and will be testing it during the next few days and come back with some feedback then.

One more thing: I thought you might want to know that the lock's contact sensor now shows as always being open (within HomeKit) despite the lock registering the change every time the door is opened/closed (it was always showing as being closed whilst running the beta yesterday, so maybe it has to do with some recent change)

keep up the good work!

**Comment by crouchingtiger** [comment]
Getting this in my logs, not on all command pushes though.

```
[9/22/2022, 1:36:56 PM] [SwitchBot] Esszimmer Vorhang Rechts Mode: Default Mode
[9/22/2022, 1:36:56 PM] [SwitchBot] Curtain: Esszimmer Vorhang Rechts Sending request to SwitchBot API. body: {"command":"setPosition","parameter":"0,ff,100","commandType":"command"},
[9/22/2022, 1:36:56 PM] [SwitchBot] Curtain: Esszimmer Vorhang Rechts failed pushChanges with OpenAPI Connection
[9/22/2022, 1:36:56 PM] [SwitchBot] Curtain: Esszimmer Vorhang Rechts failed pushChanges with OpenAPI Connection, Error Message: "Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle"
```

**Comment by donavanbecker** [comment]
> Getting this in my logs, not on all command pushes though.
> 
> ```
> [9/22/2022, 1:36:56 PM] [SwitchBot] Esszimmer Vorhang Rechts Mode: Default Mode
> [9/22/2022, 1:36:56 PM] [SwitchBot] Curtain: Esszimmer Vorhang Rechts Sending request to SwitchBot API. body: {"command":"setPosition","parameter":"0,ff,100","commandType":"command"},
> [9/22/2022, 1:36:56 PM] [SwitchBot] Curtain: Esszimmer Vorhang Rechts failed pushChanges with OpenAPI Connection
> [9/22/2022, 1:36:56 PM] [SwitchBot] Curtain: Esszimmer Vorhang Rechts failed pushChanges with OpenAPI Connection, Error Message: "Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle"
> ```

I will look into this.

**Comment by donavanbecker** [comment]
@crouchingtiger this is only happening on your curtains right?

If so, can you test the latest beta?

**Comment by crouchingtiger** [comment]
@donavanbecker Yes, I only have curtains (18 of them) and a Hub Mini. Updated to ``v2.0.0-beta.4``, so far no errors on parsing that I can see 👍 

Thanks for the plugin, it's what made me take the plunge and order so many...

**Comment by donavanbecker** [comment]
Wow! 18 of them, glad that I can help. Looks like a pause command might have been added to the API, so might try to implement that.

**Comment by Jacksonbm1** [comment]
Just wanted to double check, the beta doesn't support ble direct connections yet right? Thanks for your help!

**Comment by nyjklein** [comment]
I tried installing the beta (beta4) but the conversion to the new API seems to have gone wrong for me:

[23/09/2022, 09:22:41] [SwitchBot] Failed to Discover Devices, Error Message: "The \"key\" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined"

Did i miss a step? How can I correct this?

Jeff

**Comment by donavanbecker** [comment]
@nyjklein can you create a separate issue and fill out all info so I have more info?

**Comment by donavanbecker** [comment]
> Just wanted to double check, the beta doesn't support ble direct connections yet right? Thanks for your help!

BLE support has been in this plugin for a while for certain devices. Which device are you wondering about?

**Comment by Jacksonbm1** [comment]
Oops. I meant for the lock

**Comment by donavanbecker** [comment]
> Oops. I meant for the lock

Unfortunately that API isn't available yet. Once it is, I will implement.

**Comment by nyjklein** [comment]
> @nyjklein can you create a separate issue and fill out all info so I have more info?

I noticed in the account config that the new "secret" was blank. Looks like it didn't get "translated" in my case. I used the SwitchBot app developer instructions and saw that it now generates the secret as well as the token. Pasted the secret into the Homebridge swicthbot account settings and I'm up and running!

Jeff

**Comment by donavanbecker** [comment]
Awesome! 

Yes the openToken should have also been moved to the token parameter automatically for you also. I am guessing you saw a log that said restart homebridge/child bridge?

**Comment by nyjklein** [comment]
![Screenshot 2022-09-23 093755](https://user-images.githubusercontent.com/76184316/191984144-82c083ba-843c-4109-8137-75d165c4a10b.png)
> Awesome!
> 
> Yes the openToken should have also been moved to the token parameter automatically for you also. I am guessing you saw a log that said restart homebridge/child bridge?

Yes. And I had read the notes above that said a second restart would "migrate" the secret key. Not sure why it didn't for me.

**Comment by donavanbecker** [comment]
> Yes. And I had read the notes above that said a second restart would "migrate" the secret key. Not sure why it didn't for me.

where did you see that note?

**Comment by nyjklein** [comment]
> > Yes. And I had read the notes above that said a second restart would "migrate" the secret key. Not sure why it didn't for me.
> 
> where did you see that note?

Duh! Sorry. I misinterpreted the notes above thinking it would "migrate" the token to the secret.

**Comment by crouchingtiger** [comment]
> Wow! 18 of them, glad that I can help. Looks like a pause command might have been added to the API, so might try to implement that.

I just switched over this morning from OpenAPI to BLE on my Pi, just to remove the latency and additional point of failure as I don't require any of the other Switchbot cloud services. Seems to run fairly smoothly, hard to tell but there's definitely a few ms of speed gained by interacting via the Pi rather than the Hub Mini.

Off-topic: Have you run any long-term battery tests of BLE from the Hub or the Homebridge device and noticed any performance differences? Is there an ideal scan duration or curtain update rate I could set that might extend the battery life?

**Comment by donavanbecker** [comment]
I have added an option to allow for making devices, external accessories. Please test this out. 

You will see this option under device settings. 
You will need to get the device id and set external accessory parameter to true.

**Comment by nyjklein** [comment]
> 

Could you clarify what making a device an "external accessory" means?

Jeff

**Comment by donavanbecker** [comment]
you have your own pairing code so won't automatically show up in the home app when its connected to homebridge/child bridge. 

Like the TV does if you have an IR TV accessory.

**Comment by donavanbecker** [comment]
@martindinicolino @nyjklein, also if the single accessory is taking a long time to load it doesn't hold up the rest of the device on homebridge.

Only downfall is you loose cache which would only matter in the case of IR Devices.

**Comment by martindinicolino** [comment]
> @martindinicolino @nyjklein, also if the single accessory is taking a long time to load it doesn't hold up the rest of the device on homebridge.
> 
> Only downfall is you loose cache which would only matter in the case of IR Devices.

thank you for the information

**Comment by Niklas31** [comment]
Hi! I opened the issue #490, but I believe now that it belong to this topic. Could you help me?

**Comment by donavanbecker** [comment]
@Niklas31, You need to add your secret in from the SwitchBot app. See the Notes section of this Issue.

**Comment by Niklas31** [comment]
Awesome! Worked like a charm. Now the only warning I have is `WARNING Curtain: Curtain scanDuration is less then updateRate, overriding scanDuration with updateRate `

I could not find scandurantion in settings to change it

**Comment by donavanbecker** [comment]
<img width="727" alt="Screenshot 2022-10-05 at 10 55 07 AM" src="https://user-images.githubusercontent.com/9875439/194106040-59aed8f4-6d70-4f98-aa11-1b7c7d11bdc1.png">
BLE Scan Duration

**Comment by Niklas31** [comment]
There is no Scan Duration on mine:
![image](https://user-images.githubusercontent.com/64484669/194117697-6c560612-cfcf-4412-8ebe-881f51e23dda.png)

But I added it manually in.

Only one more question:

I have only two Switchbot accessories, but it is finding 2 more from CACHE. How can I clean my cache?
Here is my LOG:
`BridgeSwitchBotTotal SwitchBot Devices Found: 4`
`Switchbot BridgeSwitchBotRestoring existing accessory from cache: Curtain DeviceID: C8F115DC060C`
`Switchbot BridgeSwitchBotRestoring existing accessory from cache: Fan DeviceID: CE5138BFD63E `

**Comment by donavanbecker** [comment]
@Niklas31 you are using HOOBs right? Switch to homebridge.


This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by Niklas31** [comment]
OK, I will check on that. Thanks for the support. Everything is working perfect now (it is not passing the 2 extra accessories to HomeKit).

**Comment by jonathan-catt** [comment]
Hey @donavanbecker I am testing out the beta but am having a hard time with setting up a new IR device. It looks like the plugin is recognizing an IR device in the logs, but it never prints the DeviceID such that it can be setup in the config.

Here is what my logs look like after a child bridge restart:
`
[10/8/2022, 7:58:14 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[10/8/2022, 7:58:14 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v2.0.0-beta.19 child bridge successfully
[10/8/2022, 7:58:14 PM] Loaded 2 cached accessories from cachedAccessories.0E12876AA27E.
[10/8/2022, 7:58:14 PM] [SwitchBot] The devices config section is missing the *Device ID* in the config. Please check your config.
[10/8/2022, 7:58:14 PM] [SwitchBot] The devices config section is missing the *Device Type* in the config. Please check your config.
[10/8/2022, 7:58:14 PM] Homebridge v1.5.0 (HAP v0.10.3) (SwitchBot) is running on port 58654.
[10/8/2022, 7:58:14 PM] [SwitchBot] Total SwitchBot Devices Found: 4
[10/8/2022, 7:58:14 PM] [SwitchBot] Restoring existing accessory from cache: Front Door DeviceID: D3C08FFAD710
[10/8/2022, 7:58:14 PM] [SwitchBot] Restoring existing accessory from cache: Window Fan DeviceID: F01F5A5C3BD8
[10/8/2022, 7:58:14 PM] [SwitchBot] Device: Front Door Keypad with Device Type: Keypad Touch, is currently not supported.
[10/8/2022, 7:58:14 PM] [SwitchBot] Submit Feature Requests Here: https://git.io/JL14Z
[10/8/2022, 7:58:14 PM] [SwitchBot] Total IR Devices Found: 1
[10/8/2022, 7:58:14 PM] [SwitchBot] Cannot read properties of undefined (reading 'toUpperCase')
[10/8/2022, 7:58:14 PM] [SwitchBot] Bot: Window Fan Config: {"mode":"switch","deviceType":"fan","allowPush":true,"doublePress":1,"openAPI":true}
[10/8/2022, 7:58:14 PM] [SwitchBot] Bot: Window Fan Displaying as Fan
`

And relevant config section:
`    
"options": {
        "devices": [
            {
                "deviceId": "F01F5A5C3BD8",
                "configDeviceName": "Window Fan",
                "configDeviceType": "Bot",
                "openAPI": true,
                "bot": {
                    "mode": "switch",
                    "deviceType": "fan",
                    "allowPush": true,
                    "doublePress": 1
                }
            }
        ],
        "irdevices": [
            {
                "openAPI": true
            }
        ]
    },
`

**Comment by chinedu40** [comment]
Beta version 21 has removed all my switchbot and IR devices.

**Comment by donavanbecker** [comment]
@chinedu40, you need to set your connectionType. Also I will fix it so there is a default.

**Comment by chinedu40** [comment]
How do i set my connectionType?

**Comment by donavanbecker** [comment]
@chinedu40, set your device, in the device config with its device id, then assign connection type.

**Comment by donavanbecker** [comment]
Also beta.21 shouldn't have deleted the devices. Only beta.20 had that problem.

**Comment by donavanbecker** [comment]
V2.0.0 has been released. If you have any issues please open a new issue with info needed to research.
