### ISSUE TITLE
Support Request: Plugin waiting 15 seconds before sending command to Switch-Bot App/API

### ISSUE THREAD

**Issue by jimmyfisher** [OpenWonderLabs/homebridge-switchbot#509]
### Describe Your Problem

I just updated to 2.0.0 from 1.15.0. Reconfigured the openToken to token as well as adding the secret. All of my devices show up as they did before, but now when I turn something on/off in the Home app, I can see in my logs that there is a 15 second delay (exactly, every time) between when the plugin sees the command and when the command is sent to Switch-bot. Can't figure out how to change that. I updated the 'push rate' to '1', but that only made the delay exactly 16 seconds.

### Relevant log output

```shell
10/12/2022, 12:26:02 PMSwitchbot BridgeSwitchBotBot: Deck Lights Set On: true
10/12/2022, 12:26:18 PMSwitchbot BridgeSwitchBotBot: Deck Lights Sending request to SwitchBot API. body: {"command":"turnOn","parameter":"default","commandType":"command"},
10/12/2022, 12:27:03 PMSwitchbot BridgeSwitchBotBot: Deck Lights Set On: false
10/12/2022, 12:27:19 PMSwitchbot BridgeSwitchBotBot: Deck Lights Sending request to SwitchBot API. body: {"command":"turnOff","parameter":"default","commandType":"command"},

10/12/2022, 12:28:59 PMSwitchbot BridgeSwitchBotBot: Deck Lights Set On: true
10/12/2022, 12:29:14 PMSwitchbot BridgeSwitchBotBot: Deck Lights Sending request to SwitchBot API. body: {"command":"turnOn","parameter":"default","commandType":"command"},
10/12/2022, 12:29:22 PMSwitchbot BridgeSwitchBotBot: Deck Lights Set On: false
10/12/2022, 12:29:37 PMSwitchbot BridgeSwitchBotBot: Deck Lights Sending request to SwitchBot API. body: {"command":"turnOff","parameter":"default","commandType":"command"},
```

### Device & Model

RPi 4

### Node.js Version

16.17.1

### NPM Version

8.19.2

### Homebridge Version

1.5.0

### Homebridge SwitchBot Plugin Version

2.0.0

### Operating System

Raspbian

**Comment by xhi-nico** [comment]
I am having the same issue; I am noticing that while the plugin receives the request immediately, it takes a while before sending the actual request to OpenAPI:

[12/10/2022, 14:54:33] [SwitchBot] Bot: Door Buzzer Set On: true --REQUEST RECEIVED
[12/10/2022, 14:54:48] [SwitchBot] Bot: Door Buzzer Sending request to SwitchBot API. body: {"command":"press","parameter":"default","commandType":"command"} --REQUEST SENT

I don't think this was an issue in the beta.

**Comment by Gus-smarthome** [comment]
Same issue here!

**Comment by jimmyfisher** [comment]
Totally guessing here, but in the bot.ts source files, there's this line that has 15000 (is that 15 seconds?)

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/35467099/195439289-8d02d976-18df-4bf4-82e1-5cf83c80402f.png">

Have no idea, but trying to see if I could find something involving the bot, 15 seconds, and refreshing/syncing info

**Comment by jimmyfisher** [comment]
No, that didn't do anything. I changed the code on my end to do a temporary test and same 15 second delay between Home app press and the API call.

That said, I can't find anything else in the code that has 15000 listed out as milliseconds. So maybe it is this, but something is getting hung up elsewhere?

**Comment by jimmyfisher** [comment]
OK further exploration in hopes of solving...

If I enter any number, including the placeholder '1', in the 'Push Rate' field, it's adding to 15 seconds. So here:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/35467099/195450847-34bb4a8d-deb9-421a-9bce-e1e468b54d03.png">

Ends up with this in the logs:

> 10/12/2022, 4:24:02 PMSwitchbot BridgeSwitchBotBot: Bedroom Stars Set On: true
> 
> 10/12/2022, 4:24:20 PMSwitchbot BridgeSwitchBotBot: Bedroom Stars Sending request to SwitchBot API. body: {"command":"turnOn","parameter":"default","commandType":"command"},
> 

You'll see the timestamps are 18 seconds apart (the 'default' 15 + the 3 that I added in the 'Push Rate' field)

Another random example:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/35467099/195451054-8f715e27-d50a-4a5b-a371-a86a475a5f48.png">

And the log showing 25 seconds apart ('default' 15 + the 10 second 'Push Rate':

> 10/12/2022, 4:26:44 PMSwitchbot BridgeSwitchBotBot: Bedroom Stars Set On: true
> 
> 10/12/2022, 4:27:09 PMSwitchbot BridgeSwitchBotBot: Bedroom Stars Sending request to SwitchBot API. body: {"command":"turnOn","parameter":"default","commandType":"command"},
> 
> 10/12/2022, 4:27:23 PMSwitchbot BridgeSwitchBotBot: Bedroom Stars Set On: false
> 
> 10/12/2022, 4:27:48 PMSwitchbot BridgeSwitchBotBot: Bedroom Stars Sending request to SwitchBot API. body: {"command":"turnOff","parameter":"default","commandType":"command"},
> 

Changing the refresh rate doesn't do anything as far as timing, in my tests. Only seems to mess up/disable it actually doing anything if I make it quick vs. the 6 min/360 second default (or at least placeholder in the configuration)

If I leave the 'Push Rate' field blank, that's where I see the 15 second delay.

**Comment by CooperCGN** [comment]
Same problem, good to know it’s nothing specific on my side.

**Comment by donavanbecker** [comment]
is this only happening with Bot devices?

**Comment by jimmyfisher** [comment]
I only have bots to test - however, was going to open another ticket tonight or tomorrow re: motion sensors showing immediate 'motion detected' alerts in the Switchbot app but not coming through most times to the Home app when 'cloud services' is turned on.

Attempted to do BLE on 1.15.0 - did the config info properly, and the motion sensor showed up, but there was an error saying 'couldn't connect to BLE, defaulting back to OpenAPI' (or something along those lines). 

Once updated to 2.0.0, it won't even show up unless I use OpenAPI via the 'cloud services' option in the app. The config info is all there, tested the BLE by scanning in the terminal (all works and the motion sensor's MAC address shows up), but still nothing in the plugin logs.

Assuming these are two unrelated issues, but since the motion being detected is having a lag (and this is also lag-related), figured worth mentioning.

**Comment by jimmyfisher** [comment]
Actually, I do have a strip light that I forgot about.

Just plugged it in, refreshed the bridge for the app, and when I turn on off, this is what the logs show:

> 10/12/2022, 5:49:22 PMSwitchbot BridgeSwitchBotStrip Light: Strip Light Sending request to SwitchBot API. body: {"command":"turnOn","parameter":"default","commandType":"command"},

> 10/12/2022, 5:49:33 PMSwitchbot BridgeSwitchBotStrip Light: Strip Light Sending request to SwitchBot API. body: {"command":"turnOff","parameter":"default","commandType":"command"},

And it turns on/off immediately. By that I mean within 2-3 seconds from the Home app press.

It is kinda weird - if I tap on/off too quickly in the Home app, it shows this:

> 10/12/2022, 5:51:50 PMSwitchbot BridgeSwitchBotStrip Light: Strip Light Sending request to SwitchBot API. body: {"command":"turnOn","parameter":"default","commandType":"command"},
> 
> 10/12/2022, 5:51:54 PMSwitchbot BridgeSwitchBotStrip Light: Strip Light Set On: false
> 
> 10/12/2022, 5:52:00 PMSwitchbot BridgeSwitchBotStrip Light: Strip Light Sending request to SwitchBot API. body: {"command":"turnOff","parameter":"default","commandType":"command"},
> 

And it shows 'off' in the Home app momentarily, then shows 'on', then I tap again, and it actually goes off.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.1.0-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

- Added `pushRatePress` config to set how many seconds inbetween doublePresses.
  - Also if `doublePress` isn't set it will not wait to pushChanges.

**Comment by jimmyfisher** [comment]
Is there a way to get that beta to show up in the 'versions'?

I'm on HOOBS and it appears that the only way to do the 'different version' test is via this tab (unless I'm mistaken... still kinda new to all of this)

<img width="391" alt="image" src="https://user-images.githubusercontent.com/35467099/195463803-4e329db8-3033-4bf1-b13c-f9becbd37b2e.png">

**Comment by donavanbecker** [comment]
@jimmyfisher

This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by jimmyfisher** [comment]
Thanks - I know and saw that as a reply to a diff thread. But want to see if I can help - is there a way for me to get the beta installed? I can theoretically manually make the changes that you've done in there, but figured this may be possible.

**Comment by jimmyfisher** [comment]
> @jimmyfisher
> 
> This plugin isn't developed for HOOBs.
> 
> I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

Also, I'm on HOOBs v4 - seems like that link specifically says that it doesn't work beyond v3. So I'm a bit stuck.

**Comment by jimmyfisher** [comment]
FWIW - I manually did those changes from the beta that were pertinent to this, and still the 15 second delay.

Downgraded back to 1.15.0 and, while I had to paste the token in the configuration field, once I did that, everything is functioning normally.

**Comment by donavanbecker** [comment]
> FWIW - I manually did those changes from the beta that were pertinent to this, and still the 15 second delay.
> 
> 
> 
> Downgraded back to 1.15.0 and, while I had to paste the token in the configuration field, once I did that, everything is functioning normally.

Doesn't really help this issue if you weren't able to test my changes. Please switch to homebridge if you would like to test.

**Comment by jimmyfisher** [comment]
As I was saying, I did test the changes - I made them manually to the specific files (matched your change log). Those didn't work and I figured after the day of troubleshooting and trying to figure out what was going on, I would temporarily revert back until I heard back.

@CooperCGN @Gus-smarthome @GeorgeeNico - are you able to test the beta and see if it fixes it? I'm curious.

@donavanbecker - if HOOBS is based on Homebridge, what's the difference between the two? When you say the plugin isn't developed for HOOBS (all of the plugins I have installed on HOOBS are all homebridge-______)

Thanks!

**Comment by xhi-nico** [comment]
Fixed on latest beta! No delay at all.

```
[12/10/2022, 20:55:08] [SwitchBot] Bot: Door Buzzer Set On: true
[12/10/2022, 20:55:08] [SwitchBot] Bot: Door Buzzer Sending request to SwitchBot API. body: {"command":"press","parameter":"default","commandType":"command"}
```

**Comment by donavanbecker** [comment]
> @donavanbecker - if HOOBS is based on Homebridge, what's the difference between the two? When you say the plugin isn't developed for HOOBS (all of the plugins I have installed on HOOBS are all homebridge-______)

HOOBs is not based off homebridge. Also Homebridge has a completely different UI which is what I design my plugin around and HOOBs doesn't support. just because homebridge-______ plugins can be installed doesn't mean it is designed for it.

**Comment by donavanbecker** [comment]
> Fixed on latest beta! No delay at all.
> 
> ```
> [12/10/2022, 20:55:08] [SwitchBot] Bot: Door Buzzer Set On: true
> [12/10/2022, 20:55:08] [SwitchBot] Bot: Door Buzzer Sending request to SwitchBot API. body: {"command":"press","parameter":"default","commandType":"command"}
> ```

@GeorgeeNico thanks for confirming!!!

**Comment by jimmyfisher** [comment]
> > @donavanbecker - if HOOBS is based on Homebridge, what's the difference between the two? When you say the plugin isn't developed for HOOBS (all of the plugins I have installed on HOOBS are all homebridge-______)
> 
> HOOBs is not based off homebridge. Also Homebridge has a completely different UI which is what I design my plugin around and HOOBs doesn't support. just because homebridge-______ plugins can be installed doesn't mean it is designed for it.

Thanks - didn't know all that. Makes sense. Glad that beta worked for others.

**Comment by donavanbecker** [comment]
@jimmyfisher sorry if I come off strong, but just stating my thoughts. Also feel homebridge has a better UI.

**Comment by CooperCGN** [comment]
@donavanbecker can confirm too, latest beta working as expected. Bot is turned on without the long delay.

**Comment by jimmyfisher** [comment]
@donavanbecker should I open a diff issue re: the motion sensors not updating in the Home app? I'm currently using Switchbot's automations to do what I was trying to do in the Home app yesterday.

I cannot get the BLE thing to work where the motion sensor is talking directly to the RPi. I did confirm that my hardware has BLE and is able to show me a scan using BlueZ and sees the MAC address of the sensor.

Is there a process in which the motion sensor detecting motion fairly quickly shows up in the Home app? Or that's a refresh issue?

**Comment by donavanbecker** [comment]
@jimmyfisher, unfortunately motion sensors will never be good with the OpenAPI because of the daily refresh limit.

**Comment by jimmyfisher** [comment]
That's why I'd use the BLE right?

I guess I'm lost as to the configuration. If I add the device ID, the name, choose 'motion sensor', and check 'Enable BLE', when I restart the bridge, it scans and identifies the motion sensor, but then doesn't update. 1.15.0 was showing the sensor while 2.0.0 (when I had the config the same way) didn't show it at all.

I followed all of the install steps with BLE, BlueZ, blocking that one plugin in the .js file... but still nothing showing up.

Is the best bet to just stick to using Switchbot's app for motion sensor automations?

Thanks again!

**Comment by donavanbecker** [comment]
Let's open a new issue for this. I haven't messed around with motion sensors and BLE for a while.

**Comment by donavanbecker** [comment]
v2.1.0 will be released soon which resolves this issue.
