### ISSUE TITLE
Curtains don´t work after update 

### ISSUE THREAD

**Issue by frimar75** [OpenWonderLabs/homebridge-switchbot#510]
### Describe The Bug

The curtains are shown in homekit but don´t work

### To Reproduce

upgrade, try to close/ open the curtains

### Expected behavior

they open/ close

### Relevant log output

```shell
[12/10/2022, 20:22:36] [SwitchBot] "secret" config is not populated, you must populate then please restart Homebridge.
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "token": ""
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "C2D8D079561D",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "F15CF1775320",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "C37C96724591",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "D39B279E7BF9",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch"
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Device & Model

curtains

### Node.js Version

16.17.1

### NPM Version

8.19.2

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

2.0.0

### Homebridge Config UI X Plugin Version

4.50.1

### Operating System

raspbian

**Comment by att11** [comment]
Exact same problem with my devices, also raspbian. Rolled back to 1.15, but did not help.

**Comment by jimmyfisher** [comment]
From the main page:

> Generate an Secret within the App
Click Bottom Profile Tab
Click Preference
Click App version 10 Times, this will enable Developer Options
Click Developer Options
Click Copy secret to Clipboard
Input your secret into the config parameter

I'm on HOOBS and when I updated, the configuration didn't show any new field for 'secret', but if you go to Advanced, under the credentials section, you change 'openToken' to 'token' and add a 'secret' field like this:

`            "credentials": {
                "notice": "Keep your token a secret!",
                "token": "put your token here",
                "secret": "put your secret here"
            },
`

This section:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/35467099/195449272-11c71fcc-1dad-4f4f-9761-492d9c5afacb.png">


No idea if that's related to the curtains, but as far as that log message, this is how you get it to reconnect.

**Comment by donavanbecker** [comment]
@frimar75, did you populate the secret from the app?


@att11, Would need more info on your setup.

@jimmyfisher, This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by att11** [comment]
hi @donavanbecker, thanks, in my case the line with the secret was missing from the config completely - not sure if it was there before when it worked (can't remember) and disappeared after the upgrade? Anyway, entered a line with it and put a code in, now works fine.

**Comment by donavanbecker** [comment]
@att11, secret is a new credential config that you need, so probably wasn't there. Glad its working.

**Comment by donavanbecker** [comment]
perfect closing as I will release v2.1.0 soon with this fix.
