### ISSUE TITLE
Support Request: Secret

### ISSUE THREAD

**Issue by siobhanellis** [OpenWonderLabs/homebridge-switchbot#512]
### Describe Your Problem

Config now asks for Secret

### Relevant log output

```shell
Config now asks for Secret. I have looked in Help/documentation on Github and can't find any information on this.
```

### Screenshots

![Screen Shot 2022-10-13 at 09 11 50](https://user-images.githubusercontent.com/33163141/195540553-f7c9b039-a62e-43d2-b42e-7fd0c70ac2fd.png)

### Device & Model

Config

### Node.js Version

v16.14.0

### NPM Version

8.3.1

### Homebridge Version

1.5.0

### Homebridge SwitchBot Plugin Version

v2.0.0

### Homebridge Config UI X Plugin Version

4.50.1

### Operating System

MacOS

**Comment by donavanbecker** [comment]
@siobhanellis sorry about that. This is part of the [API Change](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/latest/CHANGELOG.md#whats-changed) from v1.0 to v1.1. Once you input that from the app you will be good to go.

**Comment by siobhanellis** [comment]
Where do I find this in the app?

Siobhan

**Comment by donavanbecker** [comment]
same place you found the token, in Developer Options.

**Comment by siobhanellis** [comment]
All good. Working now.

Siobhan

IOT: Practical HomeKit: ( https://practicalhomekit.blogspot.com )
Charity Fundraising: Lammie Drive: ( lammiedrive.blogspot.com<http://lammiedrive.blogspot.com/> )


From: Donavan Becker ***@***.***>
Date: Thursday, 13 October 2022 at 11:16
To: OpenWonderLabs/homebridge-switchbot ***@***.***>
Cc: siobhanellis ***@***.***>, Mention ***@***.***>
Subject: Re: [OpenWonderLabs/homebridge-switchbot] Support Request: (Issue #512)

same place you found the token, in Developer Options.
