### ISSUE TITLE
Support Request: Getting Motion Sensors to Connect Over BLE and Update the Home App Quickly

### ISSUE THREAD

**Issue by jimmyfisher** [OpenWonderLabs/homebridge-switchbot#514]
### Describe Your Problem

The goal is to add the motion sensor to the Home app to allow for automations (like you can do in the Switchbot app) where if motion is detected, something else happens. 

Right now, when connecting over OpenAPI, the device shows up in the Home app, but only has responded to the 'motion detected' trigger (visible in the Switchbot app) on rare occasion. I believe this has to do with the refresh rate. 

Attempted to use the config to add the sensor over BLE (running off a RPi 4, tested BlueZ and it can accurately scan/locate the MAC address of the motion sensor). In 1.15.0, the sensor showed up in the logs, saying it was connecting over BLE vs. OpenAPI. However, it did not show up in the Home app.

Updated to 2.0.0 and, with the same config, couldn't get a log entry at all. At one point on 1.15.0, it gave me a red 'cannot connect via BLE, using OpenAPI' message.

### Relevant log output

```shell
10/13/2022, 2:44:40 PMSwitchbot BridgeSwitchBotAdding new accessory: Basement Door Motion Motion Sensor DeviceID: xxxxxxxxxxx

10/13/2022, 2:44:40 PMSwitchbot BridgeSwitchBotMotion Sensor: Basement Door Motion Config: {"ble":true}
```

### Config for homebridge-switchbot

```shell
"options": {
                "debug": "debug",
                "devices": [
                    {
                        "deviceId": "xxxxxxxxxxx",
                        "configDeviceName": "Basement Door Motion",
                        "configDeviceType": "Motion Sensor",
                        "ble": true
                    }
                ]
```

### Device & Model

RPi 4

### Node.js Version

16.17.1

### NPM Version

8.19.2

### Homebridge Version

1.5.0

### Homebridge SwitchBot Plugin Version

1.15.0 / 2.0.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
can you give v2.2.2 a try?
