### ISSUE TITLE
There is still a small problem with the status of the curtains in Homekit.

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/homebridge-switchbot#517]
There is still a small problem with the status of the curtains in Homekit.
When I press the slider in the HomeApp and open the curtain completely it does that.
However, the percentage display then slowly jumps from 20%, 60%, 80% only after it is completely open.
After about a minute, the status is then updated and displayed correctly.

_Originally posted by @Spy-1 in https://github.com/OpenWonderLabs/homebridge-switchbot/issues/508#issuecomment-1278492161_

**Comment by donavanbecker** [comment]
@Spy-1 are you using OpenAPI or BLE? or it doesn't matter?

**Comment by Spy-1** [comment]
i´m using OpenAPI

**Comment by donavanbecker** [comment]
@Spy-1 

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.1.1-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by Spy-1** [comment]
With V 2.1.1
Same behavior as before.
No change.

**Comment by donavanbecker** [comment]
@Spy-1 

Did you set the min and max close?

**Comment by Spy-1** [comment]
Yes set to 10 and 90.
However, the percentage display then stays on 20% and after about a minute, the status is then updated and displayed correctly.

**Comment by donavanbecker** [comment]
@Spy-1 How about updateRate? Try adjusting that and see if you can get it to display correctly when making changes.

It's hard, because it has to request a status refresh to get that state to make sure it is actually closed.

**Comment by Spy-1** [comment]
Different update rates between 0 and 15 seconds do not bring any changes.
In the home app, I sometimes have to press the slider 2-3 times to make the curtain move.
The curtain always opens and closes completely, but the percentage now stops at 20 and then goes to the open or closed status message after a minute.

Let's see how tonight the automations run.
![Zwischenablagebild](https://user-images.githubusercontent.com/44490104/195893450-61694732-80bf-4166-9cff-d6dce4216904.jpg)

**Comment by donavanbecker** [comment]
maybe it is the silent mode for the closing mode? can you try changing that to performance?

**Comment by Spy-1** [comment]
No, it is not. I have already tried that.

**Comment by LeClerc66** [comment]
Noob question from a rookie here: have 10 curtains (grouped in 5 sets of 2). Would love to tweak the settings as described above in this thread (the white-on-black config screen) but have no idea how to get there. Could anyone enlighten me?

**Comment by Spy-1** [comment]
It works for me!
V2.1.2

**Comment by donavanbecker** [comment]
v2.1.2 fixed it?

**Comment by Spy-1** [comment]
Yes, i did the update this morning. 
After first tests it‘s now fine for me. 
🥳

**Comment by donavanbecker** [comment]
Awesome!
