### ISSUE TITLE
Bug:  characteristic 'Brightness': characteristic value expected valid finite number and received "NaN"

### ISSUE THREAD

**Issue by yjeanrenaud** [OpenWonderLabs/homebridge-switchbot#518]
### Describe The Bug

homebridge log shows error

### To Reproduce

Just updated to v.2.0.1

### Expected behavior

no error

### Relevant log output

```shell
@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
```

### Config for homebridge-switchbot

```shell
{
  "name": "SwitchBot",
  "credentials": {
    "token": "xxx",
    "secret": "xxx",
    "notice": "Keep your token a secret!"
  },
  "options": {
    "irdevices": [
      {
        "deviceId": "xxx",
        "configRemoteType": "TV"
      }
    ],
    "refreshRate": 30,
    "pushRate": 1,
    "logging": "standard"
  },
  "platform": "SwitchBot"
}
```

### Device & Model

rPI 3 1 GB

### Node.js Version

v16.17.1

### NPM Version

8.15.0

### Homebridge Version

v1.5.0

### Homebridge Switchbot Plugin Version

v2.0.1

### Homebridge Config UI X Plugin Version

v4.50.1

### Operating System

Raspian Buster

**Comment by yjeanrenaud** [comment]
I just browsed the code quickly and I guess this is something that should be fixed on API level?

**Comment by donavanbecker** [comment]
@yjeanrenaud What deviceType?

**Comment by yjeanrenaud** [comment]
not sure. the log is quite generic. But I guess it comes from a curtain that is currently offline

**Comment by donavanbecker** [comment]
@yjeanrenaud You have no other devices? 

That characteristic isn't in a curtain, so pretty much impossible.

**Comment by yjeanrenaud** [comment]
I have 21 devices. but the curtains have a brightness sensor, don't they? I will look at the debug log if it helps to figure out which device

**Comment by yjeanrenaud** [comment]
ok I can't. "Requests reached the daily limit"

**Comment by donavanbecker** [comment]
> I have 21 devices. but the curtains have a brightness sensor, don't they? I will look at the debug log if it helps to figure out which device

Light sensor. The Brightness Characteristic is only used for lights.

**Comment by yjeanrenaud** [comment]
I see. Then it must be the striplight

**Comment by donavanbecker** [comment]
@yjeanrenaud 

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.2.0-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by yjeanrenaud** [comment]
sorry, wasn't that quick. beta did not help, v2.2.1, neither, I thought. I needed a restart of the whole homebridge.
even thought he update produced some build errors it works. And I checked nodejs and updated to v16.18.0.
