### ISSUE TITLE
Feature Request: Home Key Support for Switchbot Lock

### ISSUE THREAD

**Issue by weitheng** [OpenWonderLabs/homebridge-switchbot#536]
### Solution

Are there any plans for Switchbot lock to support Apple Home Key? So that it can be unlocked with just a tap of the phone?

**Comment by donavanbecker** [comment]
@weitheng Don't think this will be ever possible, but will leave this open just incase.

Not sure how we would be able to get the signal quick enough to make the door unlocked with OpenAPI, potentially with BLE, but not sure HomeKey supports that.

**Comment by weitheng** [comment]
> @weitheng Don't think this will be ever possible, but will leave this open just incase.
> 
> Not sure how we would be able to get the signal quick enough to make the door unlocked with OpenAPI, potentially with BLE, but not sure HomeKey supports that.

In this case, for this feature to be a reality is it safe to assume that Switchbot would have to implement this somehow in their backend instead?

**Comment by alvst** [comment]
I don't think this is possible to be implemented solely through HomeKit and Homebridge. I'm pretty sure the way it works is Apple and the maker of the device, register an NFC chip and thats how the phone knows this is a lock, not just a regular NFC tag. In theory, you could implement something similar right now by creating a personal automation in Shortcuts and an NFC tag on the outside of your door but thats as close as you can get unless Switchbot implements starts supporting HomeKit.
