### ISSUE TITLE
Support Request: Where to get Node.js 16.18?

### ISSUE THREAD

**Issue by HolgerAusB** [OpenWonderLabs/homebridge-switchbot#538]
### Describe Your Problem

SwitchBot-App gives a warning in log that my node.js is too old

### Relevant log output

```shell
Log:
The plugin "homebridge-switchbot" requires Node.js version of ^14.20.1 || ^16.18.0 || ^18.10.0 which does not satisfy the current Node.js version of v16.17.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

I installed Homebridge not via homebridge.io, so no hb-service. In deb.nodesorce.com/node_16.x the newest version is 16.17.1 and I din'd find a 16.18.x for Raspberry/Bullseye elsewhere. Or is that a bug?

So it ist just a warning. The plugin works for the moment.
```

### Screenshots

-

### Device & Model

Bot, Meter, MeterPlus, Contact

### Node.js Version

16.17.1

### NPM Version

8.15.0

### Homebridge Version

1.5.0

### Homebridge SwitchBot Plugin Version

2.1.2

### Homebridge Config UI X Plugin Version

4.50.1

### Operating System

Debian Bullseye on RaspberryPi 4

**Comment by donavanbecker** [comment]
Run the following command if you are using the image or if your running the hb-service.
`sudo hb-service update-node`

**Comment by HolgerAusB** [comment]
As I wrote. No hb-service here. I did not install Homebridge via `deb repo.homebridge.io`. This service was not available or recommended when I installed my homebridge.

nodejs 16.18.0 seems to be kinda beta or release candidate? It is not in the official nodesource repo yet. Latest version there is 16.17.1

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/196167241-b1f6000f-0134-4030-8437-43b2c27804ee.jpeg)

Does your system information say service mode like this?

Deb repo isn't the only thing with service mode.

**Comment by HolgerAusB** [comment]
What does service mode mean? It is a 'Yes' here.

Meanwhile the 16.18.0 has arrived in the official nodesource repo, so I could `apt upgrade` it. But you should consider not to push higher version dependencies too early.

**Comment by donavanbecker** [comment]
since you have service, just run this command:
```
sudo hb-service update-node
```

**Comment by HolgerAusB** [comment]
shame on me! I thought hb-service was available only when installed via repo.homebridge.io but you are right, it is there.

Thank you so much!
