### ISSUE TITLE
Bug: Bots stopped working after last update

### ISSUE THREAD

**Issue by PBXLthrMan** [OpenWonderLabs/homebridge-switchbot#539]
### Describe The Bug

Bots are no longer executing manually or in automations

### To Reproduce

Click switch, or try running a test automation

### Expected behavior

Bot executes

### Relevant log output

```shell
[17/10/2022, 14:04:54] [Homebridge UI] [@switchbot/homebridge-switchbot] Terminating child process...
[17/10/2022, 14:04:54] [Homebridge UI] [@switchbot/homebridge-switchbot] Child process ended

When I try to click on the switches manually in the Home App, I am no longer seeing any communications to Homebridge.

I did update them to BLE/Open API with the latest update and rebooted the server.
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "token": “XXX”,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": “XXX”,
                        "configDeviceType": "Bot",
                        "connectionType": "BLE/OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true
                        },
                        "logging": "standard"
                    },
                    {
                        "deviceId": "XXX",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE/OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true
                        },
                        "logging": "standard"
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

![IMG_324433D0B23D-1](https://user-images.githubusercontent.com/90646855/196251567-e7fe9e21-3561-41a7-9fe7-115058ab0015.jpeg)

### Device & Model

Switchbot Bot Firmware 4.9

### Node.js Version

v16.16.0

### NPM Version

v.8.11.0

### Homebridge Version

v.1.5.0

### Homebridge Switchbot Plugin Version

@switchbot/homebridge-switchbot v2.1.2

### Homebridge Config UI X Plugin Version

homebridge-config-ui-x v4.50.1 

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by donavanbecker** [comment]
do you have your secret inputted? I would guess there is a log that says you don't have a secret. you need to input that from the SwitchBot App.

**Comment by PBXLthrMan** [comment]
LOL. I guess I missed that, how do I get the secret?

**Comment by PBXLthrMan** [comment]
@donavanbecker Nevermind, figured it out. It's now working again. Thanks.
