### ISSUE TITLE
Bug: Not sure how to fix this error message

### ISSUE THREAD

**Issue by gregpa** [OpenWonderLabs/homebridge-switchbot#541]
### Describe The Bug

"SwitchBot ERROR"secret" config is not populated, you must populate then please restart Bridge."

### To Reproduce

error log

### Expected behavior

unsure

### Relevant log output

```shell
switchbot bridge stopping
10/18/2022, 8:04:12 AM Switchbot Bridge starting
10/18/2022, 8:04:40 AM Switchbot Bridge Loaded plugin '@switchbot/homebridge-switchbot'
10/18/2022, 8:04:40 AM Switchbot Bridge Loading 1 platforms...
10/18/2022, 8:04:40 AM Switchbot Bridge SwitchBot WARNING This plugin has been updated to use OpenAPI v1.1, config is set with openToken, "openToken" cconfig has been moved to the "token" config
10/18/2022, 8:04:40 AM Switchbot Bridge SwitchBot ERROR"secret" config is not populated, you must populate then please restart Bridge.
10/18/2022, 8:04:41 AM Switchbot Bridge Bridge is running on port 51856.
10/18/2022, 8:23:30 AM Switchbot Bridge Configuration change
10/18/2022, 8:23:30 AM switchbotbridge stopping
10/18/2022, 8:23:36 AM Switchbot Bridge starting
10/18/2022, 8:24:02 AM Switchbot Bridge Loaded plugin '@switchbot/homebridge-switchbot'
10/18/2022, 8:24:02 AM Switchbot Bridge Loading 1 platforms...
10/18/2022, 8:24:02 AM Switchbot Bridge SwitchBot WARNING This plugin has been updated to use OpenAPI v1.1, config is set with openToken, "openToken" cconfig has been moved to the "token" config
10/18/2022, 8:24:02 AM Switchbot Bridge SwitchBot ERROR"secret" config is not populated, you must populate then please restart Bridge.
10/18/2022, 8:24:03 AM Switchbot Bridge Bridge is running on port 51856.
```

### Config for homebridge-switchbot

```shell
not available at this time
```

### Device & Model

unknown

### Node.js Version

unknown

### NPM Version

unknown

### Homebridge Version

unknown

### Homebridge Switchbot Plugin Version

unknown

### Homebridge Config UI X Plugin Version

unknown

### Operating System

raspberry

**Comment by donavanbecker** [comment]
Can't tell what your config looks like since you didn't post it, but my guess is that you don't have the new Secret config set. You will have to get that from the SwitchBot app, same way you go the token, and paste in the config.

**Comment by gregpa** [comment]
Thanks for your help and effort on this . Truly. 
I see where to put the token, but not the Secret?  it wasn't very clear, sorry. I'm using the plugin within HOOBS
![Screenshot 2022-10-18 085513](https://user-images.githubusercontent.com/13455955/196450062-fdbcd358-a05d-4792-8cd3-4f982fb66cad.png)

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by gregpa** [comment]
![image](https://user-images.githubusercontent.com/13455955/196457911-2db21c02-2d45-4b04-a69b-ce6be410f9a5.png)
 Damn, it shows as certified,   that's too much work to switch as everything works fine right now except this. .. :)  thanks anyway

**Comment by donavanbecker** [comment]
@gregpa, HOOBs puts that on there, I have no control over that. 

It would be better to switch now then wait.
