### ISSUE TITLE
Bug: HOOBs not supported

### ISSUE THREAD

**Issue by ddanetidwell** [OpenWonderLabs/homebridge-switchbot#546]
### Describe The Bug

Plug-in doesn’t work in Hoobs

### To Reproduce

Install plug-in, enter token

### Expected behavior

SwitchBot items should show up in Home app

### Relevant log output

```shell
10/19/2022, 5:35:58 PMHomeConnectSwitchBotERROR"secret" config is not populated, you must populate then please restart Bridge.
```

### Config for homebridge-switchbot

```shell
The token and structure
```

### Device & Model

Na

### Node.js Version

16.18.0

### NPM Version

Current

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

2.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by tjridge** [comment]
I'm getting the same error on HOOBS.

**Comment by donavanbecker** [comment]
I can help if you post the config, but I would recommend switching to homebridge.

**Comment by bwp91** [comment]
the error would suggest you don’t have the “secret” config setting filled in the plugin settings

**Comment by donavanbecker** [comment]
yes, but issues is with HOOBs UI not displaying correct. Switching to Homebridge would help.

**Comment by tjridge** [comment]
Unfortunately, switching to homebridge isn’t an option for me.

**Comment by bwp91** [comment]
@tjridge 

trying to help here as i am more familiar with hoobs.

re my message above, if you are getting the same error, it means you haven’t filled in the “secret” config item?

**Comment by donavanbecker** [comment]
> Unfortunately, switching to homebridge isn’t an option for me. 

Why not?

**Comment by askovi** [comment]
Got pinged about this issue. It has now been fixed. Please update the plugin to the latest version. If you're still experiencing the issue after update, make sure to click Clear Cache from the hub settings in the top right menu.
