### ISSUE TITLE
Bug: Device not responding (only in home app)

### ISSUE THREAD

**Issue by tjridge** [OpenWonderLabs/homebridge-switchbot#548]
### Describe The Bug

smart plug no longer responding 

### To Reproduce

get error code mentioned below

### Expected behavior

toggle outlet on an off

### Relevant log output

```shell
could not be updated as Request failed with status code 400 at settle (file:///var/lib/hoobs/govee/node_modules/axios/lib/core/settle.js:19:12).
```

### Config for homebridge-switchbot

```shell
N/A
```

### Device & Model

N/A

### Node.js Version

16.18

### NPM Version

N/A

### Homebridge Version

1.5

### Homebridge Switchbot Plugin Version

1.15

### Operating System

HOOBS

**Comment by donavanbecker** [comment]
Same as #546
