### ISSUE TITLE
Bug: Can't Connect to MeterPlus (US) Over BLE

### ISSUE THREAD

**Issue by RemuxZaph** [OpenWonderLabs/homebridge-switchbot#550]
### Describe The Bug

Homebridge cannot connect to the MeterPlus

### To Reproduce

Enter the device's BLE ID number and device name. Reboot HB instance.

### Expected behavior

I'd expect no errors in the logs and for the device to appear in HK.

### Relevant log output

```shell
[10/20/2022, 1:12:13 PM] [SwitchBot] Total SwitchBot Devices Found: 1
[10/20/2022, 1:12:13 PM] [SwitchBot] Adding new accessory: SwitchMeter MeterPlus DeviceID: CFC849XXXXXX
[10/20/2022, 1:12:13 PM] [SwitchBot] MeterPlus: SwitchMeter Config: {"hide_humidity":true,"connectionType":"BLE"}
[10/20/2022, 1:12:13 PM] [SwitchBot] MeterPlus: SwitchMeter failed BLERefreshStatus with BLE Connection, Error Message: "ENODEV, No such device"
[10/20/2022, 1:12:13 PM] [SwitchBot] MeterPlus: SwitchMeter wasn't able to establish BLE Connection, node-switchbot: [object Object]
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "59b4ff9826a26502e39e84662b01f8e1b34689ccXXXXX",
                "secret": "23955238404a4f1fXXXXXXXXXXXX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "CFC849XXXXXX",
                        "configDeviceName": "SwitchMeter",
                        "configDeviceType": "MeterPlus",
                        "connectionType": "BLE",
                        "meter": {
                            "hide_humidity": true
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

MeterPlus (US)

### Node.js Version

v16.18.0

### NPM Version

v8.19.2

### Homebridge Version

v1.5

### Homebridge Switchbot Plugin Version

v2.2.1

### Homebridge Config UI X Plugin Version

v4.50.1

### Operating System

Docker (unRAID)

**Comment by RemuxZaph** [comment]
I ran "npm install @abandonware/noble" in the HomeBridge terminal, rebooted, and got the same output in the log.

**Comment by donavanbecker** [comment]
Installing that wouldn't help. Have you went through all perquisites for noble?

**Comment by RemuxZaph** [comment]
I looked through them...but couldn't get what to do next for my docker instance of Homebridge running on unRAID.

**Comment by donavanbecker** [comment]
yeah unfortunately with docker, not sure this will ever work.

**Comment by RemuxZaph** [comment]
Thanks @donavanbecker. I'll consider the hub to access via API then. Appreciate the communication. Please close this issue.
