### ISSUE TITLE
Support Request: SwitchBot auto toggle off

### ISSUE THREAD

**Issue by 350d** [OpenWonderLabs/homebridge-switchbot#552]
### Describe Your Problem

I've added SwitchBot via OpenAPI and it works in HomeKit as a switch, so I need to move it On or OFF to trigger SwitchBot to click on button. Is there any way to auto toggle to OFF position like Garage door works?

### Device & Model

SwitchBot

### Node.js Version

NA

### NPM Version

NA

### Homebridge Version

v1.5.0

### Homebridge SwitchBot Plugin Version

 v2.2.1

### Operating System

Raspberian

**Comment by donavanbecker** [comment]
@350d are you using press mode or switch mode for the Bot? Sounds like switch?

If you do press it should auto revert back to off.

**Comment by 350d** [comment]
I have it in Press mode for sureOn

**Comment by donavanbecker** [comment]
Please post your homebridge config and screenshot of SwitchBot app.

**Comment by 350d** [comment]
```{
            "name": "SwitchBot",
            "credentials": {
                "token": "mytoken",
                "secret": "mysecret",
                "notice": "Keep your Token & Secret a secret!"
            },
            "platform": "SwitchBot"
        }
```


![IMG_7740](https://user-images.githubusercontent.com/429208/197206643-cd4ab18f-c7db-427b-9551-4124b4487427.PNG)

**Comment by 350d** [comment]
<img width="458" alt="Screenshot 2022-10-21 at 16 27 16" src="https://user-images.githubusercontent.com/429208/197207229-e19599ca-3ca3-47f2-98b4-892bc7f472b9.png">

**Comment by donavanbecker** [comment]
You need to set your config in homebridge to be press mode. Take your device id from the device tab, go to SwitchBot device settings, input deviceID, select Bot for device type and then your mode as press

API doesn't tell me what mode your bot is in, so plugin just defaults to Switch.

**Comment by 350d** [comment]
Now it make sense! Thanks!
