### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by weber267** [OpenWonderLabs/homebridge-switchbot#557]
### Describe The Bug

Unable control the switch bot curtain 

### To Reproduce

n

### Expected behavior

n

### Relevant log output

```shell
10/21/2022, 6:02:04 PMSwitchbot BridgeLoaded plugin '@switchbot/homebridge-switchbot'
10/21/2022, 6:02:04 PMSwitchbot BridgeLoading 1 platforms...
10/21/2022, 6:02:04 PMSwitchbot BridgeBridge is running on port 11111.
10/21/2022, 6:02:04 PMSwitchbot BridgeSwitchBotERRORAPI Request: TypeError: Cannot read properties of undefined (reading 'length'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
    "accessories": [],
    "platforms": [
        {
            "platform": "SwitchBot",
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "token": "xxxxxxxxxxxxxx",
                "secret": "xxxxxxxxx"
            },
            "options": {
                "debug": "debug"
            }
        }
    ]
}
```

### Device & Model

n

### Node.js Version

n

### NPM Version

n

### Homebridge Version

n

### Homebridge Switchbot Plugin Version

newest 

### Homebridge Config UI X Plugin Version

Hoobs 4.2.8

### Operating System

Mac

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by donavanbecker** [comment]
Also I would need more logs to troubleshoot.

**Comment by weber267** [comment]
That is what I have

**Comment by donavanbecker** [comment]
then I would recommend switching to homebridge since I don't design this plugin for HOOBs and won't be able to support it. Last issue someone had with HOOBs was a HOOBs UI issue.

**Comment by donavanbecker** [comment]
Maybe try going to an older version?

Also please feel out issue more specific. `Newest` Or `n` doesn't give me a version number.
