### ISSUE TITLE
Bug: Daily Limit

### ISSUE THREAD

**Issue by AtTimesChris** [OpenWonderLabs/homebridge-switchbot#558]
### Describe The Bug

Unresponsive 

### To Reproduce

Restarting homebridge 

### Expected behavior

Response swiftly and correctly

### Relevant log output

```shell
API Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge 67B6",
        "username": "0E:09:15:6B:67:B6",
        "port": 51733,
        "pin": "144-95-508",
        "advertiser": "avahi"
    },
    "accessories": [
        {
            "name": "Automation-Dummy",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "DummySwitch2",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Govee",
            "username": "cosm------",
            "password": "Y@------",
            "apiKey": "9c8--------",
            "platform": "Govee"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "68-----------",
                "secret": "48--------",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 31,
                "logging": "standard"
            },
            "platform": "SwitchBot"
        }
    ]
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/9095643/197405232-73ec9eda-817c-4626-b4cf-c6d81a08f73f.png)

### Device & Model

Switchbot bot x2, Switchbot Curtains, Switchbot Light Strip, Switchbot Colour Bulb, Switchbot Motion Detector, Switchbot meter plus 

### Node.js Version

v16.18.0

### NPM Version

unaware how to see

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

2.2.2

### Operating System

Synology NAS

**Comment by donavanbecker** [comment]
Please post debug logs.

**Comment by donavanbecker** [comment]
see #559

**Comment by AtTimesChris** [comment]
I dont understand i didnt used to have any issues and haven't changed any settings to cause such, it was working last night but now same thing not responding.
I have been able to get debug logs
[homebridge.log](https://github.com/OpenWonderLabs/homebridge-switchbot/files/9853913/homebridge.log)

but I dont understand is refreshRate not meant to be how responsive it is so how long it takes from pressing the button on homekit to send the signal to switchbot like how responsive it would be from a button press? If I haven't sent any signal is it still adding to whatever my daily limit is, how do i increase the limit if at all possible? Can refresh rates be set for different devices cause some I don't need as fast, especially if affecting others negatively? Is there a way to remove things that are added to homekit but keep on switchbot because it adds in all but don't need and think that could also be contributing then.

**Comment by donavanbecker** [comment]
Refresh means pulling or getting or updating info on the device. 

The pushRate would be what you are talking about.

**Comment by AtTimesChris** [comment]
Right okay so if i increase my refresh rate while keeping my pushRate low that will fix this issue

**Comment by donavanbecker** [comment]
Yes. Also you can set you refreshRate per device, if you need one devices status to be updated sooner then others, Like a motion or contact sensor

**Comment by AtTimesChris** [comment]
Ohhh right that would make sense then ha, how would you go about doing that, is it within the hombridge plugin settings or on switchbot itself

**Comment by donavanbecker** [comment]
Homebridge plug-in settings
