### ISSUE TITLE
Bug: Cannot Read Properties of Undefined (reading 'deviceList')

### ISSUE THREAD

**Issue by SSutherland94** [OpenWonderLabs/homebridge-switchbot#560]
### Describe The Bug

SwitchBot Bots do not populate in Home App

### To Reproduce

Removed entire switchbot config.json code and recreated all through HomeBridge GUI

### Expected behavior

Expected SwitchBot Bots to appear in Home App

### Relevant log output

```shell
[24/10/2022, 11:27:52] [SwitchBot] API Request: TypeError: Cannot read properties of undefined (reading ‘deviceList’), Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
“name”: “SwitchBot”,
“credentials”: {
	“token”: “token”,
	“secret”: “secret”,
	“notice”: “Keep your Token & Secret a secret!”
},
“options”: {
	“devices”: [
		{
			“deviceId”: “MAC”,
			“configDeviceName”: “Open Blinds”,
			“configDeviceType”: “Bot”,
			“connectionType”: “BLE”,
			“scanDuration”: 5,
			“bot”: {
				“mode”: “press”,
				“deviceType”: “windowcovering”,
				“doublePress”: 1,
				“maxRetry”: 10
			},
			“logging”: “standard”
		},
		{
			“deviceId”: “MAC”,
			“configDeviceName”: “Close Blinds”,
			“configDeviceType”: “Bot”,
			“connectionType”: “BLE”,
			“scanDuration”: 5,
			“bot”: {
				“mode”: “press”,
				“deviceType”: “windowcovering”,
				“doublePress”: 1,
				“maxRetry”: 10
			},
			“logging”: “standard”
		},
		{
			“deviceId”: “MAC”,
			“configDeviceName”: “Server”,
			“configDeviceType”: “Bot”,
			“connectionType”: “BLE”,
			“scanDuration”: 5,
			“bot”: {
				“mode”: “press”,
				“deviceType”: “switch”,
				“doublePress”: 1,
				“maxRetry”: 10
			},
			“logging”: “standard”
		},
		{
			“deviceId”: “MAC”,
			“configDeviceName”: “Ripper”,
			“configDeviceType”: “Bot”,
			“connectionType”: “BLE”,
			“scanDuration”: 5,
			“bot”: {
				“mode”: “press”,
				“deviceType”: “switch”,
				“doublePress”: 1,
				“maxRetry”: 10
			},
			“logging”: “standard”
		}
	]
},
“platform”: “SwitchBot”
}
```

### Device & Model

SwitchBot Bot

### Node.js Version

16.18.0

### NPM Version

8.19.2

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

2.2.2

### Homebridge Config UI X Plugin Version

4.50.1

### Operating System

Raspbian Homebridge Image

**Comment by donavanbecker** [comment]
please turn on debug mode and get me more logs

**Comment by SSutherland94** [comment]
I turned on debug mode, and this was the only additional output:
`[24/10/2022, 13:06:50] [SwitchBot] [DEBUG] statusCode: 401
[24/10/2022, 13:06:50] [SwitchBot] [DEBUG] headers: {"date":"Mon, 24 Oct 2022 17:06:50 GMT","content-type":"application/json","content-length":"26","connection":"close","x-amzn-requestid":"8dae4dea-2a06-4062-9fe5-abb484509490","x-amzn-errortype":"UnauthorizedException","x-amz-apigw-id":"ahPmvGVJIAMFpJQ="}
[24/10/2022, 13:06:50] [SwitchBot] [DEBUG] d: {"message":"Unauthorized"}
[24/10/2022, 13:06:50] [SwitchBot] [DEBUG] devicesAPI: [Undefined]`

**Comment by donavanbecker** [comment]
Can you try regenerating your token and secret in the SwitchBot app?
![image](https://user-images.githubusercontent.com/9875439/197586530-51a26fa3-d387-495c-b25a-997eb8990181.jpeg)

**Comment by SSutherland94** [comment]
If I am still using BLE, as I do not have a SwitchBot hub, should I wait until I am within range of the SwitchBot units before trying to regenerate the token and secret?

**Comment by donavanbecker** [comment]
No just remove token and secret

**Comment by SSutherland94** [comment]
Looks like that fixed it! I could've sworn I re-entered all of that when it told me the "secret" was missing, but we seem okay now, thanks!!

**Comment by donavanbecker** [comment]
@SSutherland94 If your doing BLE only, OpenAPI credentials aren't needed.

Once you get the hub then I would input your secret and token. Then change connectionType to `BLE/OpenAPI` so you can use OpenAPI as a backup.
