### ISSUE TITLE
Bug: Was 'node-switchbot' found: false

### ISSUE THREAD

**Issue by nyjklein** [OpenWonderLabs/homebridge-switchbot#566]
### Describe The Bug

Upgraded to node.js V18.12.0. Now getting this error whenever curtain status is queried: Was 'node-switchbot' found: false

### To Reproduce

Upgrade to node.js 18:12.0

### Expected behavior

No error

### Relevant log output

```shell
[28/10/2022, 10:19:16] [SwitchBot] Curtain: Living Room Curtain Config: {"set_minStep":10,"set_min":5,"set_max":96,"setOpenMode":"0","setCloseMode":"0","connectionType":"BLE/OpenAPI","logging":"standard","refreshRate":120,"scanDuration":5}
[28/10/2022, 10:19:16] [SwitchBot] Was 'node-switchbot' found: false
[28/10/2022, 10:19:16] [SwitchBot] [DEBUG] Curtain uuid: DFC80D28CE14-Curtain, (290ba6f5-8474-4a54-8d14-ce396a2e4251)
[28/10/2022, 10:19:16] [SwitchBot] Curtain: Living Room Curtain wasn't able to establish BLE Connection, node-switchbot: false
[28/10/2022, 10:19:16] [SwitchBot] Curtain: Living Room Curtain Using OpenAPI Connection to Refresh Status
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge BFAB",
        "username": "0E:1C:BB:1A:BF:AB",
        "port": 51567,
        "pin": "xxx"
    },
   "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
         {
            "name": "SwitchBot",
            "credentials": {
                "token": "xxx,
                "secret": "xxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "DFC80D28CE14",
                        "configDeviceName": "Living Room Curtain",
                        "hide_device": false,
                        "configDeviceType": "Curtain",
                        "connectionType": "BLE/OpenAPI",
                        "scanDuration": 5,
                        "curtain": {
                            "set_minStep": 10,
                            "set_min": 5,
                            "set_max": 96,
                            "setOpenMode": "0",
                            "setCloseMode": "0"
                        },
                        "refreshRate": 120,
                        "logging": "standard"
                    },
                    {
                        "deviceId": "98F4AB2F20EE",
                        "configDeviceName": "Bedroom Humidifier",
                        "hide_device": false,
                        "configDeviceType": "Humidifier",
                        "connectionType": "OpenAPI",
                        "humidifier": {
                            "hide_temperature": true,
                            "set_minStep": 33
                        },
                        "logging": "standard"
                    }
                ],
                "refreshRate": 120,
                "logging": "standard"
            },
            "platform": "SwitchBot"
        },
        }
    ]
}
```

### Device & Model

Curtains

### Node.js Version

v18.12.0

### NPM Version

v8.19.2

### Homebridge Version

v1.5.1

### Homebridge Switchbot Plugin Version

v2.2.2

### Homebridge Config UI X Plugin Version

homebridge-config-ui-x v4.50.1

### Operating System

Raspbian GNU/Linux Buster

**Comment by donavanbecker** [comment]
revert back to node 16 till this is figured out.

**Comment by nyjklein** [comment]
For now, I just changed the curtains to OpenAPI only since everything else seems to be functioning fine.

**Comment by donavanbecker** [comment]
Try this:

Step 1:
```
cd /var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot
```
so that this folder is in focus. may want to send me a screenshot of your output on this. 

Step 2:
```
rm -rf node_modules
```

Step 3:
```
rm -rf package-lock.json
```

Step 4:
```
npm i
```

Step 5:
```
npm I @abandonware/bluetooth-hci-socket
```

**Comment by nyjklein** [comment]
I had trouble with your instructions.

Originally in the e-mail with instructions you wrote: **cd @switchbot/homebridge-switchbot**

I took this to mean: **/var/lib/homebridge/@switchbot/homebridge-switchbot**

But that directory didn't exist. There is this:  **/var/lib/homebridge/@switchbot/homebridge-switchbot-ble**


In your edited post above, you now have: **cd /var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot**

But there is no @switchbot directory in **node_modules**

So I'm confused.

**Comment by nyjklein** [comment]
I re-installed the plugin and the error went away. 

Noticed some errors during the install including this:

(##################) ⠏ reify:googleapis: http fetch GET 200 https://registry.npmjs.org/g
> @abandonware/bluetooth-hci-socket@0.5.3-8 install
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v108-linux-arm.tar.gz 

And I do get this when I try an action with the curtains from homebridge:
[29/10/2022, 10:28:57] [SwitchBot] Living Room Curtain Target Position: 100
[29/10/2022, 10:28:58] [SwitchBot] Curtain: Living Room Curtain failed BLEpushChanges with BLE/OpenAPI Connection, Error Message: "Failed to discover services and characteristics: DISCONNECTED"
[29/10/2022, 10:28:58] [SwitchBot] Curtain: Living Room Curtain Using OpenAPI Connection to Push Changes

**Comment by PaperMashe** [comment]
I am using a switchbot meter and had similar issues (same software versions but different accessory) , and after doing the above commands I am at the stage where humidity is fine but the temperature is -0.1° and the log says: 

[29/10/2022, 19:41:30] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "[object Object]" (object). See https://homebridge.io/w/JtMGR for more info.

**Comment by swsoyee** [comment]
@nyjklein I have the same issue, but I can solve it now. Please try the steps as follow:

1. Since you are using Raspbian, you may not find `@switchbot` in `/var/lib/homebridge/node_modules`, the path maybe 
    ```
    cd /usr/lib/node_modules/@switchbot/homebridge-switchbot
    ```
    (See: https://github.com/homebridge/homebridge/issues/1009#issuecomment-269628600)
2. `package-lock.json` maybe not exist in the directory, so just install all the dependecies and add `@abandonware/bluetooth-hci-socket` by
    ```
    sudo npm i
    sudo npm i @abandonware/bluetooth-hci-socket
    ``` 
3. Restart homebridge. And the bluetooth connection would be work fine.
    ```
    [11/6/2022, 10:14:16 AM] [SwitchBot] [DEBUG] Contact Sensor: Door Config BLE Address: --:--:--:--:--:--, BLE Address Found: --:--:--:--:--:--
    ```

----

Edit: I found that the bluetooth conncetion is not stable (and may not work fine), sometime it show the log `Contact Sensor: Door wasn't able to establish BLE Connection, node-switchbot: [object Object]` and back to the open API connect.

**Comment by niqbert89** [comment]
I have the same bug after upgrade to node 18.12.1
[SwitchBot] Was 'node-switchbot' found: false

What can I do? The above commands didn't work. I use a Raspberry for Homebridge.

**Comment by donavanbecker** [comment]
this is not a bug of the plugin but of `@abandonware/bluetooth-hci-socket`

**Comment by niqbert89** [comment]
Ok, thank you. So I should downgrade back to 16.x or wait for a update?

**Comment by nyjklein** [comment]
FWIW, I resolved this issue by deleting and then re-installing the plugin (don't forget to backup your configuration).

Jeff

**Comment by niqbert89** [comment]
> FWIW, I resolved this issue by deleting and then re-installing the plugin (don't forget to backup your configuration).
> 
> Jeff

For me it did not helped :(
