### ISSUE TITLE
Bug: switchbot fails to connect after restarting machine

### ISSUE THREAD

**Issue by alexandercaley** [OpenWonderLabs/homebridge-switchbot#567]
### Describe The Bug

Switchbot fails to connect every time I restart my machine

### To Reproduce

Homebridge installed on Mac mini running via node, restart machine and notice failure in logs, restart home bridge from UI to fix

### Expected behavior

Connection is properly established with switchbot

### Relevant log output

```shell
[10/28/2022, 2:11:08 PM] [SwitchBot] req: Error: Client network socket disconnected before secure TLS connection was established, Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "****************",
                "secret": "***************",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "************",
                        "configDeviceName": "Bedroom Light",
                        "hide_device": false,
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch",
                            "allowPush": true
                        },
                        "offline": false,
                        "logging": "standard"
                    }
                ]
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

switch

### Node.js Version

v16.17.0

### NPM Version

8.18.0

### Homebridge Version

v4.50.1

### Homebridge Switchbot Plugin Version

v2.2.2

### Homebridge Config UI X Plugin Version

homebridge-config-ui-x v4.50.1

### Operating System

macOS 12.6

**Comment by donavanbecker** [comment]
Haven't seen this before.

**Comment by produdegr** [comment]
Mine worked ok for two weeks. Then all of a suden after upgrading something (Homebridge to 1.5.1 or Node to latest version), switchbot devices in Homekit stopped working. After removing them re-creating the plugin and settings, no devices appear (either in BLE or API mode). Ended up tr-installing whole raspberry from scratch using Oznu 's Homebridge image. The result this plugin does not install at all and when forcing the installation it does not work.
So you are not alone. I already regret investing in Switchbots (2 + 2 Hubs).

I laso believe that Switchbot API, although enabled in the app, does not work for some reason. Figure out...
