### ISSUE TITLE
Bug: API Request: TypeError: Cannot read properties of undefined (reading 'map'),

### ISSUE THREAD

**Issue by MSDaytona** [OpenWonderLabs/homebridge-switchbot#569]
### Describe The Bug

API Request: TypeError: Cannot read properties of undefined (reading 'map'),

### To Reproduce

Upon each start of the plug-in

### Expected behavior

..

### Relevant log output

```shell
30/10/2022, 11:24:53Switchbot Bridge starting
30/10/2022, 11:25:04Switchbot BridgeLoaded plugin '@switchbot/homebridge-switchbot'
30/10/2022, 11:25:04Switchbot BridgeLoading 1 platforms...
30/10/2022, 11:25:04Switchbot BridgeBridge is running on port 51846.
30/10/2022, 11:25:05Switchbot BridgeSwitchBotERRORAPI Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
"platform": "SwitchBot",
    "name": "SwitchBot",
    "credentials": {
        "token": "*********************************",
        "secret": "********************************"
    },
    "options": {
        "devices": [
            {
                "deviceId": "C3E34613XXXX",
                "configDeviceName": "Curtain",
                "configDeviceType": "Curtain",
                "connectionType": "BLE/OpenAPI",
                "curtain": {
                    "setOpenMode": "0",
                    "setCloseMode": "0",
                    "hide_lightsensor": true
                },
                "contact": {
                    "hide_lightsensor": false
                },
                "scanDuration": 10,
                "bot": {
                    "mode": "press"
                }
            },
            {
                "deviceId": "AC67B2D2XXX",
                "configDeviceName": "Humidifier",
                "configDeviceType": "Humidifier",
                "connectionType": "BLE/OpenAPI",
                "bot": {
                    "allowPush": true
                },
                "meter": {
                    "hide_temperature": true,
                    "hide_humidity": false
                },
                "scanDuration": 10
            },
            {
                "deviceId": "E7F6AA2XXXX",
                "configDeviceName": "HubMini",
                "configDeviceType": "Plug Mini (US)",
                "connectionType": "BLE/OpenAPI",
                "scanDuration": 10
            }
        ],
        "pushRate": 5,
        "refreshRate": 31
    }
}
```

### Device & Model

Hoops

### Node.js Version

v16.18.0

### NPM Version

??

### Homebridge Version

v1.5.0

### Homebridge Switchbot Plugin Version

v2.2.2

### Homebridge Config UI X Plugin Version

v4.2.8

### Operating System

Hoobs

**Comment by donavanbecker** [comment]
Your refreshrate is at 31, my guess is that if you turn on debug mode you will find a log that say you hit your rate limit.

**Comment by MSDaytona** [comment]
> Your refreshrate is at 31, my guess is that if you turn on debug mode you will find a log that say you hit your rate limit.

Lowered it down to 5 and switched debug mode on: still the same

**Comment by donavanbecker** [comment]
Post your logs, lowering will make it worse.

Also, This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by MSDaytona** [comment]
> Post your logs, lowering will make it worse.
> 
> Also, This plugin isn't developed for HOOBs.
> 
> I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

I waited two days, doing nothing ( no change of config etc ) and now it works, even under Hoobs. Seems certain things have to settle down first.  BTW: The plugin is certified by Hoobs to work under Hoops !!

**Comment by donavanbecker** [comment]
I didn't certify it. That is HOOBs putting that on there with out my okay.
