### ISSUE TITLE
Bug: SwitchBot Meter not parsing Temperature

### ISSUE THREAD

**Issue by henrulin** [OpenWonderLabs/homebridge-switchbot#571]
### Describe The Bug

SwitchBot Meter not parsing Temperature but is able to parse Humidity

### To Reproduce

Add Meter config and enable

### Expected behavior

Be able to parse both Temperature and Humidity values. Be able to display values.

### Relevant log output

```shell
Switchbot BridgeSwitchBot[DEBUG] SwitchBot Meter BatteryLevel: 100, StatusLowBattery: 0
2/11/2022, 9:05:37 amSwitchbot BridgeSwitchBot[DEBUG] Meter: SwitchBot Meter Humidity: 65%
2/11/2022, 9:05:37 amSwitchbot BridgeSwitchBot[DEBUG] Meter: SwitchBot Meter Temperature: [object Object]°c
2/11/2022, 9:05:37 amSwitchbot BridgeSwitchBot[DEBUG] Meter: SwitchBot Meter updateCharacteristic CurrentRelativeHumidity: 65
2/11/2022, 9:05:37 amSwitchbot BridgeSwitchBot[DEBUG] Meter: SwitchBot Meter updateCharacteristic CurrentTemperature: [object Object]
2/11/2022, 9:05:37 amSwitchbot BridgeSwitchBot[DEBUG] Meter: SwitchBot Meter updateCharacteristic BatteryLevel: 100
2/11/2022, 9:05:37 amSwitchbot BridgeSwitchBot[DEBUG] Meter: SwitchBot Meter updateCharacteristic StatusLowBattery: 0
2/11/2022, 9:05:37 amSwitchbot BridgeERROR[Switchbot Bridge 7F57@Switch Meter 2F@@Current Temperature] characteristic value expected valid finite number and received "[object Object]" (object)
```

### Config for homebridge-switchbot

```shell
{
    "platform": "SwitchBot",
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!",
        "openToken": "<blah>",
        "token": "<blah>",
        "secret": "<blah>"
    },
    "options": {
        "devices": [
            {
                "configDeviceName": "SwitchBot Meter",
                "configDeviceType": "Meter",
                "connectionType": "BLE",
                "scanDuration": 300,
                "bot": {
                    "deviceType": "fan",
                    "allowPush": true
                },
                "deviceId": "<blah>",
                "lock": {
                    "hide_contactsensor": false
                },
                "external": false,
                "meter": {
                    "hide_temperature": false
                }
            }
        ],
        "logging": "standard"
    }
}
```

### Device & Model

SwitchBot Meter (Firmware v2.6)

### Node.js Version

16.17.0

### NPM Version

8.15.0

### Homebridge Version

1.5

### Homebridge Switchbot Plugin Version

2.2.2

### Operating System

Raspbian GNU/Linux 11 (bullseye)

**Comment by lukeskywlkr** [comment]
Hi everyone I have the same problem. It seems that the temperature field is an object that contains both Celsius and Fahrenheit values as you can see from this log extract:

```[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum serviceData: {"model":"T","modelName":"WoSensorTH","temperature":{"c":21.6,"f":70.9},"fahrenheit":false,"humidity":55,"battery":100}
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum model: T, modelName: WoSensorTH, temperature: 21.6, humidity: 55, battery: 100
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum connected: true
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum BLEparseStatus
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Temp&Hum BatteryLevel: 100, StatusLowBattery: 0
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum Humidity: 55%
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum Temperature: [object Object]°c
[11/11/2022, 18:42:39] [SwitchBot] [DEBUG] Meter: Temp&Hum updateCharacteristic CurrentRelativeHumidity: 55
[11/11/2022, 18:42:39] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "[object Object]" (object). See https://homebridge.io/w/JtMGR for more info.

**Comment by nowheremanx** [comment]
I am facing the same issue, please fix it

**Comment by lukeskywlkr** [comment]
I think that I have found the culprit: on line 215 of [meter.ts](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/latest/src/device/meter.ts#L215) when parsing data from BLE connection the `this.CurrentTemperature` variable is being updated with the whole `this.temperature` object that contains both Celsius and Fahrenheit values. The content of `CurrentTemperature` is then passed to HomeKit characteristics with function `updateHomeKitCharacteristics()`. This triggers the error because HomeKit expects a finite number and not an object.

**Comment by PaperMashe** [comment]
same issue

**Comment by ChainsLunatic** [comment]
Same for MeterPlus

**Comment by giuliomagnifico** [comment]
Just fixed it by using an [old commit from 12 October](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/20811cf3df2cfc11dbe8aac1f1059c5caedff29c/src/device/meterplus.ts).

I replaced the `meterplus.ts` file and recompiled the plugin. Now it works again also the temperature, and yes as @lukeskywlkr pointed, it's something with the Current Temperature

```
    // Current Temperature
    if (!this.device.meter?.hide_temperature) {
      this.temperature < 0 ? 0 : this.temperature > 100 ? 100 : this.temperature;
      this.CurrentTemperature = this.temperature;
      this.debugLog(`${this.device.deviceType}: ${this.accessory.displayName} Temperature: ${this.CurrentTemperature}°c`);
    }
  }

...

    // Current Temperature
    if (!this.device.meter?.hide_temperature) {
      this.CurrentTemperature = this.Temperature!;
      this.debugLog(`${this.device.deviceType}: ${this.accessory.displayName} Temperature: ${this.CurrentTemperature}°c`);
    }
  }

```

I haven't digged into the issue but there's something with Celsius, the updated file has this inside:

```
// Current Temperature
    if (!this.device.meter?.hide_temperature) {
      this.celsius < 0 ? 0 : this.celsius > 100 ? 100 : this.temperature;
      this.CurrentTemperature = this.temperature;
      this.debugLog(`${this.device.deviceType}: ${this.accessory.displayName} Temperature: ${this.CurrentTemperature}°c`);
    }
  }

...

    // Current Temperature
    if (!this.device.meter?.hide_temperature) {
      this.CurrentTemperature = this.Temperature!;
      this.debugLog(`${this.device.deviceType}: ${this.accessory.displayName} Temperature: ${this.CurrentTemperature}°c`);
    }
  }
```

But I don't know if someone who is using Fahrenheit has other issue, I can't try. So I just edited and recompiled it.

**Comment by donavanbecker** [comment]
@giuliomagnifico Open a PR, and I can merge it into beta.

**Comment by giuliomagnifico** [comment]
@donavanbecker done, hope it's correct: https://github.com/OpenWonderLabs/homebridge-switchbot/pull/598 (edit: I've made the PR already on the beta)

**Comment by donavanbecker** [comment]
> @donavanbecker done, hope it's correct: https://github.com/OpenWonderLabs/homebridge-switchbot/pull/598 (edit: I've made the PR already on the beta)

Thanks! I have merged it. Should Build a new beta.

**Comment by donavanbecker** [comment]
Looks like the build errored. I will have to look into it.

**Comment by giuliomagnifico** [comment]
> Looks like the build errored. I will have to look into it.

Uh, weird, maybe on the beta branch there are other changes?

I’ve compiled it on the latest not beta (v2.2.2 IIRC), try in locale to change only the file _meterplus.ts_ and build the SwitchBot plug-in-. For me it’s working well (finally). 

But now I’m out home and I can’t test with the beta.

**Comment by donavanbecker** [comment]
@giuliomagnifico Not sure how it would build for you as you used temperate which can't be a number and an object.

I have fixed that and now push it to the latest beta.

**Comment by giuliomagnifico** [comment]
@donavanbecker Assuming that I know nothing about node, I simply entered into my local SwitchBot folder, changed those lines of code and ran `npm run build`.

Anyway thanks for fixing it!

**Comment by nowheremanx** [comment]
> @giuliomagnifico Not sure how it would build for you as you used temperate which can't be a number and an object.
> 
> I have fixed that and now push it to the latest beta.

Hi, may I know when will you release the fix? It is super weird to read 0°C everyday

**Comment by donavanbecker** [comment]
> > @giuliomagnifico Not sure how it would build for you as you used temperate which can't be a number and an object.
> 
> > 
> 
> > I have fixed that and now push it to the latest beta.
> 
> 
> 
> Hi, may I know when will you release the fix? It is super weird to read 0°C everyday 

@nowheremanx Does the latest beta work for you?

**Comment by nowheremanx** [comment]
> > > @giuliomagnifico Not sure how it would build for you as you used temperate which can't be a number and an object.
> > 
> > 
> > > 
> > 
> > 
> > > I have fixed that and now push it to the latest beta.
> > 
> > 
> > Hi, may I know when will you release the fix? It is super weird to read 0°C everyday
> 
> @nowheremanx Does the latest beta work for you?

Please let me know how to install the beta in homebridge, I can test it out for you.

**Comment by donavanbecker** [comment]
Click install alternative version and select latest beta

**Comment by nowheremanx** [comment]
> 

It works for me, thank you very much!

**Comment by donavanbecker** [comment]
If I get time this week, I will try to finish what's in this release and push out a release.

**Comment by donavanbecker** [comment]
v2.3.0 released.

**Comment by henrulin** [comment]
Yay thanks!
