### ISSUE TITLE
Feature Request: Two actions are possible by Switch Bot 

### ISSUE THREAD

**Issue by Kohle81** [OpenWonderLabs/homebridge-switchbot#572]
### Problem

In beta version of Switchbot there are 2 actions for one Bot

### Solution

can you implement this option?

**Comment by Kohle81** [comment]
![052AF14D-840F-4768-A4CD-95909503BC69](https://user-images.githubusercontent.com/33038709/199440039-883048fa-37b5-4f45-88e6-a7e16233d7da.png)

**Comment by Kohle81** [comment]
Any possibility?

**Comment by alvst** [comment]
While not exactly what you are requesting, the beta (v2.4.0) allows you to do this by allowing you to send non-predefined amounts of push requests to your device. I will think about this, but there is another feature/way I'm thinking about that would accomplish this.
