### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by grandevice** [OpenWonderLabs/homebridge-switchbot#573]
### Describe Your Problem

It seems that ceiling light pro is supported, but there is no setting in config.schema.json, so could you update it?  I am always grateful for your help.

### Screenshots

![4FE73F91-5D0A-423D-A3B3-4272978D3E8D](https://user-images.githubusercontent.com/76737843/199654748-0cba56a9-bfbc-43d8-899c-bb162211c7ab.png)

### Device & Model

ceiling light pro

### Node.js Version

v16.18.0

### NPM Version

v8.19.2

### Homebridge Version

v1.5.1

### Homebridge SwitchBot Plugin Version

v2.2.2

### Homebridge Config UI X Plugin Version

v4.50.1

### Operating System

pi is 64bit

**Comment by donavanbecker** [comment]
This is added in the latest beta
