### ISSUE TITLE
Plugin doesn’t add any devices any more

### ISSUE THREAD

**Issue by WaldperlachFabi** [OpenWonderLabs/homebridge-switchbot#577]
### Describe Your Problem

Since I updated my Homebridge, the SwitchBot devices got removed from the home app and I am not able to re-add them.

### Relevant log output

```shell
Can be fund at the images.
```

### Screenshots

![DE2E1853-D035-41ED-A943-0E74C8C5AC83](https://user-images.githubusercontent.com/80318133/200491169-ba2cecc7-23a7-48f0-aa77-6f772e058ded.png)
![0CA89B05-4586-4785-8C47-B1E73BCC3FD6](https://user-images.githubusercontent.com/80318133/200491187-4f1b32be-f6e1-46b0-810b-b71ae9a8f07a.png)

### Device & Model

Curtain, Meter, Strip Light, Motion

### Node.js Version

16.18.0

### NPM Version

8.19.2

### Homebridge Version

1.5.1

### Homebridge SwitchBot Plugin Version

2.3.0-beta-2

### Homebridge Config UI X Plugin Version

4.50.1

### Operating System

Docker

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.3.0-beta.8/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)
