### ISSUE TITLE
Bug: The devices config section is missing the *Device ID* in the config. Please check your config.

### ISSUE THREAD

**Issue by tzwada** [OpenWonderLabs/homebridge-switchbot#582]
### Describe The Bug

Device ID is in my config but the log says missing

### To Reproduce

every time when Homebridge starts

### Expected behavior

The error log should not be displayed.

### Relevant log output

```shell
Every time I start the Homebridge, the log says like this:
[13/11/2022, 14:42:01] [SwitchBot] The devices config section is missing the *Device ID* in the config. Please check your config.
[13/11/2022, 14:42:01] [SwitchBot] The devices config section is missing the *Device Type* in the config. Please check your config.

However, my config surely has the Device ID and Device Type.

My environment:
Homebridge v1.5.1
Homebridge UI v4.50.2
Homebridge SwitchBot v2.2.2
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": omitted,
                "secret": omitted,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "************", #omitted (ex. D5D2088A9A7D)
                        "configDeviceName": "Bot 7E",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "garagedoor",
                            "allowPush": true,
                            "doublePress": 2
                        },
                        "logging": "standard"
                    }
                ],
                "irdevices": [
                    {
                        "logging": "standard"
                    }
                ],
                "logging": "standard"
            },
            "_bridge": {
                "username": "**:**:**:**:**:**",
                "port": 49974
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

![スクリーンショット 2022-11-13 14 53 18](https://user-images.githubusercontent.com/7919609/201507987-ef961134-6486-4d17-a71d-57a683052457.png)

### Device & Model

homebridge-switchbot v2.2.2

### Node.js Version

v18.12.1

### NPM Version

v9.1.1

### Homebridge Version

v1.5.1

### Homebridge Switchbot Plugin Version

v2.2.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Look at your Config, for some reason you have a config in the `irdevices` section.

**Comment by tzwada** [comment]
Thanks Donovan. I trashed Switchbot config in my homebridge UI. Then recreate it by going to config screen. Then reboot the homebridge. Now the error disappeared. I'll close this issue. 

Now I have different issue (Switchbot doesn't show up in accessories in homebridge UI) but this is different issue, then.
