### ISSUE TITLE
Bug: No update to curtain status

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot#583]
### Describe The Bug

Curtain status stuck at Open all the time. 

### To Reproduce

When you set a curtain close at a percentage (1~100%), the curtain does move correctly. But the home app status changes back to 100% open right after.

### Expected behavior

Can not open the curtains by home app. Because it stuck at Open status all the them.

### Relevant log output

```shell
[2022-11-13, 4:47:13 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room openAPIRefreshStatus
[2022-11-13, 4:47:13 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room sign: slyMj9ivaO6sAQBaqw5/ByKV5RhyWlWJ4v2dg6oXmyg=
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room statusCode: 200
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room d: {"statusCode":100,"body":{"deviceId":"F479D00DB650","deviceType":"Curtain","hubDeviceId":"FEAF3FEDE63C","calibrate":true,"group":false,"moving":false,"slidePosition":0},"message":"success"}
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room refreshStatus: {"statusCode":100,"body":{"deviceId":"F479D00DB650","deviceType":"Curtain","hubDeviceId":"FEAF3FEDE63C","calibrate":true,"group":false,"moving":false,"slidePosition":0},"message":"success"}
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room openAPIparseStatus
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain Living Room CurrentPosition: 100
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room Standby, CurrentPosition: 100
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room Stopped
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room CurrentPosition: 100, TargetPosition: 100, PositionState: 2,
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room CurrentAmbientLightLevel: 6001
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room updateCharacteristic CurrentPosition: 100
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room updateCharacteristic PositionState: 2
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room updateCharacteristic TargetPosition: 100
[2022-11-13, 4:47:14 p.m.] [SwitchBot] [DEBUG] Curtain: Living Room updateCharacteristic CurrentAmbientLightLevel: 6001
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxx",
                "secret": "xxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "logging": "debug"
            },
            "_bridge": {
                "username": "0E:66:1E:83:C5:66",
                "port": 59580
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

Recently updated SwitchBot hub mini firmware version to V5.2-3.3

### Device & Model

SwithBot curtain

### Node.js Version

v16.18.0

### NPM Version

v8.19.2

### Homebridge Version

v1.5.1

### Homebridge Switchbot Plugin Version

v2.2.2, and v2.3.0-beta.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by jonpeng** [comment]
Also the SwitchBot light level sensor always return at 6001 lux

**Comment by martijnverheij** [comment]
I have the same issue, I can close my curtains but not open them.
In home app the curtains are open.

**Comment by jonpeng** [comment]
Just noticed that SwitchBot app cannot connect to the curtains over cloud. It can be used over Bluretooth while at home. I am thinking this should be related to the hub firmware update.

**Comment by AKWillows** [comment]
Hi. I’m experiencing the same since updating my Switchbot Hub Mini to firmware V5.2-3.3. Curtains constantly show as Open in the app. It’s not possible to open the curtains using Home app or Siri (I assume because Home thinks they are already open)

**Comment by ThatGirl0903** [comment]
> Just noticed that SwitchBot app cannot connect to the curtains over cloud. It can be used over Bluretooth while at home. I am thinking this should be related to the hub firmware update.

Wanted to chime in that I am having the same issue as this and the comment from AKWillows.

**Comment by jonpeng** [comment]
I contacted SwitchBot, and they just solved this issue on the server end. Now my Home app status can be updated properly. As you know it's 3:00 am local time in China. SwitchBot really care about their customers. I am not sure if the server end fix will apply to all users or not. If not please don't hesitate to contact them.

**Comment by AKWillows** [comment]
@jonpeng  Hi… after reading this, i checked my setup and it wasn’t fixed - even after rebooting the bridge.  So, it appears it was only fixed for you - unless I’m missing something? I emailed their support but I’ve been asked to complete feedback via the app so that they can “investigate’. Are you able to share the detail of who you contacted and what you actually asked please? Thank you!

**Comment by martijnverheij** [comment]
For me the is this also not solved.

**Comment by jonpeng** [comment]
@AKWillows I was using the SwitchBot app->Profile->Feedback...

**Comment by jonpeng** [comment]
@AKWillows @Minsheng @SwitchBot With this firmware update issue, SwichBot app home page should not show the correct curtain status via cloud/Internet.

**Comment by AKWillows** [comment]
@jonpeng My Switchbot app is showing the correct status of the curtains and also showing that they are connected via cloud. The Apple Home app is still showing them permanently open. 

Although I initially used the Support form at the @SwitchBot @SwitchBot-Wonderlabs website, the request is showing as a ticket in the Feedback section of the app. The latest response is “we will forward your problem to our tech team for further assistance. “ at about 9.30 this morning (UK time). I included a link to this thread.

**Comment by jonpeng** [comment]
@AKWillows You can't trust the little cloud icon on the SwitchBot app, and determine the connection is over internet. To do the test correctly, you need to away from SwitchBot hub and other SwitchBot products. And only the home page of SwitchBot app doesn't update the status. Once you click into the individual curtain, the status shows correct.

**Comment by AKWillows** [comment]
@jonpeng Yes… it shows the cloud in the app when I’m away from home. I’ve had no issues with the Switchbot app…. Just Apple Home app via this homebridge plugin. I thought that was what Switchbot were able to fix for you?

**Comment by jonpeng** [comment]
@AKWillows Then mine was different. The following screen shots was my issues before they did the server end fix.
![image](https://user-images.githubusercontent.com/48269361/202535733-56ce8788-00ba-487b-b4ae-7c51aef7fe95.png)
![image](https://user-images.githubusercontent.com/48269361/202535833-84d1a0cd-9635-424a-aa00-5c4e35eb2532.png)

**Comment by AKWillows** [comment]
@jonpeng …oh, but this thread is about the switchbot plugin for homebridge … and that was what your initial post shows the log for. And you refer to the Home app and the log and config screenshots are for the Homebridge plugin. So it would appear that the action switchbot took has fixed the SWITCHBOT app for you. the homebridge issue is NOT fixed then?

**Comment by jonpeng** [comment]
@AKWillows I noticed the Home app status issue first. So I posted this thread here. I thought it was the plugin issue. Later on, I noticed the SwichBot app has this status issue as well when I away home. I was thinking that should be the same issue from the recent hub firmware update. So I contacted SwitchBot support. After they fixed the SwitchBot app issue, Home app backed to normal.

**Comment by AKWillows** [comment]
@jonpeng ah ok. I’ll open a new ticket here tomorrow for my problem then as this one is closed now and,unless Switchbot come back to me with anything I don’t think it will get resolved
