### ISSUE TITLE
Bug: SwitchBot doesn't show up on Homebridge Accessories

### ISSUE THREAD

**Issue by tzwada** [OpenWonderLabs/homebridge-switchbot#585]
### Describe The Bug

SwitchBot doesn't show up on Homebridge Accessories screen

### To Reproduce

Always (if Connection Type is "BLE")

### Expected behavior

SwitchBot accessory should appear in Homebridge UI Accessories screen

### Relevant log output

```shell
I have one SwitchBot Bot. I have trashed SwitchBot config via Homebridge UI. Then re-configured the Homebridge SwitchBot. Homebridge log seems OK, no error. However, SwitchBot never be appeared in Accessories screen in the Homebridge UI.

I tried several settings. If the Connection Type is "BLE/Open API", then the SwitchBot appears on the Accessories. But it is not good for me. Since I don't have SwitchBot Hub, Homebridge generates an error of "no SwitchBot Cloud Service" under this setting.
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "secret", #deleted 
        "secret": "secret", #deleted
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "secret", #deleted
                "configDeviceType": "Bot",
                "connectionType": "BLE",
                "bot": {
                    "mode": "switch",
                    "deviceType": "garagedoor",
                    "allowPush": true
                },
                "external": true,
                "logging": "debug"
            }
        ]
    },
    "_bridge": {
        "username": "secret", #deleted
        "port": secret #deleted
    },
    "platform": "SwitchBot"
}
```

### Screenshots

![Notification_Center](https://user-images.githubusercontent.com/7919609/201612852-0719861c-9946-4447-a816-8a864148d031.png)

### Device & Model

SwitchBot Bot

### Node.js Version

v18.12.1

### NPM Version

v9.1.1

### Homebridge Version

v1.5.1

### Homebridge Switchbot Plugin Version

v2.2.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
I don't believe external accessories will not show in Homebridge UI.

**Comment by tzwada** [comment]
@donavanbecker It is true. As I wrote, SwitchBot never be displayed if Connection Type is "BLE". It will if the Connection Type is "BLE/Open API".
