### ISSUE TITLE
Bots unresponsive in the Home app

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#589]
### Describe The Bug

Starting this morning, my bots have become unresponsive in the Home app. They work just fine from the SwitchBot app, but nothing happens from the Home app. One curtain is currently stuck on an "opening" loop.

### To Reproduce

Sending commands through the Home app to see if the bots are unresponsive on your end as well

### Expected behavior

Bots should be working fine when commands are given from the Home app

### Relevant log output

```shell
N/A, nothing appears in the logs
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!",
        "token": "ac15160423b5d05962d442ecbb160714a3ea9cc10807965c5f054602e24856f3dfe65614067992d58f65718216b70d45"
    },
    "options": {
        "devices": [
            {
                "deviceId": "d7f207aae11e",
                "configDeviceName": "Lights",
                "configDeviceType": "Bot",
                "bot": {
                    "mode": "press",
                    "deviceType": "switch",
                    "doublePress": 0
                }
            },
            {
                "deviceId": "F1666f7d31c3",
                "configDeviceName": "Front Door",
                "configDeviceType": "Bot",
                "bot": {
                    "mode": "press",
                    "deviceType": "door",
                    "doublePress": 0
                }
            },
            {
                "deviceId": "CD0D21CC6099",
                "configDeviceName": "Bedroom Curtain",
                "configDeviceType": "Curtain",
                "curtain": {
                    "hide_lightsensor": true
                }
            },
            {
                "deviceId": "FBFA012797C2",
                "configDeviceName": "Kitchen Curtain",
                "configDeviceType": "Curtain",
                "curtain": {
                    "hide_lightsensor": true
                }
            },
            {
                "deviceId": "ED4C4E67DA99",
                "configDeviceName": "Living Room Curtain",
                "configDeviceType": "Curtain",
                "curtain": {
                    "hide_lightsensor": true
                }
            }
        ]
    },
    "platform": "SwitchBot"
}
```

### Screenshots

The exact same issue happened yesterday with the Govee plugin. My Govee lights could not be controlled through the Home app, but they could through the Govee app. Turned out it was an issue with the Govee API on Govee's end. Could it be the same with SwitchBot?

### Device & Model

SwitchBot Bot and Curtain

### Node.js Version

18.12.1

### NPM Version

N/A

### Homebridge Version

1.5.1

### Homebridge Switchbot Plugin Version

2.2.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Logs?

**Comment by FranciRoosters** [comment]
As I mentioned in the ticket submitted, the logs don’t show anything. Whatever I do in the Home app doesn’t not get registered in the logs.

**Comment by donavanbecker** [comment]
@FranciRoosters If you turn on debug logs I would guess that you would get some kind of log.

**Comment by FranciRoosters** [comment]
I’m sorry, but I have no idea how to do this.

**Comment by donavanbecker** [comment]
> I’m sorry, but I have no idea how to do this.

There is a config option in the plugin settings, you will the have to restart you child bridge if you have one of Homebridge.

**Comment by FranciRoosters** [comment]
Nothing shows, either with Debug logging turned on under advanced settings or any of the device settings.

**Comment by FranciRoosters** [comment]
I’ve noticed there’s a new Secret field under SwitchBot account info and it’s blank. I’ve never seen it before. What is it?

**Comment by donavanbecker** [comment]
v2.0.0 release.

**Comment by FranciRoosters** [comment]
Could be this the reason why?

**Comment by donavanbecker** [comment]
> Could be this the reason why?

Definitely, since this was introduced in v2.0.0

**Comment by FranciRoosters** [comment]
Ok, what is the secret and how do I retrieve it?

**Comment by donavanbecker** [comment]
SwitchBot app.

Check the v2.0.0 release notes.
