### ISSUE TITLE
Bug: Curtains show as “Open” in HomeKit regardless of their current state

### ISSUE THREAD

**Issue by AKWillows** [OpenWonderLabs/homebridge-switchbot#590]
### Describe The Bug

This sounds similar to a previously closed Bug. However, the OP of that one had a different experience to me in the Switchbot app. For me, the current state of the curtains shows correctly in the Switchbot app but never updates from Open in Homebridge/Home app. This occurred after updating the Hub Mini firmware to version 5.2-3.3. Everything was working fine before that. 

### To Reproduce

Close curtains in the Home app via Homebridge - the icon in Home app will quickly return to Open even though the curtains have closed. 

### Expected behavior

Curtain will update to show it’s actual state. 

### Relevant log output

```shell
The log shows that it is checking status after a command is sent - screenshot below
```

### Config for homebridge-switchbot

```shell
Apologies, this is pasted on an iPad using OCR from a screenshot so there could be some errors

"accessories":
"platforms": [
"platform": "SwitchBot"
"name": "SwitchBot"
"credentials": {
"notice":
"Keep your token a secret!"
"openToken",
"Xxxxxx"
"token":
"xxxxxxx",
"secret":""
3,
"options": {
"devices":
"deviceId": "D0D7500854A2"
"configDeviceName":
"configDeviceType":
"Dining Room Curtain",
"Curtain"
"curtain": {
"set_minStep"
20,
"set_min"
5,
"set _max": 95,
"refreshRate": 10,
"hide_lightsensor":
true
"deviceId": "D11F47E52332"
"configDeviceName":
"Guest Curtain",
"configDeviceType":
"Curtain"
"curtain": {
"set_minStep":
20,
"set_min":
5,
"set_max": 95,
"refreshRate": 10,
"hide_lightsensor": true
"deviceId": "E9EE7EODODOA"
"configDeviceName":
"configDeviceType":
"Bedroom Curtain",
"Curtain"
"curtain": K
"set_minStep": 20,
"set_min"
5,
"set_max": 95,
"refreshRate": 10,
"hide_lightsensor": true
"deviceId": "FF019AB9AA64",
"configDeviceName": "Lounge Curtain",
"configDeviceType":
"Curtain"
"curtain": {
"set minStep":
29.
```

### Screenshots

![IMG_1817](https://user-images.githubusercontent.com/31076973/202653482-5c29ac56-f9ac-4867-81f3-d0f1cf3d06ed.jpeg)

### Device & Model

Xx

### Node.js Version

16.18.1

### NPM Version

Xx

### Homebridge Version

1.5.0

### Homebridge Switchbot Plugin Version

2.2.2

### Homebridge Config UI X Plugin Version

HOOBS

### Operating System

Raspbian/HOOBS

**Comment by donavanbecker** [comment]
Closing till logs are provided that show that the curtains show as closed from the API and the Home app shows different.

If logs show closed and Home app shows closed then it is an API issue just like the other issues.

**Comment by AKWillows** [comment]
@donavanbecker Thanks for the reply. I understand what you mean. I have turned on the debug log for this plug-in and can see that the API appears to be passing back the incorrect value. I will raise a support ticket with Switchbot.

**Comment by donavanbecker** [comment]
@AKWillows Thanks

**Comment by Dominashaun** [comment]
@AKWillows please let us know if you hear back from SwitchBot or if you find any potential fix/work around. I’m experiencing the same issue, as is @tony-brookes. All of our problems seem to be stemming from the recent firmware update pushed by SwitchBot. I’ve reached out to SwitchBot and they say they’ve forwarded the issue to their tech department.

**Comment by AKWillows** [comment]
@Dominashaun I will. I received the same message from Switchbot…

**Comment by AKWillows** [comment]
@Dominashaun I have just received an update from @SwitchBot. They said "According to the reply from our developers, we have analysed and debugged the system. Please try it again and check the state synchronization.". Unfortunately is hasn't fixed the issue. I turned on debug logging in the Homebridge Switchbot config and I can see that the close command is sent, but even though the curtain has closed, the API is sending back that the curtain position is "43", which means it is still showing as 43% open which is the same as it was before. I have tried with other curtains too and they all show as fully open in the Home app, even though they are closed.

I've responded to them again and sent the home bridge log.. we'll see what they say next!

@donavanbecker Just tagging you as you may be interested.

**Comment by donavanbecker** [comment]
thanks @AKWillows

**Comment by jonpeng** [comment]
@AKWillows Just a reference, my SwitchBot ticket ID was 230759, which they used to fixed my issues.

**Comment by AKWillows** [comment]
Thanks @jonpeng

**Comment by Dominashaun** [comment]
Thanks for the update @AKWillows

**Comment by Dominashaun** [comment]
@AKWillows  I received a message from SwitchBot simply stating that "their tech department has checked the issue and they suggest trying again after one hour." They didn't offer any further explanation or require anything else from me, but sure enough, the curtains are now displaying the correct open/close status in the Home app and are operating exactly as expected. They did say that if the problem still exists, I should send a relevant screen recording showing the issue and they would send further assistance accordingly, but fortunately that wasn't needed. I wish I could offer you an actual solution, but whatever they did on the back end completely resolved my issue. Here's to hoping yours will be resolved soon as well!

**Comment by AKWillows** [comment]
Hi @Dominashaun could you let me have your ticket number please? Just so I can say “whatever you did for him, please do for me!”

**Comment by Dominashaun** [comment]
@AKWillows Of course. Ticket ID: 233878

**Comment by AKWillows** [comment]
Hi all. Just had a response from Switchbot… apparently the mini hub needs a further firmware update and there is no confirmed timeline for that. I did refer to both of your cases above (thanks for sharing)… but it would appear that isn’t the issue I am facing!
