### ISSUE TITLE
Support Request: Bot switch status not updating in home app when changed in switchbot app

### ISSUE THREAD

**Issue by mhunt407** [OpenWonderLabs/homebridge-switchbot#597]
### Describe Your Problem

When switching a bot to on/off in the switchbot app, it doesn't update the status in the home app on iphone. but if I update in home, it updates in switchbot app.

### Relevant log output

```shell
"devices": [
                    {
                        "deviceId": "DFE25CXXXX",
                        "configDeviceName": "Office",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "switch",
                            "deviceType": "switch",
                            "doublePress": 1
                        },
                        "refreshRate": 60,
                        "logging": "standard"
                    },
```

### Device & Model

switchbot bot

### Node.js Version

v18.12.1

### NPM Version

8.19.2

### Homebridge Version

v1.5.1

### Homebridge SwitchBot Plugin Version

2.2.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Windows

**Comment by AKWillows** [comment]
This sounds like the same issue I’m facing with the Switchbot curtain. If so, it’s an issue with the Switchbot API. I have a case open with them… I think others do too

**Comment by JeeAre70** [comment]
Same here. Curtains not properly updating in home app. Switchbot app showing right situation.

**Comment by AKWillows** [comment]
@JeeAre70 Worth opening a case with Switchbot… the more of us that do that, the more likely they will fix it!

**Comment by JeeAre70** [comment]
Ticket opened!

**Comment by ericbeecher1** [comment]
In case it works for anyone else: I was having this same issue, right after updating the firmware for my hub and curtain bots, the curtains that I had were always appearing as closed, even right after I opened them.

 I unplugged my hub for ten minutes, while it was unplugged I deleted all of my curtains from the switchbot app and factory reset them using the instructions here: https://www.reddit.com/r/smarthome/comments/o0uhny/switchbot_curtain_factory_reset_info/
Then I plugged my hub back in, re added them to cloud services, reset my homebridge and they are working now. 

I made the classic error and changed too many things at once, so I am not sure if any particular thing did the trick. But it might be worth a shot to make work.

**Comment by JeeAre70** [comment]
> In case it works for anyone else: I was having this same issue, right after updating the firmware for my hub and curtain bots, the curtains that I had were always appearing as closed, even right after I opened them.
> 
> I unplugged my hub for ten minutes, while it was unplugged I deleted all of my curtains from the switchbot app and factory reset them using the instructions here: https://www.reddit.com/r/smarthome/comments/o0uhny/switchbot_curtain_factory_reset_info/ Then I plugged my hub back in, re added them to cloud services, reset my homebridge and they are working now.
> 
> I made the classic error and changed too many things at once, so I am not sure if any particular thing did the trick. But it might be worth a shot to make work.

I can confirm the full reset works. I followed the above instruction and the curtain is properly working again in the home app. Now going to do my other 4 switchbot curtains. 

Have performed the same on my other 4 curtains. These are 2 grouped setup curtains. Although also here the full reset works the interaction between de homebridge plugin and the home app is not perfect. It does not actively update the status of the curtains. After full opening or closing you need to close the home app and reopen again to get the status of curtains correct in the app. So I will leave the ticket open with homebridge as there is clearly some incompatibility with the latest firmware for the curtains and the homebridge plugin.
