### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Stetocasa** [OpenWonderLabs/homebridge-switchbot#599]
### Describe Your Problem

Change Type

### Relevant log output

```shell
Hello, I used since months one bot exposed in HomeKit as a smart lock. Due to some restore issue I was to reconfigure the plug-in. All works but now also if the config shows smart lock in HomeKit I see a plug. Do you know how can fix it?
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxxxx",
                "secret": "xxxxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "C0043623E577",
                        "configDeviceName": "Portone",
                        "configDeviceType": "Smart Lock",
                        "connectionType": "BLE"
                    },
                    {
                        "deviceId": "DF0AA6E9AE90",
                        "configDeviceName": "Beko_Pause",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE"
                    }
                ]
            },
```

### Screenshots

![F9C38B0D-8533-46FB-BF00-30580AB8AC3D](https://user-images.githubusercontent.com/70729310/204102584-2f645c7d-63c5-4fbb-a399-0f3c2739d5b2.jpeg)

### Device & Model

Switch bot

### Node.js Version

18.12.1

### NPM Version

Nd

### Homebridge Version

1.6.0.

### Homebridge SwitchBot Plugin Version

2.2.2.

### Homebridge Config UI X Plugin Version

4.50.2

### Operating System

PI 3

**Comment by donavanbecker** [comment]
`configDeviceType` is only used to bring the configs in correctly. You have to set the bot mode first, either switch or press. Then a setting for a Bot deviceType will show up.
