### ISSUE TITLE
Support Request: Unable to install switchbot plugin on hoobs

### ISSUE THREAD

**Issue by hectorkd** [OpenWonderLabs/homebridge-switchbot#602]
### Describe Your Problem

I was having issues with the switchbot plugin after doing firmware updates to my switchbot devices (no idea if that's why it stopped working). I decided to uninstall the plugin and re-install to see if that would fix the issue but now I'm unable to install the plugin at all.

### Relevant log output

```shell
01/12/2022, 11:57:07WARNINGplugin site unavailable
01/12/2022, 11:57:07yarn add v1.22.19
01/12/2022, 11:57:07info No lockfile found.
01/12/2022, 11:57:08[1/4] Resolving packages...
01/12/2022, 11:57:08error An unexpected error occurred: "https://registry.yarnpkg.com/@switchbot%2fhomebridge-switchbot: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
01/12/2022, 11:57:08info If you think this is a bug, please open a bug report with the information provided in "/var/lib/hoobs/switchbotbridge/yarn-error.log".
01/12/2022, 11:57:08info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

----------------------------------------

Arguments: 
  /usr/bin/node /usr/lib/hoobsd/node_modules/yarn/bin/yarn.js add --unsafe-perm --ignore-engines @switchbot/homebridge-switchbot@latest

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.19

Node version: 
  16.18.1

Platform: 
  linux arm

Trace: 
  Error: getaddrinfo EAI_AGAIN registry.yarnpkg.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```

### Config for homebridge-switchbot

```shell
{
    "name": "plugins",
    "description": "HOOBS Plugins",
    "private": true,
    "dependencies": {
        "hap-nodejs": "^0.10.4"
    }
}
```

### Screenshots

<img width="462" alt="Screenshot 2022-12-01 at 11 50 10" src="https://user-images.githubusercontent.com/62357077/205045564-cee973a4-b935-4b3f-a14f-322beb2fc541.png">

### Device & Model

Rasperry pi 4

### Node.js Version

16.18.1

### NPM Version

8.19.2

### Homebridge Version

1.5.0

### Homebridge SwitchBot Plugin Version

not installed

### Operating System

Rasbian

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
