### ISSUE TITLE
Feature Request: BLE Password support

### ISSUE THREAD

**Issue by Paukhard** [OpenWonderLabs/homebridge-switchbot#604]
### Problem

Leaving your Switchbot Bot without a password is a massive security risk. Not only can anybody who has the Switchbot App (or a script) find and control the bot, but they are also able to set a password themselves, effectively locking the owner of the bot out of his own device. Unfortunately, when setting a password home bridge is not able to connect through BLE anymore.

### Solution

Amend the plugin with an option to input the password for a given bot.

**Comment by donavanbecker** [comment]
Pull Requests are welcomed.

**Comment by donavanbecker** [comment]
Same as #45
