### ISSUE TITLE
Feature Request: Set threshold for curtains for open closed

### ISSUE THREAD

**Issue by ericbeecher1** [OpenWonderLabs/homebridge-switchbot#611]
### Problem

Occasionally when updating the status of the curtains, the app returns a 99% closed, or 1% open, because of slight variations of opening and closing the curtains

### Solution

It would be great if we could set a threshold in homebridge that would still return fully opened or fully closed in the app. For example if I set my threshold as 5 then anything that comes back as under 5% open would come as fully closed in Homekit.

**Comment by donavanbecker** [comment]
There is a config for this, it's called `Minimum Open State` and `Maximum Close State`. I usually set mine to 10 and 90 and set the `Minimum Step` to 20.

[config wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Configuration#breakdown-of-each-device-config-option)

**Comment by ericbeecher1** [comment]
Oh man you are right! Thanks so much for your reply!
