### ISSUE TITLE
Support Request: Switchbot Lock Contact Sensor wrong status

### ISSUE THREAD

**Issue by Lling** [OpenWonderLabs/homebridge-switchbot#624]
### Describe Your Problem

when the door is closed, the contact sensor shows status open

### Relevant log output

```shell
My contact sensor from the switchbot log shows the wrong status.
If my door is open, the sensor shows status closed
If my door is closed, the sensor shows status open
```

### Config for homebridge-switchbot

```shell
{
                        "deviceId": "########",
                        "configDeviceName": "Haustür",
                        "configDeviceType": "Smart Lock",
                        "connectionType": "OpenAPI",
                        "lock": {
                            "hide_contactsensor": false
                        },
                        "refreshRate": 3,
                        "offline": false
                    }
```

### Device & Model

DS1618+

### Node.js Version

v16.18.1

### NPM Version

v

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

v2.3.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Synology DSM 7

**Comment by donavanbecker** [comment]
do you have logs? you commented in the logs section, but didn't post any logs.

**Comment by Lling** [comment]
Sorry, was my mistake. No i don’t have a log.
But the message is the same 😅. if my door is closed, the Status from the contact sensor in homebridge changed to open. And if i open my door the sensor shows closed.

**Comment by Lling** [comment]
Solved the problem with a new calibration

**Comment by blowen123** [comment]
I am actually trying to get the contact sensor from the lock to show up in HomeKit but your config looks a little different than mine. Are you using the wonderlabs plug-in?
