### ISSUE TITLE
Bug: api error „map“

### ISSUE THREAD

**Issue by Lling** [OpenWonderLabs/homebridge-switchbot#625]
### Describe The Bug

Plugin Bug every evening

### To Reproduce

just start the plugin

### Expected behavior

working normal would be good

### Relevant log output

```shell
12/20/2022, 9:08:33 PM] [SwitchBot] API Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "****",
                "secret": "****",
                "notice": "Keep your Token & Secret a secret!"
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

![02EC0A73-6D59-40CE-B0F7-DDC341E1ECFC](https://user-images.githubusercontent.com/6634017/208757346-0863ccad-274c-4363-968a-3c3c21fd773b.jpeg)

### Device & Model

DSM 7.0

### Node.js Version

v16.18.2

### NPM Version

v

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v.2.3.2

### Operating System

DSM7.0

**Comment by Lling** [comment]
Ok i think at the evening the max api request is reached. Every morning the plugin works again.

**Comment by donavanbecker** [comment]
Yep this error usually means that. I would set a higher refreshrate or set individual refreshrate for your devices, setting meters and other devices that can be higher at a higher refreshRate and devices like contact, etc at a lower one.

**Comment by Lling** [comment]
Good idea. Thanks for the tip
