### ISSUE TITLE
Switchbot Bot issuing two clicks when activated via Home App

### ISSUE THREAD

**Issue by macguyincali** [OpenWonderLabs/homebridge-switchbot#627]
### Describe Your Problem

Switchbot Bot issuing two clicks when activated via Home App.  For coffeemaker it is essentially turning on and then immediately turning off the coffeemaker.

### Relevant log output

```shell
[12/22/2022, 7:20:31 AM] [SwitchBot] Bot: Coffee maker Set On: true
[12/22/2022, 7:20:34 AM] [SwitchBot] Bot: Coffee maker Set On: true
```

### Device & Model

SwitchBot Bot

### Node.js Version

v18.12.1

### NPM Version

no idea

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

v2.3.2

### Operating System

MacOS13.1

**Comment by alvst** [comment]
Does this happen when it is invoked from Homebridge? Subsequent requests should be ignored when they are issued that close together. Also odd that there was no intermediary false state (unless that was cut out).

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.4.0-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by macguyincali** [comment]
Hi, it appears that this has been resolved with the new version!
