### ISSUE TITLE
Wrong Homebridge version detected

### ISSUE THREAD

**Issue by badxhabit** [OpenWonderLabs/homebridge-switchbot#634]
### Describe The Bug

Switchbot plugin says that the Homebridge version detected is 1.5.1, but I clearly have 1.6.0 installed.

### To Reproduce

Boot up Homebridge

### Expected behavior

Detect the correct version?

### Relevant log output

```shell
Switchbot plugin says that the Homebridge version detected is 1.5.1, but I clearly have 1.6.0 installed. Started happening a few versions ago. (2.2.2, I think?)
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxx",
                "secret": "xxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xxxx",
                        "configDeviceName": "Thermometer & Hygrometer",
                        "configDeviceType": "Meter",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "deviceType": "outlet"
                        },
                        "history": true
                    },
                    {
                        "deviceId": "xxxx",
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "logging": "standard"
                    },
                    {
                        "deviceId": "xxxx",
                        "configDeviceName": "Master Bedroom Curtains",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "logging": "standard"
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

<img width="1134" alt="Screenshot 2022-12-27 at 7 46 57 PM" src="https://user-images.githubusercontent.com/2319140/209754575-8e92b6de-7992-49c4-8aa3-1313469bfb92.png">

### Device & Model

RPi 4, 4GB

### Node.js Version

v18.12.1

### NPM Version

v8.19.2

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v2.4.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
This is being thrown by Homebridge and not the plugin, so you must have two instances of Homebridge running.

**Comment by badxhabit** [comment]
I don't see any other instances running.

**Comment by badxhabit** [comment]
For posterity, be sure to run the command inside the Homebridge-config-ui-x terminal and not on Raspbian terminal.
`npm install -g --unsafe-perm homebridge`
