### ISSUE TITLE
Bug: Max retry functionality not working as expected

### ISSUE THREAD

**Issue by dnicolson** [OpenWonderLabs/homebridge-switchbot#636]
### Describe The Bug

When BLE connection errors occur it seems that `discover` needs to be called again and not just `turnOn`/`turnOff`. I tested with 5 second intervals for minutes and the result of the log output below did not change.

### To Reproduce

Turn a Bot off and on repeatedly 

### Expected behavior

Retry attempts to have a different result

### Relevant log output

```shell
[28/12/2022, 19:13:59] [SwitchBot] Retrying
[28/12/2022, 19:14:00] [SwitchBot] TypeError: Cannot read properties of null (reading 'write')
```

### Config for homebridge-switchbot

```shell
{
    "deviceId": "D787C65C8DEB",
    "configDeviceName": "Light",
    "configDeviceType": "Bot",
    "connectionType": "BLE",
    "bot": {
        "mode": "switch",
        "deviceType": "switch"
    },
    "maxRetry": 5,
    "logging": "standard"
}
```

### Device & Model

SwitchBot Bot

### Node.js Version

v18.12.1

### NPM Version

v8.19.2

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v2.4.0

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspian

**Comment by donavanbecker** [comment]
latest beta has the latest node-switchbot beta as a dependency.

**Comment by dnicolson** [comment]
That helps with the error messages, it doesn't affect the retry behavior though.

**Comment by dnicolson** [comment]
@donavanbecker I'm not sure why this is invalid, I plan to submit a pull request with the proposed fix after https://github.com/OpenWonderLabs/homebridge-switchbot/pull/690 is merged.
