### ISSUE TITLE
Support Request: Curtain not moving 

### ISSUE THREAD

**Issue by philippvogel** [OpenWonderLabs/homebridge-switchbot#637]
### Describe Your Problem

The curtain device is not moving and also closed in HomeKit

### Relevant log output

```shell
[30/12/2022, 14:38:31] [SwitchBot] [DEBUG] Curtain: Curtain No Changes, Set TargetPosition: 100
[30/12/2022, 14:38:31] [SwitchBot] [DEBUG] Curtain: Curtain value: 100, CurrentPosition: 0
[30/12/2022, 14:38:31] [SwitchBot] [DEBUG] Curtain: Curtain updateRate: 5
[30/12/2022, 14:38:34] [SwitchBot] [DEBUG] Curtain: Curtain Refresh Status When Moving, PositionState: 1
[30/12/2022, 14:38:34] [SwitchBot] [DEBUG] Curtain: Curtain openAPIRefreshStatus
[30/12/2022, 14:38:34] [SwitchBot] [DEBUG] Curtain: Curtain sign: ****************************************
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain statusCode: 200
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain d: {"statusCode":100,"body":{"deviceId":"***********","deviceType":"Curtain","hubDeviceId":"***********","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"************","deviceType":"Curtain","hubDeviceId":"**********","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain openAPIparseStatus
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain Curtain CurrentPosition: 0
[30/12/2022, 14:38:35] [SwitchBot] Curtain: Curtain Checking Status ...
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain Standby, CurrentPosition: 0
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain Stopped
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 2,
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain updateCharacteristic CurrentPosition: 0
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain updateCharacteristic PositionState: 2
[30/12/2022, 14:38:35] [SwitchBot] [DEBUG] Curtain: Curtain updateCharacteristic TargetPosition: 0
[30/12/2022, 14:38:36] [SwitchBot] [DEBUG] Curtain: Curtain setNewTarget true timeout
[30/12/2022, 14:38:36] [SwitchBot] [DEBUG] Curtain: Curtain OpenAPI pushChanges
[30/12/2022, 14:38:36] [SwitchBot] [DEBUG] Curtain: Curtain No OpenAPI Changes, CurrentPosition & TargetPosition Are the Same. CurrentPosition: 0, TargetPosition  0
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "*******************************************************************",
                "secret": "**********************************+",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "**************",
                        "configDeviceName": "Curtain 2",
                        "hide_device": true,
                        "configDeviceType": "Curtain",
                        "curtain": {
                            "set_minStep": 1,
                            "set_min": 10,
                            "set_max": 90,
                            "updateRate": 1,
                            "hide_lightsensor": true
                        },
                        "logging": "debug"
                    },
                    {
                        "deviceId": "***************",
                        "configDeviceName": "Bot FA Bot",
                        "configDeviceType": "Bot",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": false,
                            "doublePress": 1
                        },
                        "logging": "standard"
                    },
                    {
                        "deviceId": "***************",
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "curtain": {
                            "set_min": 10,
                            "set_max": 90,
                            "updateRate": 5,
                            "setOpenMode": "0",
                            "setCloseMode": "1",
                            "hide_lightsensor": true
                        },
                        "history": false,
                        "refreshRate": 360,
                        "logging": "debug"
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "*******************",
                        "configRemoteType": "Light",
                        "logging": "debug"
                    }
                ],
                "refreshRate": 360,
                "pushRate": 5,
                "logging": "debug"
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

The curtain is not moving after trigger via HomeKit. According to the logs the API calls are successful, but one line was interesting: [30/12/2022, 14:38:36] [SwitchBot] [DEBUG] Curtain: Curtain No OpenAPI Changes, CurrentPosition & TargetPosition Are the Same. CurrentPosition: 0, TargetPosition  0

It seems to me that the plugin isn't even considering to move the curtain. What does this mean and is this in connection to the problem that the curtain is not moving?

The curtain can be controlled without any problem from the SwitchBot App, and the state is correctly displayed there.
But the logs inside the SwitchBot App don't show any actions from today (Dec. 30)
![IMG_0141](https://user-images.githubusercontent.com/11444948/210078188-a7d72b85-c822-4bf6-b6d7-3d3eb62e1c12.PNG)

### Device & Model

SwitchBot: Curtain, Firmware V3.9

### Node.js Version

v14.21.2

### NPM Version

v6.14.17

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

v2.4.0

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian GNU/Linux Buster (10)

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.4.1-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

and set the config for your curtain to Disable Caching? Then push a change and post the logs.

**Comment by philippvogel** [comment]
I tested on the latest beta with disabled caching, after restart Homebridge the first action is working (open or close). After that the device state remains a very long time, but a restart of Homebridge updates the state immediately. At the timepoint where the correct state is updated it is working again. This is the current complete config: 

{
    "name": "SwitchBot",
    "credentials": {
        "token": "****************************",
        "secret": "****************************",
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "************",
                "configDeviceName": "Curtain",
                "hide_device": true,
                "configDeviceType": "Curtain",
                "connectionType": "OpenAPI",
                "curtain": {
                    "set_minStep": 1,
                    "set_min": 10,
                    "set_max": 90,
                    "updateRate": 1,
                    "hide_lightsensor": true
                },
                "logging": "debug"
            },
            {
                "deviceId": "************",
                "configDeviceName": "Bot FA Bot",
                "configDeviceType": "Bot",
                "bot": {
                    "mode": "press",
                    "deviceType": "switch",
                    "allowPush": false,
                    "doublePress": 1
                },
                "logging": "standard"
            },
            {
                "deviceId": "************",
                "configDeviceName": "Curtain 2",
                "configDeviceType": "Curtain",
                "connectionType": "OpenAPI",
                "curtain": {
                    "set_minStep": 0,
                    "set_min": 10,
                    "set_max": 90,
                    "updateRate": 30,
                    "setOpenMode": "0",
                    "setCloseMode": "0",
                    "hide_lightsensor": true
                },
                "disableCaching": true,
                "history": false,
                "refreshRate": 360,
                "logging": "debug"
            }
        ],
        "irdevices": [
            {
                "deviceId": "************",
                "configRemoteType": "Light",
                "logging": "debug"
            }
        ],
        "refreshRate": 360,
        "pushRate": 5,
        "logging": "debug"
    },
    "platform": "SwitchBot"
}

The affected device is "Curtain 2" (2nd Generation)
"Curtain" (1st Generation) isn't moving at all.

**Comment by donavanbecker** [comment]
please try v2.5.0

**Comment by philippvogel** [comment]
v2.5.0 is working. There is still some delay in state but not as much as before.

**Comment by donavanbecker** [comment]
Looks like @dnicolson has submitted some PRs so hopefully that will help as well.
