### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by binomialstew** [OpenWonderLabs/homebridge-switchbot#641]
### Describe The Bug

Prior to app version 6.21.1 in iOS, I was able to use OpenAPI to control the SwitchBot. After the update to both the iOS app and homebridge switchbot, when trying to control the switch in the same way by connecting with a secret token, I am now getting the error message “Cloud access: false”. However, it seems I cannot enable cloud access in the app because it will only allow me to select a hub, which I do not have. This OpenAPI connection worked prior to this version without a hub.

### To Reproduce

Attempt to control switchbot with OpenAPI

### Expected behavior

Control should be possible without cloud enabled

### Relevant log output

```shell
[1/4/2023, 10:44:10 PM] [SwitchBot] Bot: [Bot name] Set TargetPosition: 100
[1/4/2023, 10:44:10 PM] [SwitchBot] Bot: [Bot name] pushChanges enableCloudService: false
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "secret": "xxxxxxxxxxxxxxxxxxxxxx",
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "XXXXXXXXXXXXXX",
                "configDeviceName": "Bot Name",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "window"
                },
                "offline": true
            },
            {
                "deviceId": "XXXXXXXXXXXXXX",
                "configDeviceName": "Another Bot Name",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "window"
                },
                "offline": true
            }
        ]
    },
    "platform": "SwitchBot"
},
```

### Device & Model

SwitchBot Bot

### Node.js Version

v16.16.0

### NPM Version

v8.11.0

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v2.4.0

### Homebridge Config UI X Plugin Version

v4.49.0

### Operating System

Docker

**Comment by donavanbecker** [comment]
If you are trying to connect without a hub, your connectiontype needs to be BLE.
