### ISSUE TITLE
Projector IR buttons - only one available.

### ISSUE THREAD

**Issue by macguyincali** [OpenWonderLabs/homebridge-switchbot#643]
### Describe Your Problem

I have a projector which has an on and an off button, but these are not accessible via homebridge. The Homekit version of the IR device only has one button (power toggle) but the remote itself (on both the Switchbot app and the actual remote) has an on and an off button.   Is there anyway to choose which buttons appear in the Homekit device? The problem is that I'd like to issue "off" commands or "on" commands, not a toggle command. Any way to do this?

Also, any way to issue a double click would be great. The "off" command requires two clicks to confirm.

### Relevant log output

```shell

```

### Device & Model

Switchbot hub

### Node.js Version

v18.12.1

### NPM Version

Not sure

### Homebridge Version

1.3.4

### Homebridge SwitchBot Plugin Version

v2.4.0

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

macOS Ventura

**Comment by w879al4** [comment]
I faced a similar issue with my Epson projector and worked around it by defining 2 remotes. One has power on as the power toggle and the other has standby. 
I then use the dummy switch add-on for the projector with an automation to call the desired action, the power off being a double press.
A bit clunky but does the job for me, hope this helps.

**Comment by alvst** [comment]
I think what you should really do is create a shim device (via a separate small plugin) and then from there you could define on as a single click and off as a double click either by sending the Switchbot 2 presses or by configuring it in a custom mode. Feel free to use [this project](https://github.com/alvst/homebridge-switchbot-thermostat), which I created, as a template for creating shim layer.
