### ISSUE TITLE
Support Request: Can install homebridge-switchbot

### ISSUE THREAD

**Issue by fklingenberg** [OpenWonderLabs/homebridge-switchbot#646]
### Describe Your Problem

I cant install homebridge-switchbot on my rapsberry pi

### Relevant log output

```shell
Hello, whenever I want to install homebridge-switch on my raspberry pi i get an 404 error in the post-install script. The script is trying to download somethink from a github repository that does no longer exist.
Does anyone else have the same problem?
```

### Screenshots

![IMG_0750](https://user-images.githubusercontent.com/10289945/211151674-b76ec88e-7217-4d04-9d39-db414aec154a.PNG)

### Device & Model

Raspberry Pi Zero

### Node.js Version

v18.12.1

### NPM Version

v9.1.3

### Homebridge Version

v1.6

### Homebridge SwitchBot Plugin Version

v2.4.0

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Install prerequisites for node-SwitchBot. See readme for Bluetooth prerequisites.

**Comment by florinmoreanu** [comment]
Hi! Did you manage to get it working? Currently I have the same issue.

**Comment by fklingenberg** [comment]
> Hi! Did you manage to get it working? Currently I have the same issue.

@florinmoreanu No, unfortunately I have not. The only way I have found is via IFTTT with a webhook

**Comment by florinmoreanu** [comment]
Do you need a Hub for this,right ?

**Comment by fklingenberg** [comment]
> Do you need a Hub for this,right ?

@florinmoreanu Yes

**Comment by donavanbecker** [comment]
> Do you need a Hub for this,right ? 

No you do not need a hub for this plugin. You can use BLE connection.

**Comment by florinmoreanu** [comment]
Hi @donavanbecker ! Thanks for your answer! 
I have the same issue as jusTreme. Tried to install the plugin on a Homebridge image/fresh installation of Raspbian (bullseye) and also installed the prerequisites shown. Also tried with different versions of node but still no luck.

**Comment by donavanbecker** [comment]
@florinmoreanu You could try installing noble separately and see if that resolves the issue.

**Comment by florinmoreanu** [comment]
Installed noble and @abandonware/bluetooth-hci-socket but unfortunately the issue still persists:(
