### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by n7ckn03** [OpenWonderLabs/homebridge-switchbot#647]
### Describe The Bug

An error is recorded when Honebridge starts

### To Reproduce

The plug-in loads with this error 

### Expected behavior

I’m not sure of its impact but I’m reporting the bug as requested

### Relevant log output

```shell
API Request:
TypeError: Cannot read properties of undefined (reading
'map'
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "***",
                "secret": "***",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "02-202210280515-72744923",
                        "configDeviceName": "Door Strip",
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "Power",
                        "customOff": "Power",
                        "other": {
                            "deviceType": "Fan"
                        },
                        "external": true,
                        "logging": "standard"
                    }
                ],
                "refreshRate": 9,
                "pushRate": 2,
                "logging": "standard"
            },
            "_bridge": {
                "username": "0E:9E:2F:9A:9B:0D",
                "port": 43588
            },
            "platform": "SwitchBot"
        },
```

### Device & Model

Raspberry Pi 4b

### Node.js Version

18.13.0

### NPM Version

9.2.0

### Homebridge Version

1.6.0

### Homebridge Switchbot Plugin Version

2.4.0

### Homebridge Config UI X Plugin Version

4.50.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@n7ckn03 my guess is that you have reach your daily refresh limit.

**Comment by n7ckn03** [comment]
I’ve tried to set the refresh to a level that will be low and not exceed the 10,000 daily limit thus setting it to 9 seconds.

Should I have a configuration for each of my SwitchBot devices or leave them to get auto deployed?

The default 360 seconds is too long. Is the refresh per device and therefore compounded to make me exceeds the limit, or are they governed by the main refresh interval setting?

Thanks for your help.
Nick

**Comment by donavanbecker** [comment]
I would set it for each, or use BLE connection.
