### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by macguyincali** [OpenWonderLabs/homebridge-switchbot#648]
### Describe Your Problem

Re-entered Secret/Token Now Device Not Responding in Homekit

### Relevant log output

```shell
Hi there! I had to reenter my Token/Secret recently (not sure why it was deleted in configuration--probably something I did). When I restarted the plugin, my "Coffeemaker Accessory" in home app (via SwitchBot Bot) was no longer responding. The Accessory in Homebridge does seem to work fine, so it appears that the HomeKit accessory and the Homebridge version are not linked. I think I need to somehow "re-add" the device, but can't figure out how to do that. Any help would be appreciated.
```

### Device & Model

Switchbot Bot

### Node.js Version

v18.12.1

### NPM Version

not sure

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

v2.4.0

### Operating System

Mac OS Ventura

**Comment by donavanbecker** [comment]
You will need to post your config for me to help you on this.

**Comment by macguyincali** [comment]
The config didn't seem to have a lot of helpful info, but here it is attached.  I was able to start a child bridge and created a new device for the coffee maker which I was able to add to Home Kit. I ended up deleting the other bridge on HomeKit since it was not associated with anything.  So, at this point I am up and running.
           "name": "SwitchBot",
            "credentials": {
                "token": "----",
                "secret": "----",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "logging": "standard"
            },
            "platform": "SwitchBot",
            "_bridge": {
                "username": "----",
                "port": 44712
