### ISSUE TITLE
Feature Request: Support for SwitchBot Blind Tilt

### ISSUE THREAD

**Issue by sdaltons1** [OpenWonderLabs/homebridge-switchbot#649]
### Problem

Saw that the blind tilts have now been added to the API

### Solution

Can support for the blind tilts be added to this plug-in? Please and thanks!

**Comment by donavanbecker** [comment]
Working on it.

**Comment by donavanbecker** [comment]
@sdaltons1, latest beta should display the Blind Tilts, I haven't been able to implement push commends yet.

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.4.1-beta.7/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by timmy8784** [comment]
The blinds do show up using the latest beta. Seems to have some issues with understanding "open" vs closed up or closed down. 

When the blinds are 100% open HomeKit shows 50% and when moving to 100% it actually closes them. 

I think this is more an issue with SwitchBot as I've noticed this with all voice assistants. They need to build a default close direction or something like that

**Comment by donavanbecker** [comment]
@timmy8784 we will probably have to create a config to say what is closedup and what is closedDown

**Comment by sdaltons1** [comment]
Have updated to the beta and have mine showing as well. If the blinds are open and I tap on them (using Apple Home), they will close properly. But once they are closed, HK doesn't seem to understand how to open them. I haven't played with the sliders yet.

**Comment by donavanbecker** [comment]
@sdaltons1, like I said. I haven't implemented push commands yet.

**Comment by donavanbecker** [comment]
@timmy8784 or @sdaltons1 can you get me some debug logs of the status updates you are getting from the Blind Tilts? I will actually be able to do a close or open and and move the blinds closedUp or ClosedDown using HomeKit [TargetHorizontalTiltAngle](https://developers.homebridge.io/#/characteristic/TargetHorizontalTiltAngle) Characteristic.

**Comment by timmy8784** [comment]
> @timmy8784 or @sdaltons1 can you get me some debug logs of the status updates you are getting from the Blind Tilts? I will actually be able to do a close or open and and move the blinds closedUp or ClosedDown using HomeKit [TargetHorizontalTiltAngle](https://developers.homebridge.io/#/characteristic/TargetHorizontalTiltAngle) Characteristic.

Forgive my ignorance, but how exactly would I do this?  Is this simply trying to access the blinds and copy what shows in the activity in homebridge?

**Comment by donavanbecker** [comment]
Well first you will need to either turn debug mode on for Homebridge, the plugin, or for the device. Then copy any logs on the blind tilt.

Easier to set debug on a per device level. You can do this by getting the deviceID which is in the logs and pasting it in the plugin config under SwitchBot device settings. Then there is a logging option, select debug.

**Comment by timmy8784** [comment]
> Well first you will need to either turn debug mode on for Homebridge, the plugin, or for the device. Then copy any logs on the blind tilt.
> 
> Easier to set debug on a per device level. You can do this by getting the deviceID which is in the logs and pasting it in the plugin config under SwitchBot device settings. Then there is a logging option, select debug.

Does any of this help?


13/01/2023, 13:52:42] [SwitchBot] Blind Tilt: Living Room Blinds 2 openAPIRefreshStatus
[13/01/2023, 13:52:42] [SwitchBot] Blind Tilt: Living Room Blinds 2 sign: DFCRF7tI63eGoPBBb648H7HwAxKrRkY2+D1B7QQ+HxQ=
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 statusCode: 200
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 d: {"statusCode":100,"body":{"deviceId":"DEBB31881913","deviceType":"Blind Tilt","hubDeviceId":"DA6EB96E5C43","version":20,"calibrate":true,"battery":100,"direction":"Up","slidePosition":57},"message":"success"}
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 refreshStatus: {"statusCode":100,"body":{"deviceId":"DEBB31881913","deviceType":"Blind Tilt","hubDeviceId":"DA6EB96E5C43","version":20,"calibrate":true,"battery":100,"direction":"Up","slidePosition":57},"message":"success"}
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 openAPIparseStatus
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 CurrentPosition: 43
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 Standby, CurrentPosition: 43
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 Stopped
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 CurrentPosition: 43, TargetPosition: 43, PositionState: 2,
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 CurrentAmbientLightLevel: 6001
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 updateCharacteristic CurrentPosition: 43
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 updateCharacteristic PositionState: 2
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 updateCharacteristic TargetPosition: 43
[13/01/2023, 13:52:43] [SwitchBot] Blind Tilt: Living Room Blinds 2 updateCharacteristic CurrentAmbientLightLevel: 6001

**Comment by donavanbecker** [comment]
Yes it does! Thanks!

**Comment by sdaltons1** [comment]
> @sdaltons1, like I said. I haven't implemented push commands yet.

Not sure how I missed that 🤦‍♂️

Let me know if I can help in any other way. And thanks for doing this!

**Comment by tjridge** [comment]
I also have a few blind tiles devices. Let me know if there is any info I can provide to help.

**Comment by AndreasVerhoeven** [comment]
> @timmy8784 or @sdaltons1 can you get me some debug logs of the status updates you are getting from the Blind Tilts? I will actually be able to do a close or open and and move the blinds closedUp or ClosedDown using HomeKit [TargetHorizontalTiltAngle](https://developers.homebridge.io/#/characteristic/TargetHorizontalTiltAngle) Characteristic.

I've been trying to implement `TargetHorizontalTiltAngle` in the plugin since it maps nicely to the `up|down;percentage` setPosition call of the OpenAPI, except that the characteristic never shows up in the Home app as controllable. It does show up in Eve, so homekit does read it.

Not sure if I'm doing something wrong or if this is just not supported by the Home app right now.

Mapping 0-100 to  0=100% down, 50 = open, 100=100% up also does not seem really great; The blinds will only show up closed when tilting down, not up. I'm not sure what the best way is here. Any guidance?

**Comment by donavanbecker** [comment]
@AndreasVerhoeven, I just haven't had time to work on this, so thanks. 

It does display, but if you are still display the light sensor the controls are within the separate services of the accessory. I can push what I have so far if that helps. Also the controls are not displayed up front, you have to scroll down and you will see a bar that you can go from left to right and right to left.

**Comment by AndreasVerhoeven** [comment]
> @AndreasVerhoeven, I just haven't had time to work on this, so thanks. 
> 
> 
> 
> It does display, but if you are still display the light sensor the controls are within the separate services of the accessory. I can push what I have so far if that helps. Also the controls are not displayed up front, you have to scroll down and you will see a bar that you can go from left to right and right to left.

If you can push what you have, I can try to pick it up from there!

**Comment by donavanbecker** [comment]
> If you can push what you have, I can try to pick it up from there!

okay changes are in branch `beta-2.5.0`

**Comment by AndreasVerhoeven** [comment]
> > If you can push what you have, I can try to pick it up from there!
> 
> okay changes are in branch `beta-2.5.0`

Thanks! I know see the HorizontalTilt slider in the Home app! Wondering what would be smart to do:

**Option 1: map the slidePosition the HorizontalTilt 0% -> -90deg, 50% = 0deg, 100%=90deg**
Pros: it maps neatly to what we ant
Cons: the TargetPosition slider is still the main thing to interact with in Home/Siri, so that slider kinda became useless and siri gets easily confused :(

**Option 2: use a combination of tilt and position**
- Use HorizontalTilt to determine if we should tilt up or down. If HorizontalTilt < 0, then we should tilt down, otherwise up**
- Actual tilt position is determined by the main TargetPosition

Pros: the big slider is used
Cons: we kinda misuse HorizontalTilt?
 
 **Option 3: only use TargetPosition and let the user configure a set direction**
E.g. I set direction="up" and the 0% maps to open and 100% maps to 100% closed upwards. This would be perfect for my use case, since I only tilt upwards.

Pros: simple
Cons: Only a single direction

**Option 4: 0=closed downwards, 50%=open, 100%=closed upwards with option to invert**

Pros: simple, already works
Cons: doesn't always show as closed


Or should this be user configurable? Might be a lot of work?

**Comment by donavanbecker** [comment]
I think it should be user configurable. So we can have options for Valid Values of TargetHorizontalTiltAngle. We would have defaults and then allow for config changes.

Something like this:

```
validValues: [this.minus90, this.zero, this.plus90],
```

**Comment by AndreasVerhoeven** [comment]
> I think it should be user configurable. So we can have options for Valid Values of TargetHorizontalTiltAngle. We would have defaults and then allow for config changes.
> 
> Something like this:
> 
> ```
> validValues: [this.minus90, this.zero, this.plus90],
> ```

What would the main position slider do in this case?

**Comment by donavanbecker** [comment]
We would have to determine that somewhere.

Once I get some blinds I can play around with this more :) haha

**Comment by sdaltons1** [comment]
I know you guys weren't really asking me but I also only really open them or close them up.  So I will throw in a meaningless vote for option 3 above!

**Comment by donavanbecker** [comment]
okay nvm, sorry I don't have the blinds yet, so wasn't sure what it could all do. I reviewed a view and can now see that will will want to use the `TargetPosition` for the opening.

I think we do this. We use `TargetHorizontalTiltAngle` to say either up or down. and we use `TargetPostion` to open or close. 

So this is how it would work:

We would only allow `-90` or` 90` for `TargetHorizontalTiltAngle`.

If `TargetHorizontalTiltAngle` is at `-90` and `TargetPostion` is `Closed` then we would do closedDownward

If `TargetHorizontalTiltAngle` is at `90` and `TargetPostion` is `Closed` then we would do closedUpward

**Comment by AndreasVerhoeven** [comment]
> 

I was thinking of something along the lines of:

```
enum BlindTiltMappingMode {
  OnlyUp = 'only_up', // 0 means open, 100 means closed up
  OnlyDown = 'only_down', // 0 means open, 100 means closed down
  DownAndUp = 'down_and_up', // 0 means closed down, 50 means open, 100 means closed up
  UpAndDown = 'up_and_down', // 0 means closed up, 50 means open, 100 means closed down
  UseTiltForDirection = 'use_tilt_for_direction', // tilt -90 means down, tilt 90 means up, 0 = open, 100 is closed in the corresponding direction
}

// user configurable
mappingMode: BlindTiltMappingMode = BlindTiltMappingMode.DownAndUp;

  /**
   * Maps device values to homekit values
   * 
   * @param mode the user defined mode
   * @param devicePosition the position as reported by the devide
   * @param direction the direction as reported by the device
   * @returns [homekit position, homekit tiltAngle]
   */
  mapDeviceValuesToHomekitValues(mode: BlindTiltMappingMode, devicePosition: number, deviceDirection: string): [CharacteristicValue, CharacteristicValue?] {
    switch(mode) {
      case BlindTiltMappingMode.OnlyUp: return [deviceDirection === 'down' ? 0 : devicePosition, undefined];
      case BlindTiltMappingMode.OnlyDown: return [deviceDirection === 'up' ? 0 : devicePosition, undefined];
      case BlindTiltMappingMode.DownAndUp: return [deviceDirection === 'down' ? devicePosition / 2 : 50 + devicePosition / 2, undefined];
      case BlindTiltMappingMode.UpAndDown: return [deviceDirection === 'up' ? devicePosition / 2 : 50 + devicePosition / 2, undefined];
      case BlindTiltMappingMode.UseTiltForDirection: return [devicePosition, deviceDirection === 'up' ? 90 : -90];
    }
  }

  /**
   * Maps homekit values to device values
   * 
   * @param mode the user defined mode
   * @param homekitPosition the position as reported by homekit
   * @param homekitTiltAngle the tilt angle as reported by homekit
   * @returns [device position, device direction]
   */
  mapHomekitValuesToDeviceValues(mode: BlindTiltMappingMode, homekitPosition: number, homekitTiltAngle: number?): [string, number] {
    switch(mode) {
      case BlindTiltMappingMode.OnlyUp: return ['up', homekitPosition];
      case BlindTiltMappingMode.OnlyDown: return ['down', homekitPosition];
      case BlindTiltMappingMode.DownAndUp: return homekitPosition < 50 ? ['down', homekitPosition * 2] : ['up', (50 - homekitPosition) * 2];
      case BlindTiltMappingMode.UpAndDown: return homekitPosition < 50 ? ['up', homekitPosition * 2] : ['down', (50 - homekitPosition) * 2];
      case BlindTiltMappingMode.UseTiltForDirection: return [homekitTiltAngle! < 0 ? 'down' : 'up', homekitPosition];
    }
  }
  ```

That way, it's pretty flexible and support a lot of use cases? Sdalton1 and me only closes the blinds upwards, so we would configure it as 'only_up', while other people might want to use the tilt direction?

**Comment by AndreasVerhoeven** [comment]
@donavanbecker I got something working

> okay nvm, sorry I don't have the blinds yet, so wasn't sure what it could all do. I reviewed a view and can now see that will will want to use the `TargetPosition` for the opening.
> 
> I think we do this. We use `TargetHorizontalTiltAngle` to say either up or down. and we use `TargetPostion` to open or close.
> 
> So this is how it would work:
> 
> We would only allow `-90` or` 90` for `TargetHorizontalTiltAngle`.
> 
> If `TargetHorizontalTiltAngle` is at `-90` and `TargetPostion` is `Closed` then we would do closedDownward
> 
> If `TargetHorizontalTiltAngle` is at `90` and `TargetPostion` is `Closed` then we would do closedUpward

I got a lot of it working after messing with the OpenAPI, but I'm constantly running into this piece of code:

```

    /**
     * If Blind Tilt movement time is short, the moving flag from backend is always false.
     * The minimum time depends on the network control latency.
     */
    clearTimeout(this.setNewTargetTimer);
    this.debugLog(`${this.device.deviceType}: ${this.accessory.displayName} updateRate: ${this.updateRate}`);
    if (this.setNewTarget) {
      this.setNewTargetTimer = setTimeout(() => {
        this.debugLog(`${this.device.deviceType}: ${this.accessory.displayName} setNewTarget ${this.setNewTarget} timeout`);
        this.setNewTarget = false;
      }, this.updateRate * 1000);
    }
```
    
If I understand correctly, we want to trigger update checks also if the device never told us it is moving. However, the `if` checks for both `setNewTarget && isMoving`. I think it should check for `setNewTarget || isMoving` ?

**Comment by donavanbecker** [comment]
@AndreasVerhoeven feel free to change what you need. I just copied the curtain file to get this started. Also if you want to work on BLE, I can give you direction.

**Comment by AndreasVerhoeven** [comment]
> @AndreasVerhoeven feel free to change what you need. I just copied the curtain file to get this started. Also if you want to work on BLE, I can give you direction.

I think I'm hitting a bug I've also hit with curtains here. 

Another problem seems to be that the OpenAPI is never telling us if the device is moving:
```
 Blind Tilt: Blind Tilt d: {"statusCode":100,"body":{"deviceId":"C5F845068223","deviceType":"Blind Tilt","hubDeviceId":"E78266062E32","version":12,"calibrate":true,"battery":100,"direction":"Up","slidePosition":65},"message":"success"}
[1/25/2023, 3:26:23 PM] [SwitchBot] Blind Tilt: Blind Tilt refreshStatus: {"statusCode":100,"body":{"deviceId":"C5F845068223","deviceType":"Blind Tilt","hubDeviceId":"E78266062E32","version":12,"calibrate":true,"battery":100,"direction":"Up","slidePosition":65},"message":"success"}
```

Don't know how to work around this yet. I'll try to work on the BLE part as well, but it has been highly unstable for me in the past, so unsure how much success I will have with that

**Comment by donavanbecker** [comment]
@AndreasVerhoeven You could probably find a lot of info for BLE here: https://github.com/Danielhiversen/pySwitchbot/pull/181

And we would need to integrate it in this repo: https://github.com/OpenWonderLabs/node-switchbot/issues/179

**Comment by donavanbecker** [comment]
@AndreasVerhoeven I got my blind tilts today!! So I can work on this more.

Would you want to submit what you have so far with a pull request? And then we can both work base off of that.

**Comment by AndreasVerhoeven** [comment]
> @AndreasVerhoeven I got my blind tilts today!! So I can work on this more.
> 
> Would you want to submit what you have so far with a pull request? And then we can both work base off of that.

That's great news! I've based my changes on 2.4.1-beta branch in https://github.com/AndreasVerhoeven/homebridge-switchbot/blob/beta-2.4.1/src/device/blindtilt.ts . I'll clean it up a bit later and make a PR in a few hours.

Few issues I ran into:
 - the `moving` is not incorrectly present in the API response, resulting in the state not being tracked properly in the plugin. I've been trying to come up with ways around it, but nothing super successful for now
 - `down;0` errors out the API, this can probably be worked around by just recognizing this case and sending `down;1` to the API as a workaround.
 
 Apart from that, controlling the device thru homekit via several configurable methods works pretty well already!

**Comment by donavanbecker** [comment]
@AndreasVerhoeven, took what you had so far and released it in v2.5.0. We can make improvements of that. Thanks!

>* the `moving` is not incorrectly present in the API response, resulting in the state not being tracked properly in the plugin. I've been trying to come up with ways around it, but nothing super successful for now

Do you have Curtains? if not look over the Curtain file. I have `set_min` & `set_max` these are used to Set the Minimum Open State (Sets the minimum percentage before needed to set Curtain to Open) & the Maximum Close State (Sets the maximum percentage before needing to set Curtain to Closed). Could help once it gets to a certain percentage, we just say it is closed. That is already in the BlindTilt file at line 985.

> * `down;0` errors out the API, this can probably be worked around by just recognizing this case and sending `down;1` to the API as a workaround.

works for me.

**Comment by The-Croz** [comment]
I am up an running with mine on 2.5.1. I have mine set to Middle to Down in my config, but when the plugin loads, I get this in the logs:
```
[1/29/2023, 4:17:54 PM] [SwitchBot] Blind Tilt: Playroom Front R Blinds Config: {"mode":"only_down","connectionType":"OpenAPI","logging":"standard","mappingMode":"only_up"}
[1/29/2023, 4:17:54 PM] [SwitchBot] Blind Tilt: Playroom Side Blinds Config: {"mode":"only_down","connectionType":"OpenAPI","logging":"standard","mappingMode":"only_up"}
[1/29/2023, 4:17:54 PM] [SwitchBot] Blind Tilt: Front Room R Blinds Config: {"mode":"only_down","connectionType":"OpenAPI","logging":"standard","mappingMode":"only_up"}
[1/29/2023, 4:17:54 PM] [SwitchBot] Blind Tilt: Playroom Front L Blinds Config: {"mode":"only_down","connectionType":"OpenAPI","logging":"standard","mappingMode":"only_up"}
[1/29/2023, 4:17:54 PM] [SwitchBot] Blind Tilt: Front Room L Blinds Config: {"mode":"only_down","connectionType":"OpenAPI","logging":"standard","mappingMode":"only_up"}
```
"mode" is properly set to only_down due to my change in the config, but "mappingMode" is at only_up. When closed they go up and not down as set. Any ideas? I'm on firmware 2.0 on my Blind Tilts.

**Comment by AndreasVerhoeven** [comment]
> @AndreasVerhoeven, took what you had so far and released it in v2.5.0. We can make improvements of that. Thanks!
> 
> > * the `moving` is not incorrectly present in the API response, resulting in the state not being tracked properly in the plugin. I've been trying to come up with ways around it, but nothing super successful for now
>
> Do you have Curtains? if not look over the Curtain file. I have `set_min` & `set_max` these are used to Set the Minimum Open State (Sets the minimum percentage before needed to set Curtain to Open) & the Maximum Close State (Sets the maximum percentage before needing to set Curtain to Closed). Could help once it gets to a certain percentage, we just say it is closed. That is already in the BlindTilt file at line 985.

It's more that because of a lack of the `moving` flag, the timer that polls sets the device to STOPPED in homekit and the frequent polling stops working. Seems to be reported by others as well https://github.com/OpenWonderLabs/SwitchBotAPI/issues/175

> 
> > * `down;0` errors out the API, this can probably be worked around by just recognizing this case and sending `down;1` to the API as a workaround.
> 
> works for me.

`down;0` seems to be broken in the API according to https://github.com/OpenWonderLabs/SwitchBotAPI/issues/176, but I see you used `fully closed` instead :)

**Comment by donavanbecker** [comment]
@AndreasVerhoeven I have reopened them. FYI, I don't actually work for SwitchBot, I just maintain this plugin and have some access to the othe repos to help out.

**Comment by AndreasVerhoeven** [comment]
> @AndreasVerhoeven I have reopened them. FYI, I don't actually work for SwitchBot, I just maintain this plugin and have some access to the othe repos to help out.

Sorry, with `fully closed` I mean the API method in v2.5. 2.5.1 used just up/down I see :) I wasn't under the impression you were an employee of switchbot; I appreciate all your work!

**Comment by ryanmbrinton** [comment]
Hey y'all, just wanted to add that I have switchbot tilt blinds, I'm also happy to beta test and get y'all whatever logs you needs, if it'd be helpful!

**Comment by P4Halbig** [comment]
The current beta 9 sees the blinds, sends commands... but fails to make a bluetooth connection or control the blinds. The SB app does work, so I know it's not an issue with the bots per se.

And yes, I would be happy to test any fixes. :D

**Comment by JeremyLaurenson** [comment]
Just got four blinds and am starting work with the plug-in. Looks good and configured for down only and API.

All works awesome.. though status feedback is slow.

**Comment by simonrb2000** [comment]
Sorry, how do I set blinds to close down only? I noticed there are mentions of it and pictures of peoples config files with Mode = .. I don’t have any of that in my config file. Thank you

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/235151445-00ca9801-66bf-48f1-881d-86500cc4c911.png)

You will want to set this config, and then in the Home App, if you go into the device, scroll down and you will see a directional bar. Set that bar to either left or right. I believe left is down, and right is up. 

Once you try if I am wrong on the last part please correct me.

**Comment by simonrb2000** [comment]
Thank you for the reply. I don’t have that Mapping Mode anywhere?

**Comment by donavanbecker** [comment]
@simonrb2000 Open a new issue, so I can see your config. You aren't setting anthing in the device settings.
