### ISSUE TITLE
Feature Request: Smaller minimum refresh rate.

### ISSUE THREAD

**Issue by hiyakake** [OpenWonderLabs/homebridge-switchbot#65]
### Problem

The current refresh rate is set to a minimum of 30 seconds. This results in a loss of agility when using motion sensors as triggers for Apple Home.

### Solution

Setting the minimum refresh rate to 9 seconds will make it a little better. According to the SwitchBot Open API specification, the maximum number of requests that can be made in a day is 10000, so this should not be a problem.

**Comment by hiyakake** [comment]
There are better ways to make the motion sensor respond more in real time, such as using Bluetooth, but lowering the refresh rate is an easy temporary solution.

**Comment by donavanbecker** [comment]
thanks for the PR. I will actually be closing it. There is another spot that needs to be changed. It will be in the next update.

**Comment by hiyakake** [comment]
Thank you.
I'm looking forward to the day when it is completed.

**Comment by donavanbecker** [comment]
@hiyakake this is in the current beta, it will be pushed to new release as soon as I fix some issues in it.
