### ISSUE TITLE
Bug: Can't add IR Device to Home App

### ISSUE THREAD

**Issue by ScottGuthart** [OpenWonderLabs/homebridge-switchbot#651]
### Describe The Bug

IR TV device is detected and added to homebridge but doesn't show in Home app. Logs instruct to add it manually using a set up code but the setup code doesn't work.

### To Reproduce

Add new IR TV device to Switchbot

### Expected behavior

Manually entering the code displayed in the config in the home app should add the device.

### Relevant log output

```shell
[1/14/2023, 11:28:59 AM] [SwitchBot] DIY TV: TV Config: {"connectionType":"OpenAPI","external":true}
[1/14/2023, 11:28:59 AM] TV C1B7 is running on port 55015.
[1/14/2023, 11:28:59 AM] Please add [TV C1B7] manually in Home app. Setup Code: 989-40-038
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "***************************",
                "secret": "**************************",
                "notice": "Keep your Token & Secret a secret!"
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

TV IR Device

### Node.js Version

v16.19.0

### NPM Version

8.19.3

### Homebridge Version

v2.0.0-beta.0

### Homebridge Switchbot Plugin Version

v2.4.1-beta.7

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

macOS

**Comment by donavanbecker** [comment]
this is usually a network issue.

**Comment by ScottGuthart** [comment]
You're right, I tried a different router and it works.
