### ISSUE TITLE
Auto-off function for Switchbot Bot?

### ISSUE THREAD

**Issue by macguyincali** [OpenWonderLabs/homebridge-switchbot#655]
### Problem

I run the Bot every morning to activate a coffeemaker for the wife when she disarms the security system from her bedside table. The Bot works great, pushes the button on the coffeemaker and when she gets downstairs, voilá! hot coffee. However, the challenge is that the switch remains in the "On" state. The coffeemaker does turn itself off after a couple of hours.  But the Homekit switch stays on. If I forget to manually switch off the Homekit switch, then the next morning, the Morning Scene assumes the coffeemaker is already on, so it won't push the button to start it. 

### Solution

A solution would be to have a Config preference that tells the homekit switch to automatically turn off after a certain period of time. For the coffeemaker it would be 1 or 2 hours based on how long the coffeemaker actually stays on. The key is to not actually activate the Bot switch itself, just update its status in Homekit. I don't want to click the button on the coffeemaker after it has already made coffee.

### Additional context

Just a side note, I'm really enjoying your plugin and of course, am really thankful that there are people like you out there with the skills and knowledge to do this (it seems crazy complicated to me, the non-coder) and to share it with a wider community. It is truly amazing. Thanks again!

**Comment by donavanbecker** [comment]
have you tried any of the [config](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Configuration) options?

**Comment by macguyincali** [comment]
The allow press configuration seems like it might be useful. I'm not exactly sure how to enable that.  Am I supposed to insert that code somewhere?  Is there a certain syntax I'm supposed to use? I've added a device (using the device ID) and these config options aren't visible. And there isn't a field for me to enter them. I'm probably missing something super obvious as a non-coder. Apologies for my ignorance.

**Comment by donavanbecker** [comment]
add the deviceID and select Bot, then config options will appear.
<img width="737" alt="Screenshot 2023-01-28 at 11 35 41 PM" src="https://user-images.githubusercontent.com/9875439/215307205-a89b75ea-d3c8-4c51-b7c8-38768ae94ebe.png">

**Comment by macguyincali** [comment]
Ah, ok. That totally makes sense. I was confused by the various Device settings. Thought the device was already added and worried about creating an additional instance. I'm a little slow on the uptake, obviously. Thanks. This does the trick.

**Comment by donavanbecker** [comment]
Awesome
