### ISSUE TITLE
Bug: API Request Failed 

### ISSUE THREAD

**Issue by lawiltshire** [OpenWonderLabs/homebridge-switchbot#665]
### Describe The Bug

When trying to open or close blinds in HomeKit app. Doesn’t respond. Homebridge logs show error

### To Reproduce

Controlling blinds in HomeKit 

### Expected behavior

Open or close blinds

### Relevant log output

```shell
API Request: TypeError: Cannot read properties of undefined (reading 'map'),
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "token": "xxxxxxxx",
                "secret": "xxxxxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "refreshRate": 10
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

Switchbot tilt blinds 

### Node.js Version

14.7.6

### NPM Version

7.22.0

### Homebridge Version

1.3.4

### Homebridge Switchbot Plugin Version

2.5.1

### Homebridge Config UI X Plugin Version

4.50.2

### Operating System

Raspian pi

**Comment by lawiltshire** [comment]
I’m not a pro with homebridge but noticed the link to say report bug so I have tried my best to provide all the info I can. Sorry if I have missed anything

**Comment by donavanbecker** [comment]
I got this to recently. Might be something ok SwitchBot side or you reaches your daily refresh limit.

**Comment by lawiltshire** [comment]
Hey, I contacted Switchbot support and they have upped the refresh limit 

“Please kindly notice the amount of API calls per day is limited to 10000 times now.”

**Comment by DJay-X** [comment]
Same problem here. No device is responding via homebride anymore. 🫤
`[4.2.2023, 18:16:20] [SwitchBot] API Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug`

SwitchBot API Status is showing “Operational”. 🤷‍♂️
https://status.switch-bot.com

However, in the SwitchBot App there is an error in the option for developers, showing “Failed to load, please try again later”.
Usually, my token is showing up there. 

![Samstag, 04 Feb  2023 18:35:34](https://user-images.githubusercontent.com/3874239/216781561-905d1e04-a6f1-4d1a-8442-dba9694e7305.png)

**Comment by lawiltshire** [comment]
I thought mine was fixed but mine does it every day around about midday and then resolves after midnight Thanks LukeOn 4 Feb 2023, at 17:21, DJay ***@***.***> wrote:﻿
Same problem here. No device is responding via homebride anymore. 🫤
[4.2.2023, 18:16:20] [SwitchBot] API Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug

**Comment by donavanbecker** [comment]
I am experiencing this as well. This has to be a SwitchBot API issue

**Comment by FlorinFrance** [comment]
same here

**Comment by GConger66** [comment]
Im getting this as well...I have tried everything removed all devices from switchbot app, removed from Hoobs, reinstalled everything same error...I do have the correct token

**Comment by donavanbecker** [comment]
> Im getting this as well...I have tried everything removed all devices from switchbot app, removed from Hoobs, reinstalled everything same error...I do have the correct token

This plugin hasn't been designed for HOOBs, so I would recommend switching to Homebridge.

**Comment by GConger66** [comment]
> > Im getting this as well...I have tried everything removed all devices from switchbot app, removed from Hoobs, reinstalled everything same error...I do have the correct token
> 
> This plugin hasn't been designed for HOOBs, so I would recommend switching to Homebridge.

agreed! seems to be working with homebridge no problem

**Comment by GConger66** [comment]
can you please reopen this because of course now the same issue is happening in homebridge...exact same api error in homebridge. Any fixes?
