### ISSUE TITLE
Feature Request: Air conditioner temperature setting and room temperature display

### ISSUE THREAD

**Issue by taikun114** [OpenWonderLabs/homebridge-switchbot#668]
### Problem

The room temperature display of the air conditioner shows the previous set temperature (temperature 1 in the image).

### Solution

I would like to have a setting for the room temperature display of the air conditioner (temperature 1 in the image) to be able to display the temperature of the SwitchBot Meter (or the SwitchBot Hub 2 to be released) that is registered in the plug-in.

### Alternatives

I would like the air conditioner to display the same value as the set temperature (temperature 2 in the image) each time the temperature setting is changed.

### Additional context

When I ask Siri for the current room temperature, it returns a different temperature (temperature 1 in the image) from the actual room temperature, and when I look at the room temperature display, it shows the temperature set by the air conditioner one set earlier as the room temperature.
![スクリーンショット 2023-01-31 12 54 22](https://user-images.githubusercontent.com/98800458/215661501-1b69d7bd-712b-4967-99a0-c1b86a3692c5.png)
![スクリーンショット 2023-01-31 12 53 57](https://user-images.githubusercontent.com/98800458/215661526-9a20cc04-d190-4787-92d0-f1bdb52a818d.png)

**Comment by donavanbecker** [comment]
I don't plan on supporting this, but would be open to a pull request if brought forward.

**Comment by taikun114** [comment]
I see.

Unfortunately, it seems difficult for me as I have no knowledge or skills in coding.

Thank you very much.
