### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by ThisWill1992** [OpenWonderLabs/homebridge-switchbot#680]
### Describe Your Problem

Switchbot devices not receiving API calls

### Relevant log output

```shell
[SwitchBot] API Req uest: TypeError: Cannot read properties of undefined (reading
'map'), Submit Bugs He
re: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxx",
                "secret": "xxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "F5AB8AA58AF8",
                        "configDeviceName": "Water Heater",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE/OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true
                        },
                        "logging": "debug"
                    }
                ]
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

Switchbot all

### Node.js Version

V18.14.2

### NPM Version

?

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

Latest

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
You have used up your daily refresh limit.

**Comment by ThisWill1992** [comment]
Ok understood - so I’m polling too often? How can I update how many times I’m refreshing? I’ve not changed any settings for months.

**Comment by donavanbecker** [comment]
You can set a per device refresh rate

**Comment by donavanbecker** [comment]
Set some that don't need to be refreshed as much higher, and then ones that need to be refresh more, lower.

**Comment by ThisWill1992** [comment]
I’ve just realised that, before earlier, one was set to 5 seconds. That’s probably what caused it. I didn’t realise there was a limit; thanks for helping me identify the problem.

**Comment by ThisWill1992** [comment]
At what point is the restriction lifted exactly, as I am nearly 24 hours in with no API. Thanks.
