### ISSUE TITLE
Bug: 1% Open

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#688]
### Describe The Bug

Despite multiple attempts at recalibrating the SwitchBot Curtain, the Home app still shows 1% when instead the SwitchBot app shows 100%

### To Reproduce

Try closing a curtain from both app to see the difference

### Expected behavior

Home app should not show 1%

### Relevant log output

```shell
No problematic log outputs
```

### Config for homebridge-switchbot

```shell
N/A, shouldn’t matter
```

### Device & Model

SwitchBot Curtain (current model available on Amazon)

### Node.js Version

18.14.2

### NPM Version

Latest

### Homebridge Version

1.6.0

### Homebridge Switchbot Plugin Version

Latest

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
You will need to use min/max closer/open config setting.

**Comment by FranciRoosters** [comment]
![IMG_0315](https://user-images.githubusercontent.com/81822833/231957963-5d404162-a142-4d01-b454-12cc9604ab30.jpeg)
The setting is already in use as you can see from the screenshot below. On 13 Apr 2023, at 14:52, Donavan Becker ***@***.***> wrote:﻿
You will need to use min/max closer/open config setting.

**Comment by donavanbecker** [comment]
@FranciRoosters You need to set them even more so that it picks it up. So like 5 and 95, or 10 and 90.

**Comment by FranciRoosters** [comment]
Ok, I’ll give this a go, but I’m confused: how would setting different numbers than 1 and 100 potentially fix this? Thanks!On 14 Apr 2023, at 13:07, Donavan Becker ***@***.***> wrote:﻿
@FranciRoosters You need to set them even more so that it picks it up. So like 5 and 95, or 10 and 90.

**Comment by donavanbecker** [comment]
Because it looks at any number below let’s say 10 or higher then 90, and if it falls with that, it tells the plugin to tell HomeKit the curtains are closed.

**Comment by FranciRoosters** [comment]
Setting 5 and 95 worked a charm. You can close the issue. Thanks!
