### ISSUE TITLE
Bug: Lux sensor isn’t hidden on the Home app despite being flagged on HomeBridge

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#689]
### Describe The Bug

I can still see the lid sensor being shown in a room’s top overview despite having flagged the “Hide lux sensor” on HomeBridge

### To Reproduce

Enable “hide Lux sensor” on HomeBridge and see if it appears on the top overview of a room in the home app. 

### Expected behavior

Lux sensor should let be displayed on the home app if disabled on HomeBridge.

### Relevant log output

```shell
N/A, shouldn’t matter
```

### Config for homebridge-switchbot

```shell
See image below.
```

### Screenshots

![B90231DB-7EBE-4395-BBF5-92D2C8DB1EB6](https://user-images.githubusercontent.com/81822833/223707957-33cb08d9-1ed2-49ea-b89a-8e2f6922ecc5.jpeg)

### Device & Model

Latest SwitchBot Curtain available on Amazon 

### Node.js Version

18.14.2

### NPM Version

Latest

### Homebridge Version

1.6.0

### Homebridge Switchbot Plugin Version

Latest

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Are you using HOOBs and can you post your config?

**Comment by donavanbecker** [comment]
If running HOOBS, switch to Homebridge.
