### ISSUE TITLE
Support Request:When fully closed curtains reporting as 2% open? 

### ISSUE THREAD

**Issue by OneScuzzie2k** [OpenWonderLabs/homebridge-switchbot#692]
### Describe Your Problem

When I close the Curtain bot it says at 2% open on Homekit either with API or BLE

### Device & Model

Switchbot Hub and Curtains

### Node.js Version

18.15.0

### NPM Version

1.9.2-20

### Homebridge Version

v1.6.0 

### Homebridge SwitchBot Plugin Version

v2.5.2 

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
There are configs that you can set for min and max

**Comment by donavanbecker** [comment]
[Configuration Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Configuration)

* `curtain`: Object that holds Curtain device config options
        * `set_min`: sets the level of what the plugin will look at to set the curtain to closed.
        * `set_max`: sets the level of what the plugin will look at to set the curtain to open.
