### ISSUE TITLE
Feature Request: Hub 2 integration

### ISSUE THREAD

**Issue by DJay-X** [OpenWonderLabs/homebridge-switchbot#695]
### Problem

Only as a preparation and desire to be able to use this plugin with the Hub 2 in the very near future. :)

### Solution

Update Plugin to use with SwitchBot Hub 2

**Comment by alvst** [comment]
I'm waiting on approval from Donavan to get started on working on this but in the mean time, feel free to use [this plugin](https://github.com/alvst/Homebridge-Switchbot-Hub-2) I made yesterday which allows you to display the temperature and humidity from Hub 2's in the Home app. Also, you can use it along side this plugin. Hopefully we'll have a beta version of this plugin later this week/early next week that adds this functionality to the main plugin.

**Comment by donavanbecker** [comment]
@alvst Be my guest

**Comment by donavanbecker** [comment]
v2.6.0 added the Temperature and Humidity Sensor thanks to @alvst
