### ISSUE TITLE
Add Contact and Motion Sensor Support

### ISSUE THREAD

**Issue by DJay-X** [OpenWonderLabs/homebridge-switchbot#7]
@donavanbecker Regarding https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/issues/225 

**Is your feature request related to a problem? Please describe.**

"deprecated" homebridge-switchbot-openapi uninstalled with Homebridge UI, the config kept like it was, install this new plugin homebridge-switchbot v0.1.0 and no changes to the config. Restart. It kept all my existing devices (bots/curtains) and they worked as expected and as before. Also the new contact sensor and motion sensor was added.

**Describe the solution you'd like**

However, both new sensors are not changing status. No motion, no open/close with the contact sensor.
The Contact Sensor is also not showing up as a contact sensor type. Instead it's a motions sensor at the moment. 

```
{
            "name": "SwitchBotAPI",
            "credentials": {
                "openToken": "e11c70b30ccca4aa27cfa102646ef0c1d4f9254ff5cb3dbb9ae76a5a2c8c6b4da88e1d2ce5e65e2cf67106b03977eb63",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "bot": {
                    "device_press": [
                        "xxC09xxDxx09",
                        "xx82Fxx6xxFC",
                        "xx368xxBxxAA",
                        "xx6F2xx0xx5A",
                        "xx35xxC2xx70"
                    ],
                    "switch": true
                },
                "curtain": {
                    "refreshRate": 5
                }
            },
            "platform": "SwitchBot"
        },
```

<img width="1138" alt="Napkin 11 09 21, 11 01 24 AM" src="https://user-images.githubusercontent.com/3874239/132942557-a82f9e19-fd71-464c-b1db-f9eafc0e4be3.png">

**Comment by donavanbecker** [comment]
@DJay-X v0.1.1 should fix this, but you will have to remove the contact sensor from cache. Also remember this is all based off your refreshRate so until I add the BLE Function this will not work as well since it is relying on the API refresh.

**Comment by DJay-X** [comment]
Thanks. v0.1.1 fixed the contact sensor typ. However there is no status change at all. Not from the motion sensor, nor contact sensor. Not even after endless seconds and one minute. 
Both sensors are connected to the hub and showing the status instantly in the SwitchBot App.
In Home/Eve App there is no status change at all.

**Comment by DJay-X** [comment]
I just noticed in the log.. for example Contact Sensor
"openState":"open"} but in Home/Eve App it is and was always closed.
With Motion Sensor the was no last movement logged in Eve App.

```
[11.9.2021, 15:58:00] [SwitchBotAPI] Motion Motion Sensor F7 Motion Sensor refreshStatus - {"statusCode":100,"body":{"deviceId":"xx3CD7xx82xx","deviceType":"Motion Sensor","hubDeviceId":"xxEFxxE89Cxx","moveDetected":false,"brightness":"bright"},"message":"success"}
[11.9.2021, 15:58:00] [SwitchBotAPI] Contact Contact Sensor E9 Contact Sensor refreshStatus - {"statusCode":100,"body":{"deviceId":"xx903xx923xx","deviceType":"Contact Sensor","hubDeviceId":"xxEFxxE89Cxx","moveDetected":false,"brightness":"bright","openState":"open"},"message":"success"}
```

```
[11.9.2021, 16:14:40] [SwitchBotAPI] Motion Motion Sensor F7 Motion Sensor refreshStatus - {"statusCode":100,"body":{"deviceId":"xx3CD7xx82xx","deviceType":"Motion Sensor","hubDeviceId":"xxEFxxE89Cxx","moveDetected":false,"brightness":"bright"},"message":"success"}
[11.9.2021, 16:14:40] [SwitchBotAPI] Contact Contact Sensor E9 Contact Sensor refreshStatus - {"statusCode":100,"body":{"deviceId":"xx903xx923xx","deviceType":"Contact Sensor","hubDeviceId":"xxEFxxE89Cxx","moveDetected":false,"brightness":"bright","openState":"timeOutNotClose"},"message":"success"}
```

**Comment by yjeanrenaud** [comment]
same here for the Contact Sensor. The Motion Sensor eventually gets triggered when I set the polling interval down to 120

**Comment by DJay-X** [comment]
@donavanbecker Any News? Anything I/we can help?

**Comment by donavanbecker** [comment]
Time to work on it... ha

**Comment by DJay-X** [comment]
Hey @donavanbecker I hope you are well.
Because of the situation we want to write an article about the new SwitchBot sensor on [SmartApfel.de](https://smartapfel.de) an 📸[@SmartApfel.de](https://www.instagram.com/smartapfel.de/) but only when they support HomeKit via Homebridge, can you estimate on when this will work or if it's even possible in the near future. We would make the publication of the article dependent on this.
Thanks in advance. 🙏

**Comment by donavanbecker** [comment]
@DJay-X Hoping to work on it this coming week

**Comment by donavanbecker** [comment]
@DJay-X can you try the latest beta?

**Comment by DJay-X** [comment]
Thanks @donavanbecker 
Unfortunately with homebridge-switchbot@0.1.2-beta.12 no success.
The contact and motion sensor are showing up but no status change at all.
I also removed them from the cash and restarted Homebridge but no change.
Also in Eve App the two sensors are permanently marked as not reachable.

-D Log attached


[homebridge.log-2.txt](https://github.com/OpenWonderLabs/homebridge-switchbot/files/7272855/homebridge.log-2.txt)

<img width="794" alt="xBildschirmfoto 2021-10-03 um 08 43 Kopie" src="https://user-images.githubusercontent.com/3874239/135743526-3e5f7653-16ca-4545-879e-84b1c44e51ca.png">

<img width="514" alt="Napkin 03 10 21, 9 03 12 AM" src="https://user-images.githubusercontent.com/3874239/135743762-02c0366b-a07f-438f-b62e-4c8ea5aa7470.png">



```
        {
            "name": "SwitchBotAPI",
            "credentials": {
                "openToken": "XXXXXXXXXXX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "bot": {
                    "device_press": [
                        "XXXXXXXXXXX",
                        "XXXXXXXXXXX",
                        "XXXXXXXXXXX",
                        "XXXXXXXXXXX",
                        "XXXXXXXXXXX"
                    ],
                    "switch": true
                },
                "curtain": {
                    "refreshRate": 5
                }
            },
            "platform": "SwitchBot"
        },

```

**Comment by donavanbecker** [comment]
@DJay-X You haven't even let the plugin refresh status of the motion or contact sensor. And looking at the logs the API says `moveDetected: false` so it will not change HomeKit either then.
You can up your refreshRate since SwitchBot have updated the daily refresh amount, and give it like 5 mins and as long as there is motion or contact sensor is open at that time you will have an update.

**Comment by DJay-X** [comment]
I didn't use the Config UI. So now it's added
```
"options": {
                "refreshRate": 300,
```

However, the contact sensor it not changing any status after 3 Min. open.
The Motion sensor  is detecting motion and showing it after 3 Minutes in Home App.

As I understand with the Motion sensor, this is all what you get out of the API. Never instant reaction, right?

**Comment by donavanbecker** [comment]
@DJay-X Yeah I have to look at the contact sensor again.

**Comment by donavanbecker** [comment]
@DJay-X, just pushed an update for contact sensors, can you try the next beta?

**Comment by DJay-X** [comment]
homebridge-switchbot@0.1.2-beta.13 and beta.14

Contact Sensor still not changing any status.

**Comment by DJay-X** [comment]
@donavanbecker 
Unfortunately even with homebridge-switchbot@0.1.2-beta.16 the contact sensor is still not showing any status change at all in Home. SwitchBot App is showing the change instantly via Hub/Cloud. 

Motion Sensor seems to work okay and is changing status in the range of refreshRate 300.
However there is a info in the log. 
`[5.10.2021, 08:11:23] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Motion Detected': Characteristic not in required or optional characteristic section for service . Adding anyway.. See https://git.io/JtMGR for more info.`

Thanks again for the ongoing investigation. 
Unfortunately I'm only able to test today. Next chance is next week. 
But happy to help to get a final 0.1.2 :)

**Comment by DJay-X** [comment]
With beta.18 contact sensor is now showing closed all the time. Before it was always open. 
Motion sensor on the contact sensor IS detecting motion.

**Comment by DJay-X** [comment]
@donavanbecker /homebridge-switchbot v0.1.2-beta.26 
I had to remove all SwitchBot devices from cache. 
Motion from Motion Sensor and Contact sensor is detected.
Contact Sensor open/close still not working for me an no status change at all. Contact sensor is set in SwitchBot App to Installation "Door". But it doesn't make any change when set to Window or Others.
Is there anything I can do to help going to a final version? Please of course let me know.

**Comment by donavanbecker** [comment]
@DJay-X From what I am aware of there is nothing in the api that cares about window/door/etc, but I will check again.

Yes to fix another issue I had to change the way the uuid is created, which requires removing accessories from cache.

**Comment by DJay-X** [comment]
No worries. This is a beta so I expected to remove all my SwitchBot devices from HomeKit from time to time. 
I take the hassle if it helps to bring the plugin to a final version and the contact sensor will show the status. 
I guess others have the same problem with the contact sensor too, right?

**Comment by DJay-X** [comment]
@donavanbecker For whatever reason now with v0.1.2-beta.28 the curtains are not working open/close anymore. This was never a problem before. 

[14.10.2021, 18:39:57] [SwitchBotAPI] Total SwitchBot Devices Found: 12
[14.10.2021, 18:39:57] [SwitchBotAPI] Total IR Devices Found: 0
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Vorhang links Curtain DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: SwitchBot Balkon klein Bot DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Bot 02 Bot DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Motion Sensor F7 Motion Sensor DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Bot 70 Bot DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Contact Sensor E9 Contact Sensor DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Kfz Aufzug Bot DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: SwitchBot Balkon groß Bot DeviceID: xxxx
[14.10.2021, 18:39:57] [SwitchBotAPI] Restoring existing accessory from cache: Vorhang rechts Curtain DeviceID: xxxx

Also no change with contact sensor.

**Comment by donavanbecker** [comment]
I will have to look over that. Sorry have been busy lately

**Comment by DJay-X** [comment]
Thanks..
beta.30 Curtains seems to work again. No Idea what or if it really was a problem with previous beta.  I will have an eye on it.

Anyway, Contact sensor is still not sowing any changes.

**Comment by donavanbecker** [comment]
@DJay-X okay Beta: 

[![npm version](https://badgen.net/npm/v/@switchbot/homebridge-switchbot/beta)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

should be working at least I can confirm for myself that it is working. when I opened my window, I have the sensor on, it said it was open and vis versa.

**Comment by DJay-X** [comment]
Great news and I can confirm this version also now works for me. Both motion and contact sensor are changing status after about three minutes.
I think this could be the final version. 😉

Regarding the practicality of the motion sensor only triggering after this long time there is no other way to show a status change faster, right? It's due to the refresh of the API, correct?

Thanks for your work and patience.

**Comment by donavanbecker** [comment]
@DJay-X, once we get BLE support added into the plug. Then you would want to potentially set them to use BLE. Till then, I would update your refreshRate. They updated the daily refresh rate from 1000 to [10000](https://github.com/OpenWonderLabs/SwitchBotAPI#request-limit).

**Comment by donavanbecker** [comment]
@DJay-X, okay the latest beta should support BLE for motion sensors. this is a huge change, you will have to change your config. so if you have anything in the options portion of the config you will need to remove it and reset your config. 

I have created a device config section where any custom configs that you would like to apply to a device you must set for each device.

**Comment by DJay-X** [comment]
@donavanbecker Great news. Unfortunately I can't test this time. I hope someone else can help with BLE.
Are you going to make v0.1.2-beta.40 productive and the last final version? This is still 1.1.
Sorry again I can't help currently with BLE

**Comment by donavanbecker** [comment]
@DJay-X No I won't release a new version till v1.0.0. Which I hope to have out soon.

**Comment by donavanbecker** [comment]
v.1.0.0 has been released.
