### ISSUE TITLE
Bug: API connection fault

### ISSUE THREAD

**Issue by ssasuki** [OpenWonderLabs/homebridge-switchbot#704]
### Describe the Bug

Dear staffs,

This is Sho. I'm using homebridge-switchbot systems. when I connected it, it shows some message below:
API Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug

I uninstalled it and install it again but didn't work well.
I also restarted the Homebridge but nothing changed.

Thank you for handling this bug.

Best regards,
Sho

### To Reproduce

just installed the switchbot plugin.

### Expected Behavior

connect to SwitchBot API successfully.

### Relevant Log Output

```shell
[29/03/2023, 17:28:10] [SwitchBot] API Request: TypeError: Cannot read properties of undefined (reading 'map'), Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
"platforms": [
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "XXXXXXX",
                "secret": "XXXXXX",
                "notice": "Keep your Token & Secret a secret!"
            },
            "platform": "SwitchBot"
        }
    ]
```

### Device and Model

Raspberry pi zero W

### Node.js Version

v18.15.0

### NPM Version

v9.5.0

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v2.5.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by FlorinFrance** [comment]
ME TOO

**Comment by donavanbecker** [comment]
Please try v2.6.0

**Comment by FlorinFrance** [comment]
> Please try v2.6.0

💪
