### ISSUE TITLE
Feature Request: Lock BLE support

### ISSUE THREAD

**Issue by CappyD** [OpenWonderLabs/homebridge-switchbot#712]
### Describe Your Problem

The notes for release 2.3.0 mention BLE support for the Switchbot Lock, but the Supported Devices list in Readme indicates that BLE is not supported. Could you clarify?

### Device & Model

Lock

### Node.js Version

v16.14.2

### NPM Version

v8.5.0

### Homebridge Version

v1.4.0

### Homebridge SwitchBot Plugin Version

v2.5.3

### Operating System

MacOS 13.2.1

**Comment by donavanbecker** [comment]
BLE API would need to support this.
