### ISSUE TITLE
Commands not working with v2.6.0 & v2.6.1

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/homebridge-switchbot#721]
### Describe the Bug

Not sending commands 

### To Reproduce

Send a command to change 

### Expected Behavior

Send command successfully

### Relevant Log Output

```shell
N/A
```

### Config for homebridge-switchbot

```shell
N/A
```

### Device and Model

All

### Node.js Version

18.16.0

### NPM Version

9.8.6

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v2.6.0

### Homebridge Config UI X Plugin Version

v4.52.0

### Operating System

macOS

**Comment by ThisWill1992** [comment]
Also having exactly the same problems since this morning. Commands are not sending, but HomeBridge does get status updates if devices are changed outside of Home

**Comment by domre77** [comment]
Same here. No commands getting through for any Switchbot devices (confirmed in hub log).

**Comment by Z1mDMan** [comment]
I am also seeing this issue. Roll back to 2.5.3 resolved it for me.

**Comment by donavanbecker** [comment]
Yes, known issue. Will try to resolve soon.

**Comment by nyjklein** [comment]
Just a note: same here and on 2.6.1.

**Comment by donavanbecker** [comment]
Can you all try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.6.2-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

## Confirmed Fixed SwitchBot Device Types:
- [x] Curtains
- [x] Bot
- [ ] Ceiling Lights
- [x] Blind Tilt
- [x] Color Bulbs
- [x] Strip Lights
- [x] Lock
- [ ] Plug
- [ ] Robot Vacuum

## Confirmed Fixed IR Device Types:
- [ ] TV
- [ ] Projector (Displayed as TV)
- [ ] Set Top Box (Displayed as Set Top Box)
- [ ] DVD (Displayed as Set Top Box)
- [ ] Streamer (Displayed as Streaming Stick)
- [ ] Speaker (Displayed as Speaker)
- [ ] Fans
- [ ] Lights
- [ ] Air Purifiers
- [ ] Air Conditioners
- [ ] Cameras
- [ ] Vacuum Cleaners
- [ ] Water Heaters
- [ ] Others

**Comment by nyjklein** [comment]
2.6.2-beta.0 fixes the issue for me.

Thanks!

**Comment by donavanbecker** [comment]
Once we get a few more confirms, I will post a new version.

@nyjklein What devices can you confirm?

**Comment by nyjklein** [comment]
V2 curtainsSent from my iPhoneOn Apr 16, 2023, at 4:46 PM, Donavan Becker ***@***.***> wrote:﻿
Once a get a few more confirms, I will post a new version.
@nyjklein What devices can you confirm?

**Comment by jafarapple** [comment]
The beta is also working for me

**Comment by donavanbecker** [comment]
@jafarapple, what devices can you confirm?

**Comment by jafarapple** [comment]
Only the lock from switchbot I’m using for this pluginJafar Ibrahim. 00971585918340On Apr 17, 2023, at 3:02 AM, Donavan Becker ***@***.***> wrote:﻿
@jafarapple, what devices can you confirm?

**Comment by Z1mDMan** [comment]
Confirmed Beta resolved my IR issue (Fan)

**Comment by JeremyLaurenson** [comment]
Confirmed fixed here. My tilts were API controlled but also didnt work.

**Comment by JeremyLaurenson** [comment]
Hey @donavanbecker   do you want to maybe set up a group of us to gate any non-beta release. Presumably if we have 10 folks weigh in that all is clear for a specific build we could help. I don't do *every* beta but Id totally test release candidates.

**Comment by donavanbecker** [comment]
@JeremyLaurenson, going forward on bigger releases, I can open an issue saying something like "Beta 2.7.0 Testing". That work?

**Comment by donavanbecker** [comment]
I will be keeping this issue open until at least 50% are confirmed working.

**Comment by donavanbecker** [comment]
v2.6.2 has been released.

**Comment by JeremyLaurenson** [comment]
> @JeremyLaurenson, going forward on bigger releases, I can open an issue saying something like "Beta 2.7.0 Testing". That work?

I dont know that I would get a notification. Maybe a discussion that you add to, that we can subscribe to?

**Comment by nyjklein** [comment]
Updated to 2.6.2. All is still fine.

**Comment by donavanbecker** [comment]
> > @JeremyLaurenson, going forward on bigger releases, I can open an issue saying something like "Beta 2.7.0 Testing". That work?
> 
> 
> 
> I dont know that I would get a notification. Maybe a discussion that you add to, that we can subscribe to?
> 
> 

I can do that, I will start a new one called Beta Testing.

**Comment by donavanbecker** [comment]
@JeremyLaurenson Here you go: https://github.com/OpenWonderLabs/homebridge-switchbot/discussions/726

**Comment by domre77** [comment]
Installed and working again. Thanks for the speed fix.

**Comment by donavanbecker** [comment]
> Installed and working again. Thanks for the speed fix.

@domre77 What devices can you confirm?

**Comment by domre77** [comment]
My 4 bots.

(1 is playing up intermittently, but always has with this plugin, which I’ve never been able to diagnose).

**Comment by salemsayed** [comment]
Lock still not working on latest version 

EDIT: rolled back to 2.5.3 and it’s still not working, not sure what’s the issue here. Pretty sure it was all working before 2.6.0

EDIT #2: 2.6.2 is definitely working for the lock, the problem was on my side, apologies

**Comment by JeremyLaurenson** [comment]
> > > @JeremyLaurenson, going forward on bigger releases, I can open an issue saying something like "Beta 2.7.0 Testing". That work?
> > 
> > 
> > I dont know that I would get a notification. Maybe a discussion that you add to, that we can subscribe to?
> 
> I can do that, I will start a new one called Beta Testing.

Lets have you post to that discussion when you have a "release candidate" beta build out.

**Comment by ievolk** [comment]
I am now having this issue while on 2.6.2. Mine are light strips and push bots. Rolled back to previous versions and not working. Reinstalled 2.6.2 still not working.
