### ISSUE TITLE
Feature Request: Version that can install without BLE support

### ISSUE THREAD

**Issue by fluffy-critter** [OpenWonderLabs/homebridge-switchbot#722]
### Problem

I run Homebridge on my Synology NAS, and only use the OpenAPI connection, as my NAS isn't within Bluetooth range of my Switchbot devices anyway. However, I am unable to upgrade the installed version of the Homebridge plugin due to the issues described in issue #713, and even attempting the various workaround solutions as described in that thread fails. However, the dependency issue seems to only be relevant for BLE connections and not OpenAPI ones.

### Solution

Splitting the plugin into two separate versions, hoembridge-switchbot-ble and homebridge-switchbot-openapi, which only pull in the dependencies necessary for each respective thing. The actual code could probably be kept in something like homebridge-switchbot-common and then each of those separate plugins would simply depend on -common and the respective support libraries.

**Comment by donavanbecker** [comment]
As stated in that issue, this isn't a plug-in issue. You should open and issue on noble or hci-bluetooth.

Also separating would cause not work and would only be a work around not a solution.

**Comment by marvinjoa** [comment]
@fluffy-critter To be fair, you reference a thread where a solution was posted.
https://github.com/OpenWonderLabs/homebridge-switchbot/issues/713#issuecomment-1510022812

**Comment by donavanbecker** [comment]
Yes, which the issue has nothing to do with the plugin but the dependencies.

**Comment by marvinjoa** [comment]
> Yes, which the issue has nothing to do with the plugin but the dependencies.

This was directed to fluffy not to you :)

**Comment by fluffy-critter** [comment]
> @fluffy-critter To be fair, you reference a thread where a solution was posted. [#713 (comment)](https://github.com/OpenWonderLabs/homebridge-switchbot/issues/713#issuecomment-1510022812)

That's the solution that I tried, and which failed to work.

**Comment by fluffy-critter** [comment]
> As stated in that issue, this isn't a plug-in issue. You should open and issue on noble or hci-bluetooth.
> 
> Also separating would cause not work and would only be a work around not a solution.

Given that the plugin has two modes of operation (BLE and OpenAPI), why would this be a workaround and not a solution? Shouldn't there be separate versions just to avoid pulling in extraneous dependencies that aren't needed by one config path vs. the other? This is a pretty common solution in Linux distributions, for example having a service that separates out its dependencies based on which backing database is being used.

**Comment by donavanbecker** [comment]
@fluffy-critter once again, we will not be creating two different versions.

If you can find a fix that will resolve this issue for you, like through a script or something that can be added to the plugin. Then I will accept that PR.

BLE support has been part of this plugin since version 1.0.0

**Comment by fluffy-critter** [comment]
Okay, thanks. BLE support hasn't been an issue on Synology until very recently so I wasn't aware that it was even part of the plugin, and unfortunately the hci-bluetooth and noble people are themselves passing the buck on their own packaging issues. I'll try to find some other workaround. Unfortunately I don't know a lot about the nodejs/npm ecosystem to know if there's any way of doing a local override for a package or the like.
