### ISSUE TITLE
Bug: [DEBUG] Failed to Discover Devices, Error: ConnectTimeoutError: Connect Timeout Error

### ISSUE THREAD

**Issue by ievolk** [OpenWonderLabs/homebridge-switchbot#730]
### Describe the Bug

Im getting the same issue that was reported where 2.6.2 was supposed to fix. The state of the device is present in HomeKit, but it doesn't push the command.

When I run debug logging this is what shows up:

[DEBUG] Failed to Discover Devices, Error: ConnectTimeoutError: Connect Timeout Error

### To Reproduce

This log happens every time I restart home bridge. After, no log items from the plugin.

### Expected Behavior

Should push command.

### Relevant Log Output

```shell
[DEBUG] Failed to Discover Devices, Error: ConnectTimeoutError: Connect Timeout Error
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "1d2197b3f7b49092e062fc2cdf9277dbbc6cb493eb2be7089b73e3ccc2647118629533ba2c1c3af1ed44082c6c5c239e",
                "secret": "28aec30d82ce816465a9792eb56ef067",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "C2D555FE231C",
                        "configDeviceName": "Bedroom TV Close",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true
                        },
                        "logging": "standard"
                    },
                    {
                        "deviceId": "DEC9025BA821",
                        "configDeviceName": "Bedroom TV Open",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true
                        },
                        "logging": "standard"
                    }
                ],
                "refreshRate": 60,
                "pushRate": 2,
                "logging": "debug"
            },
```

### Device and Model

Lightstrips and Bots

### Node.js Version

v18.16.0

### NPM Version

na

### Homebridge Version

1.6.0

### Homebridge Switchbot Plugin Version

2.6.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspberry Pi

**Comment by donavanbecker** [comment]
This isn't the same error. This is a connection timeout error.

Do you have more logs by chance?

**Comment by ievolk** [comment]
> This isn't the same error. This is a connection timeout error.
> 
> Do you have more logs by chance?

Here is all the logs I get for the plugin when I restart homebridge:

[19/04/2023
07:33:10] [SwitchBot] Initializing SwitchBot platform...
[19/04/2023
[19/04/2023,
07:33:10] [SwitchBot] [DEBUG] Using Config Logging: debug
[19/04/2023,
07:33:10] [SwitchBot] [DEBUG] Finished initializing platform:
07:33:10] [SwitchBot] Platform Config: {"logging": "debug" , "refreshRate": 500 , "pushRate" : 2}
[19/04/2023,
07:33:10] [SwitchBot] [DEBUG] Config OK
[19/04/2023, 07:33:10] Loading 1 accessories...
[19/04/2023
[19/04/2023
07:33:10] [Occupancy] Initializing DummySwitch accessory.
07:33:12] [Occupancy] Setting switch to true
[19/04/2023
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Basement Bench Light
[19/04/2023
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Dining Room Island Light
[19/04/2023
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Bedroom Bench Light
[19/04/2023
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Basement TV Light
[19/04/2023,
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Living Room Bench Light
[19/04/2023,
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Living Room TV Light
[19/04/2023,
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Bedroom TV Close
[19/04/2023,
[19/04/2023,
07:33:12] [SwitchBot] [DEBUG] Loading accessory from cache: Bedroom TV Open
[19/04/2023, 07:33:131 [SwitchBot] [DEBUG] Executed didFinishLaunching callback
Setup Payload:
X-HM://0023X00TW5U17
[19/04/2023,
07:33:291 [SwitchBot] [DEBUG] Failed to Discover Devices, Error Message: "Connect Timeout Error",
Submit Bugs Here: https://tinyurl.com/SwitchBotBug
[19/04/2023, 07:33:291 [SwitchBot] [DEBUG Failed to Discover Devices, Error: ConnectTimeoutError: Connect Tim eout Error


And after that there is never another log for the plugin. But it's the same logs every time I restart. I have tried changing the refreshRate to different values. Last API log on my switchbot app was Monday April 17th at 6:32am MST 'executed successfully' and nothing is pushed since then unless I use the switchbot app. So strange.

**Comment by donavanbecker** [comment]
Can you open an issue on the SwitchBot app, reference this issue.

**Comment by donavanbecker** [comment]
@ievolk were you able to get it to work?

**Comment by ievolk** [comment]
> @ievolk were you able to get it to work?

No, but I uninstalled and reinstalled the plugin and it worked but then had weird phantom old plugins reinstall themselves and then it stopped working again when I uninstalled those so I think I just have a corrupt homebridge pi. Gonna do a fresh install but doesn't seem to be an issue with this plugin specifically.
