### ISSUE TITLE
Bug: unable to update, delete or uninstall

### ISSUE THREAD

**Issue by tim-fin** [OpenWonderLabs/homebridge-switchbot#731]
### Describe the Bug

I've tried to update in my HomeBridge many times over the last several months but keep hitting this same error described below.  I've tried uninstalling, deleting and overinstalling but nothing works.

### To Reproduce

samer error occurs  every time I try to update.  deleting does nothing and uninstall also fails.

### Expected Behavior

I just want to be able to update the app, and if I can't update then let me delete or uninstall it.

### Relevant Log Output

```shell
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g @switchbot/homebridge-switchbot@2.6.2

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/@switchbot/homebridge-switchbot
npm ERR! dest /usr/lib/node_modules/@switchbot/.homebridge-switchbot-BggO5Jhy
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/@switchbot/homebridge-switchbot' -> '/usr/lib/node_modules/@switchbot/.homebridge-switchbot-BggO5Jhy'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-04-22T16_39_13_503Z-debug-0.log

Operation failed. Please review log for details.
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "token_info_here",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }
```

### Device and Model

?

### Node.js Version

18.16.0

### NPM Version

9.5.1

### Homebridge Version

1.6

### Homebridge Switchbot Plugin Version

1.13.0

### Operating System

raspbian

**Comment by bastiengrignon** [comment]
I'm on windows and I'm unable to update to the new version too

**Comment by donavanbecker** [comment]
ssh into the machine and do the following commands:
```
sudo rm -R /usr/lib/node_modules/@switchbot/homebridge-switchbot
sudo rm -R /usr/lib/node_modules/@switchbot/.homebridge-switchbot-BggO5Jhy
```
Then reinstall (do all of this with our restarting homebridge till after you reinstall.

**Comment by donavanbecker** [comment]
> I'm on windows and I'm unable to update to the new version too

@bastiengrignon, Open a new issue, as this is for raspbian and not windows.

**Comment by tim-fin** [comment]
success!  resolving, thanks for the blazingly fast response.
