### ISSUE TITLE
problems installing plugin

### ISSUE THREAD

**Issue by Spy-1** [OpenWonderLabs/homebridge-switchbot#734]
### Describe Your Problem

canot install plugin after new,install of homebridge under docker/synology

### Relevant log output

```shell
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-04-28T13_02_01_093Z-debug-0.log
Failed to rebuild.

Bundled install / update could not complete. Trying regular install / update using npm.

USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save @switchbot/homebridge-switchbot@2.6.2
```

### Device & Model

Synology NAS

### Node.js Version

v16.20.0

### NPM Version

v9.5.1

### Homebridge Version

v1.6.0

### Homebridge SwitchBot Plugin Version

v2.6.2

### Operating System

Docker

**Comment by donavanbecker** [comment]
Check the [Bluetooth Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Bluetooth-Issues).

**Comment by Spy-1** [comment]
This don´t work at all:
`Peter@Diskstation:/volume1/homebridge$ npm install --save @switchbot/homebridge-switchbot@2.6.2
Peter@Diskstation:/volume1/homebridge$ npm install --save @switchbot/homebridge-switchbot@2.6.2
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠼ idealTree:homebridge: sill idealTree buildDeps
I´dont use BLuetooth and all installations befor worked with out installing any bluetooth tools!`

**Comment by Spy-1** [comment]
I am able to install the plugin from first version till v2.5.2 and its working.
as of v2.5.3 it no longer installs and crashes.

**Comment by donavanbecker** [comment]
@Spy-1 were you able to install?

**Comment by Spy-1** [comment]
Yes, i was. Ist was a Problem with the latest Docker Image. von unterwegs gesendetAm 01.05.2023 um 19:46 schrieb Donavan Becker ***@***.***>:﻿
@Spy-1 were you able to install?
