### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by simonrb2000** [OpenWonderLabs/homebridge-switchbot#735]
### Describe Your Problem

No Mapping Options

### Relevant log output

```shell
As discussed on previous closed thread.

I don’t have any mapping options, All blinds are showing up in Homekit.
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "token": "XXXXXX",
                "secret": "XXXX",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "refreshRate": 60,
                "logging": "standard"
            },
            "_bridge": {
                "username": "0X:XX:XX:XX:XX:XX",
                "port": 123456
            },
            "platform": "SwitchBot"
```

### Device & Model

Tilt Blinds

### Node.js Version

v18.13.0

### NPM Version

V

### Homebridge Version

V1.6.0

### Homebridge SwitchBot Plugin Version

v2.6.3-beta.3

### Homebridge Config UI X Plugin Version

 v4.50.2

### Operating System

Bullseye

**Comment by donavanbecker** [comment]
Do you have Homebridge UI?

**Comment by simonrb2000** [comment]
Hey, yes I do.

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/235172518-7bbcc498-a9b5-48ff-8784-c693aad4dec3.png)

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/235172812-af764d12-a816-4d77-836f-34e18f786edf.png)

Type in your deviceID, this can be found on the Devices tab.

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/235173177-195bad9a-f8d9-45be-941c-6a9a7e9301aa.png)

Then you have your config.

**Comment by simonrb2000** [comment]
Ah ok, so that has to be done with every blind that I’d like to change the tilt? I assumed it wasn’t required as all blinds are in HomeKit without doing that.

I’ll get started!

Thank you

Simon

On 28 Apr 2023, at 15:20, Donavan Becker ***@***.***> wrote:

﻿

[image]<https://user-images.githubusercontent.com/9875439/235173177-195bad9a-f8d9-45be-941c-6a9a7e9301aa.png>

Then you have your config.

**Comment by donavanbecker** [comment]
Yes, if you want to change default settings, you need to set these settings.
