### ISSUE TITLE
Feature Request: Deleting Old DIY Devices

### ISSUE THREAD

**Issue by jeanofthedead** [OpenWonderLabs/homebridge-switchbot#736]
### Problem

I am unable to delete old SwitchBot DIY devices that are no longer in the SwitchBot app, but remain in the plug-in Devices list.

### Solution

I would like to have a refreshed list of Devices in the plugin, not a stale list of ones that don't exist anymore.

**Comment by donavanbecker** [comment]
Take the device ID, add it to the device config, check the hide device, and the device will be removed After next Homebridge restart.

**Comment by jeanofthedead** [comment]
Thanks, that's what I've been doing. I just have to do it for a bunch of duplicates at this point, as I've created and deleted devices in the SwitchBot app. I guess they will linger forever, lol.

**Comment by donavanbecker** [comment]
Yeah with how easy it is to remove them, It's not worth the effort of making the plugin do it, plus could remove devices when people don't want them to be removed.

**Comment by jeanofthedead** [comment]
Sounds good - I just wish I hadn't created IR devices in SwitchBot, deleted them, and created duplicates several times over. But the hide feature is working just fine - I appreciate it!

**Comment by siobhanellis** [comment]
I seem to have multiples of the same device, and it only ignores the first one.

**Comment by jeanofthedead** [comment]
Removing all cached devices in Homebridge settings fixes this for me now.
