### ISSUE TITLE
Support Request: Unable to install

### ISSUE THREAD

**Issue by zevillau** [OpenWonderLabs/homebridge-switchbot#737]
### Describe Your Problem

Unable to install

### Screenshots

![IMG_0025](https://user-images.githubusercontent.com/76636748/236620065-91993507-c646-4a9f-b0cd-e7455c88c229.jpeg)
![IMG_0026](https://user-images.githubusercontent.com/76636748/236620070-f9524faa-4e0b-478b-8001-881f93d54697.jpeg)
![IMG_0027](https://user-images.githubusercontent.com/76636748/236620072-2947ed78-1ad0-4b93-92d0-98768db4bc87.jpeg)
![IMG_0028](https://user-images.githubusercontent.com/76636748/236620075-9fe38cbc-ff30-4034-9193-13b7e3e492b2.jpeg)
![IMG_0029](https://user-images.githubusercontent.com/76636748/236620080-2f63bc8a-dbb9-4307-ae1f-f9a4bf42776c.jpeg)
![IMG_0030](https://user-images.githubusercontent.com/76636748/236620084-5eb8da37-a4b7-4188-89e9-d900602644e2.jpeg)
![IMG_0031](https://user-images.githubusercontent.com/76636748/236620086-bfcc64fc-76b7-49dc-bca8-19ed26034f0a.jpeg)
![IMG_0032](https://user-images.githubusercontent.com/76636748/236620089-6b0a8f32-78ca-44f5-bc65-33dfa66eac9b.jpeg)
![IMG_0033](https://user-images.githubusercontent.com/76636748/236620090-c2f87635-aadf-44f8-8176-fa8ecb0a189b.jpeg)

### Device & Model

Synology DS1621+

### Node.js Version

16.16.0

### NPM Version

9.6.6

### Homebridge Version

V1.6.1

### Homebridge SwitchBot Plugin Version

V2.6.2

### Operating System

Linux

**Comment by ZY-Ang** [comment]
@zevillau how did you resolve this?
