### ISSUE TITLE
Support Request: After the upgrade cannot reach any device through Homekit/Homebrigde

### ISSUE THREAD

**Issue by att11** [OpenWonderLabs/homebridge-switchbot#739]
### Describe Your Problem

Using 4 pairs of SB Curtains /w Hub Mini, after the last upgrade cannot see any of them here. Native app works fine. Tried to rollback, beta, reinstall, did not help. When installing upgrading the below error message is visible, but the insall always ends with success (not sure if it is relevant, as using hub mini). Also tried to enter optional device info, no change.

### Relevant log output

```shell
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v108-linux-arm.tar.gz 
make: Entering directory '/usr/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.o
In file included from /home/homebridge/.cache/node-gyp/18.12.1/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/homebridge/.cache/node-gyp/18.12.1/include/node/node.h:976:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/homebridge/.cache/node-gyp/18.12.1/include/node/node.h:1010:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/BluetoothHciSocket.cpp:740:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(binding, BluetoothHciSocket::Init);
 ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/bluetooth_hci_socket.nodees/@switchbot/home
  COPY Release/bluetooth_hci_socket.node timing reifyNode:node_modules/@switchbot/home
  COPY /usr/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node
  TOUCH Release/obj.target/action_after_build.stampfyNode:node_modules/@switchbot/home
make: Leaving directory '/usr/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/bluetooth-hci-socket/build'
(##################) ⠼ reify:googleapis: timing reifyNode:node_modules/@switchbot/home
> @abandonware/noble@1.9.2-20 install
> node-gyp-build

make: Entering directory '/usr/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble/build'
  SOLINK_MODULE(target) Release/obj.target/noble.node
  COPY Release/noble.nodeify:googleapis: timing reifyNode:node_modules/@switchbot/home
make: Leaving directory '/usr/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble/build'
(##################) ⠧ reify:googleapis: timing reifyNode:node_modules/@switchbot/home
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "token": "***",
                "secret": "***",
                "notice": "Keep your Token & Secret a secret!"
            },
            "platform": "SwitchBot"
```

### Device & Model

Raspberry Pi 4

### Node.js Version

v18.16.0

### NPM Version

9.5.1

### Homebridge Version

v1.6.1

### Homebridge SwitchBot Plugin Version

v2.6.2

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Please checkout the [Bluetooth Issues Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Bluetooth-Issues)

**Comment by att11** [comment]
Hi, thanks for the response, sorry I may be too much of a beginner, but can you give me a little more info please... which part of that article should I look at?

**Comment by donavanbecker** [comment]
Verify all of it.

My install and testing only happens on a Mac so I don't have experience with the other environments

**Comment by att11** [comment]
Well, interesting. Nothing of the above helped. Finally made a new install of the Pi, Homebridge, everything (was tested a lot of things on it lately anyway).
Same thing came up... Just noticed that after the first error message (BLE) there are others around the end of the install process - don't know how to look at them as at the end of the install terminal screen disappears. 

Tried one more thing, to roll back to earlier release. And at 2.5.3 it works again... A bit slower, but works. One error message at startup: "The plugin "homebridge-switchbot" requires Node.js version of ^16.20.0 || ^18.15.0 which does not satisfy the current Node.js version of v18.13.0. " 
Have any thought about this at all? Should I upgrade node.js?

Thanks, A.
