### ISSUE TITLE
Support Request: Outdoor Meter 2C readings incorrect

### ISSUE THREAD

**Issue by IanAlbinson** [OpenWonderLabs/homebridge-switchbot#743]
### Describe Your Problem

The Switchbot app displays the correct values for temp and humidity. The same sensor in Apple Home via Homebridge with this plugin does not. Current reading: 71F/46% in Switchbot app, 59F/95% in Apple Home. Others Switchbot sensors also seem to be off, but not at this level.

### Device & Model

Outdoor Meter 2C

### Node.js Version

v18.12.1

### NPM Version

n/a

### Homebridge Version

v1.6.1

### Homebridge SwitchBot Plugin Version

v2.6.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Without sending logs not much we can do.

**Comment by IanAlbinson** [comment]
Ah, sorry, yes. What's the best way to get you a log? Are you looking for the full Homebridge log or Switchbot specific?

**Comment by donavanbecker** [comment]
SwitchBot specific, the plugin has a debug mode in the config. But setting a device specific debug would be best.

**Comment by PlatGitHub468** [comment]
I have similar issue with Meter Plus where initially both Temperature and Humidity display correctly in HomeKit. After a day or so, the values are off when compared to the native Switchbot App.

How do I set up device specific debug log ?

**Comment by IanAlbinson** [comment]
> SwitchBot specific, the plugin has a debug mode in the config. But setting a device specific debug would be best.

Apologies for the lack of response on this. What's the best way to get you a "device specific debug" file? I can view the Homebridge log of everything, but is there an easier way of getting Switchbot logs?

**Comment by donavanbecker** [comment]
@IanAlbinson, please input your Config UI version. 

If you are using HOOBS, this plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by IanAlbinson** [comment]
@donavanbecker, I am currently on v1.6.1 of Homebridge, and I just updated to v2.7.0.

I'll check and see if the plugin displays the correct values this week.

**Comment by donavanbecker** [comment]
v2.8.0 is released
