### ISSUE TITLE
Bug: Plugin is not working, no “Secret” field to fill in the information 

### ISSUE THREAD

**Issue by Hedrakk** [OpenWonderLabs/homebridge-switchbot#746]
### Describe the Bug

Hi!

I’ve been using a SwitchBot Bot to turn on and off my pool’s water heater. The last time I used it, in the summer of 2022, it was working fine. 

Now summer is coming back and the plugin doesn’t seems to be working anymore. 

I’m getting feedbacks from the HOOBS’ log, but it’s mentioning issues with “openToken” vs “Token” and the “secret” that is not defined, but there’s not “secret” field in the plugin configuration. 

Anyone had that kind of issues and how did you solved it?

Thanks

### To Reproduce

I have removed and reinstalled the plugin without more success.

When I check my devices in my HOOBS, my SwitchBot Bot is not there. If I try to control the bot from the SwitchBot App on my iPhone, it is responding as expected. 

### Expected Behavior

Well, it should be working as it was working last year…

### Relevant Log Output

```shell
2023-05-30 07:55:50 03 - Switchbot Bridge Configuration change
2023-05-30 07:56:14 03 - Switchbot Bridge Loaded plugin @switchbot/homebridge-switchbot'
2023-05-30 07:56:14 03 - Switchbot Bridge Loading 1 platforms...
2023-05-30 07:56:14 03 - Switchbot
Bridge SwitchBot WARNING This plugin has been updated to use OpenAPI v1.1, config is set with openToken, "openToken" config has been moved to the "token" config
2023-05-30 07:56:14 03 - Switchbot
Bridge SwitchBot ERROR
"secret" config is not populated, you
must populate then please restart Bridge.
2023-05-30 07:56:14 03 - Switchbot Bridge Bridge is running on port 51846.
```

### Config for homebridge-switchbot

```shell
?
```

### Device and Model

SwitchBot bot and SwitchBot hub 

### Node.js Version

?

### NPM Version

?

### Homebridge Version

?

### Homebridge Switchbot Plugin Version

Latest

### Homebridge Config UI X Plugin Version

?

### Operating System

HOOBS

**Comment by donavanbecker** [comment]
Yep, you need to change over to API 1.1

Which takes a token and secret in the config.

**Comment by Hedrakk** [comment]
Ok, but how do I do that? It’s not mentioned how to do that in the plugin install page. Is it a new version of this plugin? I picked the certified one thinking I would be covered from bug or missing features. Jean-Francois Chabot__________________________________Capitaine/CaptainEquipe Extra-Life des Bionic Marmots|Bionic Marmots Extra Life Team|www.extra-life.org/participant/jfchabotLe 30 mai 2023 à 11:09, Donavan Becker ***@***.***> a écrit :﻿
Yep, you need to change over to API 1.1
Which takes a token and secret in the config.

**Comment by donavanbecker** [comment]
Check Release notes. 

Also this plugin has never supported HOOBs so you may run into issues.

My recommendation would be to switch to Homebridge.

**Comment by Hedrakk** [comment]
The plugin is clearly tag as certified for HOOBS…Jean-Francois Chabot__________________________________Capitaine/CaptainEquipe Extra-Life des Bionic Marmots|Bionic Marmots Extra Life Team|www.extra-life.org/participant/jfchabotLe 30 mai 2023 à 12:02, Donavan Becker ***@***.***> a écrit :﻿
Check Release notes.
Also this plugin has never supported HOOBs so you may run into issues.
My recommendation would be to switch to Homebridge.

**Comment by donavanbecker** [comment]
@Hedrakk That is out there by HOOBs not us.

So if you run into issues, since I only design this for Homebridge, you can run into issues. Just so you are aware.
