### ISSUE TITLE
Bug: Unable to connect to Switch Bot

### ISSUE THREAD

**Issue by lucamancusodev** [OpenWonderLabs/homebridge-switchbot#753]
### Describe the Bug

After installed the plugin and configured the switch bot params I got some errors and now work as excepted.
I already tried to check the prerequisites and everything is fine, tried also reboot, reinstall without success.
From Switch app I can activate the bot.

### To Reproduce

Install the plugin and configure.

### Expected Behavior

I expect to show in home app and in the home bridge accessories

### Relevant Log Output

```shell
I attached my logs
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "mytoken",
                "secret": "mysecret",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "DAE1CDDDD696",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE",
                        "bot": {
                            "mode": "press",
                            "deviceType": "garagedoor",
                            "doublePress": 1
                        },
                        "logging": "debug"
                    }
                ],
                "logging": "debug"
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

<img width="995" alt="Screenshot 2023-06-21 alle 21 19 00" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/41821623/6a7f724c-c69c-4ab7-ad8c-11dc5ba8acba">
<img width="1040" alt="Screenshot 2023-06-21 alle 21 20 41" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/41821623/4f575411-73b0-4b1f-bd1f-660cf55ca46b">

### Device and Model

Raspberry Pi 4 

### Node.js Version

v18.16.0

### NPM Version

v9.5.1

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.6.2

### Operating System

Raspbian

**Comment by DylanBadolato** [comment]
I keep getting a 401 error on the API call. 

I have tried to reset the token with no luck. I am assuming that is why the Call inside of Home Bridge fails because the authorization to the API doesn't authenticate.

**Comment by carlheinmostert** [comment]
Having same issue.

**Comment by lucamancusodev** [comment]
What it worked for me is to hard reset two times the Switch.

**Comment by donavanbecker** [comment]
@Luccio96, what Config UI X version are you using?
@DylanBadolato please open your own issue as your Homebridge instance is more than likely different.
@carlheinmostert please open your own issue as your Homebridge instance is more than likely different.

**Comment by donavanbecker** [comment]
v2.8.0 is released
