### ISSUE TITLE
Feature Request: Add option to link temperature sensor from homebridge to air conditioner IR control

### ISSUE THREAD

**Issue by pandit-psw** [OpenWonderLabs/homebridge-switchbot#758]
### Problem

Now the IR Air Conditioner only displays 24 ˚ C and makes so confusing when controlling the temperature

### Solution

Allow us to set default temperature, or link a temperature sensor within homebridge

**Comment by donavanbecker** [comment]
this will be include in next release if you want to test out in the latest beta.

**Comment by donavanbecker** [comment]
v2.8.0 is released
