### ISSUE TITLE
Feature Request: Disable individual devices from showing in Home app

### ISSUE THREAD

**Issue by shinratdr** [OpenWonderLabs/homebridge-switchbot#763]
### Problem

My SwitchBot lock is now supported via Matter through the Hub 2, but my SwitchBot Bot isn't. I want to hide the SwitchBot Lock from HomeKit, but keep my SwitchBot Bot available. Right now I have to disable the plugin entirely to not end up with duplicate devices.

### Solution

Disable unwanted/duplicate devices from the HomeBridge plugin, or delete them from the Home app.

### Alternatives

Allowing individual devices to be moved to Child Hubs would also work, so then I could just move devices that I don't want to add to a child hub and then not add that hub to Home.

**Comment by donavanbecker** [comment]
Use device settings to hide devices.

**Comment by shinratdr** [comment]
Yep, that did it. Sorry I didn’t realize I had to copy the Device ID over to the settings tab to expose the settings for each individual device. Once I did that, the hide from HomeKit checkbox appeared. Thanks!

**Comment by shinratdr** [comment]
Resolved.
