### ISSUE TITLE
Feature Request: SwitchBot Bot HomeKit (button press - Homekit toggle on/off)

### ISSUE THREAD

**Issue by dwest26** [OpenWonderLabs/homebridge-switchbot#767]
### Problem

Currently have switchbot bot set in press mode for a tower fan (single button press) in app and in home bridge (OPEN API). In Homekit, when I say "Turn on Tower Fan" after like 30-45 seconds, the bot presses the fan power button, turns on the fan, and for about 10 seconds the "fan" aka switchbot bot in Homekit says that it's powered on, but after a few seconds, it shows that it's powered off again, which is really annoying because all I want to do is say "Turn on fan", "turn off fan" with Homekit and have it's true power status reflected.

### Solution

I want my "Fan" to show when/if/invoked powered on, and then show as powered off, when activated/invoked by Siri through HomeKit.

**Comment by donavanbecker** [comment]
@dwest26 chnage the bot mode to switch mode instead of press mode for that specific bot, under device config.
