### ISSUE TITLE
Bug:  This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined."

### ISSUE THREAD

**Issue by jeanofthedead** [OpenWonderLabs/homebridge-switchbot#777]
### Describe the Bug

I am receiving the following error in Homebridge logs:

`This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`

I am using the SwitchBot Hub 2 and have configured that device as the ambient temperature for my DIY Air Conditioner device within your plugin's settings.

### To Reproduce

This error message appears right after this log message:

`[SwitchBot] update temperature and humidity for Hub 2`

### Expected Behavior

Expecting temperature and humidity readings to appear normally.

### Relevant Log Output

```shell
[SwitchBot] update temperature and humidity for Hub 2
[@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[SwitchBot] update temperature and humidity for Hub 2
```

### Config for homebridge-switchbot

```shell
{
                        "deviceId": "REDACTED",
                        "configDeviceName": "Hub 2",
                        "hide_device": false,
                        "configDeviceType": "Hub 2",
                        "hidHub": {
                            "hide_temperature": false,
                            "hide_humidity": false
                        }

"irdevices": [
                    {
                        "deviceId": "REDACTED",
                        "configDeviceName": "Air Conditioner",
                        "configRemoteType": "DIY Air Conditioner",
                        "connectionType": "OpenAPI",
                        "customize": false,
                        "irair": {
                            "hide_automode": true,
                            "meterType": "Hub 2",
                            "meterId": "REDACTED"
                        }
```

### Device and Model

SwitchBot Hub 2

### Node.js Version

v18.17.0 

### NPM Version

9.6.7

### Homebridge Version

1.6.1

### Homebridge Switchbot Plugin Version

2.7.0

### Operating System

LePotato running Armbian

**Comment by jeanofthedead** [comment]
It seems that this error only appears if I set the "existing Switchbot device for temperature/humidity" to my Hub 2. The error does not appear if I use my WolOSensor-type Outdoor Meter.

**Comment by donavanbecker** [comment]
@mrlt8

**Comment by mrlt8** [comment]
This is similar to what @hamzaahmadk has noted in #761 because the hub isn't updating the temp/humidity the same way as the meter.

@donavanbecker is there a dev or beta branch where I can do a PR?

**Comment by donavanbecker** [comment]
@mrlt8 I just created one for you: beta-2.7.1

**Comment by donavanbecker** [comment]
@jeanofthedead please try the latest beta

**Comment by donavanbecker** [comment]
@jeanofthedead Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.7.1-beta.1/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
@jeanofthedead Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.7.1-beta.1/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by jeanofthedead** [comment]
Just wanted to update that while I never tried the beta, your latest update (2.7.1) works as it should. Thanks so much!
