### ISSUE TITLE
Bug: Battery Service is removed from Meter if not BLE?

### ISSUE THREAD

**Issue by mrlt8** [OpenWonderLabs/homebridge-switchbot#781]
### Describe the Bug

Is there any particular reason why the battery service on the meter devices is removed if not BLE?

https://github.com/OpenWonderLabs/homebridge-switchbot/blob/472aef8bf69434f757c7cc573dc29d2b81d7bdf6/src/device/meter.ts#L151-L168

The API seems to return the battery level, and I can see the level get returned in the logs:
https://github.com/OpenWonderLabs/SwitchBotAPI#meter-1

```
[SwitchBot] [DEBUG] Meter: Guest Room Meter Devices: {"deviceId":"ABCDEFG","deviceType":"Meter","hubDeviceId":"ABCDEFG","humidity":55,"temperature":24.7,"version":"V2.6","battery":78}
```

### To Reproduce

Use Meter with OpenAPI connection type.

### Expected Behavior

Battery level in home app.

### Relevant Log Output

```shell
[SwitchBot] [DEBUG] Meter: Guest Room Meter Removing Battery Service
```

### Config for homebridge-switchbot

```shell
...
"configDeviceType": "Meter",
"connectionType": "OpenAPI",
...
```

### Device and Model

Meter

### Node.js Version

NA

### NPM Version

NA

### Homebridge Version

NA

### Homebridge Switchbot Plugin Version

NA

### Operating System

NA

**Comment by donavanbecker** [comment]
@mrlt8 At one point the API didn't have the battery status so I had to remove it if you set a Meter up without BLE. The API must of updated to include it.

**Comment by donavanbecker** [comment]
Will be added to v2.8.0

**Comment by donavanbecker** [comment]
v2.8.0 is released
