### ISSUE TITLE
Feature Request: [IR Device: Air Conditioner] CurrentHeaterCoolerState should match TargetHeaterCoolerState?

### ISSUE THREAD

**Issue by mrlt8** [OpenWonderLabs/homebridge-switchbot#790]
### Problem

`CurrentHeaterCoolerState` is being set by comparing the target temperature to the current temperature if available (or the default temperature if not linked to a meter). This will result in the Home app flipping the status from "cooling" to  "heating" if the current temperature passes the target temperature.

### Solution

Not sure what other `HeaterCooler` devices do when the exceed the target temperature, but `CurrentHeaterCoolerState` could return `TargetHeaterCoolerState` if the AC is active and/or return `IDLE` if the current temperature exceeds the target temperature?

### Alternatives

Always return `TargetHeaterCoolerState`? This would work for all IR air conditioners even if they aren't linked to a meter.

### Additional context

I don't use the "auto" mode, but it could fall back to the current method of comparing the current temp to the target temp or just return `IDLE` all the time?  `airpurifier.ts` also seems to be using a comparison to set the `CurrentHeaterCoolerState`.

**Comment by donavanbecker** [comment]
v2.8.0 is released
