### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by SCOTTS948** [OpenWonderLabs/homebridge-switchbot#794]
### Describe the Bug

Devices no longer respond in Home app. They still show up and they look like they respond in the HOme app, but nothing happens. Looking at my homebridge logs, homebridge is not responding or logging anything when i try to control these devices. It's been about a week. 

I have tried resetting my token and secret, but that was unsuccessful. 

### To Reproduce

Try to operate a device within home app. 

### Expected Behavior

I expect the device to respond properly when controlling it with the Home app. 

### Relevant Log Output

```shell
[8/16/2023, 7:08:05 PM] [SwitchBot] Unknown statusCode, statusCode: 401, Submit Bugs Here: ' + 'https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
    "credentials": {
        "token": "removed",
        "secret": "removed",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "refreshRate": 30,
        "pushRate": 368
    },
    "platform": "SwitchBot"
}
```

### Screenshots

n/a

### Device and Model

Windows 

### Node.js Version

v16.18.1

### NPM Version

v9.8.1

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.7.1

### Operating System

Windows

**Comment by donavanbecker** [comment]
If you are using HOOBS, This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

If you are using Homebride UI (you never responded about this questions so assuming you don't) then can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.8.0-beta.18/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by SCOTTS948** [comment]
I am using Homebridge already. Had no issues until recently.

**Comment by donavanbecker** [comment]
v2.8.0 is released
