### ISSUE TITLE
Support Request: Add Switch to IR Other Type

### ISSUE THREAD

**Issue by thatpaulallen** [OpenWonderLabs/homebridge-switchbot#810]
### Describe Your Problem

Can't add Others device as Switch instead of Fan

### Relevant log output

```shell
[28/08/2023, 17:49:08] [SwitchBot] Total SwitchBot Devices Found: 1
[28/08/2023, 17:49:08] [SwitchBot] Restoring existing accessory from cache: Power DeviceID: 02-202308281519-11754152
[28/08/2023, 17:49:08] [SwitchBot] Restoring existing accessory from cache: Atmos DeviceID: 02-202308281523-21664685
[28/08/2023, 17:49:08] [SwitchBot] Restoring existing accessory from cache: HDMI-ARC DeviceID: 02-202308281525-74763591
[28/08/2023, 17:49:09] [SwitchBot] Restoring existing accessory from cache: AUX DeviceID: 02-202308281526-54117653
[28/08/2023, 17:49:09] [SwitchBot] Restoring existing accessory from cache: Test DeviceID: 02-202308281741-66051983
[28/08/2023, 17:49:09] [SwitchBot] Others: Test Using Device Type: Switch
[28/08/2023, 17:49:09] [SwitchBot] Total IR Devices Found: 5
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "token": "token",
                "secret": "secret",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "02-202308281741-66051983",
                        "configDeviceName": "Test",
                        "configRemoteType": "Others",
                        "connectionType": "Disabled",
                        "customize": true,
                        "other": {
                            "deviceType": "Switch"
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
```

### Screenshots

![Screen Shot 2023-08-28 at 6 00 46 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/7da577d7-5998-41b3-9dd2-847d9a8080d2)
![Screen Shot 2023-08-28 at 6 00 21 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/9ae29b34-1df0-4e3b-9f1a-555cea164793)

### Device & Model

Raspberry Pi 3b+

### Node.js Version

v18.17.1 

### NPM Version

?

### Homebridge Version

v1.6.1

### Homebridge SwitchBot Plugin Version

v2.8.2

### Operating System

Raspbian?

**Comment by thatpaulallen** [comment]
The dropdown for "What Type of Device Do You Want to Display in the Home App?" only shows None and Fan

**Comment by donavanbecker** [comment]
Is there a reason this IR device isn't under the Fan Device Type in the SwitchBot App?

**Comment by thatpaulallen** [comment]
> Is there a reason this IR device isn't under the Fan Device Type in the SwitchBot App?

Because I want to add my device as a switch and not a fan?

**Comment by donavanbecker** [comment]
Okay I will add this when I have time next.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.0-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by thatpaulallen** [comment]
The beta is a huge improvement! I no longer get an error when my Others device is added!

That said, I probably need some help correctly formatting my device in the Switchbot app. I created a test device with two buttons, On and Off, but I can't get the device to work in Homebridge. On and off commands do nothing. Is there something I'm missing?

**Comment by thatpaulallen** [comment]
This is what my device looks like in the Switchbot app, and how I have it setup in the plugin settings.(I've also tried leaving "Custom IR Commands" unchecked and blank but I get the same non response.)


![IMG_5506](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/5a1a328e-58cd-45fe-ae11-e71f5748bc5f)
![IMG_2791](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/2ac88526-a222-4975-af0e-df753ab8bcef)
![IMG_4075](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/4eed2fea-4e43-4296-a4c6-9f6dc6c47fc4)

**Comment by donavanbecker** [comment]
See the following comment: https://github.com/OpenWonderLabs/SwitchBotAPI/issues/232#issuecomment-1686251268

I am going to add commandType to the config and then you can add tag and see if that works.

**Comment by donavanbecker** [comment]
> The beta is a huge improvement! I no longer get an error when my Others device is added!
> 
> 
> 
> That said, I probably need some help correctly formatting my device in the Switchbot app. I created a test device with two buttons, On and Off, but I can't get the device to work in Homebridge. On and off commands do nothing. Is there something I'm missing?

I accidentally took out the push change commands when adding all the deviceTypes... that has been added back in, in the latest beta.

**Comment by thatpaulallen** [comment]
It took some trial and error but I got everything working as expected with the new beta. Thanks for the help.

**Comment by failbit** [comment]
@thatpaulallen could you kindly provide your working configuration? I want to try it out aswell.

**Comment by thatpaulallen** [comment]
> @thatpaulallen could you kindly provide your working configuration? I want to try it out aswell.

Sure! When setting up my Others device in the Switchbot app, I programmed two buttons and named them On and Off. (Not sure if the caps matter, but that’s what I did.)

Back in Homebridge I went to the DEVICES tab and copied the Device ID. Then I went back to the SETTINGS tab, clicked on IR Device Settings and pasted it there. (I also gave it a name)

The rest of the settings are as follows: 

Remote Type: Others (IR)
Connection Type: OpenAPI
Type of Device: Switch
Custom IR Commands: Checked
On Command: On
Off Command: Off
(The rest I didn’t touch)

Click save, restart your Homebridge, and see how it goes!

**Comment by donavanbecker** [comment]
This will be in v2.9.0, once released

**Comment by hsakoh** [comment]
@donavanbecker 
For your information.

It seems that in some regions, the API with CommandType="tag" has stopped working. 
It appears to be released gradually in each region.
Instead, you can perform the same operation by sending the key set number with CommandType="customize".

before:
```
{"commandType":"tag","command":"10","parameter":"default"}
```

after:
```
{"commandType":"customize","command":"10","parameter":"default"}
```
