### ISSUE TITLE
Bug: switchbot.discover is not a function

### ISSUE THREAD

**Issue by binomialstew** [OpenWonderLabs/homebridge-switchbot#817]
### Describe the Bug

Triggering the switchbot from homebridge is no longer working as of the latest version with the error message `switchbot.discover is not a function`. These devices had been added and working for a few years prior.

### To Reproduce

Run homebridge and view logs. Attempt to control switchbot through homebridge. Switchbot can be operated through switchbot app in iOS.

### Expected Behavior

The plugin should be able to discover devices

### Relevant Log Output

```shell
[9/6/2023, 2:05:40 PM] [SwitchBot] Was 'node-switchbot' found: false
[9/6/2023, 2:05:40 PM] [SwitchBot] Bot: Skylights Closed failed pushChanges with BLE Connection, Error Message: "switchbot.discover is not a function"
```
```


### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "secret": "xxxxxxxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xxxxxxxxxxxxxx",
                        "configDeviceName": "Open",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE",
                        "bot": {
                            "mode": "press",
                            "deviceType": "window",
                            "doublePress": 1
                        },
                        "offline": true
                    },
                    {
                        "deviceId": "xxxxxxxxxxxxxxx",
                        "configDeviceName": "Closed",
                        "configDeviceType": "Bot",
                        "connectionType": "BLE",
                        "bot": {
                            "mode": "press",
                            "deviceType": "window",
                            "doublePress": 1
                        },
                        "offline": true
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Device and Model

Switchbot

### Node.js Version

v18.17.1

### NPM Version

v9.6.7

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.8.2

### Homebridge Config UI X Plugin Version

v4.50.5

### Operating System

Raspbian GNU/Linux (11)

**Comment by binomialstew** [comment]
The latest version that works for me is:
```
@abandonware/noble@1.9.2-23
@switchbot/homebridge-switchbot@2.7.1
homebridge@1.6.1
node-switchbot@1.7.3
```

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.0-beta.18/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by binomialstew** [comment]
> Can you try the latest beta:
> 
> [![npm version](https://camo.githubusercontent.com/292f66807b43d26c84929e6e4aa12613aea009fd36b73751e544597d88ce5018/68747470733a2f2f62616467656e2e6e65742f62616467652f686f6d656272696467652d737769746368626f7440626574612f2533453d322e392e302d626574612e31382f6f72616e6765)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)
> 
> [Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

Same error message, unfortunately

**Comment by donavanbecker** [comment]
> The latest version that works for me is:
> 
> ```
> @abandonware/noble@1.9.2-23
> @switchbot/homebridge-switchbot@2.7.1
> homebridge@1.6.1
> node-switchbot@1.7.3
> ```

please install latest beta `2.9.0-beta.21` and then post this info again

**Comment by binomialstew** [comment]
> please install latest beta `2.9.0-beta.21` and then post this info again
```
@abandonware/noble@1.9.2-23
@switchbot/homebridge-switchbot@2.9.1-beta.2
homebridge@1.6.1
node-switchbot@1.7.3
```
and
```
@abandonware/noble@1.9.2-23
@switchbot/homebridge-switchbot@2.9.0-beta.21
homebridge@1.6.1
node-switchbot@1.7.3
```
Unfortunately I see the same message with the beta you recommended and also the latest beta:
`failed pushChanges with BLE Connection, Error Message: "switchbot.discover is not a function"`

I believe I was wrong about the latest version that works for me. I just checked and I have `v2.6.2` installed. Any version after that, I see the same `not a function` error message.
