### ISSUE TITLE
Support Request: Hub2 and Eve History with fakegato-history

### ISSUE THREAD

**Issue by joffroy59** [OpenWonderLabs/homebridge-switchbot#818]
### Describe Your Problem

Eve History for hub 

### Relevant log output

```shell
Is it possible to have data from hub 2 to eve history via fakegato (temperature, humidity, light) ?
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxxx",
                "secret": "xxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "XXXXXXXXXXXXXXX",
                        "configDeviceType": "Hub 2",
                        "refreshRate": 30,
                        "offline": false,
                        "history": true,
                        "external": false
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "XXXXXXXXXXXXXXXXXXXXXXX",
                        "configDeviceName": "Télécommande Sony grande",
                        "hide_device": true,
                        "configRemoteType": "TV",
                        "connectionType": "OpenAPI",
                        "customize": false,
                        "disablePushOn": true,
                        "disablePushOff": true,
                        "disablePushDetail": false,
                        "external": false
                    }
                ],
                "refreshRate": 30
            },
            "platform": "SwitchBot"
        },
```

### Device & Model

Hub 2 

### Node.js Version

v16.20.2

### NPM Version

v8.19.4

### Homebridge Version

v16.20.2

### Homebridge SwitchBot Plugin Version

v2.8.2

### Homebridge Config UI X Plugin Version

 v4.50.5

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Should be able too. I will look into this.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.0-beta.20/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by joffroy59** [comment]
It works for humidity and temperature with beta version 

Not for the lightning level 
Thanks for the work

![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/977031/b49c9eef-239b-4e40-a738-02d5fefd35b8)
![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/977031/30f87c60-8d1f-4a36-88ba-832a9c68e1cc)
![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/977031/3f59ce2d-8424-482c-9e41-774cf4889e92)
![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/977031/0ad3a4a1-6636-4802-b497-4912938576b0)

**Comment by donavanbecker** [comment]
Sorry totally forgot, I will get a new beta out in a little bit.

**Comment by joffroy59** [comment]
why sorry ? ;-) things happened ...
