### ISSUE TITLE
how to exclude devices?

### ISSUE THREAD

**Issue by francescosabia** [OpenWonderLabs/homebridge-switchbot#820]
### Problem

i only added a bot in the config. but when i connect the plugin to homekit it shows me all the accessories (lock and sensors of hub 2)

### Solution

i only want to show the accessories i put in the config

**Comment by donavanbecker** [comment]
Plugin is not setup to look at which devices are connected to a hub, as not all devices need a hub. If you want to hide a device, you can use the device tab to get the deviceID and then take that to the device settings, input device id and check hide device.

**Comment by francescosabia** [comment]
> Plugin is not setup to look at which devices are connected to a hub, as not all devices need a hub. If you want to hide a device, you can use the device tab to get the deviceID and then take that to the device settings, input device id and check hide device.

It s also possible to hide hub 2 sensors?

**Comment by donavanbecker** [comment]
Yes through the same process. Hide your Hub 2 using Plugin Settings.

**Comment by francescosabia** [comment]
> Yes through the same process. Hide your Hub 2 using Plugin Settings.

i got to hide devices but  can't do the same with hub 2... i always see it s temp,humidity and light sensor in home app. can u teach me please how to also exclude it step by step? thanks
