### ISSUE TITLE
Bug: Swing mode being turned on also sends turnOn command

### ISSUE THREAD

**Issue by WhatTheKJ** [OpenWonderLabs/homebridge-switchbot#823]
### Describe the Bug

On my DIY Fan in Homekit, when I turn on oscillating it sends a turnOn command then swing command in homebridge. This does not happen with I use swing mode directly in Switchbot. Note this only happens when turning on oscillating, not turning off.

### To Reproduce

Enable Swing mode on DIY Fan

### Expected Behavior

Fan to stay on when switching swing modes.

### Relevant Log Output

```shell
Output is attached…
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxx",
                "secret": "xxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xxxx",
                        "configDeviceName": "Hub",
                        "hide_device": true
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "xxxx",
                        "configDeviceName": "Dyson",
                        "configRemoteType": "DIY Fan",
                        "connectionType": "OpenAPI",
                        "customize": false,
                        "customOn": "turnOn",
                        "customOff": "turnOff",
                        "disablePushOn": false,
                        "disablePushOff": false,
                        "disablePushDetail": false,
                        "irfan": {
                            "swing_mode": true,
                            "rotation_speed": false,
                            "set_minStep": 0
                        },
                        "external": true,
                        "logging": "standard"
                    }
                ],
                "refreshRate": 43200,
                "logging": "standard"
            },
            "platform": "SwitchBot"
```

### Screenshots

![IMG_0079](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/28029584/c75975f0-8cea-4631-ae34-3cfb3a8ecd5c)

### Device and Model

Dyson fan

### Node.js Version

v18.16.0

### NPM Version

9.6.7

### Homebridge Version

1.6.1

### Homebridge Switchbot Plugin Version

2.8.2

### Homebridge Config UI X Plugin Version

4.50.5

### Operating System

Ubuntu

**Comment by donavanbecker** [comment]
this is because it is designed to make sure that the fan is on before send the isolating command. I can look and see if I can change this at all. can you get me a little more logs?

**Comment by WhatTheKJ** [comment]
> this is because it is designed to make sure that the fan is on before send the isolating command. I can look and see if I can change this at all. can you get me a little more logs?

Thanks for looking into it. My expectation is that swing would try to swing the fan if its on such as the remote would. If it cant work that way I would then expect turning on swing would then show the On to be triggered on in the home app but turning off swing would not trigger the Off switch and leave it shown as On in the Home app.

Im not sure what other logs youre looking for. What I posted is when the issue happens.
