### ISSUE TITLE
v2.9.0 is causing homebridge docker to crash repeatedly

### ISSUE THREAD

**Issue by razzamatazm** [OpenWonderLabs/homebridge-switchbot#828]
### Describe the Bug

After updating the plugin, I get repeated crashes until downgrading. 

### To Reproduce

Start homebridge. Downgrading will fix the issue.

### Expected Behavior

Homebridge to start and remain running

### Relevant Log Output

```shell
[9/19/2023, 3:47:21 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Firmware Revision': characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future. See https://homebridge.io/w/JtMGR for more info.
[9/19/2023, 3:47:21 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Firmware Revision': characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future. See https://homebridge.io/w/JtMGR for more info.
[9/19/2023, 3:47:21 PM] TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at BlindTilt.updateHomeKitCharacteristics (/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/blindtilt.ts:911:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/19/2023, 3:47:21 PM] Got SIGTERM, shutting down Homebridge...
[9/19/2023, 3:47:21 PM] [Meross] [Outdoor Switch] mqtt connection closed.
[9/19/2023, 3:47:21 PM] Got SIGTERM, shutting down child bridge process...
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "XXXXXXXXXXXXXXX",
                "secret": "XXXXXXXXXXXXXXXXXX",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "XXXXXXXXXXXXXXXXX",
                        "configDeviceType": "Blind Tilt",
                        "connectionType": "OpenAPI",
                        "blindTilt": {
                            "set_minStep": 5
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Device and Model

Blind Tilt and Hub Mini

### Node.js Version

v18.16.0

### NPM Version

?

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.9.0

### Homebridge Config UI X Plugin Version

v4.50.5

### Operating System

Docker

**Comment by JosiahSayers** [comment]
Chiming in to say that I'm seeing the same error message after updating to 2.9.0 and downgrading also fixes the issue for me. I'm running 2 blind tilts through my setup. Happy to provide any logs if needed.

**Comment by razzamatazm** [comment]
I also tried the new beta and had the same issue
________________________________

**Comment by Bgoshua** [comment]
I had this happen as well (I'm running HB 1.6.1 and node 20.6.0 on a Mac mini), clearing the cache of the device(s) causing the error fixed it for me. Blind tilt and an ir TV were the culprits in my case.

**Comment by senseotech** [comment]
Ran into this as well and tried clearing the cache as mentioned above with no luck, ended up having to downgrade.  I was seeing both firmware and battery characteristics throwing the error, 3 tilt blinds here.

**Comment by donavanbecker** [comment]
That error would not cause a restart, that is more of a warning. You will need to turn debug logs on to see exactly what is causing this.

**Comment by razzamatazm** [comment]
Here is the debug log:

[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds body:
{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":{"data":{"type":"Buffer","data":[123,34,115,116,97,116,117,115,67,111,100,101,34,58,49,48,48,44,34,98,111,100,121,34,58,123,34,100,101,118,105,99,101,73,100,34,58,34,68,51,68,70,50,54,56,66,49,68,66,54,34,44,34,100,101,118,105,99,101,84,121,112,101,34,58,34,66,108,105,110,100,32,84,105,108,116,34,44,34,104,117,98,68,101,118,105,99,101,73,100,34,58,34,68,53,57,70,65,57,69,68,67,55,70,55,34,44,34,118,101,114,115,105,111,110,34,58,49,50,44,34,99,97,108,105,98,114,97,116,101,34,58,116,114,117,101,44,34,98,97,116,116,101,114,121,34,58,53,48,44,34,100,105,114,101,99,116,105,111,110,34,58,34,68,111,119,110,34,44,34,115,108,105,100,101,80,111,115,105,116,105,111,110,34,58,53,48,125,44,34,109,101,115,115,97,103,101,34,58,34,115,117,99,99,101,115,115,34,125]},"next":null},"tail":{"data":{"type":"Buffer","data":[123,34,115,116,97,116,117,115,67,111,100,101,34,58,49,48,48,44,34,98,111,100,121,34,58,123,34,100,101,118,105,99,101,73,100,34,58,34,68,51,68,70,50,54,56,66,49,68,66,54,34,44,34,100,101,118,105,99,101,84,121,112,101,34,58,34,66,108,105,110,100,32,84,105,108,116,34,44,34,104,117,98,68,101,118,105,99,101,73,100,34,58,34,68,53,57,70,65,57,69,68,67,55,70,55,34,44,34,118,101,114,115,105,111,110,34,58,49,50,44,34,99,97,108,105,98,114,97,116,101,34,58,116,114,117,101,44,34,98,97,116,116,101,114,121,34,58,53,48,44,34,100,105,114,101,99,116,105,111,110,34,58,34,68,111,119,110,34,44,34,115,108,105,100,101,80,111,115,105,116,105,111,110,34,58,53,48,125,44,34,109,101,115,115,97,103,101,34,58,34,115,117,99,99,101,115,115,34,125]},"next":null},"length":1},"length":209,"pipes":[],"flowing":null,"ended":true,"endEmitted":false,"reading":false,"constructed":true,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":0}
[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds
statusCode: 200
[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds
headers: {"date":"Wed, 20 Sep 2023 21:11:54
GMT","content-type":"application/json","content-length":"209","connection":"keep-alive","x-amzn-requestid":"XXXX-7c95-4c2b-XXXX-e956dc3f0e3a","x-amz-apigw-id":"XXXXX=","x-amzn-trace-id":"Root=1-XXXX-XXXX;Sampled=0;lineage=bf95bacf:0"}
[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds
deviceStatus:
{"statusCode":100,"body":{"deviceId":"XXXXXX","deviceType":"Blind
Tilt","hubDeviceId":"XXXX","version":12,"calibrate":true,"battery":50,"direction":"Down","slidePosition":50},"message":"success"}
[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds
deviceStatus body: {"deviceId":"XXXX","deviceType":"Blind
Tilt","hubDeviceId":"XXX","version":12,"calibrate":true,"battery":50,"direction":"Down","slidePosition":50}
[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds
deviceStatus statusCode: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] [DEBUG] Blind Tilt: Tyler Blinds
statusCode: 200 & deviceStatus StatusCode: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
openAPIparseStatus
[9/20/2023, 2:11:54 PM] [SwitchBot]  device: 50 => HK: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
CurrentPosition: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds Standby
because device not moving, CurrentPosition: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds Stopped
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
CurrentPosition: 100, TargetPosition: 100, PositionState: 2,
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
CurrentAmbientLightLevel: 6001
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds BatteryLevel:
50, StatusLowBattery: 0
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
updateCharacteristic CurrentPosition: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
updateCharacteristic PositionState: 2
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
updateCharacteristic TargetPosition: 100
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
updateCharacteristic CurrentAmbientLightLevel: 6001
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
updateCharacteristic BatteryLevel: 50
[9/20/2023, 2:11:54 PM] [SwitchBot] Blind Tilt: Tyler Blinds
updateCharacteristic StatusLowBattery: 0
[9/20/2023, 2:11:54 PM] ***@***.***/homebridge-switchbot] This plugin
generated a warning from the characteristic 'Firmware Revision':
characteristic was supplied illegal value: number instead of string,
supplying illegal values will throw errors in the future. See
https://homebridge.io/w/JtMGR for more info.
[9/20/2023, 2:11:54 PM] ***@***.***/homebridge-switchbot] Error:
    at FirmwareRevision.Characteristic.characteristicWarning
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at FirmwareRevision.Characteristic.validateUserInput
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2952:14)
    at FirmwareRevision.Characteristic.updateValue
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at Battery.Service.updateCharacteristic
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at BlindTilt.updateHomeKitCharacteristics
***@***.***/homebridge-switchbot/src/device/blindtilt.ts:908:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/20/2023, 2:11:54 PM] ***@***.***/homebridge-switchbot] This plugin
generated a warning from the characteristic 'Firmware Revision':
characteristic was supplied illegal value: number instead of string,
supplying illegal values will throw errors in the future. See
https://homebridge.io/w/JtMGR for more info.
[9/20/2023, 2:11:54 PM] ***@***.***/homebridge-switchbot] Error:
    at FirmwareRevision.Characteristic.characteristicWarning
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at FirmwareRevision.Characteristic.validateUserInput
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2952:14)
    at FirmwareRevision.Characteristic.updateValue
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at WindowCovering.Service.updateCharacteristic
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at BlindTilt.updateHomeKitCharacteristics
***@***.***/homebridge-switchbot/src/device/blindtilt.ts:909:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/20/2023, 2:11:54 PM] TypeError: Cannot read properties of undefined
(reading 'updateCharacteristic')
    at BlindTilt.updateHomeKitCharacteristics
***@***.***/homebridge-switchbot/src/device/blindtilt.ts:911:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/20/2023, 2:11:54 PM] Got SIGTERM, shutting down Homebridge...

**Comment by razzamatazm** [comment]
I ended up updated NodeJS in my docker container and it seems to have resolved this problem and fixed a motion sensor that wasn't working. @JosiahSayers @Bgoshua @senseotech

**Comment by Bgoshua** [comment]
@razzamatazm great news! What node version are you currently running, 18.18.0 or 20.8.0? I was running 20.6.0 when I first got the error, thought I had it resolved until I restarted my instance and the issue came back.

**Comment by razzamatazm** [comment]
I'm running 18.18.0

**Comment by Bgoshua** [comment]
I tried installing node 18.18 and 20.8 and the errors/boot loop persists for me. Had to downgrade back to v2.8.2 for now. My logs on  2.9.0 as well as the newest beta available, mirror what razzamatazm has posted earlier in the thread.

**Comment by ZarekParker** [comment]
2.8.2 also fixed the crash loop for me. I turned on debug logging but there were no errors before it just crashed and restarted

**Comment by donavanbecker** [comment]
Can you all try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.1-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

And report back.

**Comment by Bgoshua** [comment]
@donavanbecker Newest beta fixed for me 🙌

**Comment by ZarekParker** [comment]
v2.9.1-beta.4 doesn't seem to be crashing for me

**Comment by senseotech** [comment]
Same here, the new beta seems to have resolved the issue!

**Comment by donavanbecker** [comment]
v2.9.1 has been released
