### ISSUE TITLE
Bug: switchbot lock doesnt respond

### ISSUE THREAD

**Issue by nadavko** [OpenWonderLabs/homebridge-switchbot#831]
### Describe the Bug

when trying to lock the swtichbot lock via homekit smartlock gives unknown statuscode: 300 and doesnt do anything

### To Reproduce

lock the lock via homekit

### Expected Behavior

the lock locks

### Relevant Log Output

```shell
Codename Annika
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge 8B09",
        "username": "0E:DC:DE:C6:D9:4B",
        "port": 51537,
        "pin": "339-63-563",
        "advertiser": "bonjour-hap",
        "bind": [
            "vmbr0",
            "docker0",
            "vethd2f3433"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "5f957e894d4ffab725cc65f3cab9bea4644cfa89ee63966d385dbd5fa8a1e665ae2bf40744783fab580ee44e3dd2f0f3",
                "secret": "884e92c269dc7aa6745bbfa0e93e7e75",
                "notice": "Keep your Token & Secret a secret!"
            },
            "platform": "SwitchBot"
        }
    ]
}
```

### Device and Model

switchbot lock

### Node.js Version

v18.16.0

### NPM Version

v9.5.1

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.9.0

### Operating System

docker

**Comment by salemsayed** [comment]
noticing similar issues with the lock too, the status isn’t updating correctly and a full HB restart is required to fix it temporary

**Comment by donavanbecker** [comment]
Can you all try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.1-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

And report back.

**Comment by nadavko** [comment]
my problem stopped without me doing anything a couple of days ago

**Comment by spud-strabane** [comment]
i've recently discovered this bug at my end too
works fine via the SwitchBot app - but not via Home

**Comment by salemsayed** [comment]
> my problem stopped without me doing anything a couple of days ago

Same, so I thought I don’t need the beta. But then it happened again after a week. Anyway, installed the beta now and will report in a week if it’s all smooth

**Comment by salemsayed** [comment]
Unable to install beta, getting permissions error. Might me because it’s a child bridge? Made sure the permissions are correct

**Comment by spud-strabane** [comment]
@salemsayed  did you install the homebridge beta version, or the switchbot beta?

**Comment by spud-strabane** [comment]
i re-installed the door on the switchbot app and rebooted the hub itself, and it now appears to be working
will update if i observe any other issue[s]

**Comment by salemsayed** [comment]
> @salemsayed did you install the homebridge beta version, or the switchbot beta?

switchbot beta for sure, getting error on mkdir /nonexistent

**Comment by salemsayed** [comment]
Ok, fixed my errors and updated to beta, will report back
EDIT: Noticed there’s a new version released, does that include the fixes in beta or I should continue to test the beta? @donavanbecker

**Comment by salemsayed** [comment]
I’ve updated to latest beta (v2.10.0-beta1) and I still get a stuck lock on Home.app. It gets stuck in an unknown state with a reload button keeps refreshing

**Comment by salemsayed** [comment]
Hi, it’s still always stuck on Homekit. Anything I can do to help diagnose the issue?

**Comment by spud-strabane** [comment]
I see a new update was released, may be worth trying that and seeing if these is resolved? 

As mentioned, a switchbot hub reboot fixed my issues (for now)

**Comment by salemsayed** [comment]
I’m on the latest update. A reboot does fix it but only for some time and then it keeps not responding, so I’m not really sure what’s the problem here

**Comment by donavanbecker** [comment]
Can you turn debug logs on and post them?

**Comment by salemsayed** [comment]
> Can you turn debug logs on and post them?

Sure
https://pastebin.mozilla.org/pWcfxEg3

**Comment by salemsayed** [comment]
It’s always fixed with a hub reboot, which is weird because prior to the reboot, the hub is working fine through the Switchbot app
