### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by chris78664** [OpenWonderLabs/homebridge-switchbot#832]
### Describe the Bug

Update to versions over 2.8.0 fails due to a missing package and caused the child process to fail.

### To Reproduce

Update to 2.8.1-2.9.0 and receive attached errors for missing package causing a corrupted install

### Expected Behavior

A clean install and client keeps running and does not abort

### Relevant Log Output

```shell
10/6/2023, 9:05:30 AM] [Homebridge UI] [@switchbot/homebridge-switchbot] Terminating child process...
[10/6/2023, 9:05:30 AM] [Homebridge UI] [@switchbot/homebridge-switchbot] Child process ended

"Not sure were the install log is"
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "5cdf0619784b2cbeb1c2da2c75a8eb7bf6a718aa06e409233e52fe65586f5c19c6252397789857c5882501045bb04d81",
                "secret": "304e9bb9bac000b176cf6f06b4ba2c40",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "C67E6F0FC8A3",
                        "configDeviceName": "Living Room Air Scrubber Bot",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "E3B1206762D0",
                        "configDeviceName": "Living Room Air Scrubber Bot 2",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "D16C22CDC0EA",
                        "configDeviceName": "Family Room Air Scrubber Bot",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "E4586D5AB76E",
                        "configDeviceName": "Family Room Air Scrubber Bot 2",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch"
                        }
                    }
                ],
                "logging": "standard"
            },
            "_bridge": {
                "username": "0E:D2:2E:1B:D9:1C",
                "port": 54906
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

<img width="669" alt="Screenshot 2023-10-06 at 9 03 49 AM" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/1705913/7c72a994-adda-45c3-a003-102ff49c4514">
<img width="667" alt="Screenshot 2023-10-06 at 9 04 18 AM" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/1705913/4ff6a476-cf3f-4f37-a6c8-12dd483ef17b">
<img width="669" alt="Screenshot 2023-10-06 at 9 03 49 AM" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/1705913/151a823b-1cb9-4add-81b0-828bcf8f24cc">

### Device and Model

All switchbot devices

### Node.js Version

18.17.1

### NPM Version

9.6.7

### Homebridge Version

1.6.1

### Homebridge Switchbot Plugin Version

2.9.0

### Homebridge Config UI X Plugin Version

4.50.6

### Operating System

Docker

**Comment by donavanbecker** [comment]
Can you all try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.9.1-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

And report back.

**Comment by donavanbecker** [comment]
v2.9.1 has been released
