### ISSUE TITLE
Bug: failed to discover devices. cannot read property 'touppercase' of undefined

### ISSUE THREAD

**Issue by deflao** [OpenWonderLabs/homebridge-switchbot#84]
### Describe The Bug

All existing Switchbot devices disappeared in HomeKit

### To Reproduce

Install update (v1.0.1)

### Expected behavior

To still have all of my device and working normally

### Relevant log output

```shell
'failed to discover devices. cannot read property 'touppercase' of undefined'
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "secret",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                    "02-202109011807-50408529"
                ],
                "humidifier": {
                    "hide_temperature": true
                }
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

Raspberry Pi 4 Model B

### Node.js Version

14.18.1

### NPM Version

8.1.3

### Homebridge Version

1.3.6

### Homebridge Switchbot Plugin Version

1.0.1

### Homebridge Config UI X Plugin Version

4.41.2

### Operating System

Raspbian GNU/Linux Buster (10)

**Comment by donavanbecker** [comment]
@deflao You need to update your config. Remove:

```
"options": {
                "hide_device": [
                    "02-202109011807-50408529"
                ],
                "humidifier": {
                    "hide_temperature": true
                }
            },
```

And then reset up your device. I will make sure to fix this issue of old configs causing issues on start up though.

**Comment by deflao** [comment]
I’ve tried to clean install it too but same problem. Like when I do clean install, those lines weren’t even in the config but the problem still exists. I don’t want to re-install it cause it will cause my devices to disappear and it will mess with my HomeKit automation

**Comment by deflao** [comment]
Okay. It works now for some reason. But there’re other problems.
1st: Couldn’t hide IR device (DIY Fan). The hide device box is checked but it still appear in HomeKit.
2nd: hiding humidifier temperature option made it unresponsive in HomeKit. Here’s the log:
Humidifier Humidifier, Failed to update status. Error Message: "Cannot read property" updateCharacteristic of undefined"

**Comment by donavanbecker** [comment]
this will be fixed in the next release, currently in beta.

**Comment by donavanbecker** [comment]
I have release v1.0.2 with this fix.

**Comment by deflao** [comment]
> Okay. It works now for some reason. But there’re other problems.
> 1st: Couldn’t hide IR device (DIY Fan). The hide device box is checked but it still appear in HomeKit.
> 2nd: hiding humidifier temperature option made it unresponsive in HomeKit. Here’s the log:
> Humidifier Humidifier, Failed to update status. Error Message: "Cannot read property" updateCharacteristic of undefined"

These problems still occur with v1.0.2

**Comment by donavanbecker** [comment]
do you have logs?

**Comment by deflao** [comment]
![4181DD39-6A84-4A0C-8C28-90CCA7548643](https://user-images.githubusercontent.com/90084270/141924950-577dc4e8-a24e-4c26-a2be-b1e992e9dab8.jpeg)
Here you go

**Comment by deflao** [comment]
Hiding IR devices doesn’t produce any logs. It simply just didn’t hide at all since it’s still appear in the Home app

**Comment by donavanbecker** [comment]
> Here you go

looking at this log, it is a different issue. Please open new issue with more details and better logs. Screenshots don't give me much info to work off.

**Comment by donavanbecker** [comment]
> Hiding IR devices doesn’t produce any logs. It simply just didn’t hide at all since it’s still appear in the Home app

I will need logs, please open a separate issue on this so that I can track each issue separately and fix this issues.
