### ISSUE TITLE
Bug: node-switchbot not found; can't establish BLE connection

### ISSUE THREAD

**Issue by MartinVanVan** [OpenWonderLabs/homebridge-switchbot#842]
### Describe the Bug

I can't control my switchbot with homekit.
Homebridge is showing me these logs: 

- I've updated to the newest node version
- restarted homebridge mutliple times
- installed beta version of the homebridge-switchbot
- Also doesn't work with v2.9.0

### To Reproduce

just install and use it

### Expected Behavior

no errors switchbot can be controlled over homekit

### Relevant Log Output

```shell
[15/10/2023, 00:29:09] [SwitchBot] Bot: SwitchBot Door wasn't able to establish BLE Connection, node-switchbot: false
[15/10/2023, 00:29:09] [SwitchBot] Bot: SwitchBot Door Using OpenAPI Connection to Refresh Status
[15/10/2023, 00:31:09] [SwitchBot] Was 'node-switchbot' found: false
[15/10/2023, 00:31:09] [SwitchBot] Bot: SwitchBot Door wasn't able to establish BLE Connection, node-switchbot: false
[15/10/2023, 00:31:09] [SwitchBot] Bot: SwitchBot Door Using OpenAPI Connection to Refresh Status
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "xxxxxx",
        "secret": "xxxxxx",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "xxxxxx",
                "configDeviceName": "SwitchBot Door",
                "configDeviceType": "Bot",
                "connectionType": "BLE/OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "switch"
                },
                "external": true,
                "logging": "standard"
            }
        ]
    },
    "platform": "SwitchBot",
    "_bridge": {
        "username": "xxxxx",
        "port": 40109
    }
}
```

### Device and Model

SwitchBot

### Node.js Version

v18.18.2

### NPM Version

9.8.1

### Homebridge Version

v1.6.1 

### Homebridge Switchbot Plugin Version

v2.9.1

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
You may have to reinstall BLE prerequisites.

 
Bluetooth issues usually have nothing to do with the plugin, checkout the [Bluetooth Plugins Wiki](https://github.com/homebridge/homebridge/wiki/Bluetooth-Plugins).
