### ISSUE TITLE
Feature Request: Curtains 3

### ISSUE THREAD

**Issue by englishfox90** [OpenWonderLabs/homebridge-switchbot#846]
### Problem

Seems like the Curtain Rod 3 didn't pull in as a device automatically. I had to connect to the API endpoint (https://api.switch-bot.com/v1.1/devices), to get the deviceID and add it as a manually added device in the homebridge config

### Solution

The device should be able to automatically pull in as a device, or at least print the device ID in the logs for manually adding if needed

**Comment by donavanbecker** [comment]
Add device into the config using device settings.
