### ISSUE TITLE
Bug: v2.9.2 update error

### ISSUE THREAD

**Issue by deflao** [OpenWonderLabs/homebridge-switchbot#849]
### Describe the Bug

Fail to update to v2.9.2

### To Reproduce

Update plugin.

### Expected Behavior

Fail to update.

### Relevant Log Output

```shell
npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2023-10-28T01_40_37_947Z-debug-0.log
Failed to rebuild.
Restoring previous version...
Restore Complete. Installation failed.

Bundled install / update could not complete. Trying regular install / update using npm.

USER: pi
DIR: /var/lib/homebridge
CMD: npm install --save @switchbot/homebridge-switchbot@2.9.2

npm ERR! Invalid Version: 1.4.1-01

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2023-10-28T01_41_04_906Z-debug-0.log

Operation failed. Please review log for details.
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxxxx",
                "secret": "xxxxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "xxxxxxx",
                        "configRemoteType": "DIY Fan",
                        "irfan": {
                            "swing_mode": false
                        },
                        "logging": "none"
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

![Image 10-27-23 at 8 46 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/90084270/2d76db14-56e1-468d-a4ce-6bca3ea1a4bc)

### Device and Model

Raspberry Pi 4

### Node.js Version

v20.9.0

### NPM Version

10.2.1

### Homebridge Version

v1.6.1

### Homebridge Switchbot Plugin Version

v2.9.1

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by JBMJBM** [comment]
Having similar issue

**Comment by deflao** [comment]
Same problem on the latest version v2.10.0

**Comment by donavanbecker** [comment]
can you try installing using this command:
```
sudo npm install -g --unsafe-perm @switchbot/homebridge-switchbot
```

**Comment by JBMJBM** [comment]
How do I do that in the terminal?

**Comment by donavanbecker** [comment]
@JBMJBM, please open your own issue as this may be different then @deflao.

**Comment by JBMJBM** [comment]
Why am I copied on it then?

**Comment by donavanbecker** [comment]
> Having similar issue

Because of this comment, you left.

**Comment by deflao** [comment]
I've tried to updated using the command you gave, it didn't give me any error. I restarted homebridge but it still tell me that I have 1 plugin out of date.
