### ISSUE TITLE
Bug: Curtains alternate between open/close state in 1.0.0 & 1.0.1

### ISSUE THREAD

**Issue by dieugab** [OpenWonderLabs/homebridge-switchbot#85]
### Describe The Bug

The curtain state goes to open while closed or closed while open every few minutes even though they’re not being opened or closed

### To Reproduce

Nothing, it happens every few minutes regardless whether it’s open or closed

### Expected behavior

Should show the actual current state of either open or closed and stay at that

### Relevant log output

```shell
[15/11/2021, 11:55:48] Homebridge v1.3.6 (HAP v0.9.7) (Homebridge A93C) is running on port 51403.
[15/11/2021, 11:55:49] [SwitchBot] Total SwitchBot Devices Found: 7
[15/11/2021, 11:55:49] [SwitchBot] Adding new accessory: Woonkamer SwitchBot Curtain DeviceID: <HIDDEN>
[15/11/2021, 11:55:49] [SwitchBot] Adding new accessory: Achterdeur SwitchBot Curtain DeviceID: <HIDDEN>
[15/11/2021, 11:55:49] [SwitchBot] Total IR Devices Found: 0
[15/11/2021, 11:57:15] [SwitchBot] Achterdeur SwitchBot, Target Position: 0
[15/11/2021, 11:58:50] [SwitchBot] Achterdeur SwitchBot, Target Position: 100
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "HIDDEN",
                "notice": "Keep your token a secret!"
            },
```

### Screenshots

You can see it best in the Home Assistant history panel (when adding Homebridge to Home Assistant):

![5CE20DFC-5EB1-4AA6-BE38-146C41324478](https://user-images.githubusercontent.com/61377476/141771742-2e6715dc-a607-4d87-a809-bc600c502271.jpeg)

### Device & Model

SwitchBot Curtain

### Node.js Version

v16.13.0

### NPM Version

v8.1.3

### Homebridge Version

V1.3.6

### Homebridge Switchbot Plugin Version

V1.0.1

### Homebridge Config UI X Plugin Version

V4.41.2

### Operating System

Raspbian

**Comment by nyjklein** [comment]
I have something weird going on with my curtains too with V1.0.1. Similar to issues I was having months back. Even though I have minstep, min and max set like I always have, homebridge is now reporting "98% open" or "2% closed" and the iOS Home app is out of sync (reports open when closed or vice versa) or stuck on "closing" until I click on it. Please let me know if you would like more documentation.

Jeff

**Comment by donavanbecker** [comment]
I will look into this @gvssr.

**Comment by nyjklein** [comment]
With V1.0.2, I'm still seeing this weirdness. Even though the curtains are fully open, the Home app shows closed with a spinning gear in accessories view. The "action view" at the top shows "curtain closing". If I click on the accessory in the Home App, it immediately changes to "open". But as soon as the homebridge pushes it out a status update, it reverts back to "closing". 

[16/11/2021, 11:50:22] [SwitchBot] [DEBUG] Curtain Living Room Curtain updateHomeKitCharacteristics - {"CurrentPosition":100,"PositionState":2,"TargetPosition":100,"CurrentAmbientLightLevel":100000}

P.S. Am I remembering wrong, weren't you able to set the curtain options, e.g. min. max, minstep in the GUI? Now I can only set them in the json manually and I'm not sure if they're being read.

**Comment by donavanbecker** [comment]
@gvssr and @nyjklein, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.0.3-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by nyjklein** [comment]
It's better. But not quite there yet. Now it's the accessory within Homebridge that gets "stuck" at "Opening" or "Closing" even though the Home app now shows Open or Closed. And now it's out of sync. Home bridge shows opening, home shows closed (physically fully open). Status in homebridge shows:


Window Covering	
Current Position	0%
Position State	1
Target Position	0%

Is position state 1 the "moving" state?

Although the log shows this:
```
[16/11/2021, 18:21:39] [SwitchBot] [DEBUG] Curtain: Living Room Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 2,
```

**Comment by nyjklein** [comment]
And now Home app is showing "99% Open". So It looks like the "set_Min" and "set_Max" config settings may be ignored.

**Comment by nyjklein** [comment]
I'm on V1.1.0 now. But the Homebridge accessory for the curtain still shows "Opening" or "Closing" even though movement has completed. 

Also, I was unclear about your last comment on the commit regarding the set_Min, set_Max settings. I'm still seeing the "99% Open" and "2% closed" in the Home App. Am I missing something?

Lastly, quite some time back I pushed refreshRate all the way up 600 to avoid API lockouts. Can I bring that down to a  lower level?

Jeff

```
[17/11/2021, 08:47:05] [SwitchBot] [DEBUG] Curtain: Living Room Curtain Refresh Status When Moving, PositionState: 1
[17/11/2021, 08:47:05] [SwitchBot] [DEBUG] Curtains OpenAPI Device RefreshStatus
[17/11/2021, 08:47:06] [SwitchBot] [DEBUG] Curtain: Living Room Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"DFC80D28CE14","deviceType":"Curtain","hubDeviceId":"DF7B6DA19FE7","calibrate":true,"group":false,"moving":false,"slidePosition":0},"message":"success"}
[17/11/2021, 08:47:06] [SwitchBot] [DEBUG] Curtain Living Room Curtain CurrentPosition - Device is Currently: 100
[17/11/2021, 08:47:06] [SwitchBot] [DEBUG] Curtain: Living Room Curtain Standby, Current position: 100
[17/11/2021, 08:47:06] [SwitchBot] [DEBUG] Curtain: Living Room Curtain CurrentPosition: 100, TargetPosition: 100, PositionState: 2,
[17/11/2021, 08:47:06] [SwitchBot] [DEBUG] Curtain: Living Room Curtain CurrentAmbientLightLevel: 100000
[17/11/2021, 08:55:25] [SwitchBot] [DEBUG] Curtains OpenAPI Device RefreshStatus
[17/11/2021, 08:55:26] [SwitchBot] [DEBUG] Curtain: Living Room Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"DFC80D28CE14","deviceType":"Curtain","hubDeviceId":"DF7B6DA19FE7","calibrate":true,"group":false,"moving":false,"slidePosition":1},"message":"success"}
[17/11/2021, 08:55:26] [SwitchBot] [DEBUG] Curtain Living Room Curtain CurrentPosition - Device is Currently: 99
[17/11/2021, 08:55:26] [SwitchBot] [DEBUG] Curtain: Living Room Curtain Standby, Current position: 99
[17/11/2021, 08:55:26] [SwitchBot] [DEBUG] Curtain: Living Room Curtain CurrentPosition: 99, TargetPosition: 99, PositionState: 2,
[17/11/2021, 08:55:26] [SwitchBot] [DEBUG] Curtain: Living Room Curtain CurrentAmbientLightLevel: 100000
```

**Comment by donavanbecker** [comment]
> Lastly, quite some time back I pushed refreshRate all the way up 600 to avoid API lockouts. Can I bring that down to a lower level?

Yes you can move it down.

**Comment by nyjklein** [comment]
I'm really confused. Has the syntax of the config.json changed. I changed my my debug option from debug to device. Now I'm seeing this in the log:

[18/11/2021, 16:27:38] [SwitchBot] [DEVICE] Curtain: Living Room Curtain Config: (ble: undefined, disable_group: undefined, hide_lightsensor: undefined, set_minLux: undefined, set_maxLux: undefined, refreshRate: undefined, set_max: undefined, set_min: undefined, set_minStep: undefined)

But here's what I have in config:
            "name": "SwitchBot",
            "credentials": {
                "openToken": "369d3090ebe8ada4ae639960649971bb0bf38c9ae0c39c509fd8c4cdde5a3c27bb6cc5ca8c4727313ceba273938ef6f0",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 180,
                "debug": "device",
                "hide_device": [
                    "D8E9AA74909F"
                ],
                "humidifier": {
                    "hide_temperature": true,
                    "set_minStep": 33
                },
                "curtain": {
                    "set_minStep": 20,
                    "set_min": 3,
                    "set_max": 97
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        }

Is this syntax (i.e. curtain") no longer valid. Is this supposed to be in a "devices" directive? I so, what's the syntax for that devices directive? Can't find it here!

Jeff

**Comment by nyjklein** [comment]
Nevermind! Figured out how to use the "Devices" directive and this fixed my issue !!!

                "devices": [
                    {
                        "deviceId": "DFC80D28CE14",
                        "hide_device": false,
                        "deviceType": "curtain",
                        "ble": false,
                        "curtain": {
                            "set_minStep": 20,
                            "set_min": 3,
                            "set_max": 97
                        }
                    }
                ]

Now I get this:
[18/11/2021, 16:47:06] [SwitchBot] [DEVICE] Curtain: Living Room Curtain Config: (ble: false, disable_group: undefined, hide_lightsensor: undefined, set_minLux: undefined, set_maxLux: undefined, refreshRate: undefined, set_max: 97, set_min: 3, set_minStep: 20)

**Comment by donavanbecker** [comment]
@nyjklein Yes.

**Comment by nyjklein** [comment]
Is this new syntax defined somewhere? The "Configuration" link in this WiKi, still shows the old syntax.

Jeff

**Comment by donavanbecker** [comment]
Haven’t had time to update.

**Comment by donavanbecker** [comment]
Version 1.2.0 has been released, Please update me on this, and if it has been resolved with this version. 

Also Configuration wiki link has a Work In Progress Config description and example

**Comment by nyjklein** [comment]
For the most part everything seems to be working accept the accessory icon within Homebridge. It's always suck at "opening" or "closing". I've posted some screen captures that show the "Debug=Device" output and the curtain accessory.



![image](https://user-images.githubusercontent.com/76184316/142729566-9299ace2-4fa3-49be-acb6-1e0f50b38591.png)

![image](https://user-images.githubusercontent.com/76184316/142729629-0f152440-cd1d-4d8c-a4ab-f8b27c31bb67.png)

![image](https://user-images.githubusercontent.com/76184316/142729675-f87de9e5-d2db-4198-98f8-ed7947ca3dd1.png)

**Comment by dieugab** [comment]
I'm having the same issue as @nyjklein. Curtain state hangs at opening or closing. Also shows up in HomeKit and Home Assistant as opening or closing after initializing a command, never as open or closed.

**Comment by nyjklein** [comment]
And now my Homekit status has also gone wacky. Shows "90% Open" with a spinning clock/gear. Switchbot app shows "Fully open" with one side at 0% and the other at 1%. 

P.S. This is API only.

Jeff

**Comment by donavanbecker** [comment]
@gvssr And @nyjklein did you set your min and max In the config for your device?

**Comment by dieugab** [comment]
@donavanbecker no, I've never touched the min/max settings.

**Comment by nyjklein** [comment]
Yes:
                       

```
 "deviceId": "xxxxxxxxxx",
                        "hide_device": false,
                        "configDeviceType": "Curtain",
                        "ble": false,
                        "curtain": {
                            "set_minStep": 10,
                            "set_min": 3,
                            "set_max": 97
                        }```
 
And log output:
[20/11/2021, 09:45:43] [SwitchBot] [DEVICE] Curtain: Living Room Curtain Config: (ble: false, disable_group: undefined, hide_lightsensor: undefined, set_minLux: undefined, set_maxLux: undefined, refreshRate: undefined, set_max: 97, set_min: 3, set_minStep: 10)

**Comment by donavanbecker** [comment]
@nyjklein What does the SwitchBot app say it's at?

**Comment by nyjklein** [comment]
![Screenshot 2021-11-20 at 10 39 07 AM](https://user-images.githubusercontent.com/76184316/142732348-bd377649-698f-45aa-8e87-36cf5d972a63.png)

**Comment by donavanbecker** [comment]
> @donavanbecker no, I've never touched the min/max settings.

@gvssr, since the SwitchBot doesn't always fully close in some cases. I would recommend setting that for each curtian. I have it set at `max: 95` and `min: 5`

You will have to input each deviceid into the config, pick curtain then you should see the min and max, not the Lux ones.

**Comment by nyjklein** [comment]
And the main SwitchBot app screen shows "Fully Closed".

P.S. This was all working fine with these settings before the recent V1.x.x updates.

**Comment by dieugab** [comment]
> > @donavanbecker no, I've never touched the min/max settings.
> 
> @gvssr, since the SwitchBot doesn't always fully close in some cases. I would recommend setting that for each curtian. I have it set at `max: 95` and `min: 5`
> 
> You will have to input each deviceid into the config, pick curtain then you should see the min and max, not the Lux ones.

@donavanbecker that does not fix the issue. Even with min/max set it stays on "opening" and "closing". Even when the SwitchBot app reports the state as fully closed or fully opened

**Comment by donavanbecker** [comment]
@gvssr & @nyjklein, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.2.1-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by dieugab** [comment]
@donavanbecker not resolved in the beta. Still stays on "closing" or "opening" indefinitely after issuing a command. And now also no longer displays closed correctly at all (edit: this could be related to the "closing" issue though). See screenshot
![image](https://user-images.githubusercontent.com/61377476/142742392-a91278b9-a5ca-4abe-b5a1-98e11bf5d481.jpeg)

Not sure if it helps, but fyi none of these issues were there for me on 0.1.1

**Comment by donavanbecker** [comment]
I will look at 0.1.1

**Comment by nyjklein** [comment]
No change here either. When opening, Home app initially goes to "Open" but HB accessory stays at "Opening". After the refresh interval, the Home App changes to 90% Open (seems to correspond to "set_minstep" value (100-10) with spinning clock.

**Comment by donavanbecker** [comment]
@gvssr and @nyjklein okay new beta is out. Can you try the new Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.2.1-beta.1/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by nyjklein** [comment]
Sorry. This is worse. Now accessory says "Opening", Homekit says "Closed" and curtains don't move when clicking on them in Home app. It briefly turns to "Open" and then right back to "Closed".


[homebridge.log.txt](https://github.com/OpenWonderLabs/homebridge-switchbot/files/7583251/homebridge.log.txt)

**Comment by nyjklein** [comment]
Another "anomoly". The detailed status shown in Homebridge does not match what the log says. Positionstate is different! Snapshot here. Log posted above.
![image](https://user-images.githubusercontent.com/76184316/142910687-f81df607-9e51-4210-9eac-8ea34635922b.png)

**Comment by nyjklein** [comment]
And after I open the curtains with the switchbot app, now the accessory shows positionstate 1 even though the log shows 2.
![image](https://user-images.githubusercontent.com/76184316/142911576-f9db2e8f-ffe8-4cf9-a99d-ec59315cd8ca.png)

**Comment by dieugab** [comment]
@donavanbecker sadly, no change for me. Still hangs on “opening…” and “closing…” even though SwitchBot app reports they’re both closed. Setting min/max (in this case 10 / 90) also doesn’t effect it.

![E4013653-400C-41ED-A8E6-6831E561D6FB](https://user-images.githubusercontent.com/61377476/142913643-0594d66f-0ac3-4417-8ab6-0644805b9e6f.jpeg)
![16081D7B-0CC2-4642-8137-EA201468A392](https://user-images.githubusercontent.com/61377476/142913741-97cfbc71-8202-417d-b1ef-f131b803b590.jpeg)

**Comment by dieugab** [comment]
@donavanbecker maybe this will help, you can see a direct comparison between the old version and new version:

V1.2.1 beta (stays stuck like this)
https://user-images.githubusercontent.com/61377476/142916171-018dfb15-7cf7-40ff-b3cb-88dcef660603.mov

V0.1.1 (works)
https://user-images.githubusercontent.com/61377476/142916333-32470bee-6158-41b4-bdc9-5cf6206cb19d.mov

**Comment by donavanbecker** [comment]
going to be honest, I care about Home app, not homebridge accessories. so if it is working good in the home app, that's what we want. I didn't have any issues before I pushed the last beta. So if the home app is working fine then this issue can be closed.

**Comment by nyjklein** [comment]
With the latest beta, the home app is NOT working at all. It won't initiate an open or close. In the previous non-beta build, it was partially working. It would initiate the action, change to "Open" or "Closed". But when the refresh interval hit, it would change to, e.g. 90% open. Then you would need to click once to trick it to think it was open in order to click to close.

**Comment by donavanbecker** [comment]
I have reverted in latest beta if you can test.

**Comment by nyjklein** [comment]
Testing with v1.2.1-beta4. The Homebridge app accessory still consistently shows "Opening" or "Closing". While the Home app device now shows the spinning clock after the refresh interval. v1.2.1-beta1 may actually have been better. After recycling homebridge (and updating to HB v1.3.8), at least the Home app device seemed to be working right.

**Comment by donavanbecker** [comment]
@nyjklein So we are good?

**Comment by donavanbecker** [comment]
Just released v1.2.1. if you have any other issues please open a new issue. I believe this is fixed with this release. I am not having these issues with BLE.

**Comment by dieugab** [comment]
@donavanbecker still hangs on "closing" and "opening" for me unless I restart homebridge after each command. I guess I'll just stay on 0.1.1. It's your free time of course, but it's a little saddening to see functionality regressed like this.

**Comment by donavanbecker** [comment]
@gvssr I am not having the issues you are having.

If you can figure out a fix for your issue, feel free to open a pull request and I will merge it. But as I said I don't have these issues.

**Comment by dieugab** [comment]
@donavanbecker I don't have a programmer's background so would have no idea where to start. From comparing 0.1.1 and latest my guess it's due to this code change (for example 'closing'):

**0.1.1**
```
      if (this.deviceStatus.body.moving) {
        if (this.TargetPosition > this.CurrentPosition) {
          this.platform.debug(
            'Curtain %s -',
            this.accessory.displayName,
            'Current position:',
            this.CurrentPosition,
            'closing',
          );
          this.PositionState = this.platform.Characteristic.PositionState.INCREASING;
```

**Latest**
```
      if (this.deviceStatus.body.moving) {
        this.setMinMax();
        if (this.TargetPosition > this.CurrentPosition) {
          this.platform.debug(`Curtain: ${this.accessory.displayName} Closing, CurrentPosition: ${this.CurrentPosition} `);
          this.PositionState = this.platform.Characteristic.PositionState.INCREASING;
```

**Comment by nyjklein** [comment]
I'm up on v1.2.5 now and have BLE enabled. I'm still consistently getting the Homebridge accessory stuck on "Opening" and "Closing". The HomeKit view is strange. It now consistently goes to a partial state (e.g. 60% open) but after a refresh interval it USUALLY goes to the fully opened or closed state. But not always.

**Comment by nyjklein** [comment]
Also, I'm really confused about logging. First, I see different information when selecting Device or Debug as expected. But I think it would be much better if Debug included Device logging.

**Comment by donavanbecker** [comment]
> Also, I'm really confused about logging. First, I see different information when selecting Device or Debug as expected. But I think it would be much better if Debug included Device logging.

@nyjklein, this has been updated to make it more simple

**Comment by donavanbecker** [comment]
v1.111.0 should resolve this.
