### ISSUE TITLE
Plugin shoes No Devices

### ISSUE THREAD

**Issue by hansw1204** [OpenWonderLabs/homebridge-switchbot#858]
### Describe Your Problem

Had an issue and purged the devices from HomeBridge cache and re-installed the plugin. Now, after I enter the Token and Secret, no devices show up. I have a HUb2 and a Bot

### Relevant log output

```shell
[11/4/2023, 2:17:12 PM] [SwitchBot] Requests reached the daily limit, statusCode: 190
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "XXXXXXX",
        "secret": "YYYYYYY",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "refreshRate": 10,
        "pushRate": 1,
        "logging": "debug"
    },
    "_bridge": {
        "username": "64:E8:33:E4:BE:64",
        "port": 54050
    },
    "platform": "SwitchBot"
}
```

### Device & Model

Switchbot Hub 2, Switch Bot Bot

### Node.js Version

18.16.0

### NPM Version

2.10.1

### Homebridge Version

1.7.0

### Homebridge SwitchBot Plugin Version

2.10.1

### Homebridge Config UI X Plugin Version

4.52.0

### Operating System

Docker

**Comment by donavanbecker** [comment]
As logs say, you have meet your daily refresh limit. Raise your refresh and try again in 24 hours.

**Comment by hansw1204** [comment]
Thank you , Donavan! How do change the refresh rate, please? many thanks, Hans From: Donavan Becker ***@***.***>Date: Saturday, November 4, 2023 at 14:30To: OpenWonderLabs/homebridge-switchbot ***@***.***>Cc: HaWi ***@***.***>, Author ***@***.***>Subject: Re: [OpenWonderLabs/homebridge-switchbot] Plugin shoes No Devices (Issue #858)As logs say, you have meet your daily refresh limit. Raise your refresh and try again in 24 hours.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by donavanbecker** [comment]
Closing as I can't read any of that.
