### ISSUE TITLE
Support Request: Homebridge to Home Assistant to HomeKit

### ISSUE THREAD

**Issue by akballow** [OpenWonderLabs/homebridge-switchbot#860]
### Describe Your Problem

I can see all the sensors in home assistant no problem but for some reason when using homekit to my iphone all the sensors show no response. I am not sure if I am doing something wrong or missing a step. I do nothing different with my other homebridge to home asssistant to homekit apps. Otherwsie everything is working perfectly~!

### Device & Model

outdoor tempature sensor

### Node.js Version

v20.9.0

### NPM Version

1.7

### Homebridge Version

1.7

### Homebridge SwitchBot Plugin Version

@switchbot/homebridge-switchbot v2.10.1

### Operating System

Ubuntu Docker

**Comment by donavanbecker** [comment]
Wait so are you using home assistant or this plugin to push to HomeKit? 

And if it is this plugin, which devices? Can you got to the plugins setting's device tab and can you see the devices there?

**Comment by akballow** [comment]
So i use this plugin in homebridge ![Screenshot 2023-11-06 at 12 10 47 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/2824631/73e149e5-911f-488e-9297-c253fa4a79ed)

I connect the homebridge to home assistant via the homebridge kit plugin
![Screenshot 2023-11-06 at 12 11 57 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/2824631/bd83a7c3-0757-4c1c-95b8-1a788d7a80cb)

The sensors work no problem in HA
![Screenshot 2023-11-06 at 12 12 31 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/2824631/e8c30ebe-b48a-4544-a306-80b6e756897f)

But when using on my home app on the phone I get no response.
![Screenshot 2023-11-06 at 12 12 59 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/2824631/5caa9fcf-1a81-469c-bcdd-3c5daa1225a1)

**Comment by akballow** [comment]
I do the same workflow with homebridge ring setup, so i think the issue is at this app level.

**Comment by donavanbecker** [comment]
How are you pushing them to HomeKit (Home App) if you have the bridge in HomeAssistant?

Why not just use the SwitchBot BLE or Cloud integration in HomeAssistant? And put this plugin directly into HomeKit (Home App)

**Comment by akballow** [comment]
switchbot Cloud HA plugin doesn't have many supported devices it seems.

**Comment by donavanbecker** [comment]
> switchbot Cloud HA plugin doesn't have many supported devices it seems.

Still doesn't answer this question:

> How are you pushing them to HomeKit (Home App) if you have the bridge in HomeAssistant?

**Comment by akballow** [comment]
![Screenshot 2023-11-06 at 12 33 39 PM](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/2824631/1e86534d-c69e-4e00-89f7-e3c45a4bba67)
The built in homekit homebridge apps

**Comment by donavanbecker** [comment]
Well then this isn't an issue with the plugin, but with how home assistant is handling the services & characteristics that this plugin is sending over.

If you add this plugin into HomeKit directly and are still having issues, I can look into it further. 

I think best route is to close this issue, open an issue with HomeAssitant, requesting support for other device. Directing them to this plugin if they need help.

**Comment by akballow** [comment]
Will do thank you for taking a look.
