### ISSUE TITLE
Feature Request: Stateless Buttons for IR Light Device

### ISSUE THREAD

**Issue by neegool** [OpenWonderLabs/homebridge-switchbot#863]
### Problem

Currently IR lights are represented as toggle switches in HomeKit. While this works fine, an option to add stateless buttons would be better suited for lights which have separate buttons for On and Off. 

### Solution

Expose extra buttons to the accessory in HomeKit (either within the same accessory, or as extra buttons as part of an accessory group). One button is for On, and one button is for Off.

**Comment by donavanbecker** [comment]
@neegool Feel free to open a PR

**Comment by donavanbecker** [comment]
Support added in v2.12.0, please open new issue if you have any issues.

This can be enable by setting the Stateless config, by inputting your IR light deviceID into the IR Device Settings.

**Comment by neegool** [comment]
Thanks for the update! However when I tried it on an IR Light, it gives me "This accessory is not currently supported by the Home app."

**Comment by donavanbecker** [comment]
Yep because stateless switches are only available in 3rd party apps. Let me try one more thing.
