### ISSUE TITLE
Bug: Curtain Appears Motion Sensor

### ISSUE THREAD

**Issue by qoodanny** [OpenWonderLabs/homebridge-switchbot#877]
### Describe the Bug

It should not appear a motion sensor.
If a must, please add a setting to turn it off

### To Reproduce

Home App

### Expected Behavior

No motion sensor on curtain

### Relevant Log Output

```shell

```

### Config for homebridge-switchbot

```shell
{
                        "deviceId": "",
                        "configDeviceName": "Bed Room Curtain",
                        "hide_device": false,
                        "configDeviceType": "Curtain",
                        "connectionType": "BLE/OpenAPI",
                        "curtain": {
                            "hide_lightsensor": true
                        },
                        "history": true,
                        "external": false
                    },

```

### Device and Model

Rod 2

### Node.js Version

v18.18.2

### Homebridge Version
1.7
### Homebridge Switchbot Plugin Version

2.12.1

### Homebridge Config UI X Plugin Version

4.53

### Operating System

Raspberry Pi

**Comment by donavanbecker** [comment]
See #797
