### ISSUE TITLE
Feature Request: Save State of Switchbot Bot

### ISSUE THREAD

**Issue by McDin** [OpenWonderLabs/homebridge-switchbot#882]
### Problem

Is there an option that the Bot stays on in HomeKit after setting it to on? After pressing the button the Bot turns on in HomeKit but after it it returns to off. It would be nice if it stays on until I set it to off and the state is saved.

### Solution

An option for save state

**Comment by donavanbecker** [comment]
@McDin what is your config?

**Comment by McDin** [comment]
{
    "name": "SwitchBot",
    "credentials": {
        "token": "...",
        "secret": "....",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "DE9D85E3BC3A",
                "configDeviceName": "Haustür",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "door"
                },
                "lock": {
                    "activate_latchbutton": false
                }
            },
            {
                "deviceId": "DDEED064F0C9",
                "configDeviceName": "Server",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "outlet"
                },
                "lock": {
                    "activate_latchbutton": false
                }
            }
        ]
    },
    "_bridge": {
        "username": "0E:96:E3:54:92:3F",
        "port": 58493
    },
    "platform": "SwitchBot"
}

**Comment by donavanbecker** [comment]
When you have a SwitchBot set to switch, it will always go right to off. If you are wanting it to keep its state then you need to switch it to switch instead of press
