### ISSUE TITLE
Feature Request: Replace IR Aircon "Current Temperature" with reading from SwitchBot Thermometer & Hygrometer

### ISSUE THREAD

**Issue by NikkoXIV** [OpenWonderLabs/homebridge-switchbot#885]
### Problem

The temperature in Homekit always reads as "24°c" on all my IR Air Conditioners.  I do have SwitchBot Thermometer & Hygrometers in each room which shows the correct temperature.  It would be nice if there was a configuration option to use the "Current Temperature" reading from another device to replace the static number that the IR device shows.

### Solution

Add a configuration option to replace "Current Temperature" for an IR Aircon with another Switchbot device.  The user would specify the temperature sensor's device name or device id and the plugin would report that device's "Current Temperature" as the IR Aircon's "Current Temperature".

### Alternatives

If the specified device doesn't have a "Current Temperature" or the device becomes unavailable, then it reverts to 24°c.

### Additional context

It would be a nice quality of life thing to have the numbers on the IR Aircon units be accurate instead of a static number that can't change.  I'm not sure what restrictions exist that may prevent it from being possible, but if you can, that would be great!  And if I missed a setting that would let me, then sorry!  I tried to look, but I'm fairly new to homebridge.  Thanks for the plugin!

**Comment by donavanbecker** [comment]
This is already possible

**Comment by NikkoXIV** [comment]
Sorry for the bother then. Is there documentation about how to do it?  The only thing I saw in IR Aircon config instructions was to disable auto mode.  When I searched the web I only found old comments.

**Comment by NikkoXIV** [comment]
I didn't realize that the IR Device settings section actually wrote the json code for you.  Since my devices were already listed in the devices tab, I thought that I didn't need to "Add a new IR Device".  I didn't realize that I could use that area to configure my existing devices.  Maybe for dum-dums like me that don't make the connection, adding a button to the devices tab with "Configure this device" would help.  Then it could populate the device ID, name and type into the IR Device settings so you can make the rest of the changes.

**Comment by donavanbecker** [comment]
> I didn't realize that the IR Device settings section actually wrote the json code for you.  Since my devices were already listed in the devices tab, I thought that I didn't need to "Add a new IR Device".  I didn't realize that I could use that area to configure my existing devices.  Maybe for dum-dums like me that don't make the connection, adding a button to the devices tab with "Configure this device" would help.  Then it could populate the device ID, name and type into the IR Device settings so you can make the rest of the changes.

Yeah, I would like to do that, but don't know how too... :)
