### ISSUE TITLE
Feature Request: switchbot curtain 3

### ISSUE THREAD

**Issue by kokono9201** [OpenWonderLabs/homebridge-switchbot#889]
### Solution

support to switchbot curtain 3
https://www.switch-bot.com/products/switchbot-curtain-3?variant=43417958744231

**Comment by donavanbecker** [comment]
All ready works.

**Comment by donavanbecker** [comment]
https://github.com/OpenWonderLabs/homebridge-switchbot/issues/888#issuecomment-1872092308

**Comment by kokono9201** [comment]
thank you!
but somehow my homebridge cannot recognize the device
the version is already v2.13.2

**Comment by donavanbecker** [comment]
did you put your deviceID into your config?  because it definitely will if you do.

**Comment by kokono9201** [comment]
Sovled!
Thank you a lot!
