### ISSUE TITLE
Bug: unable to communicate with switchbot thermometer?

### ISSUE THREAD

**Issue by TomBolt22** [OpenWonderLabs/homebridge-switchbot#894]
### Describe the Bug

When i connected the app to the homebridge it wont update the temp in the homebridge app, keeps registering 0 degrees. error: [SwitchBot] Meter: Thermometer refreshStatus enableCloudService: undefined homebridge

### To Reproduce

install the plugin to homebridge then connect a thermostat, mine says:
[SwitchBot] Meter: Thermometer refreshStatus enableCloudService: undefined homebridge

### Expected Behavior

Thermometer not working

### Relevant Log Output

```shell
[SwitchBot] Meter: Thermometer refreshStatus enableCloudService: undefined homebridge
```

### Config for homebridge-switchbot

```shell
i dont have this as i uninstalled it as it caused homebridge to keep crashing
```

### Device and Model

Thermometer

### Node.js Version

v20.11.0

### NPM Version

unsure?

### Homebridge Version

v1.7.0

### Homebridge Switchbot Plugin Version

V2.14.0

### Homebridge Config UI X Plugin Version

v4.55.1

### Operating System

Raspian

**Comment by donavanbecker** [comment]
First of all how did this cause Homebridge to crash? Sounds like there is more in the logs that you aren't sharing.

Second, I would recommend setting up a child bridge for every plugin, so if it does go into a restart on the child bridge restarts.

Third, the logs are clear, you don't have cloud services enabled on your devices. Once you enable that, it will work.
![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/9875439/6c03147f-5366-4335-bd6a-bb54835fb80c)
