### ISSUE TITLE
Support Request: Switchbot on Hoops has ceased working - Help appreciated.

### ISSUE THREAD

**Issue by johnrotellini** [OpenWonderLabs/homebridge-switchbot#895]
### Describe Your Problem

The plugin has stopped functioning, even though it has been solid for a couple of years now - I have restarted, uninstalled, reinstalled and checked to see if the issue was unique to the current build vs. an older build.  Unfortunately, I still get the following errors which I will put into the "relevant log output" section:

### Relevant log output

```shell
1/29/2024, 6:33:28 PMSwitchbot Bridge - HendersonERRORError loading plugin "@switchbot/homebridge-switchbot"
1/29/2024, 6:33:28 PMSwitchbot Bridge - HendersonERRORReadableStream is not defined
1/29/2024, 6:33:28 PMSwitchbot Bridge - HendersonERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/switchbotbridge/node_modules/undici/lib/fetch/response.js:516:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/switchbotbridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/switchbotbridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
```

### Device & Model

HOOBS HSLF-1

### Node.js Version

16.20.2

### NPM Version

not sure

### Homebridge Version

1.7.0

### Homebridge SwitchBot Plugin Version

2.14.0

### Homebridge Config UI X Plugin Version

4.3.1

### Operating System

macOS

**Comment by donavanbecker** [comment]
The title says hoops but I am guessing you meant HOOBs, if that's the case:


This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by johnrotellini** [comment]
Hi, Donovan - it’s been working perfectly for almost two years until recently and has a number of video walkthroughs (several I had followed to install and set up) demonstrating it working in HOOBs. So I’m a bit confused as to how it can work for such a long time and then abruptly stop. Please forgive me if I’m at all being dense here. Thank you for your time and attention. It is much appreciated.Cheers,JohnOn Jan 29, 2024, at 9:14 PM, Donavan Becker ***@***.***> wrote:﻿
The title says hoops but I am guessing you meant HOOBs, if that's the case:
This plugin isn't developed for HOOBs.
I would recommend moving to homebridge.

**Comment by donavanbecker** [comment]
As stated before, this Plugin wasn't designed for HOOBs. So which to Homebridge and if you still have the issue then we can look into it further.

**Comment by frankea** [comment]
The ReadableStream API is a part of the Streams API which is widely used in web applications for handling streaming data. However, in Node.js, streams have been implemented differently, and certain features like ReadableStream from the Web Streams API might not be available in older versions of Node.js. Ensure you are running a version of Node.js that supports the ReadableStream API or the features of the undici library that require it.

Updating Node.JS to the latest version resolved it for me.

**Comment by donavanbecker** [comment]
@frankea HOOBs support will not be provided.

**Comment by frankea** [comment]
Didn't ask for it to be, just trying to help the other guy and maybe take some issues off your plate with a fix.

**Comment by donavanbecker** [comment]
Thanks for doing that, but users of HOOBs should be going to HOOBs or switch to Homebridge.

**Comment by frankea** [comment]
Given that Google brought me here based on the error, I'd expect you'd get a few more coming your way, so hopefully this will save you some time.  It's technically not a Hoobs specific issue either since it's Hoobs is an npm package installed in Node, which is the part that needs to be updated.  It's the plugin code (running on and old version of Node) invoked by Hoobs generating the error.  The user above is on Node 16 with the latest being 20.

Before trying to setup the switchbot plugin today, I'd never actually heard of homebridge-config-ui-x.  I started using Hoobs years ago because I wanted a UI, but I've never really loved using it.  I'll likely make the switch back to homebridge now that I know about the UI option.  Also since I can't actually get any devices or debug logging to show up with the plugin in Hoobs and I'm tired of troubleshooting it.

**Comment by donavanbecker** [comment]
Once on Homebridge and Homebridge UI (homebridge-config-ui-x) I would be willing to help

**Comment by johnrotellini** [comment]
How does one do that?John RotelliniRotellini Entertainment LTD.+1.702.518.2273 (Office)+1.307.752.2754 ***@***.***://www.johnrotellini.comhttp://www.rotellinientertainment.comSkype: johnrotellini      On Jan 31, 2024, at 6:59 AM, Adam Franke ***@***.***> wrote:﻿
The ReadableStream API is a part of the Streams API which is widely used in web applications for handling streaming data. However, in Node.js, streams have been implemented differently, and certain features like ReadableStream from the Web Streams API might not be available in older versions of Node.js. Ensure you are running a version of Node.js that supports the ReadableStream API or the features of the undici library that require it.
Updating Node.JS to the latest version resolved it for me.

**Comment by frankea** [comment]
> How does one do that?

Depends on your OS.  I have it on a Raspberry Pi which is Debian based, so I used these steps: https://deb.nodesource.com/

Find your OS here: https://github.com/nodesource/distributions and ask them if you run into issues.
