### ISSUE TITLE
Unable activate switchbot after update to 3.00 

### ISSUE THREAD

**Issue by corasaniti** [OpenWonderLabs/homebridge-switchbot#899]
### Describe the Bug

With the latest update from version 2.13 to 3.00 everything stopped working.
I can no longer activate my switchbots

### To Reproduce

try press switchbot plugin

### Expected Behavior

Activate my switchbot

### Relevant Log Output

```shell
Activate my switchbot
```

### Config for homebridge-switchbot

```shell
only switch bot section

{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "secret": "xxxxxxxxxxxxxxxxxxxxxxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xxxxxxxxxxxxxxxxxxxxxxxx",
                        "configDeviceName": "Proxmox",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "webhook": true,
                        "lock": {
                            "activate_latchbutton": false
                        }
                    },
                    {
                        "deviceId": "xxxxxxxxxxxxxxxxxxxxxxxx",
                        "configDeviceName": "NAS",
                        "configDeviceType": "Bot",
                        "connectionType": "OpenAPI",
                        "webhook": true,
                        "lock": {
                            "activate_latchbutton": false
                        }
                    }
                ],
                "irdevices": [
                    {
                        "deviceId": "xxxxxxxxxxxxxxxxxxxxxxxx",
                        "configDeviceName": "TV",
                        "configRemoteType": "TV",
                        "connectionType": "OpenAPI"
                    }
                ]
            },
            "platform": "SwitchBot"
},
```

### Device and Model

Activate my switchbot

### Node.js Version

v18.19.0

### NPM Version

10.2.3

### Homebridge Version

v1.7.0

### Homebridge Switchbot Plugin Version

v3.00

### Homebridge Config UI X Plugin Version

v4.55.1

### Operating System

Raspian/Docker

**Comment by PaulPizzey247** [comment]
Same here. If I go back to v 2.14.0 it works again.

**Comment by corasaniti** [comment]
@PaulPizzey247 
I confirm, I downgraded to version 2.14 and everything started working again. 
For now I am NOT installing 3.0.0 but I am waiting for a fix 
Thank you

**Comment by iSteve-O** [comment]
It’s not just the bots. I have a speaker IR device exposed through the plugin and it won’t work either. As soon as I downgraded to 2.14 everything works again. 

I would add debug logs but when on 3.0 I don’t even get any debug info in the logs. As soon as I reinstall 2.14 I get a ton of logs. 

Is that tv in your config working? I bet not…

**Comment by corasaniti** [comment]
@iSteve-O 
No, the infrared TV doesn't work either. Nothing works with version 3.0.0. I downgraded to 2.14.0. Let's wait for the fix
Thank you

**Comment by gukuhn** [comment]
Same here! Had to downgrade to 2.14.0

**Comment by SungwaYu** [comment]
Same here.

**Comment by Medar46** [comment]
Same here.Downgrade to 2.14.0

**Comment by Protodjango** [comment]
Same here

**Comment by nyjklein** [comment]
Same here. Only entry in the log:
[01/02/2024, 18:16:02] [SwitchBot] Initializing SwitchBot platform...

Falling back to v2.`14.0 restores full functionality!

**Comment by julioviegas** [comment]
Same here, downgraded to the previous version

**Comment by domre77** [comment]
Same here. Nothing works, nothing in logs. Downgraded 2.14 and everything works again.

**Comment by donavanbecker** [comment]
Is this only happening on Bots? Or are others having issues on other devices?

**Comment by corasaniti** [comment]
@donavanbecker 
I also have problems with IR devices (TV and Soundbar). From the posts I understand that it doesn't work with any device
Thanks

**Comment by domre77** [comment]
I have the same issues with my Blind tilt and motion sensor also.

Dom

**Comment by Z1mDMan** [comment]
All devices on 3.0.0, rolling back resolves.

**Comment by quebulm** [comment]
Same problem with Smart Lock

**Comment by nyjklein** [comment]
It's all devices The plug-in never gets past initializng ...

Turned on "debug logging". Still get nothing but this in the log:

[02/02/2024, 15:38:22] [SwitchBot] Initializing SwitchBot platform...

**Comment by frankea** [comment]
Fresh install of homebridge and the plugin sees the same issue.

**Comment by donavanbecker** [comment]
Closing this as it is a duplicate to #898, so post any updates there.

**Comment by corasaniti** [comment]
@donavanbecker 
Fixed With 3.1 verssion, thanks

**Comment by domre77** [comment]
Confirmed fixed with 3.1.

**Comment by iSteve-O** [comment]
Yes, all fixed, thank you @donavanbecker!!

**Comment by sonsongithub** [comment]
Thank you
