### ISSUE TITLE
Feature Request: Curtain3 Support

### ISSUE THREAD

**Issue by RohitRajendran** [OpenWonderLabs/homebridge-switchbot#901]
### Problem

I'm trying to add a Curtain3 device and I'm getting an error message saying `Device: Right with Device Type: Curtain3, is currently not supported.`

### Solution

Add support for Curtain3 devices.

**Comment by donavanbecker** [comment]
I will get this into the next release.

**Comment by RohitRajendran** [comment]
> I will get this into the next release.

Awesome to hear! Thanks!

**Comment by donavanbecker** [comment]
Added in v3.1.0
