### ISSUE TITLE
Add option to hide curtains light sensors from HomeKit

### ISSUE THREAD

**Issue by n0tkazz** [OpenWonderLabs/homebridge-switchbot#91]
### Describe Your Problem

1.0.0 added light sensors to curtains. But since I don't own any, there are new accessoires showing up in HomeKit that are reporting incorrect lux values (since I have Hue sensors already) and messing up with my setup. Is it possible to disable light sensors for curtains somewhere ? Thanks.

### Device & Model

Curtain

### Node.js Version

v16.13.0

### NPM Version

v8.1.2

### Homebridge Version

v1.3.6

### Homebridge SwitchBot Plugin Version

v1.0.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@n0tkazz, All curtains have light sensors.

<a><img src="https://user-images.githubusercontent.com/9875439/141997077-88cd332e-2d55-481a-a045-13a26ef53c99.jpeg" width="250px"></a>

Would you like me to add an option to disable the light sensor?

**Comment by n0tkazz** [comment]
Oh ! My bad, I was thinking of solar panels for battery charging 😅.

But yes, if you could add an option to disable them from HomeKit it would be perfect !

**Comment by donavanbecker** [comment]
@n0tkazz Please change title of this issue and I will use this to track and add this feature.

**Comment by donavanbecker** [comment]
@n0tkazz, I have added this feature, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.0.3-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
Added option to Version 1.1.0 which was just released.
