### ISSUE TITLE
Feature Request: Specify a range of temperature settings for the air conditioner

### ISSUE THREAD

**Issue by taikun114** [OpenWonderLabs/homebridge-switchbot#915]
### Problem

My air conditioner supports temperature settings from 16.0°C to 30.0°C, but HomeKit allows temperature settings from 0.0°C to 35.0°C, a range that my air conditioner does not support.
Nothing happens if temperatures are specified that are not supported by the air conditioner, but the range is so wide that it is hard to adjust the temperature in details because the range of temperature adjustment is so narrow.

### Solution

Retrieve the settable temperature range of the registered air conditioner (not sure if this is possible) or allow the user to enter the minimum and maximum temperatures in the plugin's settings.

### Additional context

Here is the HomeKit screen.
![スクリーンショット 2024-02-04 19 17 50](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/98800458/92087cb9-dc31-4ce3-b8db-c9957fabefbb)
![スクリーンショット 2024-02-04 19 18 01](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/98800458/db5c9def-7afc-4e45-8b58-18cf3568538a)

Even when a temperature not supported by the air conditioner was specified, the logs below were displayed as usual.
```
[2/4/2024, 7:17:40 PM] [SwitchBot] Air Conditioner: エアコン Sending request to SwitchBot API, body: {"command":"setAll","parameter":"0,2,1,on","commandType":"command"},
[2/4/2024, 7:18:01 PM] [SwitchBot] Air Conditioner: エアコン Sending request to SwitchBot API, body: {"command":"setAll","parameter":"35,2,1,on","commandType":"command"},
```

The error was logged in the history of the SwitchBot app.
![スクリーンショット 2024-02-04 19 35 05](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/98800458/8f7cabc8-6361-4242-ae23-bf548a0008f5)
In red text, the message "Device connection failed. Retry" is written (translated from Japanese, so the sentences may be slightly different).

I don't remember when the version was used, but I remember it was the correct temperature range in the version I was using about a year ago.

I am using the latest version of the Homebridge UI (v4.55.1) and the SwitchBot plugin (v3.1.0) at this time.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.3.0-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

I have added configs for this
<img width="717" alt="Screenshot 2024-02-06 at 10 15 14 PM" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/9875439/e6c43215-bea7-49bf-bd9e-15e4b2d1e468">

**Comment by taikun114** [comment]
Thanks for the reply.
I have tried and was able to change the minimum and maximum temperature settings and can no longer set the temperature outside of the range I have configured.
However, the HomeKit temperature control screen still shows a range of 0.0°C to 35.0°C, which is still difficult to control.
I have recorded the behavior, please check it out.

https://github.com/OpenWonderLabs/homebridge-switchbot/assets/98800458/fe9464eb-6590-4bab-9344-4b59fadf7007

**Comment by donavanbecker** [comment]
Sorry unfortunately that must be a HomeKit bug not something that I can change.

**Comment by taikun114** [comment]
I see. I understand.
But now that the request is no longer sent at a temperature that the air conditioner does not support, it is more convenient than before.
Thank you very much for your support!

**Comment by taikun114** [comment]
I hadn't tried deleting cached accessories, so I gave it a try and the following was logged after the first restart of Homebridge.

```
[2/7/2024, 8:35:41 PM] [SwitchBot] Adding new accessory: エアコン Air Conditioner DeviceID: XX-XXXXXXXXXXXX-XXXXXXXX
[エアコン@@Current Relative Humidity] Characteristic not in required or optional characteristic section for service HeaterCooler. Adding anyway.
[エアコン@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
[エアコン@@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
````

For a while the air conditioner did not show up in HomeKit, but after multiple restarts, it showed up again.
Then, when I changed the temperature, it showed the range I had set without any problem!
![スクリーンショット 2024-02-07 20 44 31](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/98800458/c4497a8b-ce95-4573-b750-67cbd55c2d12)
![スクリーンショット 2024-02-07 20 44 02](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/98800458/890ae6be-c523-41ab-90f4-cfda4f543390)

It seems that it was a cache issue that was not being displayed correctly.
I deleted the cache, so the air conditioner-related scenes disappeared, but I am very happy that the correct temperature range is now displayed as it was before.
Thank you for adding these settings!
