### ISSUE TITLE
Bug: Missing all device with 3.1.1

### ISSUE THREAD

**Issue by corasaniti** [OpenWonderLabs/homebridge-switchbot#920]
### Describe the Bug

Missing all device with 3.1.1. Rollback to 3.1.0

### To Reproduce

No dovice found wint 3.1.1

### Expected Behavior

No dovice found wint 3.1.1

### Relevant Log Output

```shell
No Logs
```

### Config for homebridge-switchbot

```shell
No dovice found wint 3.1.1
```

### Device and Model

Activate my switchbot

### Node.js Version

v18.19.0

### NPM Version

10.2.3

### Homebridge Version

v1.7.0

### Homebridge Switchbot Plugin Version

v3.00

### Homebridge Config UI X Plugin Version

v4.55.1

### Operating System

Raspian/Docker

**Comment by donavanbecker** [comment]
Won't be able to troubleshot without more info, looks like you just want through and put stuff in the required fields which isn't helpful.

**Comment by corasaniti** [comment]
Hi @donavanbecker 
I have no other information. With version 3.1.1 all switchbot accessories disappear from the accessories page.
If I restore version 3.1.0 my switchbots reappear correctly
Thanks

**Comment by donavanbecker** [comment]
Not trying to be mean, but then if you have no logs and no config, I will close this.

Sorry once you have that info then I have something to go off of.

**Comment by donavanbecker** [comment]
Fixed in 3.1.2

**Comment by corasaniti** [comment]
@donavanbecker 
I confirm with version 3.1.2 everything resolved. Just out of curiosity what was it?
Thanks again

**Comment by donavanbecker** [comment]
something I messed up last minute.
