### ISSUE TITLE
Feature Request: Smart Lock Pro

### ISSUE THREAD

**Issue by yima0913** [OpenWonderLabs/homebridge-switchbot#936]
### Problem

Lock Pro Not Supported

### Solution

Support Lock Pro

**Comment by donavanbecker** [comment]
do you have logs of what is displayed for a Lock Pro on a SwitchBot Account?

**Comment by yima0913** [comment]
<img width="860" alt="スクリーンショット 2024-02-11 16 46 55" src="https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46411601/ded8fcf9-bb51-4aac-bd09-cb726e7a5941">

ロックPro = Lock Pro
I want to check the door open/close sensor with Apple Home.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.3.1-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by yima0913** [comment]
Wow. It now appears on the home app. Thank you so much!
Arigatou! from Japan
![IMG_0002](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46411601/0810c04f-9c8e-46ac-be5a-886547361bf3)

**Comment by yima0913** [comment]
Wow. It now appears on the home app. Thank you so much!
Arigatou! from Japan
![IMG_0002](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46411601/b91bc1df-554c-433c-bca0-0f7498000066)

**Comment by donavanbecker** [comment]
Do the controls work?

**Comment by yima0913** [comment]
Yes! But it takes some time to get the sensor status. This is probably to prevent API usage restrictions.

**Comment by donavanbecker** [comment]
v3.4.0 has been released.
