### ISSUE TITLE
Support Request: IR Devices not showing up

### ISSUE THREAD

**Issue by Devin-G-Squire** [OpenWonderLabs/homebridge-switchbot#938]
### Describe Your Problem

I should have everything configured right but none of the IR devices are showing up it's like the sole reason I use this plug-in

### Config for homebridge-switchbot

{
    "platform": "SwitchBot",
    "name": "SwitchBot",
    "credentials": {
        "token": "xxxxxxxxxxxxxxxxxxxxxxxx",
        "secret":xxxxxxxxxxxxxx"
    }
}

### Device & Model

Hoobs Box - HSLF-1

### Node.js Version

16.20.2

### Homebridge Version

1.7.0

### Homebridge SwitchBot Plugin Version

3.3.0

### Operating System

Hoobs

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

Also without providing logs,  it much I can do to help, because I wouldn't know where to start for troubleshooting.

**Comment by Devin-G-Squire** [comment]
this is what I get witch doesn't make sense because they are set

```
Switchbot BridgeLoaded plugin '@switchbot/homebridge-switchbot'
2/11/2024, 8:22:13 PMSwitchbot BridgeLoading 1 platforms...
2/11/2024, 8:22:13 PMSwitchbot BridgeSwitchBotERRORNeither SwitchBot OpenToken or Device Config are not set.
2/11/2024, 8:22:13 PMSwitchbot BridgeBridge is running on port 51826.
```

**Comment by donavanbecker** [comment]
@Devin-G-Squire So first because you are using HOOBs, UI is not showing info that is needed, I would switch to Homebridge. 

Second the logs tell you exactly the issue.

**Comment by Devin-G-Squire** [comment]
That's so odd it's HOOBs certified & I had intentionally redacted the token & secret, but they are there. This as worked with  HOOBs before. Sounds like I'll have to find a new solution though. Do you know of an alternative that's better suited for HOOBs? I'm not that savvy with coding witch is why I went with HOOBs.

**Comment by donavanbecker** [comment]
I didn't ask it to be HOOBs certified, that is something they put on there. The better alternative would be to go away from HOOBs and use Homebridge
