### ISSUE TITLE
Bug: OpenAPI Unauthorized using valid keys

### ISSUE THREAD

**Issue by julioviegas** [OpenWonderLabs/homebridge-switchbot#942]
### Describe the Bug

Plugin stopped working few hours ago, tried to re-authenticate issuing new keys, seems to not connect

[16/02/2024, 19:27:06] [SwitchBot] Unauthorized,        Authorization for the API is required, but the request has not been authenticated, statusCode: 401
[16/02/2024, 19:27:06] [SwitchBot] Unknown statusCode, statusCode: undefined, Submit Bugs Here: ' + 'https://tinyurl.com/SwitchBotBug

Both Tilt Blind devices using OpenAPI connection:
"connectionType": "OpenAPI",

### To Reproduce

Use the plugin with valid developer credentials and connectionType: OpenAPI option

### Expected Behavior

Connection successful 

### Relevant Log Output

```shell
[16/02/2024, 19:27:06] [SwitchBot] Unauthorized,        Authorization for the API is required, but the request has not been authenticated, statusCode: 401
[16/02/2024, 19:27:06] [SwitchBot] Unknown statusCode, statusCode: undefined, Submit Bugs Here: ' + 'https://tinyurl.com/SwitchBotBug
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "<MY TOKEN>",
                "secret": "<MY SECRET>",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "<MY DEVICE ID>",
                        "configDeviceType": "Blind Tilt",
                        "connectionType": "OpenAPI",
                        "blindTilt": {
                            "mode": "use_tilt_for_direction"
                        }
                    },
                    {
                        "deviceId": "<MY DEVICE ID>",
                        "configDeviceType": "Blind Tilt",
                        "connectionType": "OpenAPI",
                        "blindTilt": {
                            "mode": "use_tilt_for_direction"
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
        },
```

### Device and Model

SwitchBot Blind Tilt

### Node.js Version

v20.11.0

### NPM Version

10.4.0

### Homebridge Version

v1.7.0 (HAP v0.11.1)

### Homebridge Switchbot Plugin Version

v3.4.0

### Operating System

Raspbian aarch64 bookworm

**Comment by julioviegas** [comment]
I erased my cloud account (had to wait 1 day for that to complete), recreated it, factory reseted all devices, re-added them, created the developer token/secret, added them to config, restarted homebridge, problem still happening.

**Comment by julioviegas** [comment]
Btw the devices are successful integrated to Alexa, so I don't know what is going on here...

**Comment by julioviegas** [comment]
I created a simple python script using my token/secret based on your API sample codes and it also returns a 401 Unauthorized... Is there something related to my cloud account??

**Comment by julioviegas** [comment]
Please disregard and erase this entire thing, it looks like I found the issue. It is related to my network configuration, as my script successfully authenticated from another machine... Thanks and sorry for the trouble.

**Comment by sirkirby** [comment]
> Please disregard and erase this entire thing, it looks like I found the issue. It is related to my network configuration, as my script successfully authenticated from another machine... Thanks and sorry for the trouble.

I'm having this same issue. @julioviegas would you mind sharing what your network config issue was?
