### ISSUE TITLE
Support Request: After the new version the devices are not found

### ISSUE THREAD

**Issue by nfsilva999** [OpenWonderLabs/homebridge-switchbot#95]
### Describe Your Problem

After the new version the devices are not found

### Relevant log output

```shell
After update to version 1.1.0 the devices are not found anymore.

I already check if the token is correct and yes, everything looks nice.

Could you help please understand what is wrong?

There is no error message on console.

Thanks.
Nelson
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "XXXXX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "bot": {
                            "deviceType": "outlet"
                        },
                        "meter": {
                            "hide_temperature": true,
                            "hide_humidity": true,
                            "unit": 1
                        },
                        "humidifier": {
                            "hide_temperature": true,
                            "set_minStep": 20
                        }
                    }
                ],
                "debug": "device"
            },
            "platform": "SwitchBot"
        }
```

### Screenshots

![Captura de ecrã 2021-11-17, às 12 34 37](https://user-images.githubusercontent.com/655453/142201954-1938cb52-fd56-4d5b-85a5-a6c2d07861bc.png)

### Device & Model

RPI3

### Node.js Version

v16.13.0

### NPM Version

8.1.3

### Homebridge Version

v1.3.6

### Homebridge SwitchBot Plugin Version

1.1.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@nfsilva999 I need logs from homebridge. I have nothing to go off of here.

Plus your device section looks completely off
```

  "devices": [
    {
      "bot": {
        "deviceType": "outlet"
      },
      "meter": {
        "hide_temperature": true,
        "hide_humidity": true,
        "unit": 1
      },
      "humidifier": {
        "hide_temperature": true,
        "set_minStep": 20
      }
    }
  ]
```

Should look something like this:
```
  "devices": [
    {
      "deviceId": "1AB3D683880",
      "deviceType": "Humidifier",
      "humidifier": {
        "hide_temperature": true,
        "set_minStep": 20
      }
    },
    {
      "deviceId": "1AB3D683880",
      "deviceType": "Meter",
      "meter": {
        "hide_temperature": true,
        "hide_humidity": true,
        "unit": 1
      }
    },
    {
      "deviceId": "1AB3D683880",
      "deviceType": "Bot",
      "bot": {
        "mode": "switch"
        "deviceType": "outlet"
      }
    }
    }
  ]
```

Are you manually putting in your config?

**Comment by nfsilva999** [comment]
No, I'm not putting manually. This is the thing. 

After install for the first time this version, I got the errors that you already solved. 

So, I uninstalled the plugin and install again for a clean installation. And after that, no more have devices found. 

I only configured the token in the plugin but nothing working. I'm missing something?

The only log that I get is this:

[17/11/2021, 12:29:50] [SwitchBot] Initializing SwitchBot platform...
[17/11/2021, 12:29:50] [SwitchBot] "The devices config section is missing the \"Device Type\" in the config, Check Your Conifg."

Nothing more :(

**Comment by donavanbecker** [comment]
@nfsilva999 Remove all of your config, and set your configs. You are missing the deviceType config section, that's why it isn't loading

**Comment by nfsilva999** [comment]
I'm sorry but i'm not understanding. 

Ok, I understand that is missing the deviceType in the config section but the thing is: I already had this plugin working until this version and I don´t remember change manually the configuration. 

I think that in past I only have to paste the token generated by App in the plugin wizard, then all the devices were loaded.

Why now I have to put the configuration? And how I get the device ids that is in the sample data from the documentation? I need to do postman calls to get that?

Sorry, I really don´t understand. The first time that i configured this was simples, and I trully don´t remember to change the configs.

**Comment by donavanbecker** [comment]
I would remove your `options` section for the config and start over with custom configs.

Then all your devices will load and you can get your deviceIDs from the devices tab.

I will work on updating the documentation.

**Comment by nfsilva999** [comment]
Hi @donavanbecker,

Same error. I use postman to get device list and use the response and add my configuration, here a simples example:

`{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "SSSS",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "AAAAA",
                        "deviceName": "Remote SB",
                        "deviceType": "Remote",
                        "enableCloudService": false,
                        "hubDeviceId": "000000000000"
                    }
                ],
                "debug": "debug"
            },
            "platform": "SwitchBot"
        }`

But always give me the same error message:

`[17/11/2021, 23:43:57] TypeError: Cannot read properties of undefined (reading 'deviceType')
    at new Bot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:68:25)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:464:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

:(

**Comment by donavanbecker** [comment]
@nfsilva999 Not sure why you are adding all of that to your config... it says remote which isn't a supported device.

Follow the UI.

**Comment by nfsilva999** [comment]
Hi @donavanbecker,
Thanks again for the reply.
Following the UI does not work anymore in my case. After this update I need just put the token in the UI window and everything's works like a charm, but not if I only put the token in the second tab "Devices" no device is found.
So, I did a get from postman and set the configs manually but always get the error:
TypeError: Cannot read properties of undefined (reading 'deviceType')
    at new Bot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:68:25)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:464:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I disable for now the plugin. I don´t understand whats going on in my configurations. I don´t know if is still a bug or not.

Thanks for the help.

**Comment by donavanbecker** [comment]
@nfsilva999, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=v1.1.1-beta.8/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by nfsilva999** [comment]
@donavanbecker yes, with beta the devices already show. 
Thanks for the help!

**Comment by donavanbecker** [comment]
Version 1.2.0 has been released
