### ISSUE TITLE
Feature Request: K10+

### ISSUE THREAD

**Issue by alesu** [OpenWonderLabs/homebridge-switchbot#964]
### Problem

Currently vacuum cleaner robot K10+ is not supported.

### Solution

Add support to homebridge.-switchbot.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.5.0-beta.15/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by alesu** [comment]
Thank you, it works in the beta.Best regards,AlesOn 24 Apr 2024, at 12:56 AM, Donavan Becker ***@***.***> wrote:﻿
Can you try the latest beta:

Click here to find out how to install Beta
