### ISSUE TITLE
Support Request: No volume control for IR speakers

### ISSUE THREAD

**Issue by MelvinSDRS** [OpenWonderLabs/homebridge-switchbot#966]
### Describe Your Problem

I just settled my pair of speakers as an IR device in Switchbot app, configured the on/off button and the volumes buttons. I added it to the homebridge pluggin but when I go to the Home app I only have the ability to turn on/off, no volume controls. Is it normal? Do I need to do something specific in the config? Thanks a lot for your help

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxxxxxxxx",
                "secret": "xxxxxxxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "D8AA06AF990F",
                        "configDeviceName": "Kanto YU4",
                        "configRemoteType": "Speaker",
                        "connectionType": "OpenAPI",
                        "customize": false,
                        "external": false
                    }
                ]
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

SwitchBot Hub Mini

### Node.js Version

v20.12.2

### NPM Version

v10.5.0

### Homebridge Version

v1.8.1

### Homebridge SwitchBot Plugin Version

v3.4.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@MelvinSDRS volume control not being in the app is normal. As there really isn't any device that has volume control inside the home app.
