### ISSUE TITLE
Bug: Unknown statusCode

### ISSUE THREAD

**Issue by ManAtArms001** [OpenWonderLabs/homebridge-switchbot#967]
### Describe the Bug

**Internal Server Error, An unexpected error on the SmartThings servers has occurred. These errors should be rare, statusCode: 500**

### To Reproduce

..

### Expected Behavior

...

### Relevant Log Output

```shell
...
```

### Config for homebridge-switchbot

```shell
...
```

### Screenshots

..

### Device and Model

...

### Node.js Version

v20.12.2

### NPM Version

tja

### Homebridge Version

v1.8.1

### Homebridge Switchbot Plugin Version

v3.4.0

### Homebridge Config UI X Plugin Version

v4.56.2

### Operating System

Raspian

**Comment by bo-2221** [comment]
I have the same problems
