### ISSUE TITLE
Feature Request: Add Troubleshooting in docs

### ISSUE THREAD

**Issue by martenmatrix** [OpenWonderLabs/homebridge-switchbot#973]
### Solution

I had an immense pain setting this up on Linux because of `bluetoothctl`. I would recommend users to run `sudo bluetoothctl power on` in their terminal to see if any errors are being outputted. If there are some errors, there is the following vague solution, which works 80% of the time; killing and restarting the processes with `rfkill block bluetooth` and `rfkill unblock bluetooth`.

Additionally, I would recommend users to check, if their Linux even recognizes their device with `sudo bluetoothctl` and `scan on` to see, if their device is listed there.

This would prevent many issues from being opened about not being able to set up the plugin.

**Comment by donavanbecker** [comment]
Feel free to open a PR

**Comment by martenmatrix** [comment]
bump, will add asap

**Comment by donavanbecker** [comment]
v3.5.1 has been released, this is included in this.
