### ISSUE TITLE
Bug: Switchbot accessory status (Garage Door) stuck at "Opening"

### ISSUE THREAD

**Issue by zsiraph** [OpenWonderLabs/homebridge-switchbot#978]
### Describe the Bug

Since updating the homebridge plugin to v3.5.0, the accessory state (garage door) is stuck at "Opening". I rolled back to v3.4.0 but it is still stucked.

I removed the plugin, restarted everything, reinstalled everything but it is still on constantly "Opening" in Homekit, but it is stuck at "Closed" in Homebridge. 

That is a problem, since right now I can not press the accessory from my car for instance, since it is already on Opening, so even the override function won't work 
![441637873_871214521451483_3544270473662171181_n](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/66639526/a4892a41-1b1c-4ed8-949e-0eb21585dde3)

It still can be triggered via Siri, and it does press the button.

### To Reproduce

Install and configure the homebridge-switchbot plugin.
Configure your bot as a "Garage Door" accessory with press mode
Observe the accessory state being stuck

### Expected Behavior

The state should return to Closed or Opened, not stucking at "Opening"

### Relevant Log Output

```shell
[28/05/2024, 07:26:03] [SwitchBot] Bot: Garage Door Set TargetDoorState: 0
[28/05/2024, 07:26:05] [SwitchBot] Bot: Garage Door request to SwitchBot API, body: {"command":"press","parameter":"default","commandType":"command"} sent successfully
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "***",
        "secret": "***",
    },
    "options": {
        "devices": [
            {
                "deviceId": "**",
                "configDeviceName": "Garage Door",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "press",
                    "deviceType": "garagedoor",
                    "allowPush": true,
                }
            }
        ]
    },
    "platform": "SwitchBot"
}
```

### Device and Model

SwitchBot V6.3

### Node.js Version

v20.13.1 

### NPM Version

v8.19.4

### Homebridge Version

v.1.8.2.

### Homebridge Switchbot Plugin Version

v3.5.0 

### Homebridge Config UI X Plugin Version

v4.56.2

### Operating System

 Debian GNU/Linux Bookworm (12)

**Comment by zsiraph** [comment]
I tested it and it is only happening when I select Garage Door as "What type of devide do you want to display in the Home App".
So for a workaround I set that up as a switch and made a dummy garage door with an other plugin, and made an automation to switch it when the dummy garage door is open but clearly it is a workaround involving using an extra plugin.

**Comment by donavanbecker** [comment]
Similar to #977

**Comment by zsiraph** [comment]
It is still a problem and it is still not resolved.
