### ISSUE TITLE
Bug: Bug: latest update has broken Custom IR devices

### ISSUE THREAD

**Issue by thatpaulallen** [OpenWonderLabs/homebridge-switchbot#981]
### Describe the Bug

Anytime I try to use a Custom IR device I get this error…

106/06/2024, 20:49:1411@switchbot/homebridge-switchbot] This plugin threw an error from the characteristic 'On':
Unhandled error thrown inside write handler for characteristic: Cannot set properties of undefined (setting 'On').
See https://homebridge.io/w/JtMGR for more info.

### To Reproduce

This is an example of how I have my custom IR device set up. Just FYI: these worked perfectly before the latest update.

![IMG_1497](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/594d99bc-9f36-447f-aa40-76cbd0583a2b)
![IMG_1499](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/c623be09-737a-4e21-a872-00ea0a537c20)

### Expected Behavior

I expected it to work and not throw an error.

### Relevant Log Output

```shell
[06/06/2024, 20:54:20] [@switchbot/homebridge-switchbot] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: Cannot set properties of undefined (setting 'On'). See https://homebridge.io/w/JtMGR for more info.
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "REDACTED",
                "secret": "REDACTED",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "02-202308301151-29602846",
                        "configDeviceName": "AUX",
                        "hide_device": false,
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off",
                        "disablePushOff": false,
                        "other": {
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "02-202308301149-50310440",
                        "configDeviceName": "EQ",
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off",
                        "disablePushOn": false,
                        "disablePushOff": false,
                        "other": {
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "02-202309250925-22506214",
                        "configDeviceName": "HDMI-ARC",
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off",
                        "disablePushOff": true,
                        "other": {
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "02-202308301147-41281781",
                        "configDeviceName": "Power",
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off",
                        "other": {
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "02-202401231437-10926103",
                        "configDeviceName": "HDMI In",
                        "hide_device": true,
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off",
                        "disablePushOn": false,
                        "disablePushOff": false,
                        "other": {
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "02-202401281632-59518813",
                        "configDeviceName": "Options",
                        "hide_device": true,
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off",
                        "other": {
                            "deviceType": "switch"
                        }
                    },
                    {
                        "deviceId": "02-202401281633-61969554",
                        "configDeviceName": "Up",
                        "hide_device": true,
                        "configRemoteType": "Others",
                        "connectionType": "OpenAPI",
                        "customize": true,
                        "customOn": "On",
                        "customOff": "Off"
                    }
                ]
            },
            "platform": "SwitchBot"
```

### Device and Model

Raspberry Pi 3b+

### Node.js Version

20.12.1

### NPM Version

No clue

### Homebridge Version

1.8.2

### Homebridge Switchbot Plugin Version

3.5.0

### Operating System

Raspbian

**Comment by failbit** [comment]
I have this issue aswell. Trying to downgrade.

**Comment by donavanbecker** [comment]
Can you try the latest beta?

**Comment by thatpaulallen** [comment]
> Can you try the latest beta?

Just installed it. It nearly fixes my issue, but now all my devices appear as switches AND plugs in the Home app. The plugs work while the switches still throw an error in the Homebridge log.

In the meantime I'm downgrading to 3.4, which woks flawlessly.

![IMG_1523](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/7bc5cd7f-34dd-4526-ae65-b751ce67cfd6)

**Comment by failbit** [comment]
Can confirm. 3.4 works flawless after downgrade.

**Comment by donavanbecker** [comment]
v3.5.1 has been released, please install and let me know if this has been resolved.

**Comment by thatpaulallen** [comment]
> v3.5.1 has been released, please install and let me know if this has been resolved.

It didn’t work. I still have a plug and a switch for each device for some reason (I only want a switch). 

 I get errors when I use the switch. The plug appears to work for the most part. I’m not sure what I’m looking at, but here’s my log…

in the meantime I’m going back to 3.4

![IMG_1552](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/46226043/55f4a2c4-8461-4aac-88b5-ddfb5db0bbda)

**Comment by thatpaulallen** [comment]
Not sure if this is helpful information or not, but both times I’ve rolled back my firmware I had to go back to 3.3 and then forward to 3.4 to get the plugs on each device to disappear.

The plugs remained if I merely rolled back to 3.4.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.5.2-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
v3.6.0 has been released. If this issue isn't resolved please open a new issue.

**Comment by failbit** [comment]
Did test it, did not work: 

`[7/7/2024, 6:19:19 PM] [SwitchBot] Others: AbzugshaubePower Set On: false
[7/7/2024, 6:19:19 PM] [SwitchBot] Others: AbzugshaubePower Sending request to SwitchBot API, body: {"command":"AbzugshaubePower","parameter":"default","commandType":"customize"},
[7/7/2024, 6:19:21 PM] [SwitchBot] Others: AbzugshaubePower request to SwitchBot API, body: {"command":"AbzugshaubePower","parameter":"default","commandType":"customize"} sent successfully
[7/7/2024, 6:19:21 PM] [@switchbot/homebridge-switchbot] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.`

**Comment by donavanbecker** [comment]
Can you try the latest beta and if that doesn't work open a new issue as closed issues will not be reviewed: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.6.1-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by thatpaulallen** [comment]
Looks like you fixed it!On Jul 13, 2024, at 2:27 AM, Donavan Becker ***@***.***> wrote:﻿
Can you try the latest beta and if that doesn't work open a new issue as closed issues will not be reviewed:

Click here to find out how to install Beta
