### ISSUE TITLE
Bug: switch lock not working throgh homebridge after 3.5 update

### ISSUE THREAD

**Issue by nadavko** [OpenWonderLabs/homebridge-switchbot#985]
### Describe the Bug

after the update the lock stopped responging to homekit. and nothing was seen on the log, as if no command was issued.

### To Reproduce

update to 3.5 and try unlocking via home app

### Expected Behavior

should lock and unlock and show status

### Relevant Log Output

```shell
there was no log
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "",
        "secret": "",
        "notice": "Keep your Token & Secret a secret!"
    },
    "platform": "SwitchBot",
    "_bridge": {
        "username": "0E:38:7C:7A:BA:34",
        "port": 38397
    }
}
```

### Device and Model

switchbot lock

### Node.js Version

v20.12.2

### NPM Version

10.5.0

### Homebridge Version

v1.8.2

### Homebridge Switchbot Plugin Version

3.5.0

### Operating System

docker

**Comment by donavanbecker** [comment]
Should be resolved in next release, try beta

**Comment by donavanbecker** [comment]
v3.5.1 has been released, please install and let me know if this has been resolved.

**Comment by donavanbecker** [comment]
v3.6.0 has been released. If this issue isn't resolved please open a new issue.
